### ISSUE TITLE
TFX with non differentiable models

### ISSUE THREAD

**Issue by frozaken** [tensorflow/tfx#1014]
Hi, i am very new to TFX but i am excited about trying it out. I have only gone through the taxi example so far, but i wanna test it out with some of our production models.

Currently we have a model that is not fully differentiable ( we use tf.math.argmax ), and for that reason we train it in 2 parts, and combine them after training. This requires two different datasets, so my question is if its still possible to run them as 1 experiment, training them side by side, and then combining them at the end.

Thanks for you work

**Comment by ruoyu90** [comment]
Hi @frozaken thanks for your interests! IIUC you should be able to reuse the standard TFX components to train the part of the model that is differentiable and you will need to compose your own custom component to combine the two models. Examples of custom components can be found [here](https://github.com/tensorflow/tfx/tree/master/tfx/examples/custom_components). Let me know if that answered your question :)

**Comment by rmothukuru** [comment]
@frozaken,
Can you please respond to @ruoyu90's comment. Thanks!

**Comment by frozaken** [comment]
@ruoyu90 Thank you, sorry for the late reply, i understand what you mean, but is there a way to essentially supply two different datasets to the pipeline, could i simply write a custom component for that?

**Comment by ruoyu90** [comment]
@frozaken yes it is possible to supply two different datasets to the pipeline. You'll essentially create two ExampleGen instances in the pipeline and wire them to different downstream components (Transform, Trainer, etc). One thing to notice is to assign different [instance_name](https://github.com/tensorflow/tfx/blob/r0.15/tfx/components/base/base_node.py#L56) to those two ExampleGens.

**Comment by rmothukuru** [comment]
@frozaken,
Can you please respond to @ruoyu90's comment so that we can work towards closure of this issue. Thanks!

**Comment by frozaken** [comment]
Excellent, Thanks for the help.
