### ISSUE TITLE
Using BigQueryExampleGen results in an unnecessary accumulation of temp files

### ISSUE THREAD

**Issue by jasonbrancazio** [tensorflow/tfx#1028]
In order to create TFRecord examples, BigQueryExampleGen must first run a job on BigQuery to materialize query results. A side effect of this process is the creation of a temp dataset and a temp table name. For example, the user will see a WARNING message like this: my-project:temp_dataset_cfae13c3dc3749c8bddd8794bee61557 does not exist so we will create it as temporary with location=US.

Repeatedly running a TFX pipeline with a BigQueryExampleGen component thus has the side effect of endlessly accumulating temp datasets and temp files on BigQuery, which leads to increased storage costs and clutter in the BigQuery UI.

We'd like to specify a custom dataset and table name to allow us to clean up after BigQueryExampleGen completes. We spent some time today reading the component and executor source code for BigQueryExampleGen but did not see a means to intervene. Ideally BigQueryExampleGen would support the "destination" and "write_disposition" arguments of a BigQuery job config: https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJobConfig.html

**Comment by 1025KB** [comment]
Hi, we use [beam.io.BigQuerySource](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/big_query_example_gen/executor.py#L74) to execute the query, I checked the beam BigQuerySource api but didn't find a place for setting the QueryJobConfig you mentioned, let me find someone at beam side

**Comment by jiyongjung0** [comment]
Hi, @jasonbrancazio thanks for the suggestion.

I looked at the beam BigQuerySource code and tried to understand your problem. But it looks like temporary dataset should be cleaned up when the job has completed. [Related source code](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L1014)
It could be possible that temporary dataset is not cleaned up if the job fails unexpectedly.

If the temporary tables and datasets are not from failed jobs, it would be helpful if you can provide your Dataflow job IDs or related information to debug.

**Comment by jasonbrancazio** [comment]
@jiyongjung0 I believe you're right. We did have several pipeline crashes over the past couple of weeks. Today we successfully orchestrated a few pipelines containing BigQueryExampleGen and saw no temp artifacts on BigQuery when they were done.

**Comment by jiyongjung0** [comment]
@jasonbrancazio Thank you for the confirmation. Let me close this issue, please feel free to reopen or raise an issue again if needed. :smile:
