### ISSUE TITLE
How to ensure the model the Trainer trained this time is better than the previous model?

### ISSUE THREAD

**Issue by tywtyw** [tensorflow/tfx#1037]
So what is the baseline that we can ensure the model is better than the previous model?

**Comment by gowthamkpr** [comment]
@tywtyw Baseline model is nothing but the best performing model that you are using now in production. This is taken care by ModelValidator. ModelValidator compares new models against a baseline (such as the currently serving model) to determine if they're "good enough" relative to the baseline.

For more information you can refer to the link [here](https://www.tensorflow.org/tfx/guide/modelval). Thanks!

**Comment by tywtyw** [comment]
Thanks for your replying. However, I know that the new model will be compared with the baseline model, what I do not understand is that what metric you are using in comparison? For an example, the AUC or accuracy in classification model, the 'mse' in regression model, that is to say, if the new model has a higher accuracy than the baseline model, we can conclude the new model is the better one. Is it the way ModelValidator works?

**Comment by gowthamkpr** [comment]
Model validator works by evaluating both models on an eval dataset and computing their performance on metrics (e.g. AUC, loss). If the new model's metrics meet developer-specified criteria relative to the baseline model (e.g. AUC is not lower), the model is "blessed" and the pusher pushes the model.

You can also refer to the following [issue](https://github.com/tensorflow/tfx/issues/166). Thanks!

**Comment by ruoyu90** [comment]
Currently our model validator is using a simple [strategy](https://github.com/tensorflow/tfx/blob/r0.15/tfx/components/model_validator/executor.py#L64) to base on accuracy of the model (and assuming it is a single output model). We're working on adding more support to that. Please stay tuned :)

Also leaving this open as a FR for more customization for model validator

/cc @1025KB 
/cc @zhitaoli 
/cc @mdreves

**Comment by ruoyu90** [comment]
Actually this is kinda duplicated to #663 . Closing this one now.

**Comment by tywtyw** [comment]
Thanks for replying
