### ISSUE TITLE
Being able to customize the execution of the Evaluator component with user code / module file

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/tfx#1047]
The only things that can be parameterized today in the Evaluator component is a list of `SingleSlicingSpec` and recently a parameter called `fairness_indicator_thresholds`. Then the actual call to TFMA is using the default extractors and evaluators.

There is so much more parameters that could be set by the user, and also our users want to be able to use custom Extractors and custom Evaluators that they have written. 

It seem that TFMA has been design with such customization in mind and it's too bad that we cannot leverage that in the tfx library.
See the [architecture for TFMA](https://github.com/tensorflow/model-analysis/blob/master/g3doc/architecture.md) and this helpful diagram:
 ![](https://raw.githubusercontent.com/tensorflow/model-analysis/master/g3doc/images/tfma_pipeline.png)

We have fairly sophisticated existing offline evaluations internally, and not being able to replicate them exactly and easily on TFMA is a major blocker for adoption.
We have, internally a component called EvaluatorWithModuleFile which calls an user define `eval_fn` with a user provided custom config similarly to what is done in the Trainer component. The output of this module file is an object that specifies all of the things that could be set by the user:
```
add_metrics_callbacks: Optional list of callbacks for adding additional
      metrics to the graph (see EvalSharedModel for more information on how to
      configure additional metrics). Metrics for example counts and example
      weight will be added automatically.
    include_default_metrics: True to include the default metrics that are part
      of the saved model graph during evaluation.
    additional_fetches: Prefixes of additional tensors stored in
      signature_def.inputs that should be fetched at prediction time. The
      "features" and "labels" tensors are handled automatically and should not
      be included.
    slicing_specs: Optional List of tfma.slicer.SingleSliceSpec
     specifying the slices to slice the data into. If None, defaults to the overall slice.
    desired_batch_size: Optional batch size for batching in Predict and
      Aggregate.
    extractors: Optional list of Extractors to apply to Extracts. Typically
      these will be added by calling the default_extractors function. If no
      extractors are provided, default_extractors (non-materialized) will be
      used.
    evaluators: Optional list of Evaluators for evaluating Extracts. Typically
      these will be added by calling the default_evaluators function. If no
      evaluators are provided, default_evaluators will be used.
    writers: Optional list of Writers for writing Evaluation output. Typically
      these will be added by calling the default_writers function. If no writers
      are provided, default_writers will be used.
    compute_confidence_intervals: Optional - whether or not to compute confidence intervals.
      Default is False.
    eval_shared_model: Optional, an instance of tfma.EvalSharedModel to use during evaluation. Some extractors and
        evaluators require this instance. If you needed to create it, fill this field so that the component does not try
        to create a new one
```

**Comment by singhniraj08** [comment]
@martin-laurent,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
