### ISSUE TITLE
ML-metadata increasingly becomes slower as the number of total runs grow

### ISSUE THREAD

**Issue by marcromeyn** [tensorflow/tfx#1053]
We use TFX extensively and have an ML-metadata instance that contains over 10k runs. This is becoming a bottleneck since cache resolution is increasingly getting slower. Re-running the taxi-example end-to-end (so that each component returns the outputs from cache) can take more than 10 minutes now.

It seems that the root cause of this is a very [inefficient filtering routine](https://github.com/tensorflow/tfx/blob/6169754c23e4cf7df441f427087089e56dc018e5/tfx/orchestration/metadata.py#L584) present in ML-metadata. All executions are returned from the metadata store, and filtering is done inside the python process. Would it be possible to optimize this?

**Comment by ucdmkt** [comment]
\cc @hughmiao @ruoyu90

**Comment by hughmiao** [comment]
@marcromeyn . thanks for pointing this out and analyzing the root cause. We are refactoring tfx/metadata.py and the cache resolution to push the unnecessary in-memory filtering to mlmd  layer. The fix should be in the next release.
