### ISSUE TITLE
What is the schema_version in MLMD?

### ISSUE THREAD

**Issue by tywtyw** [tensorflow/tfx#1063]
I am confused about the schema version in MLMD. What is the scheme exactly about? Does it refer to changes in relationships between tables in database? Hopefully to get a reply.

**Comment by gowthamkpr** [comment]
@tywtyw Can you please be specific as to where you found schema_version in MLMD? Can you point us to the source code? Thanks!

**Comment by ruoyu90** [comment]
@tywtyw the `schema_version` refers to the schema of the underlying database schema for MLMD. Instructions for upgrading / downgrading can be found [here](https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#upgrade-the-database-schema).

**Comment by gowthamkpr** [comment]
I am going to close this issue as it has been answered. Please add additional comments and we can open this issue again. Thanks!
