### ISSUE TITLE
tfdv.GenerateStatistics's output

### ISSUE THREAD

**Issue by xiaochuan-du** [tensorflow/tfx#1111]
As example suggest,
```
  with beam.Pipeline(runner=...) as p:
    _ = (p
         | 'ReadData' >> beam.io.ReadFromTFRecord(data_location)
         | 'DecodeData' >> beam.Map(TFExampleDecoder().decode)
         | 'GenerateStatistics' >> GenerateStatistics()
         | 'WriteStatsOutput' >> beam.io.WriteToTFRecord(
             output_path, shard_name_template='',
             coder=beam.coders.ProtoCoder(
                 statistics_pb2.DatasetFeatureStatisticsList)))
```
Beam is a parallel processing framework, thus the output of GenerateStatistics should be more than one file that records statistics for different data chunks. 
Do we need to merge these statistics before validating the test dataset?  For example, `col1` in data_chunk0  train dataset's legal range is from 0 to 5, `col1`in data_chunk1 legal range is from 1 to 6, thus in gross, `col1` valid data range should be from 0 to 6. Is there a buildin function to complete the task?

**Comment by xiaochuan-du** [comment]
According to infer_schema's [doc](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/infer_schema) ,

> statistics: A DatasetFeatureStatisticsList protocol buffer. Schema inference is currently only supported for lists with a single DatasetFeatureStatistics proto.

**Comment by caveness** [comment]
Hi -- GenerateStatistics in the above example will generate a single DatasetFeatureStatisticsList proto, which includes the stats for all of the tf.Examples read into the pipeline and decoded into tf.Examples. You do not need to merge different DatasetFeatureStatisticsList protos.

Unless you are using [slice functions](https://github.com/tensorflow/data-validation/blob/70b3cb2ffbc7381bffd8088a197285761d5474ec/tensorflow_data_validation/statistics/stats_options.py#L45) (specified via the optional StatsOptions object that can be passed to GenerateStatistics), the DatasetFeatureStatisticsList proto that GenerateStatistics outputs will have a single DatasetFeatureStatistics proto. You can pass that DatasetFeatureStatisticsList proto to infer_schema directly without needing to do any merging. 

Even if you are using slice functions (in which case the DatasetFeatureStatisticsList proto that GenerateStatistics outputs may include more than one DatasetFeatureStatistics proto), infer_schema will still work. In that case, it will infer the schema from the statistics corresponding to the default slice (i.e., the slice with all examples). Again, you can pass the DatasetFeatureStatisticsList proto to infer_schema directly without needing to do any merging.

Please let me know if this doesn't address your question, and I can try to clarify.

**Comment by xiaochuan-du** [comment]
> Hi -- GenerateStatistics in the above example will generate a single DatasetFeatureStatisticsList proto, which includes the stats for all of the tf.Examples read into the pipeline and decoded into tf.Examples. You do not need to merge different DatasetFeatureStatisticsList protos.
> 
> Unless you are using [slice functions](https://github.com/tensorflow/data-validation/blob/70b3cb2ffbc7381bffd8088a197285761d5474ec/tensorflow_data_validation/statistics/stats_options.py#L45) (specified via the optional StatsOptions object that can be passed to GenerateStatistics), the DatasetFeatureStatisticsList proto that GenerateStatistics outputs will have a single DatasetFeatureStatistics proto. You can pass that DatasetFeatureStatisticsList proto to infer_schema directly without needing to do any merging.
> 
> Even if you are using slice functions (in which case the DatasetFeatureStatisticsList proto that GenerateStatistics outputs may include more than one DatasetFeatureStatistics proto), infer_schema will still work. In that case, it will infer the schema from the statistics corresponding to the default slice (i.e., the slice with all examples). Again, you can pass the DatasetFeatureStatisticsList proto to infer_schema directly without needing to do any merging.
> 
> Please let me know if this doesn't address your question, and I can try to clarify.

That perfectly answers my questions. Many thanks.
