### ISSUE TITLE
predictions returns empty array: []

### ISSUE THREAD

**Issue by DurivetMatthias** [tensorflow/tfx#114]
I have implemented a custom example after working trough the taxi example.

My model takes in a string with stackoverflow tags separated by a |
like : 'javascript|python|java'
In the preprocessing function I split the one input tensor into mutiple tensors using tf.string_split

the model is a regression that should result in a single number.

The custom implementation of the pipeline runs without problems all the way.
The ml engine model exists, the saved model.pb exists.
I did not change anything to any code that seems responsible for serving.
When I input incorrect data it correctly fails, so the data is actually making it into the model.

- But when I try to make a prediction to the new ml engine model it returns an empty array.
like: {'predictions': []}

```python
import json
import numpy as np
import googleapiclient
from googleapiclient import discovery, errors


def predict_json(project, model, instances, version=None):
    """Send json data to a deployed model for prediction.

    Args:
        project (str): project where the Cloud ML Engine Model is deployed.
        model (str): model name.
        instances ([Mapping[str: Any]]): Keys should be the names of Tensors
            your deployed model expects as inputs. Values should be datatypes
            convertible to Tensors, or (potentially nested) lists of datatypes
            convertible to tensors.
        version: str, version of the model to target.
    Returns:
        Mapping[str: any]: dictionary of prediction results defined by the
            model.
    """
    # Create the ML Engine service object.
    # To authenticate set the environment variable
    # GOOGLE_APPLICATION_CREDENTIALS=<path_to_service_account_file>
    service = googleapiclient.discovery.build('ml', 'v1')
    name = 'projects/{}/models/{}'.format(project, model)

    if version is not None:
        name += '/versions/{}'.format(version)

    response = service.projects().predict(
        name=name,
        body={'instances': instances}
    ).execute()

    if 'error' in response:
        print(response['error'])

    return response


data = ['javascript|python|java', 'javascript|java|node']


response = predict_json(
    "my-project", "stackoverflow_tfx", data)

print(response)
```

- Where do I start debugging or does anyone know what could be going on?

**Comment by 1025KB** [comment]
Does transform output the intended data you want? you can also check the model by TFMA (check Evaluator result) to see if it looks normal?

You can also post this issue in [Tensorflow](https://github.com/tensorflow/tensorflow/issues) , it seems more model related

**Comment by DurivetMatthias** [comment]
@1025KB 
posted the issue in [Tensorflow](https://github.com/tensorflow/tensorflow/issues/28692#issue-443750400)

Will look into the data stored on the google storage bucket later today.

**Comment by DurivetMatthias** [comment]
@1025KB i'm continuing in the Tensorflow issues but my problem seems to fit in both. I added what I found out today to the other issue
