### ISSUE TITLE
Can I use other ML libraries on TFX?

### ISSUE THREAD

**Issue by jusingh** [tensorflow/tfx#1140]
We build models on different libraries such as TensorFlow, Vowpal Wabbit, Scikit, etc. Is it feasible to use TFX pipeline for models build on other ML libraries? 
Specifically, I am interested to use TF Data Validation, TF Model Analysis and ML Metadata libraries for our workflow. 

Not sure if I can extend these libraries to serve other models using custom components[1] as in the examples TensorFlow is used for model training, evaluation and inference and I couldn't find an example with some other ML library

[1] https://github.com/tensorflow/tfx/tree/master/tfx/examples/custom_components/presto_example_gen

**Comment by gowthamkpr** [comment]
Currently most of existing component are tf.example based, if your data is in different format, you won't be able to directly using TFX.

Please take a look at this issue #205 . Thanks!

**Comment by gowthamkpr** [comment]
@jusingh I am gonna close this issue for now and lets keep tracking it on #205. Thanks!
