### ISSUE TITLE
Getting Started doesn't work in 2.x

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tfx#1156]
Update Getting Started page to work in 2.x

I believe the Getting Started guide is correct for 1.x but not for 2.0:
https://www.tensorflow.org/tfx/transform/get_started

It uses tf.FixedLenFeature but in 2.x, you need tf.io.FixedLenFeature, for example.

**Comment by gowthamkpr** [comment]
@robertlugg Thanks for pointing out the issue. Yes, the document should definitiely updated for tensorflow 2.x.

**Comment by gowthamkpr** [comment]
@zoyahav Can you please take a look at this issue. Thanks!

**Comment by zoyahav** [comment]
Yes, I will make the appropriate changes and let you know when it's done.

**Comment by zoyahav** [comment]
The get_started guide is now updated: https://github.com/tensorflow/transform/commit/fb11520d444db23163d18f7c71ac8ba240de6f65

**Comment by gowthamkpr** [comment]
Thank you @zoyahav.

@robertlugg I am closing this issue as it has been fixed. Please add additional comments and we can open this issue again. Thanks!
