### ISSUE TITLE
Allow different stages/components use different custom container images

### ISSUE THREAD

**Issue by zhitaoli** [tensorflow/tfx#1185]
As we discussed in #19, each step/component could really use a different container image, possibly based off official tfx image.

Leaving this to @numerology @neuromage for further triaging.

**Comment by jiyongjung0** [comment]
Users can now customize container images using `pipeline_operator_funcs`. https://github.com/tensorflow/tfx/blob/bca8168dfc50d1a28218391c4114081275129da7/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L182

Let me close this bug for now. Feel free to reopen it if needed.
