### ISSUE TITLE
AttributeError: Cannot set unknown property 'run_id' on artifact Artifact(type_name: Examples, uri: , id: 0).

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/tfx#1212]
I am testing the latest 0.21rc and I noticed that the ExampleGen components fail with 
```
AttributeError: Cannot set unknown property 'run_id' on artifact Artifact(type_name: Examples, uri: , id: 0).
```

I tried two ExampleGen components. The pipeline setup was working fine under 0.15.

Colab to reproduce: https://colab.research.google.com/drive/1Lod4ll5cW-VPMBmwmTlqBqLiCCNG_umE

Is anyone else experiencing this issue under 0.21rc?

**Comment by gowthamkpr** [comment]
@hanneshapke I am running into a bunch of errors with your code. Please take a look at it [here](https://colab.research.google.com/gist/gowthamkpr/380c3e70e2a4b6e948ed7856cf555893/copy-of-example-for-examplegen-error-under-0-21rc.ipynb). Thanks!

**Comment by hanneshapke** [comment]
@gowthamkpr Did you restart the Colab runtime engine after installing the required pip packages? If you don't restart the runtime engine, you'll run into the errors. If you restart it, you'll reproduce my initial error. 

I think I read that packages installed from inside a Colab session aren't immediately available. Maybe the Python path doesn't update under the hood, not sure.

**Comment by gowthamkpr** [comment]
Yes. I did restart the colab runtime and installed all the dependencies. Here's my [gist](https://colab.research.google.com/gist/gowthamkpr/836dd6e073a553ed508544243dd17abd/copy-of-example-for-examplegen-error-under-0-21rc.ipynb).

**Comment by hanneshapke** [comment]
Hey @gowthamkpr 
Thank you for looking into this error. I made a [little screencast of executing the Colab notebook](https://youtu.be/ml1oPSFmAIk). It shows that the notebook needs to run twice to be correctly executed. 
Your gist showed this error: `NameError: name 'InteractiveContext' is not defined`
Since you imported `InteractiveContext` above, but the object can't be found in the next cell, that is an indication that the import failed.

**Comment by gowthamkpr** [comment]
Its showing that video is unavailable as it is private @hanneshapke. Can you Please take a look at it?

**Comment by hanneshapke** [comment]
PLease try again: https://youtu.be/ml1oPSFmAIk

**Comment by gowthamkpr** [comment]
@hanneshapke I have run into the same error too but this time with chicago taxi example. Heres my [gist](https://colab.research.google.com/gist/gowthamkpr/dd315fd61c901e5a62d4460ab0d72c91/copy-of-example-for-examplegen-error-under-0-21rc.ipynb#scrollTo=yCqN80wsu5jd). Thanks for reporting

**Comment by hanneshapke** [comment]
@jiyongjung0 @rcrowe-google Just tried the 0.21.0 release and the bug seems to be fixed! 
Thank you!
