### ISSUE TITLE
Failed to install tfx=0.15.0 with pyarrow=0.14.0 in windows 10

### ISSUE THREAD

**Issue by sakhawath19** [tensorflow/tfx#1227]
System information
OS Platform and Distribution: Windows 10
TensorFlow version: 1.15.0
Python version: 3.7.6
Describe the problem

(CPU_3.7.6_tfx_2) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0
Collecting tfx==0.15.0
Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Collecting tensorflow-model-analysis<0.16,>=0.15.2
Using cached tensorflow_model_analysis-0.15.4-py3-none-any.whl (1.4 MB)
Processing c:\users\sakhawath\appdata\local\pip\cache\wheels\65\72\ba\7ad835954f31d6ef4f2741f602a685ac203fce168c2f31adc6\apache_beam-2.19.0-py3-none-any.whl
Processing c:\users\sakhawath\appdata\local\pip\cache\wheels\46\91\e3\0fced4f5fbc0a051a5667096826186c9ff60f2d0e9bf0f1cdc\absl_py-0.8.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0)
.............................................................................
(CPU_3.7.6_tfx_2) C:\Users\sakhawath\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0rc0
Collecting tfx==0.15.0rc0
Using cached tfx-0.15.0rc0-py3-none-any.whl (475 kB)
ERROR: Could not find a version that satisfies the requirement tfx-bsl<0.16,>=0.15.1 (from tfx==0.15.0rc0) (from versions: 0.21.0)
ERROR: No matching distribution found for tfx-bsl<0.16,>=0.15.1 (from tfx==0.15.0rc0)
.......................................................................
(CPU_3.7.6_tfx_2) C:\Users\Sakhawath\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.21.0
ERROR: Could not find a version that satisfies the requirement tfx==0.21.0 (from versions: 0.13.0rc0, 0.13.0rc1, 0.13.0rc2, 0.13.0, 0.14.0rc1, 0.14.0, 0.15.0rc0, 0.15.0, 0.21.0rc0)
ERROR: No matching distribution found for tfx==0.21.0

**Comment by gowthamkpr** [comment]
@sakhawath19 The last error message is legitimate as `tfx 0.21.0` is not yet available in pip distribution. You should install `tfx 0.21.0rc0`. Please find my gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/62d48c866c1e5f88bdc23587cd8970b3/untitled8.ipynb).

I am not facing any issue on my linux system and ubuntu.

I dont have access to my Windows machine now. I will reproduce it in the evening and will get back to you. Thanks for reporting

**Comment by sakhawath19** [comment]
Here is the summary, you could see what I have tried so far. I have tried with python 3.7.5 too. Thanks for the information. I will try and see what happens with tfx 0.21.0rc0 

python=3.7.6, tf=1.15.0, pyarrow=0.14.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0

python=3.7.6, tf=1.15.0, pyarrow=0.15.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0

........................................................................................
python=3.7.6, tf=2.0.0, pyarrow=0.14.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0

python=3.7.6, tf=2.0.0, pyarrow=0.15.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0

pip install failed, could not find the version
python=3.7.6 environment
tf=2.1.0
tf=2.1.0rc0
tf=2.1.0rc1
tf=2.1.0rc2

........................................................................................
conda install failed
PackagesNotFoundError: The following packages are not available from current channels:
python=3.7.6 environment
tf=2.1.0
tf=2.1.0rc0
tf=2.1.0rc1
tf=2.1.0rc2

........................................................................................
python=3.7.6, tf=1.14.0, pyarrow=0.15.0 installed
failed at tfx 0.13.0
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0

........................................................................................
python=3.7.6, tf=1.14.0, pyarrow=0.14.0 installed
tfx 0.21.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
ERROR:root:Internal Python error in the inspect module. 

able to import:
import tempfile
import urllib
import tfx
from tfx.proto import pusher_pb2
from tfx.proto import evaluator_pb2
from tfx.proto import trainer_pb2
from tfx.proto.evaluator_pb2 import SingleSlicingSpec

Coud not import:
from tfx.components.evaluator.component import Evaluator
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
from tfx.components.example_validator.component import ExampleValidator
from tfx.components.model_validator.component import ModelValidator
from tfx.components.pusher.component import Pusher
from tfx.components.schema_gen.component import SchemaGen
from tfx.components.statistics_gen.component import StatisticsGen
from tfx.components.trainer.component import Trainer
from tfx.components.transform.component import Transform
from tfx.orchestration.interactive.interactive_context import InteractiveContext
from tfx.utils.dsl_utils import csv_input

........................................................................................
python=3.7.4, tf=1.14.0, pyarrow=0.14.0 installed
python=3.7.4, tf=1.14.0, pyarrow=0.15.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0

........................................................................................
python=3.7.4, tf=1.15.0, pyarrow=0.14.0 installed
python=3.7.4, tf=1.15.0, pyarrow=0.15.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0

........................................................................................
python=3.7.4, tf=2.0.0, pyarrow=0.14.0 installed
python=3.7.4, tf=2.0.0, pyarrow=0.15.0 installed
failed at tfx 0.14.0
failed at tfx 0.15.0
failed at tfx 0.15.0rc0
failed at tfx 0.21.0
......................................................................................

**Comment by sakhawath19** [comment]
tfx=0.21.0rc0 is getting installed but throwing some error 
ERROR: apache-beam 2.17.0 has requirement httplib2<=0.12.0,>=0.8, but you'll have httplib2 0.17.0 which is incompatible.
..................................................................................................................................................................

When I am trying to run taxi example it failed 
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_7\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_7\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_7\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_7\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_7\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
..................................................................................................................................................................................................
It also failed subsequently
Failed to load the native TensorFlow runtime.

**Comment by gowthamkpr** [comment]
@sakhawath19 Please downgrade httplib2 to 0.12 and it should solve your issue. Thanks!

**Comment by gowthamkpr** [comment]
@sakhawath19 Were you able to solve the issue? Thanks!
