### ISSUE TITLE
Failed to install tfx=0.15.0 with pyarrow=0.15.0 in windows 10

### ISSUE THREAD

**Issue by sakhawath19** [tensorflow/tfx#1228]
(CPU_3.7.6_tfx_2) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0

Collecting tfx==0.15.0
  Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\46\91\e3\0fced4f5fbc0a051a5667096826186c9ff60f2d0e9bf0f1cdc\absl_py-0.8.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement tfx-bsl<0.16,>=0.15.3 (from tfx==0.15.0) (from versions: 0.21.0)
ERROR: No matching distribution found for tfx-bsl<0.16,>=0.15.3 (from tfx==0.15.0)
..........................................................................................................................................................................................

(CPU_3.7.6_tfx_2) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0rc0

Collecting tfx==0.15.0rc0
  Using cached tfx-0.15.0rc0-py3-none-any.whl (475 kB)
Requirement already satisfied: protobuf<4,>=3.7 in c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_2\lib\site-packages (from tfx==0.15.0rc0) (3.11.3)
Requirement already satisfied: six<2,>=1.10 in c:\users\sakhawathhossain\appdata\roaming\python\python37\site-packages (from tfx==0.15.0rc0) (1.13.0)
Collecting jinja2<3,>=2.7.3
  Downloading Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 1.1 MB/s
ERROR: Could not find a version that satisfies the requirement tfx-bsl<0.16,>=0.15.1 (from tfx==0.15.0rc0) (from versions: 0.21.0)
ERROR: No matching distribution found for tfx-bsl<0.16,>=0.15.1 (from tfx==0.15.0rc0)
................................................................................................................................................................................................

(CPU_3.7.6_tfx_2) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx

Collecting tfx
  Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\b6\04\f6\ae7211f4531abd8ac91e3fae5d19a4d8b52803362548ea9f66\google_api_python_client-1.7.11-py3-none-any.whl
Collecting ml-metadata<0.16,>=0.15.0rc0
  Using cached ml_metadata-0.15.2-cp37-cp37m-win_amd64.whl (2.3 MB)
Requirement already satisfied: tensorflow<3,>=1.15 in c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_2\lib\site-packages (from tfx) (1.15.0)
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx)

**Comment by sakhawath19** [comment]
tensorflow=0.15.0

**Comment by gowthamkpr** [comment]
@sakhawath19 For tfx 0.15.0, you have to use pyarrow 0.14.0 as mentioned [here](https://github.com/tensorflow/tfx#compatible-versions) and from tfx 0.21.0, you can use pyarrow 0.15.

That being said you are also facing issue installing tfx with pyarrow==0.14.0 as given [here](https://github.com/tensorflow/tfx/issues/1227).

Can we close this issue and track the issue #1227 . Thanks!

**Comment by gowthamkpr** [comment]
I will close this issue for now as the support for tfx on windows is not fully established and we will track this issue [here](https://github.com/tensorflow/tfx/issues/1229). Thanks!
