### ISSUE TITLE
Failed to install tfx with tensorflow=1.15.0 and 2.0.0, pyarrow=0.14.0/0.15.0 in windows 10

### ISSUE THREAD

**Issue by sakhawath19** [tensorflow/tfx#1229]
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0
Collecting tfx==0.15.0
  Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Requirement already satisfied: tensorflow<3,>=1.15 in c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_3\lib\site-packages (from tfx==0.15.0) (2.0.0)
Collecting click<8,>=7
  Using cached Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting jinja2<3,>=2.7.3
  Using cached Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
Collecting tensorflow-transform<0.16,>=0.15
  Using cached tensorflow-transform-0.15.0.tar.gz (222 kB)
Requirement already satisfied: six<2,>=1.10 in c:\users\sakhawathhossain\appdata\roaming\python\python37\site-packages (from tfx==0.15.0) (1.13.0)
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0)
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0rc0
Collecting tfx==0.15.0rc0
  Using cached tfx-0.15.0rc0-py3-none-any.whl (475 kB)
Requirement already satisfied: tensorflow<3,>=1.15 in c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_3\lib\site-packages (from tfx==0.15.0rc0) (2.0.0)
Collecting jinja2<3,>=2.7.3
  Using cached Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0rc0) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0rc0)
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.21.0
ERROR: Could not find a version that satisfies the requirement tfx==0.21.0 (from versions: 0.13.0rc0, 0.13.0rc1, 0.13.0rc2, 0.13.0, 0.14.0rc1, 0.14.0, 0.15.0rc0, 0.15.0, 0.21.0rc0)
ERROR: No matching distribution found for tfx==0.21.0
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx
Collecting tfx
  Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\b6\04\f6\ae7211f4531abd8ac91e3fae5d19a4d8b52803362548ea9f66\google_api_python_client-1.7.11-py3-none-any.whl
Collecting pyyaml<4,>=3.12
  Using cached PyYAML-3.13-cp37-cp37m-win_amd64.whl (206 kB)
Collecting ml-metadata<0.16,>=0.15.0rc0
  Using cached ml_metadata-0.15.2-cp37-cp37m-win_amd64.whl (2.3 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx)
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.14.0
Collecting tfx==0.14.0
  Using cached tfx-0.14.0-py3-none-any.whl (384 kB)
ERROR: Could not find a version that satisfies the requirement ml-metadata<0.15,>=0.14 (from tfx==0.14.0) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0, 0.15.0, 0.15.1, 0.15.2, 0.21.0rc0, 0.21.0)
ERROR: No matching distribution found for ml-metadata<0.15,>=0.14 (from tfx==0.14.0)
...............................................................................................................................................................................................

(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install pyarrow==0.14.0
Collecting pyarrow==0.14.0
  Using cached pyarrow-0.14.0-cp37-cp37m-win_amd64.whl (17.4 MB)
Requirement already satisfied: numpy>=1.14 in c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_3\lib\site-packages (from pyarrow==0.14.0) (1.18.1)
Requirement already satisfied: six>=1.0.0 in c:\users\sakhawathhossain\appdata\roaming\python\python37\site-packages (from pyarrow==0.14.0) (1.13.0)
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 0.15.0
    Uninstalling pyarrow-0.15.0:
      Successfully uninstalled pyarrow-0.15.0
Successfully installed pyarrow-0.14.0
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.14.0
Collecting tfx==0.14.0
  Using cached tfx-0.14.0-py3-none-any.whl (384 kB)
Requirement already satisfied: six<2,>=1.10 in c:\users\sakhawathhossain\appdata\roaming\python\python37\site-packages (from tfx==0.14.0) (1.13.0)
ERROR: Could not find a version that satisfies the requirement ml-metadata<0.15,>=0.14 (from tfx==0.14.0) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0, 0.15.0, 0.15.1, 0.15.2, 0.21.0rc0, 0.21.0)
ERROR: No matching distribution found for ml-metadata<0.15,>=0.14 (from tfx==0.14.0)
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0
Collecting tfx==0.15.0
  Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Collecting tensorflow-model-analysis<0.16,>=0.15.2
  Using cached tensorflow_model_analysis-0.15.4-py3-none-any.whl (1.4 MB)
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\b6\04\f6\ae7211f4531abd8ac91e3fae5d19a4d8b52803362548ea9f66\google_api_python_client-1.7.11-py3-none-any.whl
Collecting ml-metadata<0.16,>=0.15.0rc0
  Using cached ml_metadata-0.15.2-cp37-cp37m-win_amd64.whl (2.3 MB)
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\65\72\ba\7ad835954f31d6ef4f2741f602a685ac203fce168c2f31adc6\apache_beam-2.19.0-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0)
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.15.0rc0
Collecting tfx==0.15.0rc0
  Using cached tfx-0.15.0rc0-py3-none-any.whl (475 kB)
Collecting click<8,>=7
  Using cached Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting tensorflow-model-analysis<0.16,>=0.15.2
  Using cached tensorflow_model_analysis-0.15.4-py3-none-any.whl (1.4 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0rc0) (from versions: 0.21.0)
ERROR: No matching distribution found for tensorflow-data-validation<0.16,>=0.15 (from tfx==0.15.0rc0)
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx==0.21.0
ERROR: Could not find a version that satisfies the requirement tfx==0.21.0 (from versions: 0.13.0rc0, 0.13.0rc1, 0.13.0rc2, 0.13.0, 0.14.0rc1, 0.14.0, 0.15.0rc0, 0.15.0, 0.21.0rc0)
ERROR: No matching distribution found for tfx==0.21.0
...............................................................................................................................................................................................
(CPU_3.7.6_tfx_3) C:\Users\SakhawathHossain\AppData\Local\Continuum\anaconda3\envs>pip install tfx
Collecting tfx
  Using cached tfx-0.15.0-py3-none-any.whl (504 kB)
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\b6\04\f6\ae7211f4531abd8ac91e3fae5d19a4d8b52803362548ea9f66\google_api_python_client-1.7.11-py3-none-any.whl
Processing c:\users\sakhawathhossain\appdata\local\pip\cache\wheels\65\72\ba\7ad835954f31d6ef4f2741f602a685ac203fce168c2f31adc6\apache_beam-2.19.0-py3-none-any.whl
Collecting tensorflow-model-analysis<0.16,>=0.15.2
  Using cached tensorflow_model_analysis-0.15.4-py3-none-any.whl (1.4 MB)
Collecting tensorflow-transform<0.16,>=0.15
  Using cached tensorflow-transform-0.15.0.tar.gz (222 kB)
Requirement already satisfied: six<2,>=1.10 in c:\users\sakhawathhossain\appdata\roaming\python\python37\site-packages (from tfx) (1.13.0)
Collecting ml-metadata<0.16,>=0.15.0rc0
  Using cached ml_metadata-0.15.2-cp37-cp37m-win_amd64.whl (2.3 MB)
Collecting pyyaml<4,>=3.12
  Using cached PyYAML-3.13-cp37-cp37m-win_amd64.whl (206 kB)
Requirement already satisfied: tensorflow<3,>=1.15 in c:\users\sakhawathhossain\appdata\local\continuum\anaconda3\envs\cpu_3.7.6_tfx_3\lib\site-packages (from tfx) (2.0.0)
ERROR: Could not find a version that satisfies the requirement tfx-bsl<0.16,>=0.15.3 (from tfx) (from versions: 0.21.0)
ERROR: No matching distribution found for tfx-bsl<0.16,>=0.15.3 (from tfx)

**Comment by sakhawath19** [comment]
python=3.7.6

**Comment by gowthamkpr** [comment]
@sakhawath19 Were you able to solve this issue?

**Comment by chongkong** [comment]
TFX doesn't support Windows platform at the moment. My recommendation is to try examples in a colab or inside a docker container of ubuntu images.

**Comment by jaymon0703** [comment]
Is TFX still not supported in Windows? I am able to run tfx commands such as `tfx template copy` but run into the issue mentioned [here](https://github.com/tensorflow/tfx/issues/4732) with `tfx pipeline create` when using Windows. I see no mention of OS constraints in the docs.

**Comment by chongkong** [comment]
There are some hard assumptions on the paths that we cannot easily support both posix (/) and windows (\) because TFX pipeline authoring environment and actual runtime environment can be different. We also have to setup all internal testing environments for Windows, but considering it took more than months to stabilize them for MacOS, I'm doubtful someone have enough bandwidth for adding Windows env. The ease of using WSL or docker inside Windows is also a point that deprioritizes the Windows platform support. Sorry for your inconvenience.

**Comment by jaymon0703** [comment]
Thank you @chongkong
