### ISSUE TITLE
Colab Notebook for TF Model Analysis fails due to import error

### ISSUE THREAD

**Issue by navneetkrc** [tensorflow/tfx#1233]
TFMA colab Notebook fails due to different dependencies even of same library for example scipy.
Step Install TensorFlow Model Analysis (TFMA) leads to errors and they require different versions of the same library even TF.
Most of the error is related to **tensorflow-federated** installation.
[TFX Tutorial link](https://www.tensorflow.org/tfx/tutorials/model_analysis/tfma_basic)
[Colab Document Link](https://colab.sandbox.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/model_analysis/tfma_basic.ipynb).

**Comment by gowthamkpr** [comment]
@navneetkrc Thank you for reporting this.

I cannot download the data either from `requests.get('https://storage.googleapis.com/tfx-colab-datasets/eval_saved_models-0.15.0.zip', stream=True)`

**Comment by Myeongjoon** [comment]
Hello. This issue seems to have been resolved at https://github.com/tensorflow/tfx/commit/5e7693e48556b3cf23084a569afeea9d5298f7ca#diff-ec00f49c9ca70498d85df23bbf64a19b.

**Comment by jiyongjung0** [comment]
Thank you for reporting. Let me close this issue.
