### ISSUE TITLE
chicago_taxi.ipynb refers to unreadable eval_saved_models-0.15.0.zip

### ISSUE THREAD

**Issue by msiegler-google** [tensorflow/tfx#1290]
Permissions for the saved models appear to have changed or the file has moved and this demo now cannot be run.

**Comment by chongkong** [comment]
`tfx-colab-datasets` bucket seems to have problem now. ([census.ipynb](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/transform/census.ipynb) is also suffering the same problem)

Robert, would you be able to give an update?

**Comment by rcrowe-google** [comment]
These tutorials have been updated:

https://www.tensorflow.org/tfx/tutorials/transform/census
https://www.tensorflow.org/tfx/tutorials/data_validation/tfdv_basic
https://www.tensorflow.org/tfx/tutorials/model_analysis/tfma_basic
