### ISSUE TITLE
Is there any example of nlp, like text classification? string input, not other data preprocess outside. 

### ISSUE THREAD

**Issue by yongzhuo** [tensorflow/tfx#1302]
Is there any example of nlp, like text classification? string input, not other data preprocess outside.

**Comment by chongkong** [comment]
We don't have an example for NLP use cases yet. Our examples (as you can check in tfx/examples directory) are either structured data (chicago taxi, iris) or a vision data (mnist, cifar10). We'd like to have examples for other domains, but we don't have a plan yet.

**Comment by palakkala** [comment]
is there example available now on nlp-tfx ?
