### ISSUE TITLE
Expected way to deal with missing values

### ISSUE THREAD

**Issue by timatim** [tensorflow/tfx#1337]
What is the recommended practice to deal with missing values, specific w.r.t. TF transform and TF data validation? As I was working with the two, I notice that my TF transform job fails whenever there's a missing value in a feature, if I specified that feature to be FixLenFeature. 

One way to mitigate this is to impute the missing values at the step where I'm generating the raw data. However, this contradicts with TF data validation, where it computes the % of missing values in each feature.

Another way to mitigate this is to define every feature as VarLenFeature. To my understanding, VarLenFeature means that the feature can take on greater than or equal to 0 values, while FixLenFeature is for features that are expecting 0 (missing) or 1 value. While that resolves this issue, is that the recommended behavior?

**Comment by gowthamkpr** [comment]
You can impute the missing values using mean, please go through the following [issue](https://github.com/tensorflow/transform/issues/152) where imputing missing values is discussed in depth.

You can also go through the following [doc](https://www.tensorflow.org/tfx/transform/get_started#input_and_output_with_apache_beam) to understand how missing values are being imputed. Thanks!

**Comment by gowthamkpr** [comment]
@timatim Do you still have any doubts?

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
