### ISSUE TITLE
Add correlations to TFDV

### ISSUE THREAD

**Issue by ianhellstrom** [tensorflow/tfx#134]
TensorFlow Data Validation is a great tool to look at the data. One feature that might make it even better is if it would also compute correlations among the variables, so that if two variables are highly correlated you can avoid multicollinearities by dropping one of the correlated variables. Having that available in the facets visualization would make it easier to spot issues with the data.

**Comment by gowtham-kp** [comment]
@ianhellstrom Thank you for the recommendation. Can you please post the issue [here](https://github.com/tensorflow/data-validation/issues) as this issue is more suited to the TFDV repository. Thanks!

**Comment by ianhellstrom** [comment]
See: https://github.com/tensorflow/data-validation/issues/66

Feel free to close the issue here.

**Comment by gowtham-kp** [comment]
Thank you @ianhellstrom I'm closing this issue as a new issue has been created in TFDV Repository.
