### ISSUE TITLE
Feature request: passing statistics to a Trainer

### ISSUE THREAD

**Issue by jasonbrancazio** [tensorflow/tfx#1355]
Sometimes it might be helpful to use the statistics output by StatisticsGen as metadata for a Trainer. For example, one can intelligently set the number of training steps within the Trainer based on the number of examples in the input data.

Unfortuntely, Trainer is currently not configured to accept a StatisticsGen output channel. Using named arguments, Trainer accepts transformed examples, a transform graph, and a schema, but not statistics. Furthermore, the statistics channel can't be passed in as part of custom config, due to the way custom configs are logged when Trainer starts up.

Specifically, in https://github.com/tensorflow/tfx/blob/master/tfx/components/base/base_executor.py#L166 json.dumps is used to log custom configs at startup. When trying to pass statistics_gen.outputs['statistics'] in the custom configs, one receives an error that Object of type Channel is not JSON serializable [while running 'Run[Trainer.trainer]']

One possible solution is to involve the jsonify_artifact_dict function that currently logs the inputs and outputs of trainer in the logging of the custom configs.  See https://github.com/tensorflow/tfx/blob/8a72a771932d6d8a7a83d0411a21be8fada26ccc/tfx/types/artifact_utils.py#L44  Specifically, the value associated with each key in custom configs could be logged using json.dumps unless the key-value pair is [Text, List[Artifact]] in which case jsonify_artifact_dict could be called. This could however prove to be a fragile solution.

A better solution would be to make statistics a first-class input to Trainer, similar to transform_graph, transformed_examples, and schema.

**Comment by charlesccychen** [comment]
CC: @1025KB 

Thanks, I filed an internal bug.

**Comment by nikelite** [comment]
Thank for reporting this. 

Custom configs would not be a good solution to pass the artifacts like StatisticsGen output.
We recommend using Custom TFX Component to tweak input and output channels.

Document:
https://github.com/tensorflow/tfx/blob/master/docs/guide/custom_component.md
Examples:
https://github.com/tensorflow/tfx/tree/master/tfx/examples/custom_components

**Comment by jasonbrancazio** [comment]
@nikelite I agree that custom configs are not a good solution for passing artifacts. But rather than forcing users to make a custom component, why not give further consideration to making statistics an input channel to the standard Trainer? I imagine users would have a variety of use cases for the information provided by running StatisticsGen after a Transform.

In addition, adding statistics as an Optional input channel could help with pipeline ordering. If a user currently runs Transform -> StatisticsGen (post-transform) -> Trainer, there doesn't seem to be a way of guaranteeing that the post-transform StatisticsGen runs before the Trainer.

**Comment by nikelite** [comment]
Thank you for the suggestion. Charles already filed an internal bug on that, and we will discuss that internally.
