### ISSUE TITLE
Evaluator and ModelValidator will create processes base on number of cpu

### ISSUE THREAD

**Issue by HugoPu** [tensorflow/tfx#1376]
In the [tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/airflow_workshop/), it will create workers base on the number of cpu, which is mentioned in the following code:
```
# 'DAG' below need to be kept for Airflow to detect dag.
DAG = AirflowDagRunner(_airflow_config).run(
    _create_pipeline(
        pipeline_name=_pipeline_name,
        pipeline_root=_pipeline_root,
        data_root=_data_root,
        module_file=_module_file,
        serving_model_dir=_serving_model_dir,
        metadata_path=_metadata_path,
        # 0 means auto-detect based on on the number of CPUs available during
        # execution time.
        direct_num_workers=0))
```
But models are usually trained by gpus, and if it creates workers base on cpus.  It will create mayny works, and may have no enough ram, and will raise the folloing error:
```
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[{{node save/RestoreV2}}]]
```

**Comment by charlesccychen** [comment]
CC: @1025KB 

Thank you for raising this issue.  We will look into fixing this use case.

**Comment by 1025KB** [comment]
Hi, it's a known issue, a workaround would be try "TF_FORCE_GPU_ALLOW_GROWTH=true" env var, if it still OOM, you can set direct_num_workers=n to use certain number of processes

**Comment by HugoPu** [comment]
Maybe there's something wrong with my description. What I mean is, models are usually trained by gpus, and creating workers base on cpus are strange, expecially in the tutorial. It may mean that running the code of tutorial with tensorflow-gpu will probably get errors.
