### ISSUE TITLE
io_utils.copy_dir() does not correctly copy nested subdirectories

### ISSUE THREAD

**Issue by jesand** [tensorflow/tfx#1377]
The copy_dir() method does not correctly build destination paths for creating nested subdirectories in the call to tf.io.gfile.makedirs(). It assumes that all subdirectories (recursively) are beneath the original destination directory, dst.  The path should be built similarly to how paths for leaf_files are built: a line like the line defining new_file_path should be inserted before the call to makedirs().

**Comment by pindinagesh** [comment]
@jesand 

Can you please share the standalone code to reproduce the issue from our end? Thanks!

**Comment by pindinagesh** [comment]
Hi @jesand 

Can you take a look at the workaround proposed in this [issue](https://github.com/tensorflow/tfx/issues/1915) and see if it helps in resolving your issue?. Closing this issue for now due to inactivity and please feel free to open if this exist. Thanks
