### ISSUE TITLE
taxi_pipeline_interactive.ipynb: estimator created from keras model does not contain same SignatureDefs as precanned estimator

### ISSUE THREAD

**Issue by Mar-ai** [tensorflow/tfx#1434]
The model which is created by running the taxi_pipeline_interacitve.ipynb with the precanned estimator exports the following SignatureDefs:  
```
The given SavedModel MetaGraphDef contains SignatureDefs with the following keys:
SignatureDef key: "classification"
SignatureDef key: "predict"
SignatureDef key: "regression"
SignatureDef key: "serving_default"
```

I modified the taxi_pipeline_interacitve.ipynb to create an estimator from a keras model (by using tf.keras.estimator.model_to_estimator). The pipeline seems to work fine, but the exported model only contains the serving_default (which is "predict"). 

```
The given SavedModel MetaGraphDef contains SignatureDefs with the following keys:
SignatureDef key: "serving_default"


MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['examples'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_example_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['probabilities'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: probabilities/Sigmoid:0
  Method name is: tensorflow/serving/predict

```

I need the model to contain both the predict and the classify signature. Could you advise me what I need to modify to get a "estimator-derived-from-keras-model" that exports the same signatureDefs as a precanned estimator?

**Comment by gowthamkpr** [comment]
@Mar-ai This is related to tensorflow itself. Please take a look at this [issue](https://github.com/tensorflow/serving/issues/1521) and let me know if it helps. Thanks!

**Comment by Mar-ai** [comment]
Thanks @gowthamkpr, I'll give changing  [_generate_signatures](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/save.py#L466) a try. 
I saw that the issue is already tracked on [this issue](https://github.com/tensorflow/tensorflow/issues/34968) so I'll close this for now.
