### ISSUE TITLE
Bump Beam dependency version to 2.19.0 

### ISSUE THREAD

**Issue by Jeffwan** [tensorflow/tfx#1446]
Here's some new features and improvements in 2.19.0 we want to leverage in TFX. 

Changlog.
https://beam.apache.org/blog/2020/02/04/beam-2.19.0.html

There's a few breaking changes and I am not sure if TFX have these references. It may not be an easy version upgrade. 

- BEAM-8989 Backwards incompatible change in ParDo.getSideInputs (caught by failure when running Apache Nemo quickstart)
- BEAM-8402 Backwards incompatible change related to how Environments are represented in Python DirectRunner.
- BEAM-9218 Template staging broken on Beam 2.18.0

Related issue: https://github.com/tensorflow/tfx/issues/1219

**Comment by jiyongjung0** [comment]
We are already using apache beam `>=2.38`.  Let me close this bug.
