### ISSUE TITLE
How to pass custom component to DataflowRunner?

### ISSUE THREAD

**Issue by sadeel** [tensorflow/tfx#1455]
I am using TFX on Kubeflow. I have written a custom component that does some work. I want that library (defining the custom_component) to be available on the Dataflow runner. Is there an example of how to do it?

Right now, it is complaining that my "custom_component" does not exist.

**Comment by neuromage** [comment]
@sadeel can you use the TFX CLI [1] to package your custom component? See for example the part about building the image with `skaffold` mentioned in [2]. See also the custom component docs in [3]

[1] https://github.com/tensorflow/tfx/blob/master/docs/guide/cli.md
[2] https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/template_beam.ipynb
[3] https://github.com/tensorflow/tfx/blob/master/tfx/examples/custom_components/slack/README.md#compile-the-pipeline-gcp

**Comment by sadeel** [comment]
I've done that and that works well when running just in KFP. However, inside KFP, I need to start a Dataflow job, and the Dataflow job needs to be aware of my custom component - I haven't figured a good way to do that.

**Comment by neuromage** [comment]
Got it, this is a missing feature right now. We'll take a look at fixing this.

**Comment by hbrylkowski** [comment]
@sadeel - I'm having the same issue, do you have any solutions? I considered:

- not using custom component (in my case I'm using it for ingestion so it's possible) but that's not the way it's supposed to be done.
- package it and ship as a python package which will be installed on TFX container start - should work but a lot of repetetive work and component will be defined in two places, possibly with different code - increases possibility of bugs
- passing `module.py` argument to component with file on s3 where it's defined, exactly how it's done for Trainer. But I haven't tried that one yet, based on source code for orchestration I think it might work, but it still raises same issues as python package.

**Comment by gowthamkpr** [comment]
@sadeel As mentioned [above](https://github.com/tensorflow/tfx/issues/1455#issuecomment-953972920), the above steps work perfectly. Just make sure you are using the docker image. Please go ahead and close the issue as it has been resolved. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been stale for 2 weeks. Please update response, and we will reopen it again. Thanks!!
