### ISSUE TITLE
About eager mode in tfx with tf 1.x and future plan

### ISSUE THREAD

**Issue by wendy2003888** [tensorflow/tfx#1469]
hi tfx experts,

When tfx 0.21.0 running on tf1.15, can I enable eager mode? Or it is not possible?
 I added tf.executing_eagerly() to the first line under the main function, but it seems to not work. 

I am also writing a native Keras pipeline. The Evaluator is not working under tf 1.x
I noticed that the native Keras example indirectly calls tf2 only attributes or apis.  What's the plan of tf 1.x support?

Here are code pointers about tf2 only apis:
Evaluator -> tfma.ExtractEvaluateAndWriteResults -> default_extractors -> predict_extractor_v2(because to label blessing in evaluator, it need a  eval_config which cause _is_legacy_eval returns false ) -> xxx.numpy()

https://github.com/tensorflow/tfx/blob/master/tfx/components/evaluator/executor.py#L181
https://github.com/tensorflow/model-analysis/blob/7b804120e244dcdcd8d43644346ba014311bf9b5/tensorflow_model_analysis/api/model_eval_lib.py#L505
https://github.com/tensorflow/model-analysis/blob/8fc582136295e783d14cd00acb089c06bb7ac52e/tensorflow_model_analysis/extractors/predict_extractor_v2.py#L150

logs related to my previous runs:
```
File "apache_beam/runners/common.py", line 441, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/usr/local/google/home/wendycbh/tf1/lib/python3.7/site-packages/tensorflow_model_analysis/model_util.py", line 238, in process
    result = self._batch_reducible_process(elements)
  File "/usr/local/google/home/wendycbh/tf1/lib/python3.7/site-packages/tensorflow_model_analysis/extractors/predict_extractor_v2.py", line 160, in _batch_reducible_process
    output = {k: v[i].numpy() for k, v in outputs.items()}
  File "/usr/local/google/home/wendycbh/tf1/lib/python3.7/site-packages/tensorflow_model_analysis/extractors/predict_extractor_v2.py", line 160, in <dictcomp>
    output = {k: v[i].numpy() for k, v in outputs.items()}
AttributeError: 'Tensor' object has no attribute 'numpy' [while running 'ExtractEvaluateAndWriteResults/ExtractAndEvaluate/ExtractPredictions/Predict']
 [while running 'Run[Evaluator]']
```

Thank you
Wendy

**Comment by rmothukuru** [comment]
@wendy2003888,
 Can you please try executing the command, `tf.enable_eager_execution()` instead of `tf.executing_eagerly()` to Enable the Eager Execution and let me know how it goes. Thanks!

**Comment by wendy2003888** [comment]
@rmothukuru 
This doesn't work.  I checked that eager mode was enabled before tfx pipeline runs. My guess is inside tfx, it set to run graph mode only.  Or maybe it's related to the apache_beam?

**Comment by wendy2003888** [comment]
hi,
Any update on this question? The error is version related. My code don't have issues running under tf 2.0. Will keras models be supported under tf 1.x?
