### ISSUE TITLE
Example for using custom beam PTransform in preprocessing_fn

### ISSUE THREAD

**Issue by mattmbk** [tensorflow/tfx#1507]
Hi, I've been trying to execute a pipeline with a custom beam PTransform in the preprocessing_fn with no luck.

Using a notebook with the interactive context I'm running into this error:
python3.6/site-packages/apache_beam/internal/pickler.py in _is_nested_class(cls)
     75           and cls.__module__ != 'builtins'     # Python 3
     76           and cls.__module__ != '__builtin__'  # Python 2
---> 77           and cls.__name__ not in sys.modules[cls.__module__].__dict__)
     78 
     79 

KeyError: 'user_module'

I have my custom PTransform defined in the util.py file (which seems to be an issue). Are there any examples anywhere for writing custom transforms and applying them with tft.ptransform_analyzer ?

Thanks!

**Comment by zoyahav** [comment]
Have you tried importing the custom PTransform into the notebook with something like this?
`import util as user_module`

**Comment by mattmbk** [comment]
Excellent tip, @zoyahav 

This seems to have resolved the error I mentioned. Thanks!
