### ISSUE TITLE
Over rapped TFX libraries character layout into TensorFlow Serving and Model Server on Docs

### ISSUE THREAD

**Issue by hurutoriya** [tensorflow/tfx#1519]
I found one part of the broken image in TFX docs.
But I can't edit this SVG, so I reported as issues.

![image](https://user-images.githubusercontent.com/2786333/77253640-d9a01100-6c9e-11ea-9921-3837d62b76ae.png)

https://github.com/tensorflow/tfx/blob/master/docs/guide/libraries_components.svg

**Comment by jiyongjung0** [comment]
Thank you for reporting!
Did you see this image in the guide document in https://www.tensorflow.org/tfx/guide ?

Because it renders well in my environment, can you share your browser environment when the image is broken?

**Comment by hurutoriya** [comment]
@jiyongjung0 Thanks for response 👍 
>Did you see this image in the guide document in https://www.tensorflow.org/tfx/guide ?
right.

I use Mac OS Chrome 80.0.3987.149.

I see.
My browser render below image in https://www.tensorflow.org/tfx/guide#tfx_libraries

![image](https://user-images.githubusercontent.com/2786333/77499188-c191e280-6e94-11ea-99e9-e174a565ff86.png)

> Because it renders well in my environment
Seem like this issues is not serious.

**Comment by jiyongjung0** [comment]
Thank you for the detail!

I'm using exactly same broswer / version, but it looks good.
But I found that the image looks ugly(as you have shown above) in MacOS Safari 13.0.5.

I think that this can be fixed by using png or other formats.
