### ISSUE TITLE
StatisticsGen doesn't seem to handle custom split

### ISSUE THREAD

**Issue by sadeel** [tensorflow/tfx#1532]
I have a dataset that has a custom split:

  inputt = example_gen_pb2.Input(splits=[
      example_gen_pb2.Input.Split(name='train', pattern='train*'),
      example_gen_pb2.Input.Split(name='val', pattern='val*'),
      example_gen_pb2.Input.Split(name='test', pattern='test*'),
  ])

  examples = tfrecord_input(_tfrecord_folder_parameter)
  example_gen = ImportExampleGen(input=examples, input_config=inputt)
  stats_gen = StatisticsGen(examples=example_gen.outputs['examples'])

However, when StatisticsGen runs, I get the following error:

Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 378, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 371, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/statistics_gen/executor.py", line 119, in Do
    split)
  File "/tfx-src/tfx/types/artifact_utils.py", line 106, in get_split_uri
    'artifacts %s.') % (split, matching_artifacts))
ValueError: Expected exactly one artifact with split 'val', but found matching artifacts [].

**Comment by 1025KB** [comment]
Hi, currently example gen's downstream only support 'train' and 'eval' split, we will fix stats gen to support all splits

**Comment by sadeel** [comment]
Ok thanks. Btw, this issue seems to also appear in other components (e.g. trainer)

**Comment by 1025KB** [comment]
yep, currently for all other components, we use 'train' and 'eval' splits as training and eval dataset

**Comment by gowthamkpr** [comment]
@sadeel Did the above comment answer your question.

**Comment by 1025KB** [comment]
I submit a [PR](https://github.com/tensorflow/tfx/pull/1534) that fix the stats gen split issue, you can try if it works for you, we will include that PR in our next release
