### ISSUE TITLE
CsvExampleGen for gzipped csv

### ISSUE THREAD

**Issue by marsbroshok** [tensorflow/tfx#1533]
Is it possible to use `CsvExampleGen` component with gzipped csv input file? Files with extension ".csv.gz" are transparently supported by BigQuery and Pandas, so it will be nice to be able to read it with `CsvExampleGen` component as well.

**Comment by gowthamkpr** [comment]
@marsbroshok Currently ".csv,gz" files are not supported by `CsvExampleGen`

**Comment by chongkong** [comment]
As underlying Beam support auto compression detection it wouldn't be too difficult to implement it. We added it to our backlog.

**Comment by yantriks-edi-bice** [comment]
Tested with TFX 0.26.0 and it seems to work. Should close this.

**Comment by marsbroshok** [comment]
Thanks a lot!
