### ISSUE TITLE
serving_model is not created for tf.estimator.BoostedTreesRegressor by the tfx Trainer

### ISSUE THREAD

**Issue by ghost** [tensorflow/tfx#1535]
Hi,

I used the tfx end-to-end tutorial to use tf.estimator.BoostedTreesRegressor.
We are having the issue that the trainer wouldn't produce the serving model, making it difficult to make inference. 

```
def _build_estimator_boosted_tree_regressor(config, 
                                            schema, 
                                            tf_transform_output,
                                            n_batches_per_layer=1,
                                            n_trees=100):
    feature_columns = [tf.feature_column.numeric_column(key, shape=()) 
                       for key in (integer_columns+float_columns)]
    for key in categorical_columns:
        vocabulary_list = tf_transform_output.vocabulary_by_name(key)
        feature_columns.append(tf.feature_column.indicator_column(
            tf.feature_column.categorical_column_with_identity(key, len(vocabulary_list),
                                                               default_value=0)
            )
        )
        
    return tf.estimator.BoostedTreesRegressor(feature_columns,
                                        n_batches_per_layer=n_batches_per_layer,
                                        n_trees=n_trees)
```
```
trainer = Trainer(
    module_file=os.path.abspath(_tfx_trainer_module_file),
    transformed_examples=transform.outputs['transformed_examples'],
    schema=schema_gen.outputs['schema'],
    transform_graph=transform.outputs['transform_graph'],
    train_args=trainer_pb2.TrainArgs(num_steps=10000),
    eval_args=trainer_pb2.EvalArgs(num_steps=5000))
context.run(trainer)
```
Execution doesn't produce any errors but when examining the models directory, the eval_model is available without the graph. 

Is this a bug? 
Is there a way around it?

**Comment by gowthamkpr** [comment]
@amadeusDataScienceTeam Can you please provide code with data for us to reproduce this issue. Thanks!

**Comment by 1025KB** [comment]
[This](https://github.com/tensorflow/tfx/blob/master/tfx/components/trainer/executor.py#L327) is how we train and saved the model, did you set the [model output path](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py#L189) ?

**Comment by gowthamkpr** [comment]
@ghost Can you please respond to the above comment so that we can take the discussion further. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open to this issue again.
