### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by gowthamkpr** [tensorflow/tfx#1536]
When I try to click on `View Source on github ` for `tfx.components` [here](https://www.tensorflow.org/tfx/api_docs/python/tfx/components), I am getting page not found error.
![image](https://user-images.githubusercontent.com/47574994/77466246-3860aa00-6dc7-11ea-9cba-78f9f9309f2f.png)

This is happening to all the tfx components..!!

**Comment by yashk2810** [comment]
Thanks for reporting. This was fixed. Can you please try again?

**Comment by gowthamkpr** [comment]
@yashk2810 Thanks! Its working now..!!
