### ISSUE TITLE
Status of continuous pipelines

### ISSUE THREAD

**Issue by iprapas** [tensorflow/tfx#1540]
Hello,

Can I know the status of the development of continuous pipelines? I would like to contribute on this. Is there a fork I can start from? Some kind of roadmap about this  feature? 

I find it weird that this paper [1] suggests that tfx can work for continuous training  in May 2019, when in fact in March 2020 it is only possible to use tfx for one-off training.

Related issues: #210 , #352, #421 

Cheers

[1] Baylor, Denis, et al. "Continuous Training for Production {ML} in the TensorFlow Extended ({TFX}) Platform." 2019 {USENIX} Conference on Operational Machine Learning (OpML 19). 2019.

**Comment by 1025KB** [comment]
Hi, Sorry for the delay, we are planning to have a RFC for batch continuous pipeline in April.

Currently we have a basic support for [span](https://github.com/tensorflow/tfx/blob/master/docs/guide/examplegen.md#span), it's one off batch pipeline but it can pick up the continuously arriving data span. we will have more details in the RFC about the user journey we currently or will support.

**Comment by iprapas** [comment]
Thanks for the prompt reply. I'll stay tuned for the RFC then.
