### ISSUE TITLE
big_query_ml_pusher.Executor not correctly resolving pushed_model key

### ISSUE THREAD

**Issue by tsabsch** [tensorflow/tfx#1553]
The `big_query_ml_pusher.Executor` tries to get the pushed model by retrieving `model_push` from the executor's output_dict:
```[python]
model_push = artifact_utils.get_single_instance(output_dict['model_push'])
```
(https://github.com/tensorflow/tfx/blob/r0.21.2/tfx/extensions/google_cloud_big_query_ml/pusher/executor.py#L61)

`model_push` is a deprecated element of the PusherSpec and now replaced by `pushed_model`. In theory this should not be an issue since a compatibility alias exists for this reason (https://github.com/tensorflow/tfx/blob/v0.21.2/tfx/types/standard_component_specs.py#L208). 

However, the alias functionality doesn't work because the `output_dict` in `big_query_ml_pusher.Executor` is actually not a `_PropertyDictWrapper` (where the compatibility alias would work), but just a simple dict. This is due to the output_dict being retrieved by the `get_all` function:

```[python]
self._output_dict = component.outputs.get_all()
```
(https://github.com/tensorflow/tfx/blob/v0.21.2/tfx/orchestration/launcher/base_component_launcher.py#L80)

`get_all()` returns the raw dict from a `_PropertyDictWrapper`. As a consequence, using the bigquery_ml_pusher results in the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-38-f67dc69712f4> in <module>
----> 1 context.run(pusher)

~/XXX/tfx/tfx/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     64       # __IPYTHON__ variable is set by IPython, see
     65       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 66       return fn(*args, **kwargs)
     67     else:
     68       absl.logging.warning(

~/XXX/tfx/tfx/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    166         component, pipeline_info, driver_args, metadata_connection,
    167         beam_pipeline_args, additional_pipeline_args)
--> 168     execution_id = launcher.launch().execution_id
    169 
    170     return execution_result.ExecutionResult(

~/XXX/tfx/tfx/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    203                          execution_decision.input_dict,
    204                          execution_decision.output_dict,
--> 205                          execution_decision.exec_properties)
    206 
    207     absl.logging.info('Running publisher for %s',

~/XXX/tfx/tfx/tfx/orchestration/launcher/in_process_component_launcher.py in _run_executor(self, execution_id, input_dict, output_dict, exec_properties)
     65         executor_context)  # type: ignore
     66 
---> 67     executor.Do(input_dict, output_dict, exec_properties)

~/XXX/tfx/tfx/tfx/extensions/google_cloud_big_query_ml/pusher/executor.py in Do(self, input_dict, output_dict, exec_properties)
     59     """
     60     self._log_startup(input_dict, output_dict, exec_properties)
---> 61     model_push = artifact_utils.get_single_instance(output_dict['model_push'])
     62     if not self.CheckBlessing(input_dict):
     63       model_push.set_int_custom_property('pushed', 0)

KeyError: 'model_push'
```

I see two problems in the current implementation:
1. `bigquery_ml_pusher.Executor` is using the outdated key `model_push` instead of `pushed_model`
2. By using the `get_all` function in the base component launcher, any compatibility with outdated PropertyDict keys is ignored.

Since I don't know the possible reasoning behind using `get_all`, I would like to propose a PR solving the first problem, once this issue is confirmed.

**Comment by chongkong** [comment]
Thanks for the issue. _PropertyDictWrapper is a temporary mapping while TFX team is renaming component input/output, and inside the component it is expected to use the latest name. So in this case, BQML pusher not using the latest key is the bug.

We've tracked this recently as well (including other inappropriate behaviors) and working on this. It will be fixed in the later release.

**Comment by tsabsch** [comment]
Would a PR to use the Pusher component's PUSHED_MODEL_KEY instead of a hardcoded key name be helpful, or do you want to solve this internally?

**Comment by chongkong** [comment]
There's already a pending change regarding this :)
