### ISSUE TITLE
data validation scheme export to pandas dataframe 

### ISSUE THREAD

**Issue by ra312** [tensorflow/tfx#1564]
Dear Community, 
Thanks for the awesome library tensorflow-data-validation.
I am using it to infer a schema and display it.
Here is a snapshot
 
![image](https://user-images.githubusercontent.com/12486277/78105312-b4d03a00-7412-11ea-948b-b5bac8b2fcce.png)
There are 145 columns. This table above looks like a pandas DataFrame and I was looking for an option to save the output in the picture as a dataframe.
It seems this feature is not yet available. I can see tfx.components.SchemaGen might be help to work better, but the source code is still in its infancy. 
Could anyone advice me on this issue? Thanks!

**Comment by ra312** [comment]
the output of 'conda list | grep tensor'
tensorflow                2.1.0                    pypi_0    pypi
tensorflow-base           2.0.0           mkl_py36h66b1bf0_0
tensorflow-data-validation 0.21.5                   pypi_0    pypi
tensorflow-estimator      2.1.0                    pypi_0    pypi
tensorflow-metadata       0.21.1                   pypi_0    pypi
tensorflow-model-analysis 0.21.6                   pypi_0    pypi
tensorflow-serving-api    2.1.0                    pypi_0    pypi
tensorflow-transform      0.21.2                   pypi_0    pypi

**Comment by arghyaganguly** [comment]
@ra312 ,to write/load the schema to/from a file please use the functions defined below:-

```
from google.protobuf import text_format
from tensorflow.python.lib.io import file_io
from tensorflow_metadata.proto.v0 import schema_pb2

def write_schema(schema, output_path):
  schema_text = text_format.MessageToString(schema)
  file_io.write_string_to_file(output_path, schema_text)

def load_schema(input_path):
  schema = schema_pb2.Schema()
  schema_text = file_io.read_file_to_string(input_path)
  text_format.Parse(schema_text, schema)
  return schema     
 ```

**Comment by ra312** [comment]
Thanks, @arghyaganguly 
I will definitely try it!

**Comment by arghyaganguly** [comment]
@ra312 , please close this if you are satisfied with the given approach.Thanks.

**Comment by arghyaganguly** [comment]
Closing this as it has been awaiting response for some time.Please feel free to reopen with information/insights based on above comment trace.Thanks.
