### ISSUE TITLE
how to launch the airflow webUI which is running in google collaborative.

### ISSUE THREAD

**Issue by kalpa-subbaiah** [tensorflow/tfx#1566]
Hi,

   

 As per previously logged issue I was getting below error while running apache airflow locally in my system.
![image](https://user-images.githubusercontent.com/30182218/78137367-d0ebcf80-7442-11ea-94eb-a87ca58a79f0.png)

Hence I decided to run everything in google collab. Now apache airflow web server is running fine in google collab as given below but I am not able to launch the apache airflow web UI using the link http://0.0.0.0:7070 , Please let me know what IP address/url I need to use to access airflow UI when the airflow Webserver is running in collab.

![image](https://user-images.githubusercontent.com/30182218/78137509-13151100-7443-11ea-97d6-eacf59e43953.png)

**Comment by gowthamkpr** [comment]
@kalpa-subbaiah Please share the gist of colab notebook for us to reproduce this issue. Thanks!

**Comment by kalpa-subbaiah** [comment]
Hi,
    Please find the gist of colab notebook below:
https://gist.github.com/kalpa-subbaiah/f2e819efff8f87171e16e92a83909e08
[code.zip](https://github.com/tensorflow/tfx/files/4431238/code.zip)
Let me know if you need any further details.

**Comment by gowthamkpr** [comment]
@kalpa-subbaiah You can run the airflow web server on colab but the problem is that you cannot run scheduler as this webserver keeps on running. 
Ideally you would open a new shell and run scheduler which opens the airflow web UI but in this case I am not sure how to open a new shell (or a new notebook that has a connected runtime)  on colab.
This is out of the scope of tfx as the issue is related to colab and airflow itself. I would recommend you to run this on your computer and use jupyter notebook for analysis of components.

**Comment by kalpa-subbaiah** [comment]
When I run the Airflow webserver and Airflow scheduler in my local system I get below error as mentioned in the first screenshot of the issue:
ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/ml_metadata/metadata_store/_pywrap_tf_metadata_store_serialized.so, 2): Symbol not found: ____chkstk_darwin
Referenced from: /anaconda3/lib/python3.7/site-packages/ml_metadata/metadata_store/_pywrap_tf_metadata_store_serialized.so (**which was built for Mac OS X 10.15**)

Is this error due to MacOS 10.13, is tfx not compatible with 10.13.

Otherwise please do close the issue as I see no logical conclusion to this.Thank you for your quick support.

**Comment by gowthamkpr** [comment]
Yes as the error suggests, this error should be gone if you use Mac OS X 10.15. I would recommend using Mac OS 10.15. @kalpa-subbaiah
