### ISSUE TITLE
Code formatting can affect the semantic behavior of tfx pipelines (DagRunner not being registered)

### ISSUE THREAD

**Issue by AlirezaSadeghi** [tensorflow/tfx#1567]
https://github.com/tensorflow/tfx/blob/bfbc9587c568c1247f6a6cfb59db161ed3a4970c/tfx/tools/cli/handler/base_handler.py#L106-L117

The referenced code is where the issue happens.

As can be seen, it checks for existence of a `KubeflowDagRunner(...)` in the contents, but that's a naive assumption since the opening and closing parenthesis can be in separate lines and in that case the regex won't match.

### Steps to reproduce the issue:
The following piece of code _works just fine_.
```python
 kf_config = KubeflowDagRunnerConfig(
        kubeflow_metadata_config=kf_metadata,
        tfx_image=os.environ.get("KUBEFLOW_TFX_IMAGE", None),
 )

KubeflowDagRunner(config=kf_config)
```

The following piece of code though, _fails_ with **_kubeflow runner not found in dsl._**
```python
KubeflowDagRunner(
    config=KubeflowDagRunnerConfig(
           kubeflow_metadata_config=kf_metadata,
           tfx_image=os.environ.get("KUBEFLOW_TFX_IMAGE", None),
     )
)
```

Output of the `tfx pipeline create` cli command is as follows:
```
CLI
Updating pipeline
Detected Kubeflow.
Use --engine flag if you intend to use a different orchestrator.
Reading build spec from build.yaml
Use skaffold to build the container image.
/usr/local/bin/skaffold
kubeflow runner not found in dsl.
New container image is built. Target image is available in the build spec file.
```

**Comment by chongkong** [comment]
Yeap this is problematic. Sorry for your inconvenience.

**Comment by jiyongjung0** [comment]
FYI, the runner check based on text matching was deleted in https://github.com/tensorflow/tfx/commit/cf3e338a015118334225cf357a0925c1ccf312a3. We now use metaprogramming to determine whether the runner is setup correctly.
