### ISSUE TITLE
AI platform pusher: Custom version name

### ISSUE THREAD

**Issue by tordsae** [tensorflow/tfx#1575]
Currently when using the pusher in with a native keras model, the version pushed to AI platform is named vserving_model_dir. I am trying to figure out if the is or going to be a way of defining the model version name?

**Comment by gowthamkpr** [comment]
@tordsae Is there any specific application for this that might help the community?

**Comment by tordsae** [comment]
Not any specific application other than more user freedom. The main problem is that now all versions get the name vserving_model_dir due to how the version name if selected.

**Comment by jiyongjung0** [comment]
Thank you for raising this issue and sorry for the late response.

Recently [related code](https://github.com/tensorflow/tfx/blob/6e88e4fef3d80c35b43d397b052412db24235a16/tfx/extensions/google_cloud_ai_platform/pusher/executor.py#L94) changed to generate the version name with timestamp. So it might resolve the problem with the same name for all pipeline runs.
