### ISSUE TITLE
how to pass the tfx transformer output as data to tensorflow serving

### ISSUE THREAD

**Issue by kalpa-subbaiah** [tensorflow/tfx#1584]
Dear Team,

         
As per the tutorials https://www.tensorflow.org/tfx/tutorials/tfx/components_keras I have got the serving model which I want to serve using tensorflow serving.
          
![image](https://user-images.githubusercontent.com/30182218/78458126-a4e37f00-76cc-11ea-9405-bcddbb77ddf3.png)

Now that the Tensorflow serving is running not sure how to send the transform output of Chicago taxi dataset as data to tensorflow serving in the request.post call.Tried different ways which didn't help. Your guidance on this will be of great help.

![image](https://user-images.githubusercontent.com/30182218/78458212-37841e00-76cd-11ea-8219-44df5ae23889.png)

The signature shows as below:

![image](https://user-images.githubusercontent.com/30182218/78498841-71efc880-776a-11ea-8ec5-0ea99ca8934b.png)

**Comment by gowthamkpr** [comment]
Please take a look at an example [here](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/serving/chicago_taxi_client.py) on how to preprocess data in client file.

**Comment by kalpa-subbaiah** [comment]
will check this and get back

**Comment by kalpa-subbaiah** [comment]
Hi Gowtham,

        Thank you very much for sharing the link, It resolved my problem.

**Comment by rothn** [comment]
That link probably works for some TFX models. For my TFX model, which takes a single BYTES input, I needed to use something slightly different:
```
predictions = model.signatures['predict'](tf.constant(['bytes_list { value: "I am some text" }'], dtype=tf.string))
```

In this case, the model was exported by TFX for use with [Servomatic (Google Cloud AI Blog Link)](https://cloud.google.com/blog/topics/developers-practitioners/automating-self-service-tech-support-with-tensorflow/). Closely related: [SavedModel format](https://www.tensorflow.org/guide/saved_model), [TensorFlow Serving](https://www.tensorflow.org/tfx/guide/serving).
