### ISSUE TITLE
Chicago taxi simple pipeline does not work with python3.7

### ISSUE THREAD

**Issue by gautamkmr** [tensorflow/tfx#1587]
I followed the instruction as mentioned in the [document](https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi_pipeline) however airflow did not load or even showed the `chicago_taxi_simple` in DAG list.

**Comment by gowthamkpr** [comment]
Are you able to run it using python 3.6?

**Comment by gautamkmr** [comment]
yes, thanks
