### ISSUE TITLE
Can a standard Python `.gitignore` be added?

### ISSUE THREAD

**Issue by aaronlelevier** [tensorflow/tfx#16]
Can a standard Python `.gitignore` be added?

This is the one that I usually start off with:

[https://github.com/github/gitignore/blob/master/Python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore)

**Comment by hgadig** [comment]
@aaronlelevier  I think tfx repo is not the right place to post this issue ? Please correct me if I'm wrong.

**Comment by aaronlelevier** [comment]
Ok, enough said. I'm going to close it. Thanks

**Comment by zhitaoli** [comment]
> @aaronlelevier I think tfx repo is not the right place to post this issue ? Please correct me if I'm wrong.

Hi @hgadig, can you explain why you think this is not the right place to post the issue? I feel that a well curated .gitignore will help whoever develops code on top of the tfx repo and this seems a proper way to report such improvement.

**Comment by hgadig** [comment]
Okay. Now I got confirmation from you that this has been asked for tfx. I asked to correct me if I am wrong in my previous comment. Apologies if my words misled the user to close it.

**Comment by hgadig** [comment]
I asked to correct me if it's wrong. Now I got clarity that this was asked for tfx repo.
Apologies if my previous comments misled the user to close it.

**Comment by aaronlelevier** [comment]
Just curious, what is `tensorflower`?

**Comment by wjarek2** [comment]
re: TensorFlower - I don't have a precise definition but I bet @dynamicwebpaige does :)

**Comment by wjarek2** [comment]
another reference from @mrry: https://twitter.com/mrry/status/836286124830044160?lang=en
