### ISSUE TITLE
TFX Bug in github tfx python script component_keras.ipython

### ISSUE THREAD

**Issue by pradeepmishra11** [tensorflow/tfx#1608]
# Use TFMA to compute a evaluation statistics over features of a model and
# validate them against a baseline.

# The model resolver is only required if performing model validation in addition
# to evaluation. In this case we validate against the latest blessed model. If
# no model has been blessed before (as in this case) the evaluator will make our
# candidate the first blessed model.
model_resolver = ResolverNode(
      instance_name='latest_blessed_model_resolver',
      resolver_class=latest_blessed_model_resolver.LatestBlessedModelResolver,
      model=Channel(type=Model),
      model_blessing=Channel(type=ModelBlessing))
context.run(model_resolver)

evaluator = Evaluator(
    examples=example_gen.outputs['examples'],
    model=trainer.outputs['model'],
    baseline_model=model_resolver.outputs['model'],
    # Change threshold will be ignored if there is no baseline (first run).
    eval_config=eval_config)
context.run(evaluator)
![model_resolver](https://user-images.githubusercontent.com/14539261/78890775-db7e1880-7a83-11ea-8fc5-a3a098048a80.png)

bugs
INFO:absl:Running driver for ResolverNode.latest_blessed_model_resolver
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Registering a new execution type with id 17.
WARNING:absl:Artifact type ModelBlessing not registered
INFO:absl:Running publisher for ResolverNode.latest_blessed_model_resolver
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Running driver for Evaluator
INFO:absl:MetadataStore with DB connection initialized
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-5fbedf450213> in <module>
     19     # Change threshold will be ignored if there is no baseline (first run).
     20     eval_config=eval_config)
---> 21 context.run(evaluator)

~/taxi_pipeline/lib/python3.6/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     64       # __IPYTHON__ variable is set by IPython, see
     65       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 66       return fn(*args, **kwargs)
     67     else:
     68       absl.logging.warning(

~/taxi_pipeline/lib/python3.6/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    166         component, pipeline_info, driver_args, metadata_connection,
    167         beam_pipeline_args, additional_pipeline_args)
--> 168     execution_id = launcher.launch().execution_id
    169 
    170     return execution_result.ExecutionResult(

~/taxi_pipeline/lib/python3.6/site-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    195                       self._component_info.component_id)
    196     execution_decision = self._run_driver(self._input_dict, self._output_dict,
--> 197                                           self._exec_properties)
    198 
    199     if not execution_decision.use_cached_results:

~/taxi_pipeline/lib/python3.6/site-packages/tfx/orchestration/launcher/base_component_launcher.py in _run_driver(self, input_dict, output_dict, exec_properties)
    164           driver_args=self._driver_args,
    165           pipeline_info=self._pipeline_info,
--> 166           component_info=self._component_info)
    167 
    168       return execution_decision

~/taxi_pipeline/lib/python3.6/site-packages/tfx/components/base/base_driver.py in pre_execution(self, input_dict, output_dict, exec_properties, driver_args, pipeline_info, component_info)
    232                                                    component_info)
    233     input_artifacts = self.resolve_input_artifacts(input_dict, exec_properties,
--> 234                                                    driver_args, pipeline_info)
    235     self.verify_input_artifacts(artifacts_dict=input_artifacts)
    236     absl.logging.debug('Resolved input artifacts are: %s', input_artifacts)

~/taxi_pipeline/lib/python3.6/site-packages/tfx/components/base/base_driver.py in resolve_input_artifacts(self, input_dict, exec_properties, driver_args, pipeline_info)
    142                 'components must first be run with '
    143                 '`interactive_context.run(component)` before their outputs can '
--> 144                 'be used in downstream components.') % (artifact, name))
    145         result[name] = artifacts
    146       else:

ValueError: Unresolved input channel Artifact(type_name: Model, uri: , id: 0) for input 'baseline_model' was passed in interactive mode. When running in interactive mode, upstream components must first be run with `interactive_context.run(component)` before their outputs can be used in downstream components.

**Comment by gowthamkpr** [comment]
@pradeepmishra11 Please format the code and provide us the exact steps for us to reproduce this error. Please format the issue in a readable format. Thanks!

**Comment by pradeepmishra11** [comment]
model_resolver = ResolverNode(
      instance_name='latest_blessed_model_resolver',
      resolver_class=latest_blessed_model_resolver.LatestBlessedModelResolver,
      model=Channel(type=Model),
      model_blessing=Channel(type=ModelBlessing))
context.run(model_resolver)

evaluator = Evaluator(
    examples=example_gen.outputs['examples'],
    model=trainer.outputs['model'],
    #baseline_model=model_resolver.outputs['model'],
    # Change threshold will be ignored if there is no baseline (first run).
    eval_config=eval_config)
context.run(evaluator)
![bugg_created](https://user-images.githubusercontent.com/14539261/78965131-c9e75000-7b19-11ea-8fe0-29b6effd9feb.png)

**Comment by gowthamkpr** [comment]
@pradeepmishra11 I am not able to reproduce this issue. Can you provide reproducible code for us to reproduce this issue, not just a part of it. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to open this issue again. Thanks!
