### ISSUE TITLE
TFX on component python script 

### ISSUE THREAD

**Issue by pradeepmishra11** [tensorflow/tfx#1609]
![comonent](https://user-images.githubusercontent.com/14539261/78891155-95758480-7a84-11ea-83fa-f51e8af7b42a.png)
![component_1](https://user-images.githubusercontent.com/14539261/78891159-97d7de80-7a84-11ea-9f82-09991e27ead1.png)

**Comment by gowthamkpr** [comment]
@pradeepmishra11 Please provide the code and steps you followed to reproduce the error and please avoid screenshots. Thanks!

**Comment by gowthamkpr** [comment]
Also I am gonna close this issue as its already being tracked [here](https://github.com/tensorflow/tfx/issues/1608). Please add additional comments for us to open this issue again.
