### ISSUE TITLE
tfma.view.render_slicing_metrics not working

### ISSUE THREAD

**Issue by rathnasubramanian2603** [tensorflow/tfx#163]
Hi, 
     I am following the tutorials of setting up TFX pipeline . All the steps of the airflow pipeline are working without any error. I am able to see the metric results but the render_slicing_metrics returns empty visualization. 

```
import tensorflow_model_analysis as tfma
tfma_artifact = store.get_dest_artifact_of_type(
        11,'ModelEvalPath')
tfma.load_eval_result(tfma_artifact.uri)
tfma.view.render_slicing_metrics(tfma.load_eval_result(tfma_artifact.uri))
```
![image](https://user-images.githubusercontent.com/20776844/58153518-db6b0380-7c8c-11e9-823c-7997e1f81a05.png)

But I can see the results.... 

**[EvalResult(slicing_metrics=[((('trip_start_hour', 2),), {'precision': {'doubleValue': 0.6666666865348816}, 'accuracy_baseline': {'doubleValue': 0.8188405632972717}, 
...................................
'predictioexample_weight_metric_key='post_export_metrics/example_count', num_bootstrap_samples=1))]**

Please let me know why i am not able to render the results  to visualizer?

**Comment by Malonl** [comment]
I am having the same problem.

**Comment by andrewlarimer** [comment]
I had this problem when using Firefox, but it seemed to render in Chrome. Does viewing in Chrome work for you?

**Comment by rathnasubramanian2603** [comment]
@andrewlarimer I am using Ubuntu. I tried in Chromium Web Browser. It is not working in Chromium Browser.

**Comment by Malonl** [comment]
I have been using Chrome on Ubuntu as well, and it's not working.

**Comment by Efaq** [comment]
@andrewlarimer In general, the visualizations would only work in Chrome, because of a Facets issue (see very end of github page https://github.com/PAIR-code/facets). But specifically this one is not working even when we use Chrome.

**Comment by pfyang** [comment]
It would be great if you could provide more information to help debug the issue:
- Version of TFMA
- Version of Chrome
- Any error in the browser? (Press F12 and go the console tab. Please expand the error and paste them here if possible.)

Thanks!

**Comment by rathnasubramanian2603** [comment]
Version of TFMA : 0.13.2
Version of Chromium : Version 74.0.3729.169 (Official Build) 
No Error in Browser.

**Comment by pfyang** [comment]
For clarification, are you using Chrome or Chromium? If you are using Chromium, could you please try Chrome from:
  https://www.google.com/chrome/

What is the environment you are running TFX? eg: single machine vs cloud, OS version, etc.

Do you see any error in other parts of the develoepr console? eg: network tab

If you have access to a different machine, could you please give it a try? You should be able to just copy the output to that machine for visualization.

Thanks!

**Comment by rathnasubramanian2603** [comment]
I was using Chromium . Now I installed Chrome Version 74.0.3729.169 (Official Build) (64-bit).

But still the same problem persists. The render slicing metrics returns empty visualization. 

I am not seeing errors in any other part. I am using Python 3.6. I am just getting warning from Apache Beam. 

My Environment I am using a single machine. 

I tried adding custom metrics like true positive, false negative etc. I can see those metrics in the show drop down box of the widget. Only the results are not loaded for visualization. 

And Other Visualization Widget like displaying stats for the data are working fine. 

Thanks,

**Comment by pfyang** [comment]
Just to doubhle check: Did you see any error in the browser's debug console? For Chrome on Linux, press F12.

Can you please try turn on tfma.post_export_metrics.auc_plot and / or tfma.post_export_metrics.calibration_plot_and_prediction_histogram and try to visualize them using tfma.view.render_plot?

Also, could you please include the screenshots of the entire Jupyter cell for both calls of tfma.view.render_slicing_metrics and tfma.view.render_plot?

Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
