### ISSUE TITLE
[question] ExampleGen driver vs ImporterNode

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/tfx#1631]
Hi, I just have a question regarding the importer node and the ExampleGen driver. My understanding is that they are functionally equivalent, but the ImporterNode can be used to import any arbitrary artifact type (for instance, a user-defined Schema rather than using SchemaGen). My question is, why do the ExampleGen components have their own driver (which registers external paths as artifacts in MLMD) when the importer node handles this on its own? 

If we're able to import an `ExternalPath` artifact using the `ImporterNode`, would `FileBasedExampleGen` be able to use the regular base driver, rather than have its own?

**Comment by 1025KB** [comment]
ExampleGen driver contains (or will contain) logic for Span and Version detection, which will be useful for training on continuous arriving data (will have an RFC later)

**Comment by gowthamkpr** [comment]
@andrewsmartin Didthe above comment answer your question? Can we close this issue?

**Comment by andrewsmartin** [comment]
@gowthamkpr sure, I think it's fine to close. I look forward to this RFC :)
