### ISSUE TITLE
Failed to allocate scratch buffer for device 0

### ISSUE THREAD

**Issue by kimchicanh** [tensorflow/tfx#1650]
Hi,
I am using ubuntu 16.04
tfx v0.21.4
tensorflow-gpu 2.1.0

I just run airflow example at step 3 and StatisticsGen fail:
`tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to allocate scratch buffer for device 0
	 [[{{node _SOURCE}}]]`

Thank

**Comment by gowthamkpr** [comment]
@kimchicanh What version of cuDNN version, CUDA and Compiler(GCC) versions are you using?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to reopen this issue again. Thanks!

**Comment by mofanke** [comment]
i got the same problem ,it seems out of cuda memory
