### ISSUE TITLE
Question: whether move Trainer-rewriter for TFLite to be a dedicated component

### ISSUE THREAD

**Issue by rmgogogo** [tensorflow/tfx#1662]
https://github.com/tensorflow/tfx/tree/master/tfx/components/trainer/rewriting
Any plan to move it out as a dedicated component? Similar like Pusher.

**Comment by gowthamkpr** [comment]
@rmgogogo Looks like this is not moved to a different component as you can see [here](https://github.com/tensorflow/tfx/tree/master/tfx/components/trainer/rewriting). Can you please let us know why this should be moved to a separate component. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been stale for more than 2 weeks. Please reopen it if you respond to the issue. Thanks!
