### ISSUE TITLE
KeyError: 'user_module' in Transform

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tfx#1665]
When running a TFX Pipeline, the Transform component returns an error in the form shown below. [This Colab](https://colab.research.google.com/drive/1qpd6tlRHWoVprj7LETBB0p07zF1JNAfu) reproduces the error with the `preprocessing_fn` from Transform, using a TFX Pipeline.

```python
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py", line 312, in get
    processor = self.cached_bundle_processors[bundle_descriptor_id].pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/internal/pickler.py", line 250, in dumps
    s = dill.dumps(o)
...

  File "/usr/local/lib/python3.6/dist-packages/apache_beam/internal/pickler.py", line 77, in _is_nested_class
    and cls.__name__ not in sys.modules[cls.__module__].__dict__)
KeyError: 'user_module'

During handling of the above exception, another exception occurred:
```

When using Interactive Context, issue is resolved by adding:
```python
import tensorflow_transform as tft
import sys
sys.modules['user_module'] = tft
```
However, it had no such luck when using a pipeline.

**Comment by lipinski** [comment]
You can't do it because it's a different process. You have the same context in an interactive context, but when you use Pipeline, you have a different context.

**Comment by luischinchillagarcia** [comment]
So there is no solution to running this Transform using `Pipeline` at all?

**Comment by lipinski** [comment]
You need create a file with preprocessing_fn and trainer_fn. You should add "module_file" to 
        transform = Transform(
            examples=example_gen.outputs['examples'],
            schema=infer_schema.outputs['schema'],
            module_file=module_file)

**Comment by luischinchillagarcia** [comment]
Thank you for the response. I am doing this step already though (it's under the %%writefile 'transform.py'). Here's the [Colab file I'm referencing](https://colab.research.google.com/drive/1qpd6tlRHWoVprj7LETBB0p07zF1JNAfu), where the error occurs in the 'TF Transform (ERROR: KeyError)' tab.

I should note: there's no Interactive Context here, this is purely a `Pipeline` where all the components are running. Transform fails with the error "KeyError: 'user_module'".

**Comment by luischinchillagarcia** [comment]
^ A follow-up on this issue, this error also appears in a Dataflow job.

**Comment by zhitaoli** [comment]
@charlesccychen I think this could be related to your upcoming plan for dependency management and/or interactive context?

**Comment by luischinchillagarcia** [comment]
^ Follow up to see if there's any hints that may lead to a solution.

**Comment by riyaj8888** [comment]
getting this error after running following code block

`# Ignore TF warning messages
tf.get_logger().setLevel('ERROR')

# Setup the Transform component
transform = Transform(
    examples=example_gen.outputs['examples'],
    schema=schema_gen.outputs['schema'],
    module_file=os.path.abspath(_transform_module_file))

# Run the component
context.run(transform)`

`---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~\AppData\Local\Temp\1\ipykernel_29372\732702845.py in <cell line: 11>()
      9 
     10 # Run the component
---> 11 context.run(transform)

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\experimental\interactive\interactive_context.py in run_if_ipython(*args, **kwargs)
     61       # __IPYTHON__ variable is set by IPython, see
     62       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 63       return fn(*args, **kwargs)
     64     else:
     65       absl.logging.warning(

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\experimental\interactive\interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    181         telemetry_utils.LABEL_TFX_RUNNER: runner_label,
    182     }):
--> 183       execution_id = launcher.launch().execution_id
    184 
    185     return execution_result.ExecutionResult(

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\launcher\base_component_launcher.py in launch(self)
    198       # be immutable in this context.
    199       # output_dict can still be changed, specifically properties.
--> 200       self._run_executor(execution_decision.execution_id,
    201                          copy.deepcopy(execution_decision.input_dict),
    202                          execution_decision.output_dict,

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\launcher\in_process_component_launcher.py in _run_executor(self, execution_id, input_dict, output_dict, exec_properties)
     71     # be immutable in this context.
     72     # output_dict can still be changed, specifically properties.
---> 73     executor.Do(
     74         copy.deepcopy(input_dict), output_dict, copy.deepcopy(exec_properties))

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\transform\executor.py in Do(self, input_dict, output_dict, exec_properties)
    528       label_outputs[labels.CACHE_OUTPUT_PATH_LABEL] = cache_output
    529     status_file = 'status_file'  # Unused
--> 530     self.Transform(label_inputs, label_outputs, status_file)
    531     logging.debug('Cleaning up temp path %s on executor success', temp_path)
    532     io_utils.delete_dir(temp_path)
~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\transform\executor.py in Transform(***failed resolving arguments***)
   1014     materialize_output_paths = value_utils.GetValues(
   1015         outputs, labels.TRANSFORM_MATERIALIZE_OUTPUT_PATHS_LABEL)
-> 1016     preprocessing_fn = self._GetPreprocessingFn(inputs, outputs)
   1017     stats_options_updater_fn = self._GetStatsOptionsUpdaterFn(inputs)
   1018     per_set_stats_output_paths = value_utils.GetValues(

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\transform\executor.py in _GetPreprocessingFn(self, inputs, unused_outputs)
    875           'be supplied in inputs.')
    876 
--> 877     fn = udf_utils.get_fn(
    878         {
    879             standard_component_specs.MODULE_FILE_KEY:

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py in get_fn(exec_properties, fn_name)
     54   if has_module_path:
     55     module_path = exec_properties[_MODULE_PATH_KEY]
---> 56     return import_utils.import_func_from_module(module_path, fn_name)
     57   elif has_module_file:
     58     if has_fn:
~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\utils\import_utils.py in import_func_from_module(module_path, fn_name)
     53     wheel_context_manager = udf_utils.TempPipInstallContext([wheel_path])
     54     with _imported_modules_from_source_lock:
---> 55       wheel_context_manager.__enter__()
     56   if module_path in sys.modules:
     57     importlib.reload(sys.modules[module_path])

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py in __enter__(self)
    305       self.temp_directory = tempfile.mkdtemp()
    306       for dependency in self.pip_dependencies:
--> 307         install_to_temp_directory(dependency, temp_dir=self.temp_directory)
    308       sys.path = sys.path + [self.temp_directory]
    309       os.environ['PYTHONPATH'] = ':'.join(sys.path)

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py in install_to_temp_directory(pip_dependency, temp_dir)
    337   ]
    338   logging.info('Executing: %s', install_command)
--> 339   subprocess.check_call(install_command)
    340   logging.info('Successfully installed %r.', pip_dependency)
    341   return temp_dir

C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py in check_call(*popenargs, **kwargs)
    362         if cmd is None:
    363             cmd = popenargs[0]
--> 364         raise CalledProcessError(retcode, cmd)
    365     return 0
    366 `
