### ISSUE TITLE
Results folder in ModelValidator is always empty

### ISSUE THREAD

**Issue by Malonl** [tensorflow/tfx#167]
Every time the ModelValidator component runs, two folders get created: a blessing folder and a results folder. Inside results there are the folders for the different runs (i.e. the numbered folders), but the numbered folders are always empty. 
Is this the expected outcome or should something get stored there?

**Comment by 1025KB** [comment]
Hi, the head version fixed that issue already (won't generate result folder), but 0.13 release still contains that
