### ISSUE TITLE
KubeflowDagRunner.run does not really run the pipeline

### ISSUE THREAD

**Issue by yantriks-edi-bice** [tensorflow/tfx#1681]
Unlike the seemingly equivalent BeamDagRunner, the KubeflowDagRunner.run method does not actually run the pipeline but instead simply writes it out.

**Comment by wendy2003888** [comment]
The KubeflowDagRunner compiles a .yaml file or a kubeflow compressed package. 
In my case, I upload this package to GCP to run. If you have local kfp environment, I guess you may also able to deploy the yaml file to your local environment.

**Comment by rmgogogo** [comment]
Yes, more info here:
https://github.com/kubeflow/pipelines/issues/3604

**Comment by rmgogogo** [comment]
try "tfx pipeline --help"

**Comment by yantriks-edi-bice** [comment]
Yes, I'm aware of that but the point is that one orchestrator's run method actually runs the pipeline whereas the other's (kubeflow) just writes it out to a file. I was actually producing an image of the whole thing and launching it from a Kubeflow cluster only to have the pod complete almost immediately instead of waiting until all the pipeline steps were completed. Turns out because it does not actually run them. So yeah, maybe it should not be called run() then but write(()
