### ISSUE TITLE
Setting custom TFXIO class at TFX pipeline level

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#1690]
This may be under work, but wanted to consult what's the current implementation path for https://github.com/tensorflow/community/blob/master/rfcs/20191017-tfx-standardized-inputs.md.

I'm wondering, is the plan here to support arbitrary TFXIO classes to be specified for a TFX pipeline such that the underlying data format can be switched from tf.Example to whatever we need? 

Checking the codebase, seems TFXIO integration is currently still in progress. Wondering if there's any insights into how TFXIO will be integrated into TFX pipelines?

**Comment by gowthamkpr** [comment]
@casassg The design proposal that has been mentioned in the doc describes how its being implemented. And there is no fixed timeline, we will let you know as soon as its done. Thanks!

**Comment by casassg** [comment]
Yup, it mentions `Individual TFX component users would be able to implement TFXIO for their own data formats / storage formats that are not supported by TFX.` but I was wondering if support for setting this at the `tfx.orchestration.pipeline` is possible. This way a user can set a custom TFXIO class for all components used in a pipeline.
