### ISSUE TITLE
'MetadataStore' object has no attribute '_metadata_store'

### ISSUE THREAD

**Issue by ismail-dinar** [tensorflow/tfx#1702]
Whenever I try  to set MySql as metadata store I get the following error:
```
File "/home/doblatrobla/new/lib/python3.6/site-packages/ml_metadata/metadata_store/metadata_store.py", line 116, in __del__
    metadata_store_serialized.DestroyMetadataStore(self._metadata_store)
AttributeError: 'MetadataStore' object has no attribute '_metadata_store'
```

I get this error when using interactive context/airflow/beam

**Comment by gowthamkpr** [comment]
@ismail-dinar Did you follow the steps mentioned in this [doc](https://www.tensorflow.org/tfx/guide/mlmd). Also please share the sequence of steps to reproduce this issue.

**Comment by ismail-dinar** [comment]
I just found what's causing this error.
When I set the host to **localhost** in the metadata config it causes this error, but when i change the host to **127.0.0.1** it works fine.
So i'm closing this issue.
