### ISSUE TITLE
Support Avro format for Examplegen

### ISSUE THREAD

**Issue by zhitaoli** [tensorflow/tfx#171]
Avro is already a supported format in Apache Beam Python [1], so we should be able to provide an example gen implementation with reasonable cost.

To users: if you find this feature request useful, please comment in this issue to help us better prioritize.

[1] https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/avroio.py

**Comment by jbx** [comment]
This is something that we'd (Spotify) be interested in using

**Comment by gowthamkpr** [comment]
Now, we also support reading Avro and Parquet files using this [method](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/custom_executors/avro_component_test.py). Closing this issue as it has been resolved. Thanks!
