### ISSUE TITLE
Error Using Accumulators in TFT with Pipeline

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tfx#1722]
When using a combiner function like `tft.analyzer_nodes.Combiner`, it successfully runs using TFT_beam ([shown in this Colab](https://colab.research.google.com/drive/17LPB6b1D6ojnJbzs-t_M2qzhuZfin7Wx)) or TFX Interactive Context ([shown in this Colab](https://colab.research.google.com/drive/1g-GPCcxPmBqbQyOTZHcL_FkPYB0HHlJZ)). 

However, using the *exact same* code using `tfx.orchestration.pipeline` fails with a Runtime Error pointing to dill and pickling. [Here is the Colab replicating the issue.](https://colab.research.google.com/drive/1SDsCZhdeFBG8HMBRoV_lJdFDRJCZJIqa)

The preprocessing function that TFT is calling looks like this: 
```python
class ConcatCombiner(tft.analyzer_nodes.Combiner):
    def __init__(self):
        pass
    def create_accumulator(self):
        return []

    def add_input(self, accumulator, batch_values):
        return accumulator + batch_values

    def _concatenate_accumulators(self, accumulators):
        result = []
        for lst in accumulators:
            result.extend(lst)
        return result

    def merge_accumulators(self, accumulators):
        return self._concatenate_accumulators(accumulators)

    def extract_output(self, accumulator):
        return accumulator

    def output_tensor_infos(self):
        return [analyzer_nodes.TensorInfo(tf.string, [], False)]

def _compute_user_id_vocabulary(key, value):
    combiner = ConcatCombiner()
    vocab_file = tft.analyzers._apply_cacheable_combiner_per_key_large( 
        combiner, 'user_id_to_item_id_vocab', key, value)
    return vocab_file

def preprocessing_fn(inputs):

    outputs = {}

    uid = inputs['user_id']
    iid = inputs['item_id']
    label = inputs['label']

    uid_transf = tft.compute_and_apply_vocabulary(_fill_in_missing(uid))
    iid_transf = tft.compute_and_apply_vocabulary(_fill_in_missing(iid))

    outputs.update({_transformed_name('item_id'): iid_transf,
                    _transformed_name('user_id'): uid_transf,
                    'label': _fill_in_missing(label)
                    })


    user_id_to_item_id_vocab = _compute_user_id_vocabulary(uid_transf, iid_transf)
    initializer = tf.lookup.TextFileInitializer(user_id_to_item_id_vocab,
                                                key_dtype=tf.string,
                                                key_index=1,
                                                value_dtype=tf.string,
                                                value_index=0,
                                                delimiter=' ')
    table = tf.lookup.StaticHashTable(initializer, default_value='')
    outputs['item_id_grouped'] = table.lookup(tf.strings.as_string(uid_transf))


    return outputs
```

**Comment by 1025KB** [comment]
Just confirm, are they using the same input data with the same format, and in same env (e.g., tft version)?

**Comment by luischinchillagarcia** [comment]
Yes, everything is exactly the same.

**Comment by 1025KB** [comment]
Sorry I take a look at your colab, the error is about "user_module" setup, not in TFT

**Comment by luischinchillagarcia** [comment]
Yes, so it seems the error "user_module" setup is isolated to appear in the TFT part of the TFX Pipeline.

**Comment by luischinchillagarcia** [comment]
Is there a possibility to have a fix in the same way you can do it using Interactive Context? There, you can have a line in the imports as:

```python
import sys
import tensorflow_transform as user_module
sys.modules['user_module'] = user_module
```

**Comment by 1025KB** [comment]
what's this sys.modules['user_module'] for? tft preprocessing_fn code?

here is an [example](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#transform)  about how to use module_file in colab

**Comment by luischinchillagarcia** [comment]
Without the sys.modules['user_module'], I get an error of the form as seen below. The TFT step in my example works under Interactive Context, just not in Pipeline.

If you remove the sys.modules['user_module'] from the Interactive Context, you get once again the error below:

![image](https://user-images.githubusercontent.com/50338632/81027338-47a92d80-8e32-11ea-90ad-7940f5a8e4f0.png)

**Comment by luischinchillagarcia** [comment]
The main part of the issue is:

This code works perfectly with TFT_beam. It works with TFX Interactive Context ONLY if you include the sys.modules['user_module'] fix. But it completely fails on TFX Pipeline with or without the sys.modules['user_module'].

Why does this inconsistency happen and is there a possible solution?

**Comment by 1025KB** [comment]
I'm not sure if I understand how the "sys.modules['user_module']" fix works. 

This Interactive Context [example](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#transform) works without "sys.modules['user_module']"

Note that if you want to play with the pipeline instead of detailed components, this iris pipeline [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/README.md) might be simpler

**Comment by luischinchillagarcia** [comment]
So **that** is part of the issue: _why_ does my code produce this 'Key Error: user_module' to begin with?

If this code works in with TFT_beam, why doesn't it work in a TFX Pipeline?

**Comment by 1025KB** [comment]
This Interactive Context [example](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#transform) works **without** "sys.modules['user_module']", while in your code you have this "sys.modules['user_module']" and it seems causing issues. could you try remove it the follow that example?

**Comment by luischinchillagarcia** [comment]
So it seems without it, it doesn't work.

**Comment by 1025KB** [comment]
Hi, 

I tried the Interactive Context [example](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#transform) again and it works fine, so it might be some missing steps in your Colab, e.g., I can't find "context = InteractiveContext()"

I never tried run the entire pipeline in Colab before, if you want to run the entire pipeline instead of playing with each components, try this iris pipeline [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/README.md) locally, it might be simpler (without InteractiveContext too)

**Comment by 1025KB** [comment]
Charles, do you know if we can run the entire pipeline in Colab?

**Comment by luischinchillagarcia** [comment]
Thanks for taking the time to check these over once again.

It might be that you were looking in the incorrect one. So [this Colab](https://colab.research.google.com/drive/1g-GPCcxPmBqbQyOTZHcL_FkPYB0HHlJZ#scrollTo=h-Kh7SFB_Hc9) contains the Interactive Context run, [this one](https://colab.research.google.com/drive/17LPB6b1D6ojnJbzs-t_M2qzhuZfin7Wx#scrollTo=tFcdSuXTidhH) contains the TFT_Beam, and [this one](https://colab.research.google.com/drive/1SDsCZhdeFBG8HMBRoV_lJdFDRJCZJIqa) contains the TFX Pipeline.

**Comment by 1025KB** [comment]
I tried your [colab](https://colab.sandbox.google.com/drive/1g-GPCcxPmBqbQyOTZHcL_FkPYB0HHlJZ#scrollTo=h-Kh7SFB_Hc9) that contains Interactive Context, 

I replace the following to "**!pip install "tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.3" "pyzmq==17.0.0"**" and it works fine

# Restart after installing tfx
try:
    import tfx
except:
    !pip install -qqq "tfx>=0.21.1,<0.22" 

try:
    import tensorflow_transform as user_module
    import sys
    sys.modules['user_module'] = user_module
except:
    !pip install -Uqqq tensorflow-transform==0.21.0

**Comment by luischinchillagarcia** [comment]
So thankfully, the Interactive Context Colab works with these versions!

However, this still don't work on the Pipeline (`tfx.orchestration.pipeline`). It's the same error. Why does this work with Interactive Context but not Pipeline?

**Comment by 1025KB** [comment]
I tried your pipeline Colab:

I replaced the the first section (Restart after installing tfx...) to "!pip install "tfx>=0.21.1,<0.22"" and set direct_num_workers=1 (or beam_pipeline_args=[]), it works. Notebook as some issue with Beam multiprocessing I guess

**Comment by luischinchillagarcia** [comment]
Perfect, thanks! 
a natural next question is: would this issue persist while using Dataflow or this is purely an error caused in a notebook environment?

**Comment by 1025KB** [comment]
it should work in Dataflow, if not, it might be a beam side issue or tfx set up beam incorrectly

**Comment by luischinchillagarcia** [comment]
Quick update that although this works perfectly with locally using Pipeline and Interactive Context, it fails with Dataflow under the error "no module named tfx".  Would this then be a Beam issue?
