### ISSUE TITLE
Tensorflow and tensorflow-model-analysis fighting for different versions of scipy

### ISSUE THREAD

**Issue by tordbb** [tensorflow/tfx#1727]
It seems like `tensorflow=2.1.0` and `tensorflow-model-analysis==0.21.1` are themselves compatible. 
However, they seem to require different versions of `scipy`.

If I set `scipy==1.4.1`, i get the error
`ERROR: tensorflow-model-analysis 0.21.1 has requirement scipy==1.2.2, but you'll have scipy 1.4.1 which is incompatible.`

If I change to `scipy==1.2.2`, i get the error
`ERROR: tensorflow 2.1.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.2.2 which is incompatible.`

I have the following content in `requirements.txt`:
```
absl-py==0.8.1
apache-beam==2.17.0
avro-python3==1.9.2.1
flake8==3.7.9
google-cloud-bigquery==1.24.0
grpcio==1.27.2
jupyterlab==2.1.0
jupytext==1.4.1
ml-metadata==0.21.0
numpy==1.18.1
pandas==0.25.3
pyarrow==0.15.0
pytest==5.3.5
scipy==1.4.1
seaborn==0.10.0
tables==3.6.1
tensorflow-data-validation==0.21.0
tensorflow-metadata==0.21.0
tensorflow-model-analysis==0.21.1
tensorflow-transform==0.21.0
tfx==0.21.0
tfx-bsl==0.21.0
```

**Comment by mdreves** [comment]
This should be fixed in version 0.21.2. The latest is at 0.21.6, can you retry with the latest.

**Comment by 1025KB** [comment]
Could you try tensorflow-model-analysis==0.21.6?

**Comment by tordbb** [comment]
You are right guys, it worked. Thanks!
