### ISSUE TITLE
BigQueryExampleGen handles arrays incorrectly

### ISSUE THREAD

**Issue by domedagen** [tensorflow/tfx#1738]
As I also tried to address [in my PR](https://github.com/tensorflow/tfx/pull/1731) including a BigQuery array in the query result for BigQueryExamplesGen will result in the following error.
`TypeError: [20.592889320938852, 20.514573172830033, 19.76807155325737, 20.467801775051797, 20.5308510931856, 20 has type list, but expected one of: int, long, float [while running 'InputToSerializedExample/InputSourceToExample/ToTFExample']`

I suspect this is because how the [initial type parsing](https://github.com/tensorflow/tfx/blob/05ba51906408f96570f2be5975d687b1d40dee9d/tfx/components/example_gen/big_query_example_gen/executor.py#L42) only checks the main type and not if it is a repeatable or not `SchemaField('history', 'FLOAT', 'REPEATED', None, ())`.

A quick fix as in the PR would be to check if it is a list before parsing it through.

For now a workaround would be to query the elements of the array separately, but this tedious solution if you have long array and I think TFX should complain instead of crash if it doesn't want to you use arrays.

**Comment by 1025KB** [comment]
Thanks for the PR! Let us review it!

**Comment by domedagen** [comment]
As of [this merge](https://github.com/tensorflow/tfx/pull/1760), this should be fixed and this issue can now be closed
