### ISSUE TITLE
Taxi transform step fails with "WriteToFile/Write/WriteImpl/InitializeWrite failed."

### ISSUE THREAD

**Issue by yantriks-edi-bice** [tensorflow/tfx#1762]
I'm running (from notebook) on latest Kubeflow (IAP secured) a TFX pipeline based on the Taxi template. I had to create a custom image to use the latest TFX (0.22-dev) which includes a required bug fix. This version of TFX is apparently using Beam 2.20. Pipeline completed okay previously (with TFX 0.21.4 and Beam 2.17) albeit using BeamDagRunner instead of KubeflowDagRunner.

I've ran the pipeline twice and in both cases it failed at the same step at around the same time (another interesting thing is that now it no longer autoscales higher than a single worker whereas it used 2 workers when using BeamDagRunner)

Finished operation Analyze/VocabularyPrune[compute_and_apply_vocabulary_7/vocabulary]/ApplyFrequencyThresholdAndTopK/Top(10)/Create/Read+Analyze/VocabularyPrune[compute_and_apply_vocabulary_7/vocabulary]/ApplyFrequencyThresholdAndTopK/Top(10)/GroupByKey/Reify+Analyze/VocabularyPrune[compute_and_apply_vocabulary_7/vocabulary]/ApplyFrequencyThresholdAndTopK/Top(10)/GroupByKey/Write
INFO:apache_beam.runners.dataflow.dataflow_runner:2020-05-08T20:51:30.608Z: JOB_MESSAGE_WARNING: S675:Materialize[TransformIndex0]/Write/Write/WriteImpl/DoOnce/Read+Materialize[TransformIndex0]/Write/Write/WriteImpl/InitializeWrite failed.

**Comment by 1025KB** [comment]
Our previous TFX 0.21.4 release has some issues with Beam 2.20, we will update it in our next release

For notebook, beam multiprocessing might not work properly, could you try local examples?

**Comment by yantriks-edi-bice** [comment]
@1025KB I am using the latest TFX version 0.22-dev which uses Beam 2.20. This was achieved by passing the KubeflowDagRunner a config which points it to my custom tfx_image. I don't see how I can do that for the BeamDagRunner.

**Comment by yantriks-edi-bice** [comment]
Running the same pipeline from my laptop (not Kubeflow notebook) using BeamDagRunner works okay but then again it is using TFX 0.21.4 and Apache Beam 2.17 which is known to work and is listed in compatible versions page.

The reason for this issue is being forced to use the latest TFX version as it incorporates [https://github.com/tensorflow/tfx/pull/1707](url)

Can that fix be ported to the currently supported TFX version (0.21.4 I believe)?

**Comment by 1025KB** [comment]
For beam 2.20 support, it will be available in TFX 0.22 release.

**Comment by zhitaoli** [comment]
TFX 0.22. release will require `beam>=2.21,<3`.

**Comment by yantriks-edi-bice** [comment]
Working after updating to latest TFX and Beam
