### ISSUE TITLE
Pipeline randomly does nothing

### ISSUE THREAD

**Issue by tordsae** [tensorflow/tfx#1789]
I am trying to run a tfx pipeline on kubeflow. Data is acquired by BigQueryExampleGen. It works most of the time, but suddenly it just does nothing. I'm using the exact same pipeline, the only difference is the run name and that a few extra datapoints have been added. It randomly does nothing, but then it might just start working again without anything other than me running it again. Every single component has the same log: 
```
INFO:absl:Using setup_file '/tfx-src/setup.py' to capture TFX dependencies
INFO:absl:Running driver for Trainer
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:Adding KFP pod name anomaly-test-b4rf4-3229433045 to execution
INFO:absl:Adding KFP pod name anomaly-test-b4rf4-3229433045 to execution
INFO:absl:Running publisher for Trainer
INFO:absl:MetadataStore with gRPC connection initialized
```
Wish I could give more information, but I don't know what could be relevant.

**Comment by tordsae** [comment]
Update: Renaming the pipeline root path for each run fixed the problem, but why does this happen?

**Comment by numerology** [comment]
@tordsae  Did you turn on the cache?

**Comment by tordsae** [comment]
@numerology I'm pretty sure I have. Here is the arguments I give for the Pipeline:  
```
return pipeline.Pipeline(
        pipeline_name=pipeline_name,
        pipeline_root=pipeline_root,
        components=components,
        enable_cache=True,
        metadata_connection_config=metadata_connection_config,
        beam_pipeline_args=beam_pipeline_args,
    )
```
I assume this what you asked for.

**Comment by numerology** [comment]
Thanks! @tordsae  Then I guess somewhat the caching log is triggered based on the log.

/cc @ruoyu90

**Comment by numerology** [comment]
> I'm using the exact same pipeline, the only difference is the run name and that a few extra datapoints have been added.

I'm guessing if the query sentence you use was not changed, then perhaps you would hit the cache and the actual execution was skipped. @ruoyu90 and @1025KB  can correct me if I am wrong.

**Comment by 1025KB** [comment]
Yep, current BigQueryExampleGen check the input artifact and configs, if they are same, component will perform a cache execution.

For file based ExampleGen, tfx fingerprints the previous files so if file content changes, tfx won't cache.
For table content changes, fingerprint is not supported yet. You can [turn off](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/pipeline.py#L69) cache.
We will support per component cache in the future.

**Comment by tordsae** [comment]
Turning off the cache solved the problem. Thanks!
