### ISSUE TITLE
How to get the Confusion Matrix of the Model ?

### ISSUE THREAD

**Issue by rathnasubramanian2603** [tensorflow/tfx#179]
As of now the Model evaluator return some metrics a like accuracy etc.  Is it possible to get the confusion matrix of the model? If Yes how ?

**Comment by rmothukuru** [comment]
Information regarding Confusion Matrix using Tensorflow Model Analysis is given in this [link](https://github.com/tensorflow/model-analysis/blob/master/tensorflow_model_analysis/frontend/test/tfma-multi-class-confusion-matrix_test.html). Please check if it helps.

**Comment by rathnasubramanian2603** [comment]
I am not able to understand it. I have a trained model..! I give it to the Model Evaluator component of TFX pipeline. How to extract the confusion Matrix from it ? If there are any sample Python Code to get the confusion matrix of a TFX trained model it would help me to understand it a lot. Thanks.

**Comment by mdreves** [comment]
You need to add the confusion matrix as a metric first.  There are a few options.

1) If you want them at training time as well as evaluation time you need to add the underlying TP, TF, etc metrics to your graph using tf.metrics:

tf.metrics.true_positives_at_thresholds(...)
tf.metrics.false_postivies_at_thresholds(...)
...

2) You can add the metrics to the graph post export using TFMA post export metrics

tfma.post_export_metrics.confusion_matrix_at_thresholds(...)

This would need to be added to the add_metrics_callbacks when the EvalSharedModel is created here:

https://github.com/tensorflow/model-analysis/blob/master/g3doc/api_docs/python/tfma/default_eval_shared_model.md

**Comment by rathnasubramanian2603** [comment]
Thank You so much for the Help. I am able to get it now.
