### ISSUE TITLE
docs/tutorials/transform/census.ipynb - FailedPreconditionError when running on Colab

### ISSUE THREAD

**Issue by reivio** [tensorflow/tfx#1797]
When running this [transform tutorial ](https://www.tensorflow.org/tfx/tutorials/transform/census) on Colab, the last cell generates the following error:

```
FailedPreconditionError: /tmp/transform_tmp/7a43ffaf11d44de3a31e92bcf23a2af7; Directory not empty

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py in rename_v2(src, dst, overwrite)
    519   """
    520   pywrap_tensorflow.RenameFile(
--> 521       compat.as_bytes(src), compat.as_bytes(dst), overwrite)
    522 
    523 

RuntimeError: tensorflow.python.framework.errors_impl.FailedPreconditionError: /tmp/transform_tmp/7a43ffaf11d44de3a31e92bcf23a2af7; Directory not empty [while running 'WriteTransformFn/PublishMetadataAndTransformFn']
```

**Comment by gowthamkpr** [comment]
@reivio Tried to reproduce this but was not able to. I would recommend you to go to this directory `/tmp/transform_tmp/7a43ffaf11d44de3a31e92bcf23a2af7` and delete the files it it and then start running transform. Its complaining that some files already exists in the directory and you cannot save the transform model in that directory

**Comment by gowthamkpr** [comment]
@reivio Can you please respnd to the above issue so that we can take the discussion forward. Thanks!

**Comment by reivio** [comment]
@gowthamkpr A factory reset resolved the issue. Thanks!
