### ISSUE TITLE
[Airflow tutorial] Can't execute Step 2: Hello World

### ISSUE THREAD

**Issue by atn832** [tensorflow/tfx#1851]
I'm having trouble running step 2 in the Airflow tutorial. After running `setup_demo.sh` and `airflow webserver -p 8080`, I ran `airflow scheduler` but it crashed at startup with this error:

> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: task_instance.pool_slots

Am I missing some step in the configuration?

Full gist here: https://gist.github.com/atn832/68202bf555d8b677911da4838498a23e.
My Python environment: https://gist.github.com/atn832/f4a9fe464a9b6a8dbaf750031ccb80d0

**Comment by gowthamkpr** [comment]
@atn832 Have you tried initializing the db or resetting it? airflow db init or airflow db reset

**Comment by gowthamkpr** [comment]
@atn832 Can you please respond to the above comment so that we can take the discussion forward. Thanks!

**Comment by atn832** [comment]
Thanks, running `airflow initdb` did the trick.
