### ISSUE TITLE
BigQueryExampleGen component cannot handle queries with temporary functions

### ISSUE THREAD

**Issue by chrispankow** [tensorflow/tfx#1858]
In our use of TFX, we call out to a `BigQueryExampleGen` component with a somewhat complicated query which uses two instances of `CREATE TEMP FUNCTION` to ease the unpacking of struct/arrays in the table. This functions as expected through, e.g., the BQ UI in the GCP console.

Converting this to TFX has proven to be difficult because of the way output types for tfexamples [are handled](https://github.com/tensorflow/tfx/blob/1c2e3e86a9844d39722c179a64889cab60fd675b/tfx/components/example_gen/big_query_example_gen/executor.py#L39). This embeds the incoming query and treats it as if it were also a table that could be queried to obtain metadata. However, the interpolated query still has the `CREATE TEMP FUNCTION` directives and as such cannot be directly embedded.

While we can rewrite the query to conform to this methodology, it may be cumbersome to do so. Is it possible to adjust the strategy in the linked code? E.g., would it be possible to run the query as is, store a result to a temporary space, then obtain metadata from *that* table?

Thanks in advance!

**Comment by pindinagesh** [comment]
@chrispankow 

Could you please refer similar issue which is described [here](https://github.com/tensorflow/tfx/issues/2119) and let us know if this helps. Thanks

**Comment by chrispankow** [comment]
To my understanding of the beam JIRA ticket and the proposed TFX component, and as it pertains to the expressed problem, I don't believe that is a resolution. As is noted there, the type retrieval query (expected to be a single `SELECT` type query) is the part that fails, and that isn't addressed in either. Since our pipeline uses this as the data acquisition into TF transform, preprocessing before training is required, so the custom component not sufficient.

That said, we moved to stored UDFs recently, so this is no longer a blocker.

**Comment by gowthamkpr** [comment]
@chrispankow As this is nolonger a blocker, can you please go ahead and close this issue. If you think this usecase is generic and is required for a wider community, then please explain it in detail so we can look into it. Thanks!
