### ISSUE TITLE
InfraValidator fails for on-prem deploys

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#1871]
The InfraValidator component has no option for specifying from which docker registry to pull the TF serving image. For on-prem deployments (or other isolated k8s clusters) this means that InfraValidator fails with an ImagePullBackError.

Proposed solution: Add option to specify (one) image (not just registry) along with the existing tags and digests options. The user is responsible for ensuring that the image is a working TF serving image.

**Comment by chongkong** [comment]
Thanks ConverJens. Supporting custom docker images (based on official tensorflow/serving or equivalents) is definitely in our TODO list. Your suggestion would help us a lot :) I'll keep this issue for tracking the feature development.

**Comment by ConverJens** [comment]
@chongkong Sounds great! Are you actively working on this? Otherwise I could create a pull request and give it a try. From my looking through the code, the changes needed seems to be minor. What do you think?

**Comment by chongkong** [comment]
Hi ConverJens. I'm back to this issue :) It can be as simple as adding a single line in the config, but I'm also curious on the requirements for the authentication on fetching private images. Would you share your use case on this?

**Comment by ConverJens** [comment]
Hi @chongkong.

Of course. We are running TFX pipelines in an on-prem KubeFlow cluster. For security reasons, the k8s cluster is blocked off from internet access and hence, we can't pull the images directly from the external source (GCR). We rely on pulling images in our build system and then pushing them to our own internal registry, were we can also change image names and tags if needed.

What we need is the possibility to specify the image name and registry path as well as the tag. At the moment, we have no need for any authentication options.

As of now we use the vanilla TFServing images so there are no changes to the public one.

Let me know if you have any other questions and how to proceed on this.

**Comment by zhitaoli** [comment]
@ConverJens 

> Hi @chongkong.
> 
> Of course. We are running TFX pipelines in an on-prem KubeFlow cluster. For security reasons, the k8s cluster is blocked off from internet access and hence, we can't pull the images directly from the external source (GCR). We rely on pulling images in our build system and then pushing them to our own internal registry, were we can also change image names and tags if needed.
> 
> What we need is the possibility to specify the image name and registry path as well as the tag. At the moment, we have no need for any authentication options.
> 
> As of now we use the vanilla TFServing images so there are no changes to the public one.
