### ISSUE TITLE
Taxi example: pip not finding tensorflow-metadata 13.1

### ISSUE THREAD

**Issue by ibzib** [tensorflow/tfx#189]
When I try to install dependencies for the Chicago taxi example (inside virtualenv), pip can't find the required version 13.1 of `tensorflow-metadata`:

(on head: [5ed8d9ef](https://github.com/tensorflow/tfx/commit/5ed8d9ef1e072a16a42dbd5d040a90c6cb4c974e))

```
ERROR: Could not find a version that satisfies the requirement tensorflow-metadata<0.14,>=0.13.1 (from tfx-chicago-taxi==0.13.0->-r requirements.txt (line 3)) (from versions: 0.5.0, 0.6.0, 0.9.0, 0.12.1, 0.13.0)
ERROR: No matching distribution found for tensorflow-metadata<0.14,>=0.13.1 (from tfx-chicago-taxi==0.13.0->-r requirements.txt (line 3))
```

**Comment by krazyhaas** [comment]
Fixed with https://github.com/tensorflow/tfx/commit/6a594b7d6657acb05e4f6d28299a9fa3cd145bea.  Sorry for the bug!
