### ISSUE TITLE
tfx.utils.io_utils.copy_dir doesn't support subdirectories -> Pusher is failing

### ISSUE THREAD

**Issue by lkuligin** [tensorflow/tfx#1915]
[tfx.utils.io_utils.copy_dir]() is not working properly with subdirectories (it's funny enough it fails only with local fs but not with GCS) - it creates subdirs always in the root folder and no in the corresponding subdir folder

e.g., a `src/logs/train` becomes a `dest/train` and therefore `Pusher` components fails with DirectRunner (e.g., when implementing an e2e test) since the trained model has subdirectories like `$MODEL_VERSION/logs/train/`. Error looks like this:
```
File ".../venv/tf2/lib/python3.5/site-packages/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
File ".../venv/tf2/lib/python3.5/site-packages/tfx/components/pusher/executor.py", line 132, in Do
    io_utils.copy_dir(model_path, os.path.join(model_push_uri, model_version))
File ".../venv/tf2/lib/python3.5/site-packages/tfx/utils/io_utils.py", line 70, in copy_dir
    tf.io.gfile.copy(leaf_file_path, new_file_path)
File ".../venv/tf2/lib/python3.5/site-packages/tensorflow_core/python/lib/io/file_io.py", line 488, in copy_v2
    compat.as_bytes(src), compat.as_bytes(dst), overwrite)
RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: /tmp/my_pipeline_test65ivqggp/tmpmzp2gnjz/test_e2e/tfx/pipelines/test5/Pusher/pushed_model/9/1591165904/logs/train/events.out.tfevents.1591165790.penguin.2980.4347.v2; No such file or directory [while running 'Run[Pusher]']
```

**Comment by 1025KB** [comment]
You are correct, this [line](https://github.com/tensorflow/tfx/blob/r0.22.0/tfx/utils/io_utils.py#L73) should be `tf.io.gfile.makedirs(os.path.join(dir_name.replace(src, dst, 1), sub_dir))`

Will fix soon

**Comment by arghyaganguly** [comment]
@lkuligin , closing this as the fix is now available.Thanks.
