### ISSUE TITLE
context.show(statistics_gen.outputs['statistics']) need to be run twice to show the statistics for both train and eval set

### ISSUE THREAD

**Issue by nitinmnsn** [tensorflow/tfx#1948]
Tensorflow [official tutorial ](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#statisticsgen)is showing this behavior and hence is the best minimum reproducible example. If i run the following cell just once then the data  statistics for only the train data will be displayed. Running it twice shows both the tables:

```
%%skip_for_export

context.show(statistics_gen.outputs['statistics'])
```

**Comment by arghyaganguly** [comment]
@nitinmnsn , both tables are currently visible in the first run.
Attaching the screenshot alongwith.
versions used to reproduce -
![Screenshot 2021-04-27 7 13 30 PM](https://user-images.githubusercontent.com/75770622/116252531-4a143e00-a78d-11eb-857d-4c57a6e30725.png)
![Screenshot 2021-04-27 7 13 20 PM](https://user-images.githubusercontent.com/75770622/116252540-4c769800-a78d-11eb-8f46-4de4cb1cac67.png)


TensorFlow version: 2.4.1
TFX version: 0.29.0
