### ISSUE TITLE
Interactive tutorial (TF2 Keras) pusher code outdated

### ISSUE THREAD

**Issue by jkim1014** [tensorflow/tfx#1957]
This links to the outdated part of tutorial on web: [https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#pusher](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#pusher)

The current code snippet that attempts to load the saved model reaches for the wrong directory. Instead of loading from `os.path.join(push_uri, latest_version)`, the program should load from `os.path.join(model_artifact_dir, 'serving_model_dir')`.

**Comment by KrishnaRekapalli** [comment]
I can take a stab at this!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been fixed and is not valid anymore. Thanks!
