### ISSUE TITLE
Hard crash running interactive context.show

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tfx#1990]
[Following this tutorial](https://colab.research.google.com/github/tensorflow/workshops/blob/master/blog/TFX_Pipeline_for_Bert_Preprocessing.ipynb#scrollTo=IBYoEPhBeQUi) TFX Statistic gen hard crashes (no log, no prints, resets the Jupyter kernel) at this step:
```
context.show(statistics_gen.outputs['statistics'])
```
![image](https://user-images.githubusercontent.com/112599/84558050-b0fb4680-ace4-11ea-9df8-49b40367ad83.png)

How can I debug this?
How can I increase the logging level of the library?

**Comment by gowthamkpr** [comment]
I was not able to run into your error. Please find the github gist [here](https://colab.research.google.com/gist/gowthamkpr/74f92ba9a271b691bed6a25e4b3de645/tfx_pipeline_for_bert_preprocessing.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@Mistobaan Can you please respond to the above comment so that we can take the discussion further. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
