### ISSUE TITLE
Documentation for Evaluator?

### ISSUE THREAD

**Issue by tommywei110** [tensorflow/tfx#1997]
I'm working through an example pipeline in TFX/examples.

I would like to be able to interpret the result of the evaluator component.
(specifically the ones generated in ~/tfx/pipelines/evaluator/evaluation after running the iris or mnist example locally)

However, the local output of evaluator can't be opened as nicely as the colab tensorboard example. At least, there's no documentation on how to achieve that.

I wonder if there is a way to visualize the output of evaluator.

And can we provide better documentation for the Evaluator: https://www.tensorflow.org/tfx/api_docs/python/tfx/components/evaluator

**Comment by drcat101** [comment]
You can visualize the results of the Evaluator using TensorFlow Model Analysis:
`import tensorflow_model_analysis as tfma`

`tfma_result = tfma.load_eval_result(PATH_TO_RESULT)`
`tfma.view.render_slicing_metrics(tfma_result)`

This works in a Jupyter Notebook or Colab notebook; it isn't supported in Jupyter Lab yet.
