### ISSUE TITLE
Message org.apache.beam.model.fn_execution.v1.Elements exceeds maximum protobuf size of 2GB: 7141996715

### ISSUE THREAD

**Issue by ScottHCL** [tensorflow/tfx#2014]
i use the example wide&deep code predicting chicago taxi  to train my own data with apache beam orchestration. everything runs well with 10 tfrecord files(total size 7G),but when I increase to 20 tfrecord files(total size about 14G),it crash with the below error:
ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_common.py", line 84, in _transform
    return transformer(message)
ValueError: Message org.apache.beam.model.fn_execution.v1.Elements exceeds maximum protobuf size of 2GB: 7142158491
ERROR:grpc._common:Exception serializing message!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_common.py", line 84, in _transform
    return transformer(message)
ValueError: Message org.apache.beam.model.fn_execution.v1.Elements exceeds maximum protobuf size of 2GB: 7141996715
ERROR:root:Failed to read inputs in the data plane.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/data_plane.py", line 272, in _read_inputs
    for elements in elements_iterator:
  File "/usr/local/lib/python3.6/dist-packages/grpc/_server.py", line 382, in __next__
    return self._next()

my enviriment is:
    

-   os system :unbutu 16.4
-       2 16g  Tesla P100-PCIE GPU

tensorflow plugin version：
tensorflow                         2.1.0       
tensorflow-data-validation         0.21.5      
tensorflow-estimator               2.1.0       
tensorflow-metadata                0.21.2      
tensorflow-model-analysis          0.21.6      
tensorflow-serving-api             2.1.0       
tensorflow-transform               0.21.2

tfx version：
tfx                                0.21.4      
tfx-bsl                            0.21.4 

it indicate data exceeds maximum protobuf size of 2GB，but it is very common to deal with such or even larger data,i wonder hot to solve it  and what the right way is. it is pleasure to give some advice，thx

**Comment by ConverJens** [comment]
@ScottHCL @sumitbinnani 
Did any of you manage to find a work around or solution to this?

**Comment by tvalentyn** [comment]
We made recently made some improvements in Beam to reduce the chance of this failure and add better logging, see: https://github.com/apache/beam/issues/31607
