### ISSUE TITLE
ExampleGen support for tfds

### ISSUE THREAD

**Issue by tommywei110** [tensorflow/tfx#2027]
Even though the main idea behind TFX is to enable production setting ML use cases, it would be helpful if people can use "available datasets" to test out the components and experiment with different structures.

Therefore, I think it's useful to provide tfds support in TFX ExampleGen components. Since currently ExampelGen only works with tfrecord and csv, the tf.dataset type output by tfds is not natively supported.

The easy way to provide support is to have a library that converts tf.dataset to csv and CsvExampleGen.

But there might be potential benefits to doing this natively as a stand along tfdsExampleGen. So it's worth discussing what's the best way forward.

**Comment by zhitaoli** [comment]
@1025KB Can you discuss this with @tommywei110 and @davidzats-eng ?

**Comment by 1025KB** [comment]
convert to csv might lose some type information. a custom DatasetExampleGen that takes dataset name and convert to tf.Example should be fine

**Comment by rmothukuru** [comment]
@tommywei110,
Can you please confirm if @1025KB's comment has answered your question. Thanks!

**Comment by lxkain** [comment]
Are there plans for this feature? Would a PR be welcome that would provide this functionality?

**Comment by lxkain** [comment]
Cross-referencing:
https://github.com/tensorflow/datasets/issues/2082

**Comment by windmaple** [comment]
+1
