### ISSUE TITLE
Presto based ExampleGen

### ISSUE THREAD

**Issue by zhitaoli** [tensorflow/tfx#203]
[Presto](http://prestodb.github.io/) is a very widely analytical query engine. It already has a [python API ](_https://github.com/prestodb/presto-python-client_) which supports 'fetchall' or fetch batch semantics. It will be a good idea if we could have an ExampleGen (possible as a custom component) so user can connect TFX after any analytical engine supported by Presto (hive, hbase, etc)

**Comment by junhee-yoo** [comment]
Hi, I've written some code for this issue and made a PR: https://github.com/tensorflow/tfx/pull/361
Please check it and let me know what will be needed to improve.

Thanks!

**Comment by junhee-yoo** [comment]
@zhitaoli @krazyhaas @rmothukuru
Hi, May I get some comments on PR: #361?
I copied most of PrestoExampleGen codes from BigQueryExampleGen but it has dedicated spec for Presto login/connection information.
And it has own it's component so I didn't put it into custom_executors directory.

Thank you!
p.s. If I interrupted community process, I apology. Please let me know how can I contribute in this issue.

**Comment by gowthamkpr** [comment]
This has been implemented as a custom component. You can find it [here](https://github.com/tensorflow/tfx/tree/master/tfx/examples/custom_components/presto_example_gen).
