### ISSUE TITLE
Could I use scikit learn model on TFX ? 

### ISSUE THREAD

**Issue by raghav20** [tensorflow/tfx#205]
Few of the models we built are using Scikit learn. I was wondering if we can use that model in TFX.

**Comment by 1025KB** [comment]
Currently most of existing component are tf.example based, if your data is in different format, you won't be able to directly using TFX,

if scikit can take tf.record with tf.example payload, you can custom a trainer component to fit scikit learn into TFX, but the downstream component of trainer requires a savedModel, I'm not sure if scikit can generate that

**Comment by raghav20** [comment]
We have a model pipeline where multiple models built on different libraries are run. Once the training is complete we pick the best model. Is there anything that can be done in this case ?

**Comment by wjarek2** [comment]
Currently TFX works with TensorFlow 1.x which provides a rich set of estimators - https://www.tensorflow.org/guide/estimators, https://www.tensorflow.org/api_docs/python/tf/estimator. TensorFlow also supports custom estimators if you don't see one that fits your problem. Will porting to TensorFlow be an option for you? In the future we're also planning to support TensorFlow 2.0 and greater ease of use e.g. (see https://github.com/tensorflow/tfx/blob/master/ROADMAP.md). TFX supports having multiple TensorFlow models (Trainers) trained as a part of the same pipeline.

**Comment by raghav20** [comment]
I see that was helpful guys thanks a lot looking forward to see if we will have any updates on this later

**Comment by gowtham-kp** [comment]
@raghav20 Closing this issue as it has been answered. Please add additional components and we can reopen the issue again. Thanks!

**Comment by MrRace** [comment]
By now, TFX seems can not support other format models, for example sklearn......

**Comment by dbustosp** [comment]
I was wondering the seems like is not possible for the moment.

**Comment by molejnik-mergebit** [comment]
In regards to TF 2.x, can we reopen this issue?

**Comment by zhitaoli** [comment]
@1025KB can you comment on your view of importing a sklearn into the pipeline and use it in particular components?

I think with our near term plan for supporting custom metrics extractor from TFMA, at least Evaluator/Pusher integration probably makes some sense?
