### ISSUE TITLE
Upgrade TFDV to 0.22.1

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2050]
We are currently blocked by TFX requiring TFDV to be `>=0.22`. This blocks us to upgrade TFDV and upgrade pandas to 1.0.X in our internal system. 

Would it be possible to bring in TFDV 0.22.1 released for an upcoming TFX release?

Related issue: https://github.com/tensorflow/data-validation/issues/129

**Comment by zhitaoli** [comment]
I'm not sure what's blocking you from using an upgraded version of TFDV (i.e, 0.22.1). If you reinstall this should be what your system picks up.

**Comment by casassg** [comment]
Mmm that's true. Sorry about that, there was some internal caching issue and we were picking up an old TFX version.
