### ISSUE TITLE
AttributeError: 'list' object has no attribute 'type' [while running 'GenerateStatistics[train] 

### ISSUE THREAD

**Issue by PradeepSingh96** [tensorflow/tfx#2070]
https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components.ipynb
When running TFX example on google colab, got following errors

statistics_gen = StatisticsGen(
    examples=example_gen.outputs['examples'])
context.run(statistics_gen)
Error messages:

INFO:absl:Running driver for StatisticsGen
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Running executor for StatisticsGen
INFO:absl:Using 1 process(es) for Beam pipeline execution.
INFO:absl:Generating statistics for split train
INFO:absl:Statistics for split train written to /tmp/tfx-interactive-2020-06-28T05_35_31.021774-wrfcf4sp/StatisticsGen/statistics/2/train.
INFO:absl:Generating statistics for split eval
INFO:absl:Statistics for split eval written to /tmp/tfx-interactive-2020-06-28T05_35_31.021774-wrfcf4sp/StatisticsGen/statistics/2/eval.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner.process()

98 frames
AttributeError: 'list' object has no attribute 'type'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/arrow/arrow_util.py in flatten_nested(array, return_parent_indices)
    192   parent_indices = None
    193 
--> 194   while is_list_like(array.type):
    195     if return_parent_indices:
    196       cur_parent_indices = array_util.GetFlattenedArrayParentIndices(

AttributeError: 'list' object has no attribute 'type' [while running 'GenerateStatistics[train]/RunStatsGenerators/GenerateSlicedStatisticsImpl/TopKUniquesStatsGenerator/ToTopKTuples']

**Comment by rmothukuru** [comment]
@PradeepSingh96,
This issue is being tracked in #2065. Can you please confirm if we can close this issue. Thanks!

**Comment by wazeerzulfikar** [comment]
`pip install tensorflow-data-validation==0.22.0` worked for me!

**Comment by rmothukuru** [comment]
@PradeepSingh96,
Can you please respond to the above comment. Thanks!

**Comment by PradeepSingh96** [comment]
@rmothukuru 
Yes, this issue is tracked in #2065.

**Comment by rmothukuru** [comment]
Closing this issue as it is already being tracked in #2065. Thanks!
