### ISSUE TITLE
Improve docs on ChannelParameter and ExecutionParameter

### ISSUE THREAD

**Issue by cent5** [tensorflow/tfx#2080]
These 2 types of parameters are discussed in a couple of TFX guides, but it is difficult to infer why/when to use them. Can we have some more explanation here?

- https://www.tensorflow.org/tfx/api_docs/python/tfx/types/component_spec/ExecutionParameter
- https://www.tensorflow.org/tfx/api_docs/python/tfx/types/component_spec/ChannelParameter

**Comment by UsharaniPagadala** [comment]
@cent5 
Closing this issue for now ,The above mentioned links are throwing 404 errors. Please feel free to reopen, 
Refer these [examples](https://github.com/tensorflow/tfx/blob/54aa6fbec6bffafa8352fe51b11251b1e44a2bf1/tfx/types/component_spec.py#L99) and the [docs](https://www.tensorflow.org/tfx/guide/custom_component) , hope this helps.Thanks
