### ISSUE TITLE
TFDV - Slicing data based on date range

### ISSUE THREAD

**Issue by srinivasaraov** [tensorflow/tfx#2111]
In Tensorflow Data Validation, there is a method slicing_util.get_feature_value_slicer() to slice data based on a feature value.

Is it possible to slice the data based on a date range using the above method and compare the sliced datasets ?

Let's say, I have 'n' records within date range t1-t10. If I want to split the data into 4 sets which fall in date ranges t1-t3, t4-t6 and t8-t10, is it possible with above slicing method?

**Comment by rmothukuru** [comment]
@srinivasaraov,
As this issue is not related to TFX Pipeline but it is specific to Tensorflow Data Validation, request you to raise issue in [TFDV Github Repository](https://github.com/tensorflow/data-validation/issues). Thanks!

**Comment by rmothukuru** [comment]
Closing the issue as it has been raised in TFDV Repo. Thanks!
