### ISSUE TITLE
run tfx pipeline on spark

### ISSUE THREAD

**Issue by beijinggao** [tensorflow/tfx#2120]
I try to run tfx pipeline on spark ,but only one example on spark is local model , is it can run on spark cluster model ,if yes, because the spark is distributed,whether other machine need to install tfx and tensorflow ？and if it run on spark cluster,how dose the tensorflow training? is distributed training?

**Comment by 1025KB** [comment]
The env should be the same for all workers. And training doesn't run on spark, spark is only for beam related components

**Comment by ntakouris** [comment]
Please see documentation for [Managing Python Pipeline Dependencies](https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/). 

This is a beam runtime related question.

**Comment by UsharaniPagadala** [comment]
@beijinggao 
Closing this issue.Please feel free to reopen if this still persists. Thanks!
