### ISSUE TITLE
missing comma in script

### ISSUE THREAD

**Issue by seyedrezamirkhani** [tensorflow/tfx#2121]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/guide/build_tfx_pipeline#build_a_custom_pipeline

## Description of issue (what needs changing):

A comma needs to be added to the script used in step 3 at the end of line: data_path=DATA_PATH

### Submit a pull request?
YES

https://github.com/seyedrezamirkhani/tfx/pull/1

**Comment by rmothukuru** [comment]
Closing this issue as it has been resolved. Thanks!
