### ISSUE TITLE
tfx cli is embarrasingly slow

### ISSUE THREAD

**Issue by ntakouris** [tensorflow/tfx#2164]
**Problem Description**
A single `tfx ...` command takes about 10~20 seconds to produce some output to stdout and finish executing.
This is true for any kind of command (existing, non-existing/illegal, template copy, pipeline creation, ...).

--
`tfx` version: `0.22.0`

On: macOS Mojave 10.14.1 (13.3" 2016 macbook pro)

**Comment by zhitaoli** [comment]
Sorry about that. While the performance of CLI was not an initial focus, such a slowness is indeed awkward. I wonder how much of this is about loading/setting up python environment, vs getting to concrete work.

**Comment by gowthamkpr** [comment]
@ntakouris Is it still an issue? Can you please check with latest version of tfx and let me know thanks!!
