### ISSUE TITLE
Bug: Deleted tfx/BUILD after git clone

### ISSUE THREAD

**Issue by alexlatchford** [tensorflow/tfx#2168]
```
 ✘  ~/Code/kubeflow  git clone https://github.com/tensorflow/tfx.git --verbose
Cloning into 'tfx'...
POST git-upload-pack (gzip 13415 to 6658 bytes)
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 19658 (delta 2), reused 3 (delta 0), pack-reused 19645
Receiving objects: 100% (19658/19658), 175.09 MiB | 5.57 MiB/s, done.
Resolving deltas: 100% (14631/14631), done.
 ~/Code/kubeflow  cd tfx
 ~/Code/kubeflow/tfx   master ●  git status
On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	deleted:    tfx/BUILD
no changes added to commit (use "git add" and/or "git commit -a")
```

I cloned this repo without problems yesterday (or maybe 14th) so guessing something has happened between that timeframe.

My env:
* Mac OS X 10.15
* git 2.18.0

As far as I'm aware there are no `git hooks` in the `tfx` repo, I got a co-worker to recreate this on his machine so don't think it's my laptop unless I missed some requirement I need to pre-install.

---

I was investigating [this build failure](https://travis-ci.com/github/kubeflow/pipelines/jobs/361767089) for `kubeflow/pipelines` so guessing it may be affecting the Travis CI build machines too.

**Comment by alexlatchford** [comment]
Even stranger looks like any attempts I make to run `git reset` fail and actually make it a different error 😓 :

```
 ~/Code/kubeflow/tfx   master ●  git reset --hard
HEAD is now at 22b50ab6 Merge pull request #2104 from 18jeffreyma:master
 ~/Code/kubeflow/tfx   master ●  git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    tfx/build/BUILD
	deleted:    tfx/build/gen_proto.sh

no changes added to commit (use "git add" and/or "git commit -a")
```

Also can't seem to get rid of these unstaged changes using `git checkout -- tfx/BUILD` 😕

**Comment by alexlatchford** [comment]
Looking through the commits going to guess this is related to https://github.com/tensorflow/tfx/commit/96a3f4fa81e6f02e49c698e9bd216a13925b69b3

Apologies if I've missed something I needed to do.

cc @chongkong

**Comment by 1025KB** [comment]
> Looking through the commits going to guess this is related to [96a3f4f](https://github.com/tensorflow/tfx/commit/96a3f4fa81e6f02e49c698e9bd216a13925b69b3)

yep, we changed our local debugging processed (above PR updates the instruction), bazel is now needed
> 
> Apologies if I've missed something I needed to do.
> 
> cc @chongkong
> 
> In case this matters I'm using a pretty old version of Bazel to ensure it can work with the `kubeflow/pipelines` repo:
> 
> ```
>  ✘  ~/Code/kubeflow/tfx-043b2b7e93c31f36ab205826953d4c233c74d7df  bazel version
> Starting local Bazel server and connecting to it...
> Build label: 0.23.1
> Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Mon Mar 4 10:40:32 2019 (1551696032)
> Build timestamp: 1551696032
> Build timestamp as int: 1551696032
> ```
