### ISSUE TITLE
Exception in thread beam_control_read and grpc.RpcError

### ISSUE THREAD

**Issue by PFpengfeng** [tensorflow/tfx#2178]
When running the pipeline example [mnist_pipeline_native_keras.py](https://github.com/tensorflow/tfx/blob/master/tfx/examples/mnist/mnist_pipeline_native_keras.py) .  I  get a Exception like the figure below.  I feel confused because I ran it successfully several days ago.
![image](https://user-images.githubusercontent.com/57736376/87866591-49f14180-c9b6-11ea-9c33-13931b6772d0.png)

**Comment by 1025KB** [comment]
What version? and is this local run?

**Comment by PFpengfeng** [comment]
Yeah，it's local run.  I used python3.6.  And some librarys used is below. 

tensorflow 2.2.0
tfx 0.22
tensorflow-data-validation     0.22.2
tensorflow-estimator           1.15.1
tensorflow-metadata            0.22.2
tensorflow-model-analysis      0.22.2
tensorflow-serving-api         2.2.0
tensorflow-transform           0.22.0
grpcio                         1.30.0
grpcio-gcp                     0.2.2
grpcio-tools                   1.30.0
protobuf                       3.12.2
absl-py                        0.9.0
apache-beam                    2.22.0
