### ISSUE TITLE
Project can't be cloned correctly on macOS due to case insensitivity

### ISSUE THREAD

**Issue by ColinCampbell-GBI** [tensorflow/tfx#2184]
Under the `tfx` folder there's a folder called `build` and a bazel file called `BUILD`. Because macOS is by default case insensitive, only the folder is cloned when `git clone` is run. This means that when trying to build locally, bazel won't be able to find the `BUILD` file required to compile the protobuf schemas, and will fail.

**Comment by alexlatchford** [comment]
Looks like the same issue as me :) https://github.com/tensorflow/tfx/issues/2168

Thanks for finding out why this was happening!

**Comment by chongkong** [comment]
Thanks for reporting the cause for the issues!
