### ISSUE TITLE
Trainer Component doesn't support custom SPEC_CLASS

### ISSUE THREAD

**Issue by ColinCampbell-GBI** [tensorflow/tfx#2185]
The `Trainer` component has a `SPEC_CLASS` class variable, but in the `__init__` function its hardcoded to use `TrainerSpec` instead. This means that we need to override the entire function just to use a custom spec. If the ctor instead used the `SPEC_CLASS` and passed a **kwargs variable into it, it would be much easier to create and use a custom spec for the trainer. Currently, I need to re-implement the Component just to be able to pass a new channel into the Trainer.

**Comment by 1025KB** [comment]
SPEC_CLASS is not configurable. Custom component is the correct way if you need to add a new channel.

**Comment by ColinCampbell-GBI** [comment]
If using a custom component is the only way to add a new channel, then shouldn't it be made possible to easily subclass a component and only need to change as few parts as possible? Currently to add a channel it seems like I'm forced to copy paste the entire existing Trainer code and make a few changes. This makes it much more difficult to update TFX when new versions come out, since I'll need to audit what internal code has changed and copy that over as well. If SPEC_CLASS was the only thing that needed to be changed in a subclass, then people wouldn't need to worry about the internals of Trainer at all to add a channel.

**Comment by 1025KB** [comment]
Adding a new channel requires changes to spec, component and executor.
And it's not a general change always, different users might have different way to use the new channel.

Thus we don't support custom spec as it would be the same as custom component in most case.

**Comment by ColinCampbell-GBI** [comment]
Then shouldn't there be a change to the component and executor to make it so adding a channel doesn't require massive copy pasting and modification of internal Component/Executor code? As is TFX has a large maintenance burden for anyone who needs to do anything that requires custom logic. It's going to make it much harder for anyone in our situation to update versions in the future.

I already have an internal custom component and executor that lets me add a channel just by setting the SPEC_CLASS and making a custom Executor, it seems like there should be a clean official way, so other users aren't stuck doing the same thing.

```python
class CustomTrainerExecutor(CustomSpecExecutor):
    def GetFnArgs(...):
        fn_args = super(...)
       # Add handling for new custom spec variables
       ...
        

class CustomTrainer(CustomSpecTrainer):
    SPEC_CLASS = TrainerSpecWithNewChannel
    EXECUTOR_CLASS = CustomTrainerExecutor
```

**Comment by numerology** [comment]
Hi @ColinCampbell-GBI 

We're exploring a more flexible Training component design currently, which allows users to run arbitrary custom container training job on CAIP training.

This issue, together with https://github.com/tensorflow/tfx/issues/2183, can potentially be solved by that. In general one will be able to generate the component spec dynamically and bind it to a container spec.

**Comment by ucdmkt** [comment]
Responded to #2183. 

To this immediate issue, would it be an approach to unblock, to create a very lightweight custom component as a subclass of `trainer.Trainer` class, with your own `SPEC_CLASS` and other additional constructor `**kwargs`?

**Comment by singhniraj08** [comment]
@ColinCampbell-GBI,

Could you please follow this [migration guide](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/launcher/README.md) to migrate from custom launcher to custom ExecutorOperator(a new abstraction in the IR based execution stack) and let us know if it unblocks you.
Thank you!
