### ISSUE TITLE
TFX Example_Gen Produce RuntimeError

### ISSUE THREAD

**Issue by C45513** [tensorflow/tfx#2197]
I've been getting the following error when I run `context.run(example_gen)` , and I like to understand what does it mean and how can I avoid getting the error. Please advice and thanks in advance!

**Error:** `RuntimeError: Files in same split /home/jupyter/.../data/* have different header.`

The data is a csv with headers of "A,B,C,D"

```
from  tfx.proto import example_gen_pb2

base_dir = '/home/jupyter/.../data/'
#Input has a single split 'input_dir/*
#Output 2 splits: train:eval=3:1.'
output = example_gen_pb2.Output(
            split_config=example_gen_pb2.SplitConfig(splits=[
                example_gen_pb2.SplitConfig.Split(name='train', hash_buckets=3),
                example_gen_pb2.SplitConfig.Split(name='eval', hash_buckets=1)
            ]))

examples = csv_input(os.path.join(base_dir))
example_gen = CsvExampleGen(input=examples, output_config=output)
```

**Comment by 1025KB** [comment]
All csv files should have the same header, there might be other files that matches the pattern with different header

**Comment by C45513** [comment]
@1025KB Thanks for your reply. However, there is only one csv file in the folder.

**Comment by C45513** [comment]
@1025KB To go around it, I had to delete the data folder, and recreate and reupload the CSV file for it to pick up. However, after running for another few more rounds, the error comes back again. There is only 1 CSV file in the folder.

**Comment by numerology** [comment]
@C45513 

Hi. If you're running on Jupyter notebook, do you mind checking the hidden file under the working directory? It's very likely auto-generated checkpoint files can pollute the environment.

**Comment by C45513** [comment]
Hi @numerology, yes I'm running on Jupyter notebook. I have a look and there is no other CSV file stands out, however, to avoid that, what is the best practice?

**Comment by numerology** [comment]
> Hi @numerology, yes I'm running on Jupyter notebook. I have a look and there is no other CSV file stands out, however, to avoid that, what is the best practice?

Just to clarify, it does not have to be a CSV file, any arbitrary file will be picked by the TFX IO logic. And to prevent this, my best bet will be to ensure `base_dir` does not contain any `.ipynb` file.

**Comment by C45513** [comment]
@numerology, thanks for your suggestion. Let me reorganize my directory to ensure that doesn't happen. Thanks again.

**Comment by MasoumehVahedi** [comment]
I have the same issue. Could you give me a solution?

**Comment by skydowx** [comment]
I was following a TFX tutorial and removing everything besides the CSV from the input directory worked for me.

**Comment by woker001** [comment]
> 같은 문제가 있습니다. 해결책을 주시겠습니까?

This error is caused by reading all files in that directory path. Remove all files other than data in the folder where the data is stored. 
e.g. `ls -a & rm -rf {dir_name}`

**Comment by rcgreen99** [comment]
ExampleGen can see .csv files in other directories within the input_base dir so make sure you're in the correct directory. This fixed my issue (I had to go one directory down).

**Comment by siddhantgbg** [comment]
> @C45513
> 
> Hi. If you're running on Jupyter notebook, do you mind checking the hidden file under the working directory? It's very likely that auto-generated checkpoint files can pollute the environment.

Thank you for this reply. This helped me to fix the same while running in the google colab. :)
