### ISSUE TITLE
Cannot build Docker container on Centos7

### ISSUE THREAD

**Issue by pmccarthy-dstillery** [tensorflow/tfx#2198]
$ docker --version
Docker version 17.03.2-ce, build f5ec1e2

$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

$ git status
HEAD detached at v0.22.1

I'm trying to build the Docker dev container with 
`$ ./tfx/tools/docker/build_docker_image.sh`

but the process fails with this error:

```
Installing collected packages: pyasn1, pyasn1-modules, setuptools, rsa, cachetools, six, google-auth, python-dateutil, websocket-client, urllib3, oauthlib, chardet, idna, certifi, requests, requests-oauthlib, pyyaml, kubernetes, protobuf, wrapt, numpy, scipy, gast, opt-einsum, astunparse, google-auth-oauthlib, absl-py, tensorboard-plugin-wit, werkzeug, zipp, importlib-metadata, markdown, grpcio, tensorboard, tensorflow-estimator, h5py, google-pasta, keras-preprocessing, termcolor, tensorflow, tensorflow-serving-api, httplib2, google-auth-httplib2, googleapis-common-protos, pytz, google-api-core, uritemplate, google-api-python-client, monotonic, fasteners, oauth2client, google-apitools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.0
    Uninstalling setuptools-49.2.0:
ERROR: Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty: '/opt/venv/lib/python3.6/site-packages/__pycache__/'                                                                

The command '/bin/sh -c CFLAGS=$(/usr/bin/python3.6-config --cflags) python3.6 -m pip install   "kubernetes>=10.0.1,<11"   "tensorflow>=1.15,<3"   "tensorflow-serving-api>=1.15,<3"   "google-api-python-client==1.8.0"   "google-apitools==0.5.30"   "setuptools==41.4.0"' returned a non-zero code: 1


```

**Comment by rmothukuru** [comment]
@pmccarthy-dstillery, 
From this Open [Github Issue](https://github.com/tensorflow/tfx/issues/1929), it looks like TFX is not compatible with Cent OS yet. Thanks!

**Comment by rmothukuru** [comment]
@pmccarthy-dstillery,
Can you please respond to the above comment. Thanks!

**Comment by pmccarthy-dstillery** [comment]
Hi @rmothukuru, I'm sorry I'm a little confused. What information can I provide?

Thanks!

**Comment by rmothukuru** [comment]
@pmccarthy-dstillery,
Sorry for the confused statement. What I mean to ask you is that since there is an Open Issue, #1929 about installing TFX in Cent OS, can we close this issue. Thanks!

**Comment by pmccarthy-dstillery** [comment]
I'm happy to close the issue if appropriate, but it's not clear to me that my issue is related to CentOS 7 per se. If the error occurs inside of the build process defined in the Dockerfile, doesn't that mean that it's actually an error of the tfx_base:latest container's OS?

**Comment by gowthamkpr** [comment]
@pmccarthy-dstillery This might be the OS fault not the tfx. Were you able to find a solution for this issue?

**Comment by gowthamkpr** [comment]
@pmccarthy-dstillery I am close this issue as it has been inactive for 2 weeks. Feel free to reopen it. Thanks!
