### ISSUE TITLE
Improve TFMA guide

### ISSUE THREAD

**Issue by ianhellstrom** [tensorflow/tfx#22]
The [TFMA guide](https://github.com/tensorflow/tfx/blob/096457e47bce8fd69566c66538dd56d11fd69c65/examples/chicago_taxi/chicago_taxi_tfma_local_playground.ipynb) shows what charts are available inside a Jupyter notebook, but no such notebook exists in the TFX repository, although there is one for TFDV.

On my own local machine I have done the following to connect to the MLMD:

```python
from ml_metadata.metadata_store import metadata_store
from ml_metadata.proto import metadata_store_pb2

TFX_HOME = os.path.join(os.environ['HOME'], 'tfx')
METADATA_URI = os.path.join(TFX_HOME, 'metadata/taxi/metadata.db')

conn_conf = metadata_store_pb2.ConnectionConfig()
conn_conf.sqlite.filename_uri = METADATA_URI
conn_conf.sqlite.connection_mode = 3
store = metadata_store.MetadataStore(conn_conf)

def get_uris(type_name, split):
    return [a.uri for a in store.get_artifacts_by_type(type_name) if a.properties['split'].string_value == split]

model_path = get_uris('ModelEvalPath', '')[-1] # grab last in list
result = tfma.load_eval_result(model_path)

tfma.view.render_plot(result) # shows nothing!
tfma.view.render_slicing_metrics(result) # shows nothing!
```

I started Jupyter with `jupyter notebook`. Note that the notebook does not throw any exceptions. It executes the `tfma.view.render_*` code but outputs nothing.

I kept the code from the (local) taxi pipeline [as is](https://github.com/tensorflow/tfx/blob/3d7bb6a0ae0aa0ed6269c2e1f4d2bb3e8bee2a93/examples/chicago_taxi_pipeline/taxi_pipeline_simple.py) and I've successfully run it locally with Airflow. 

Either the code I have is incorrect, or I am missing something, because I do not see any plots in my notebooks.

**Comment by pfyang** [comment]
Hi,

The TFMA notebook has been moved under [TFX's examples folder](https://github.com/tensorflow/tfx/tree/master/examples/chicago_taxi) and the notebook can be found [here](https://github.com/tensorflow/tfx/blob/master/examples/chicago_taxi/chicago_taxi_tfma_local_playground.ipynb). 

We will update the TFMA guide to point to the new location.

With respect to visualization not rendering, could you please help us debug the issue by answering the following questions:
- What version of TFMA do you have installed on your machine?
- Have you installed / enabled TFMA for Jupyter by following the steps [here](https://github.com/tensorflow/model-analysis#installation?
- Did tfma.load_eval_result return anything? What if so, what is the value of result if you just evaluate it in Jupyter
- What browser do you use? If not Chrome, could you please try it on Chrome?
- Did you see any JS error in Chrome's developer console when you call render_plot or render_slicing_metrics? If so, what are they?
- If you inspect the Jupyter notebook using Chrome's developer console, did you see any element with tfma- prefix like <tfma-nb-plot>?

Thanks!

**Comment by ianhellstrom** [comment]
Thanks!

The main problem was that I was missing the TFMA `jupyter nbextension` commands. I did not see these in the TFX repo and therefore did not think to look further and in 'tensorflow/model-analysis' for details. 

It might be a good idea to have these included in the TFX installation instructions.

**Comment by 1025KB** [comment]
Hi, 

Here is the [TFX Guide](https://www.tensorflow.org/tfx/guide), 

And for the taxi example, here is the [instructions](https://github.com/tensorflow/tfx/blob/096457e47bce8fd69566c66538dd56d11fd69c65/examples/chicago_taxi/README.md)

Let me know if you run into any issues, thanks!
