### ISSUE TITLE
fn_args schema uri attribute naming inconsistency between tuner_fn and run_fn (trainer)

### ISSUE THREAD

**Issue by ntakouris** [tensorflow/tfx#2206]
You can use a pipeline setup like:

```python
    tuner = Tuner(
            tuner_fn=tuner_fn,
            schema=schema_gen.outputs['schema'], ..)
        components.append(tuner)

        hyperparameters = tuner.outputs['best_hyperparameters']

        trainer = Trainer(
                          run_fn=run_fn,
                          schema=schema_gen.outputs['schema'], ..)
```

But on the trainer's `run_fn` the schema uri is at `fn_args.schema_file`, whereas on the `tuner_fn`, the schema uri is at `fn_args.schema_path`.

(Perhaps it makes sense to just use `schema_uri` for everything)

**Comment by montanier** [comment]
Also, transform_output is at `fn_args.transform_graph_path` in `tuner_fn` but in `fn_args.transform_output` in `run_fn`.
