### ISSUE TITLE
Add the ability to have transform component output only transform_graph and not transformed_examples

### ISSUE THREAD

**Issue by ntakouris** [tensorflow/tfx#2207]
The dataset is already read from a 'slower' datasource (for example, csv files) and fed into example gen to split performant `.tfrecord` files. 

No need to force re-duplicating the preprocessed whole dataset to the transform component's staging directory, the preprocessing could be done via the map function of `tf.data.Dataset`, on train data loading time, with the prefetch and autotune parallel calls optimisations, without performance drop. (Imagine duplicating TBs of data on the transform step)

The current behaviour of the `Transform` component with arg `transformed_examples=None` is to allocate a directory `<pipeline root>/Transform/transformed_examples/` and save the preprocessed tf records there. 

Could not avoid it with `transformed_examples=external_input(/dev/null)` and there is no documentation of a channel as far as I am aware of, that acts as a `no-output` flag.

**Comment by rmothukuru** [comment]
@ntakouris,
As the issue is specific to `TF - Transform` and  not related to `TFX` as a whole, I request you to raise an issue in [TF Transform Github Repo](https://github.com/tensorflow/transform/issues/new). Thanks!

**Comment by zoyahav** [comment]
This issue is actually tfx specific, as tf.transform the library (this repo) does allow only outputting a graph. TFX Transform doesn't currently allow not writing transformed examples. So this issue should actually be under this repo.

**Comment by rmothukuru** [comment]
@zoyahav and @ntakouris,
Ok, sorry for the misinterpretation and the confusion.

**Comment by ntakouris** [comment]
Fixed in latest version with `materialize=False` on the component level. Thank you.
