### ISSUE TITLE
When importing  tensorflow_transform.beam,  AttributeError: type object 'apache_beam.runners.worker.operations.ConsumerSet' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by umusa** [tensorflow/tfx#2219]
I trying to run the example code at https://www.tensorflow.org/tfx/tutorials/transform/simple
on databricks GPU cluster.

My env:

      7.1 ML Spark 3.0.0 Scala 2.12 GPU
      python 3.7
      tensorflow: Version: 2.1.1
      tensorflow-transform: 0.15.0

When I run 

      import tensorflow_transform.beam as tft_beam

I got error:

   AttributeError                            Traceback (most recent call last)

<command-2494512> in <module>
      2 
      3 import apache_beam.io.iobase
----> 4 import tensorflow_transform.beam as tft_beam
      5 from tensorflow_transform.tf_metadata import dataset_metadata
      6 from tensorflow_transform.tf_metadata import dataset_schema

/databricks/python/lib/python3.7/site-packages/tensorflow_transform/beam/__init__.py in <module>
     17 # analyzer_impls registers implementation of analyzers.
     18 from tensorflow_transform.beam import analyzer_impls
---> 19 from tensorflow_transform.beam.impl import AnalyzeAndTransformDataset
     20 from tensorflow_transform.beam.impl import AnalyzeDataset
     21 from tensorflow_transform.beam.impl import AnalyzeDatasetWithCache

/databricks/python/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py in <module>
     83 import apache_beam as beam
     84 
---> 85 from apache_beam.runners.portability import fn_api_runner
     86 from apache_beam.transforms import util
     87 from apache_beam.typehints import Any

/databricks/python/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/__init__.py in <module>
     17 
     18 from __future__ import absolute_import
---> 19 from apache_beam.runners.portability.fn_api_runner.fn_runner import FnApiRunner

/databricks/python/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in <module>
     56 from apache_beam.runners import runner
     57 from apache_beam.runners.portability import portable_metrics
---> 58 from apache_beam.runners.portability.fn_api_runner import execution
     59 from apache_beam.runners.portability.fn_api_runner import translations
     60 from apache_beam.runners.portability.fn_api_runner.execution import ListBuffer

/databricks/python/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/execution.py in <module>
     44 from apache_beam.portability.api import beam_runner_api_pb2
     45 from apache_beam.runners import pipeline_context
---> 46 from apache_beam.runners.portability.fn_api_runner import translations
     47 from apache_beam.runners.portability.fn_api_runner.translations import create_buffer_id
     48 from apache_beam.runners.portability.fn_api_runner.translations import only_element

/databricks/python/lib/python3.7/site-packages/apache_beam/runners/portability/fn_api_runner/translations.py in <module>
     45 from apache_beam.portability import python_urns
     46 from apache_beam.portability.api import beam_runner_api_pb2
---> 47 from apache_beam.runners.worker import bundle_processor
     48 from apache_beam.utils import proto_utils
     49 

/databricks/python/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py in <module>
     69 from apache_beam.runners import pipeline_context
     70 from apache_beam.runners.worker import operation_specs
---> 71 from apache_beam.runners.worker import operations
     72 from apache_beam.runners.worker import statesampler
     73 from apache_beam.transforms import sideinputs

/databricks/python/lib/python3.7/site-packages/apache_beam/runners/worker/operations.cpython-37m-x86_64-linux-gnu.so in init apache_beam.runners.worker.operations()

AttributeError: type object 'apache_beam.runners.worker.operations.ConsumerSet' has no attribute '__reduce_cython__'

**Comment by gowthamkpr** [comment]
@umusa This looks like the apache beam and python version mismatch. Also can you please use the latest version of tfx and let me know if the issue still persists. Thanks!!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than a month. Please add additional comments for us to open this issue again. Thanks!!
