### ISSUE TITLE
AttributeError: module 'tfx.proto.example_gen_pb2' has no attribute 'Input'

### ISSUE THREAD

**Issue by AseiSugiyama** [tensorflow/tfx#222]
# Description

From [ExampleGen user guide](https://www.tensorflow.org/tfx/guide/examplegen) `example_gen_pb2` should have `Input` method

```python
from  tfx.proto import example_gen_pb2

# Input train split is 'input_dir/train/*', eval split is 'input_dir/eval/*'.
# Output splits are generated one-to-one mapping from input splits.
input = example_gen_pb2.Input(splits=[
                example_gen_pb2.Input.Split(name='train', pattern='train/*'),
                example_gen_pb2.Input.Split(name='eval', pattern='eval/*')
            ])
examples = csv_input(input_dir)
example_gen = CsvExampleGen(input_base=examples, input_config=input)
```

However, `example_gen_pb2` raises `AttributeError` by running following script, 

```python
from  tfx.proto import example_gen_pb2
example_gen_pb2.Input
```

```console
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-936b1e260049> in <module>
      1 from  tfx.proto import example_gen_pb2
----> 2 example_gen_pb2.Input

AttributeError: module 'tfx.proto.example_gen_pb2' has no attribute 'Input'
```

# How to reproduce

Here is colab notebook : [AttributesError_example_gen_pb2.ipynb](https://gist.github.com/AseiSugiyama/923d55aa79f1937e104932145e0c11ec).

Since colab uses python 3.6, I run same code on Python 3.5 with Docker container environment. And same error raised when running same code.
Here is repo. [AseiSugiyama/TFXTestRun](https://github.com/AseiSugiyama/TFXTestRun)

# Environment

* Python : 3.5, 3.6
* TFX Version : 0.13.0
* TensorFlow Version : 1.13.1

**Comment by ruoyu90** [comment]
The error is expected, due to the fact that `Input` was introduced after 0.13.0 release. If you try to install from [head](https://github.com/tensorflow/tfx/blob/master/CONTRIBUTING.md#testing-local-change) you will get the latest feature.

**Comment by AseiSugiyama** [comment]
@ruoyu90 
With installing TFX from head, I could find `Input`.
Thank you for your support!
