### ISSUE TITLE
TensorFlow-extended: How to generate interactive HTML outputs on databricks notebook

### ISSUE THREAD

**Issue by umusa** [tensorflow/tfx#2221]
I am trying to run some example codes at https://www.tensorflow.org/tfx/tutorials/model_analysis/tfma_basic on a databricks notebook.

I would like to use TensorFlow-extended to do ML model development and production on databricks GPU clusters.

The expected results from the code should be an interactive HTML file. There will be some tabs and buttons on the HTML. The users can manipulate the results and visualize them in multiple layouts.

I have run the code by Colab and it works well. You can try it by clicking the button "Run in google Colab" at the top of the webpage and run the notebook on Colab and see the interactive results.

But, when I run the same code on databricks notebook, no interactive results are generated. Only plain txt messages are dumped to the output cells in the notebook.

The databricks env :

   7.1 ML Spark 3.0.0 Scala 2.12 GPU

Could you please help us about this ?

**Comment by rmothukuru** [comment]
@umusa,
Can you please confirm if this issue is similar to #2194? Thanks!

**Comment by umusa** [comment]
This issue is similar as #2223 [,](https://github.com/tensorflow/tfx/issues/2223) where more details are provided. thanks

**Comment by rmothukuru** [comment]
Closing this issue as it is been tracked in #2223. Thanks!
