### ISSUE TITLE
Problem running the step3 notebook

### ISSUE THREAD

**Issue by riyersk** [tensorflow/tfx#227]
I'm trying to run the step3.ipynb in tfx/tfx/examples/workshop/notebooks/step3.ipynb.  The first cell throws the attached error.  I notice the get_metadata_store takes a path as an argument, but I don't find that path in my system, so I suspect that this is the problem, but I can't find where and how I was supposed to create that directory.  Any guidance?
![tfxStep3ErrorSet](https://user-images.githubusercontent.com/2560661/59392380-4eb3e280-8d2c-11e9-85b9-d455792e9ca5.jpg)

**Comment by rcrowe-google** [comment]
Are you following the [TFX Developer Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/workshop)?  If so, then the setup.sh script should have created a directory tree called "airflow" under your home directory, and initialized Airflow.  If you have that tree, do you have a file named metadata.db under it?

**Comment by riyersk** [comment]
Yes, I am following that tutorial.  I didn't see any instruction to run a setup script, so I guess that was the issue.  After your comment, I found a setup script under tfx/tfx/workshop/examples/setup/ called setup_demo.sh.  I ran this in the terminal and then I went back and saw that there was a directory called "airflow" in my home directory.  However, I did not see a file named metadata.db under it.  I also did not see the path tfx/metadata/taxi/metadata.db inside the airflow directory, as the code above seems to suggest I should.

**Comment by rcrowe-google** [comment]
Could you delete the ~airflow directory and go back to the [TFX Developer Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/workshop) and start fresh, making sure to read the instructions at each step?  Does your system meet the prerequisites?  Do you see any errors when running setup_script.sh?

**Comment by riyersk** [comment]
I did that.  It solved the problem, thanks!
