### ISSUE TITLE
Configurable transform component

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2281]
A lot of times, we want to change transformations with a more programmatic manner. In this case we would like to propose passing down custom config to the `pre_processing_fn` so that we can do things like:

Preprocessing function:
```py
def preprocessing_fn(inputs, config=None):
  output = {}
  for feature in config['vocab']:
     output[f'{feature}_vocab'] = tf.vocab(inputs[feature])
  ...
  return output
```

Component execution:
```py
transform = Transform(preprocess_fn = preprocess_fn, transform_config = {'vocab': ['text', 'bio' ...]})
```

**Comment by casassg** [comment]
agree, its a extension on the Transform component. TF.Transform already supports doing so (we have actually implemented a version of this internally and are willing to PR it if considered okay).

**Comment by kennethyang404** [comment]
Hi Gerard, custom_config was added to Transform just yesterday: https://github.com/tensorflow/tfx/blob/66f6da0711d6f868343e52652b88a2786db1cc89/tfx/components/transform/component.py#L79

Hope that solves this issue.
