### ISSUE TITLE
BigQueryExampleGen broken ReadFromBigQuery requires a GCS location to be provided

### ISSUE THREAD

**Issue by lihan** [tensorflow/tfx#2293]
Happened on tfx 0.22.1 on Google Colab environment

![image](https://user-images.githubusercontent.com/655051/89638474-39feba80-d8ef-11ea-8a4c-3fde6c1dc681.png)

**Comment by 1025KB** [comment]
Is pipeline root set to GCS locations?

**Comment by lihan** [comment]
@1025KB No other setting used beyond above 3 lines of code, replicated on local environment too.

**Comment by gbosquechacon** [comment]
I'm having the exact same issue. Any help would be appreciated : )

**Comment by numerology** [comment]
@gbosquechacon 

I think one will need to provide --temp_location as part of the beam pipeline arg, and set that to a GCS location

**Comment by gbosquechacon** [comment]
@numerology thanks, it worked! It was just a matter of definition `temp_location` in `beam_pipeline_args` when `context` is instantiated : )
