### ISSUE TITLE
TFX Command-line Interface used locally from localhost console

### ISSUE THREAD

**Issue by wojwoj** [tensorflow/tfx#2346]
Hi,

When creating TFX pipelines from command line on localhost, I can successfully deploy the pipeline, train and push the model. The pipeline is pushed to KubeFlow running on GKE (Kubernetes Engine). However some artifacts are missing. As you can see on attached screen shots, the StatisticsGen component has missing static html with information about loaded data and also ML Metadata tab contains  only message "Corresponding ML Metadata not found.". This problem is present on pipeline's all components.

Exactly the same pipeline code deployed from jupyter notebook on AI Platform works perfectly fine.

Is there any additional configuration needed for ML Metadata when tfx is triggered from localhost console?

Looking forward for some help.

<img width="1174" alt="Screenshot 2020-08-18 at 15 46 08" src="https://user-images.githubusercontent.com/5503825/90520721-041cca00-e16a-11ea-8b2e-24ef4c7cbd57.png">
<img width="1179" alt="Screenshot 2020-08-18 at 15 45 54" src="https://user-images.githubusercontent.com/5503825/90520715-0121d980-e16a-11ea-89ce-8df677af4cde.png">

**Comment by jiyongjung0** [comment]
Hi, thank you for detailed reporting with screenshots. It looks very weird... AFAIK there should be no difference because AI Notebook is also using the same command line interface.

It looks like something is not connected well in the KFP side. Did you install kubeflow using AI Platform Pipelines? For example, using [this marketplace page](https://pantheon.corp.google.com/marketplace/details/google-cloud-ai-platform/kubeflow-pipelines).

Can you share more information about the version of KFP? It is on the AI Platform Pipelines page if you installed kubeflow from there. Or you can also find the version hash at the left bottom corner of KFP UI.

**Comment by wojwoj** [comment]
Hi,

I have followed this tutorial to deploy KubeFlow:
https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines
It leads to market place and KubeFlow was installed from there to new k8 cluster.

The  AI Platform Pipeline view shows version 0.5.1 and left bottom corner in KubeFlow shows 
Build commit: 9c16e12. 
https://github.com/kubeflow/pipelines/commit/9c16e12ba01962668b15fc19efa69b5ba78f618d

I checked the logs of StatisticsGen and there are few records with severity ERROR, for example:

`Expand all | Collapse all{
 insertId: "e6tjxqu24itw6p6fu"  
 labels: {…}  
 logName: "projects/ml-test-284908/logs/stderr"  
 receiveTimestamp: "2020-08-17T11:22:42.023870793Z"  
 resource: {…}  
 severity: "ERROR"  
 textPayload: "time="2020-08-17T11:22:36Z" level=info msg="S3 Save path: /argo/outputs/artifacts/mlpipeline-ui-metadata.tgz, key: artifacts/dot-pipeline-v2-8mgvr/dot-pipeline-v2-8mgvr-865828308/mlpipeline-ui-metadata.tgz"
"  
 timestamp: "2020-08-17T11:22:36.910285508Z"  
}`

However pipeline created from jupyter in which artifacts with static HTML and ML Metadata are displayed has exactly the same log entries :/

**Comment by numerology** [comment]
Hi @wojwoj 

Indeed this is an interesting issue. Do you mind pasting the pipeline yaml spec of dot-pipeline20 and dot-pipeline-v2 here. You can stripping out sensitive info. Thanks!

**Comment by wojwoj** [comment]
Hi,
Both yamls are attached as pipelines.zip. Thanks for help in advance.
[pipelines.zip](https://github.com/tensorflow/tfx/files/5099201/pipelines.zip)

**Comment by numerology** [comment]
/cc @Bobgy

The yaml spec looks find to me. 

The error message in https://github.com/tensorflow/tfx/issues/2346#issuecomment-676181408 seems suggest that somehow connection is broken when trying to read the MLMD.

BTW, do you mind confirming the TFX and KFP version you used in both local and AI notebook environment? Thanks

**Comment by Bobgy** [comment]
```
ml_metadata/metadata_store/metadata_store_service_impl.cc:427] GetContextByTypeAndName failed: mysql_query failed: errno: 2013, error: Lost connection to MySQL server during query
```

Yes, this seems suspicious. @dushyanthsc whether you can take a look at this MLMD -> mysql problem.

**Comment by Bobgy** [comment]
When I compare the two pipelines you uploaded, they don't seem to use the same tfx image version.
Can you confirm library version diffs in both envs?

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by arghyaganguly** [comment]
@reopened to track  #3371

**Comment by jiyongjung0** [comment]
It seems like a different issue to me, although the symptom looks similar. (Also added a comment #3371.)
