### ISSUE TITLE
TFX Command-line Interface with local KubeFlow

### ISSUE THREAD

**Issue by wojwoj** [tensorflow/tfx#2347]
KubeFlow can be installed on any K8 cluster, even on MiniKube. How can I configure tfx command line interface to create pipelines on local k8s cluster. I cannot find any documentation about it.

**Comment by rmothukuru** [comment]
@wojwoj,
Can you please refer [this Tutorial](https://www.kubeflow.org/docs/pipelines/tutorials/build-pipeline/), [this example](https://github.com/kubeflow/pipelines/blob/master/samples/core/tfx-oss/TFX%20Example.ipynb) and [this article](https://cloud.google.com/solutions/machine-learning/architecture-for-mlops-using-tfx-kubeflow-pipelines-and-cloud-build#ml-with-kubeflow-pipelines) and let us know if it helps. Thanks!

**Comment by rmothukuru** [comment]
@wojwoj,
Can you please respond to the above comment? Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
