### ISSUE TITLE
Are we able to override version name?

### ISSUE THREAD

**Issue by snehpandya123** [tensorflow/tfx#2357]
https://github.com/tensorflow/tfx/blob/9b569cd96b38a15a7751db236c80fa2cf66bcb6a/tfx/extensions/google_cloud_ai_platform/pusher/executor.py#L97

**Comment by rmothukuru** [comment]
@snehpandya123,
Can you please elaborate on what exactly you want to do. Thanks!

**Comment by rmothukuru** [comment]
@snehpandya123,
Can you please respond to the above comment. Thanks!

**Comment by snehpandya123** [comment]
Can we specify name of model version instead of v15**** which is default.

**Comment by zhitaoli** [comment]
Can you explain the use case of a different version string? The unspoken requirements we had on this version string are:
- unique
- monotonic increasing
- easy to parse.

Timestamp makes pretty good sense. If you have a different use case, can you explain that info is, and how you plan to pass it through the pipeline DSL?

**Comment by snehpandya123** [comment]
In our case we have a blue/green deployment and have 2 models, Model1(east region) and Model2(central region) and both have 2 versions Version1 and Version2.
At given time Version1 is Green and next week we will have retrained model deployed to Version2 ( Delete and Recreate ) and after deployment Version1 becomes passive.

**Comment by zhitaoli** [comment]
Thanks for the feedback. Adding owner of pusher @chongkong to the discussion, specially since he has a pending TODO on "introducing version".

**Comment by snehpandya123** [comment]
Thank You.

**Comment by chongkong** [comment]
Sorry for the late followup. At the moment we have only automatic versioning scheme (and only with timestamp). If your demand is urgent our recommendation is to create your own custom component that consumes model to publish it with your custom version name.

**Comment by zhongdai** [comment]
If we need to push the model to multiple regions, every time it runs the Pusher, it creates a new timestamp as the `model_version`, which cause the same model has different versions in different regions. Is there any suggestions or that?

**Comment by chongkong** [comment]
We haven't developed alternative [Versioning](https://github.com/tensorflow/tfx/blob/master/tfx/proto/pusher.proto) scheme yet, but we can introduce another one, depending on your purpose and needs. For example we can have external versioning scheme that accepts string version number from another custom components (that you create) to be used. Or versioning based on the pipeline_run which would be consistent across the single run. You can ask for a feature request, but unfortunately this would be low priority for the team 🥲.. The fastest option for you would be implementing your own custom pusher (maybe you can inherit from the original pusher implementation) with the functionality you want.
