### ISSUE TITLE
Add MLMD read client for exploration from interactive environments

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2380]
As a user I want to load pipeline status (and see what components are being executed) from an interactive context.

Even though this is possible at the moment, it requires user to have a deep understanding of MLMD in order to get status of pipeline runs. It would be great to have something like this:

```py
mlmd = MetadataClient(connection_config)
pipeline = mlmd.get_pipeline('pipeline_name')
>>> pipeline.runs = [PipelineRun('pipeline_name', '2020-08-24T23:31:03.286137'), PipelineRun('pipeline_name', '2020-08-21T22:42:25.102927')]

components = pipeline.runs[-1].components
>>> components = [Component('BigQueryExampleGen', 'complete'), Component('StatsGen', 'new')]# we can probs make this a more verbose name or keep as is.
```

We could even add something like InteractiveContext to explore results. 
```py
components[1].show_output('stats') # Loads viz for TFDV

# or

components[0].load_dataset() # Returns a tf.data.Dataset instance for interactive exploration 
```

This would make the task of interactively exploring results from pipeline runs easier for the user. Currently working on something similar to this as part of a remote job scheduler from notebook environments (aka schedule a pipeline in an adhoc job from a notebook). 

Code snippets are just suggestions on API, would love to discuss those as well.

Existing alternatives and why they are not fully great:
- Airflow workshop TFX utils: https://github.com/tensorflow/tfx/tree/master/tfx/examples/airflow_workshop/notebooks - Assumes pipeline has its own MLMD instance separately. Doesn't work if you start using a shared MLMD instance.
- Orchestration Metadata: https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/metadata.py - I started developing something based on this. Could PR new functions to this for usage. But doesn't have easy to use functions to query status as I show above.

**Comment by zhitaoli** [comment]
HI @casassg,

I like the idea you proposed. Something similarly was also mentioned by @hongye-sun once. 

@ruoyu90 Can you help @casassg on this?

Some replies inlined:

> It would be great to have something like this:

WDYT on building this directly in TFX side, possibly in the [Pipeline](https://github.com/tensorflow/tfx/blob/5a4229639343a373fe4da9295b1ee5113912a902/tfx/orchestration/pipeline.py#L57) object? `Run` is a concept we modeled on top of MLMD, instead of provided by latter.

> We could even add something like InteractiveContext to explore results.

Very interesting idea. This might mean the component needs a (weak?) reference to the context/DagRunner and retrieve these information that way. I see this becomes very useful though. @charlesccychen can also chime in.

**Comment by casassg** [comment]
> WDYT on building this directly in TFX side, possibly in the Pipeline object? Run is a concept we modeled on top of MLMD, instead of provided by latter.

Not sure if adding to Pipeline. It may make sense to add separately. Imagine I'm running TFX on Kubeflow/Airflow and i want to load 2 models and compare them from a notebook (do some manual exploration) or re-use some stats to compare them. I would need to manually create the pipeline object which is confusing as I wont be executing it. Also, I like how pipeline is just a model in the TFX world, it doesnt have much business logic in it, so having it in a separate class may be better?

> This might mean the component needs a (weak?) reference to the context/DagRunner

I would probs move the code that loads results into a library and re-use it. Using MLMD artifact types to know what viz to load and how to load it should allow us to avoid having to maintain a reference to DagRunner/context. Ex:
- Client checks output of component execution in Pipeline Run context
- Depending on artifact type, executes one code or another similar to how InteractiveContext does already to load results

**Comment by casassg** [comment]
Quick iteration code proposal in #2415

**Comment by casassg** [comment]
Closing for https://github.com/tensorflow/tfx-addons/issues/12
