### ISSUE TITLE
Make PCollections a first class citizen

### ISSUE THREAD

**Issue by KamalAman** [tensorflow/tfx#240]
In the current TFX architecture, the IO for each component are TF records.

This means, when creating components like StisticsGen, you are reading TF records to only convert them into a PCollection to perform processing on them. 

This seems like a lot of unneeded work, and limitations are introduced early on in the pipeline such as RowToExample in big_query_example_gen. This also impacts scaleability & stream-ability of the pipeline. 

The standard IO for each component should be PCollections, using TF records should be an implementation details for a component.

**Comment by zhitaoli** [comment]
@KamalAman , while making PCollection a first class citizen may help example processing, there are other issues I can see:

1) how does that work for components which are not built on top of Python Beam? Files are can handled by any components/executors written in any language, but we don't have adaptor from PCollection -> go/java/c++/etc;
2) are we going to force everything type of artifact to be PCollection? Several artifact types (model, schema, transform_output) are usually singular objects, and I don't know whether model them as PCollection is making anything clearer;

The fusion idea which @1025KB once looked into can partly help, but I don't think we are pursuing that in the near future.
