### ISSUE TITLE
Handle timestamps in BigQueryExampleGen

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2400]
Current implementation of BigQueryExampleGen lacks support for timestamps. solution could be as easy as just loading and output it to a string based tf.feature based on isodate.

**Comment by 1025KB** [comment]
Could you be more specific for the needs? You can update the query to generate a timestamp column, it will be converted to a feature

**Comment by casassg** [comment]
I believe it will fail if a timestamp column is returned. I may also be wrong here: https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_big_query/example_gen/executor.py#L54

**Comment by casassg** [comment]
This can be resolved, we can just convert using datetime functions on bigquery

**Comment by parnell** [comment]
Timestamp fields are still not supported. This seems like it should be supported as it's a common data type. 

`RuntimeError: BigQuery column type TIMESTAMP is not supported.`

Casting an internet vote to reopen this issue :)
