### ISSUE TITLE
Importing CSVs with empty header name causes ValueError in downstream transform task

### ISSUE THREAD

**Issue by hsahovic** [tensorflow/tfx#2421]
My team is implementing a tfx pipeline, and we came across an unexpected behavior that we suspect is unwanted.

# Behavior description

Using the built-in `CsvExampleGen` with a csv file which contains a column whose header is empty (`""`) works correctly. Downstream components, such as `StatisticsGen`, `SchemaGen`, and `ExampleValidator` also work as expected, producing expected artifacts.

However, the presence of empty keys in the generated examples causes a `ValueError` in the `Transform` component.

The details of the error, `ValueError: '/shape_default' is not a valid node name`, do not explicitly point to the root cause of the problem. Furthermore, `CsvExampleGen` and several other downstream components working correctly made identifying the cause of the issue harder than if an upstream warning or error had been raised.

Despite sounding like a bad idea, empty column names are made common by some data manipulation framework, among which `pandas`: for instance, `df.to_csv(...)`'s default behavior introduces an empty column containing the dataframe's index.

# Reproducing

[This colab](https://colab.research.google.com/drive/1F9DjM-LdrCtvGIgYR2zjdYBTHyLm6BOr?usp=sharing) reproduces the `components_keras` tutorial with an additional cell after downloading the data:

```python
# Altering the CSV with an index column, whose header is empty
# This is typical behavior of pandas dataframes' to_csv method

import pandas as pd
df = pd.read_csv(_data_filepath)
df.to_csv(_data_filepath)
```

[Link: https://colab.research.google.com/drive/1F9DjM-LdrCtvGIgYR2zjdYBTHyLm6BOr?usp=sharing](https://colab.research.google.com/drive/1F9DjM-LdrCtvGIgYR2zjdYBTHyLm6BOr?usp=sharing)

# Resolution

Removing or naming the faulty column fixed our issue.

I think that adding two warnings, one in `CsvExampleGen` and one in `Transform`, or using a default node name in `Transform` are possible solutions. 

# Other

## Example generated example

```python
  feature {
    key: ""
    value {
      int64_list {
        value: 0
      }
    }
  }
```

## Example traceback

```python
INFO:absl:Running driver for Transform
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Running executor for Transform

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tfx/components/transform/executor.py:511: Schema (from tensorflow_transform.tf_metadata.dataset_schema) is deprecated and will be removed in a future version.
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-21-b81ece606df8> in <module>()
      3     schema=schema_gen.outputs['schema'],
      4     module_file=os.path.abspath(_taxi_transform_module_file))
----> 5 context.run(transform)

15 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1737             "Cannot create a tensor proto whose content is larger than 2GB.")
   1738       if not _VALID_OP_NAME_REGEX.match(node_def.name):
-> 1739         raise ValueError("'%s' is not a valid node name" % node_def.name)
   1740       c_op = None
   1741     elif type(node_def).__name__ == "TF_Operation":

ValueError: '/shape_default' is not a valid node name
```

**Comment by timeYspace** [comment]
good solution! Thank you very much.

**Comment by chongkong** [comment]
Sorry for taking a late look at this issue after several months. TFX is now using standardized input/output (TFXIO) for handling data, and I have a gut feeling this is an obsolete issue. If this is still the problem please add a comment and we'll take a deeper look.

**Comment by hsahovic** [comment]
As mentioned above we had a hack to resolve this; our team ended up building a custom ingestion component for our pipeline.
