### ISSUE TITLE
Scale issues when searching for cached executions

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/tfx#2424]
Hi,

During the driver's pre-execution step, when searching for cached executions, [a call is made to MLMD to fetch candidate executions using the pipeline context](https://github.com/tensorflow/tfx/blob/v0.22.1/tfx/orchestration/metadata.py#L785-L786). If I'm understanding this correctly, this will return all historical executions that have been registered with the given pipeline name (pipeline context). For pipelines that are run frequently and over a long period, this set of historical executions will continue to grow over time unless the user changes the name of their pipeline.

We have run into problems before here when the executions used to be searched by type rather than context - at Spotify we have a central MLMD instance with many teams running frequent experiments and production pipelines. I anticipate that we'll run into a similar problem here with searching by pipeline name over time.

So far we've been mitigating this by manually clearing out older executions when needed, but I feel the server should limit the number of results returned based on some TTL for cache expiry. Is this something you would consider? Any other suggestions?

One thing we can do is append a week-of-year or month-of-year to the pipeline name so that the context is refreshed on some interval, but I feel this is also not the most ideal solution.

Thanks!

**Comment by jinnovation** [comment]
This issue is nearly two years old now.

Presumably the issues here are addressed by the [cache context mechanisms](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/portable/cache_utils.py#L72-L105) on `master`.

Is cache context the intended solution moving forward for determining whether a pipeline node is a cache hit/miss? If so, @rcrowe-google et al, shall we close this particular issue out?

**Comment by singhniraj08** [comment]
@andrewsmartin,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.

**Comment by jinnovation** [comment]
Hi @singhniraj08, I work on the team that @andrewsmartin was a part of when he filed this issue. Yes, we remain very much interested in a resolution here and would like to see this happen.

We have not tested with TFX 1.13. Let us know if doing so will facilitate your triaging and we can prioritize accordingly.

**Comment by rcrowe-google** [comment]
@1025KB  @jinnovation @andrewsmartin 
The cache key has not changed in a very long time, so testing with 1.13.0 won't help.  The original comment points to the pipeline name, but in fact the cache context is much richer than that:

```
The cache key is generated by applying SHA-256 hashing function on:
  - Serialized pipeline info.
  - Serialized node_info of the PipelineNode.
  - Serialized executor spec
  - Serialized input artifacts if any.
  - Serialized output artifacts if any. The uri was removed during the process.
  - Serialized parameters if any.
  - Serialized module file content if module file is present in parameters.
```

So changing any of those things will invalidate the cache, which I think is what you're looking for?
