### ISSUE TITLE
Support more stats_options through config.

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/tfx#243]
The current (0.13.0) implementation of the `StatisticsGen` component only uses the default stats_options: `stats_options = tensorflow_data_validation.statistics.stats_options.StatsOptions()`
There is a TODO statement saying that this should be configurable.
There should be a default to the current behavior.

**Comment by 1025KB** [comment]
Keep this as a feature request

**Comment by gaikwadrahul8** [comment]
@martin-laurent 

Apologies for the delay and we have updated our official documentation with respect to `tfdv.StatsOptions()` [here](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/StatsOptions) so could you please have a look once and let us know you're looking the exact thing or different ?

Thank you!
