### ISSUE TITLE
TFX Pipeline with DataflowRunner runs Training on local machine

### ISSUE THREAD

**Issue by kyledef** [tensorflow/tfx#2470]
We modified the Chicago example and added arguments to BeamRunner to run the example in Dataflow.

```
'beam_pipeline_args': [
            f'--project={project_name}',
            f'--region={region}',
            f'--job_name=tfx-{pipeline_name}-job',
            f'--temp_location={temp_location}',
            f'--setup_file={path_to_setup_file}',
            f'--subnetwork={subnet}',
            f'--runner=DataflowRunner'
        ]
```

However, we noticed each components run a new job 
![image](https://user-images.githubusercontent.com/2001345/92958460-4b7c3a80-f438-11ea-8f5d-93b1eaf8aae4.png)

And the training runs on the machine where the job was initiated from.
![image](https://user-images.githubusercontent.com/2001345/92958434-3b645b00-f438-11ea-99e0-4ada9a6d02c9.png)

This feels like a bug to me, as if I launch the job to Dataflow, I do not expect it to still be performing operations on my local machine.

Is there a way to:
1. Run all the components of the TFX operation in 1 job? I'm assuming we can create it as a typical beam pipeline, but the abstraction of tfx is one of the selling points of its use.
2. Is there an option to force the training to occur remotely
3. Can we specify worker with GPU's for the training in Dataflow?

**Comment by zhitaoli** [comment]
> Run all the components of the TFX operation in 1 job? I'm assuming we can create it as a typical beam pipeline, but the abstraction of tfx is one of the selling points of its use.

@charlesccychen had looked at this "component fusion" idea in the past, but some non beam based components would not fit.

> Is there an option to force the training to occur remotely

Can you elaborate on definition of "remotely" a bit more?

> Can we specify worker with GPU's for the training in Dataflow?

AFAIK GPU is not officially supported in Dataflow yet, so I'm not sure how can TFX solve this from our side. Mind to elaborate?

**Comment by gowthamkpr** [comment]
@kyledef Can you please respond to the above [question](https://github.com/tensorflow/tfx/issues/2470#issuecomment-691285048). Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please respond to the above question and reopen the issue. Thanks!
