### ISSUE TITLE
Graciously delete/cleanup older TFX runs in MySQL

### ISSUE THREAD

**Issue by nadgirsanket** [tensorflow/tfx#2484]
I'm using MySQL db for storing the artifacts generated via TFX runs.

Its been a while TFX has been in production. Since many schedules of the pipeline have run, MLMD database is getting filled up. Due to large tables, the performance of the database has decreased as well.

Is there a way to programmatically and graciously delete older runs to free up storage and improve DB performance? For example, delete all the TFX runs (all components related to a specific run) before XYZ date or RUN_IDs.

**Comment by charlesccychen** [comment]
CC: @hughmiao @ruoyu90 @1025KB @zhitaoli 

It sounds like the request is to garbage-collect metadata from the MLMD database over time.  Could we understand your use case a little better?  First, is there a reason other than database performance that you would look to delete old metadata?  If kept, this metadata could be useful for determining lineage information of your models and other artifacts over time.  Second, do you already have a mechanism removing the artifacts pointed to by records in your database?  That is, for old models or examples, do you already delete the data over time?  Garbage-collection in terms of removing this stale data is currently planned, but the current plan for garbage collection is to remove this data but keep the metadata records in MLMD for long-term provenance tracking.  It would be great to understand your use case in this context.

**Comment by sanatmpa1** [comment]
@nadgirsanket,

Can you take a look at the above comment by @charlesccychen and provide your response? Thanks!

**Comment by sanatmpa1** [comment]
@nadgirsanket,

Closing this issue due to lack of recent activity, Please feel free to reopen the issue with more details if the problem still persists. Thanks!
