### ISSUE TITLE
No Visualization for SchemaGen and ExampleValidator

### ISSUE THREAD

**Issue by snehpandya123** [tensorflow/tfx#2504]
Changes made to the Input function

examples = external_input(_data_root_param)
  inputpath = example_gen_pb2.Input(splits=[example_gen_pb2.Input.Split(name='train', pattern='train/*'),example_gen_pb2.Input.Split(name='eval', pattern='test/*')])
  
  example_gen = CsvExampleGen(input=examples)

  statistics_gen = StatisticsGen(examples=example_gen.outputs['examples'])

  Schema_gen = SchemaGen(
      statistics=statistics_gen.outputs['statistics'])

 example_validator = ExampleValidator(
      statistics=statistics_gen.outputs['statistics'],
      schema=schema_gen.outputs['schema'])

![image](https://user-images.githubusercontent.com/5006534/93480510-84e6f700-f8cb-11ea-89b8-64ba4765d161.png)

ExampleValidator

![image](https://user-images.githubusercontent.com/5006534/93480718-bf509400-f8cb-11ea-8820-932b295b26b6.png)

I am able to see the anomalies are avaialble in /train and /eval folder

Versions:
tensorflow : 2.3.0
tfx: 0.23.0
GCP Kubeflow :1.0.0

**Comment by gowthamkpr** [comment]
@snehpandya123 As the error message suggests, the specified path is not found. Can you try reproducing this is google colab and see if the issue is reproducible? Thanks!

**Comment by snehpandya123** [comment]
for anomalies/3990/ I have train & eval folder instead of anomalies.pbtxt

**Comment by snehpandya123** [comment]
Also I update TFX version to 0.23.0  and reran the code lab
https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components.ipynb#scrollTo=TDyAAozQcrk3
and got same error.

**Comment by 1025KB** [comment]
it‘s the same issue as [this](https://github.com/tensorflow/tfx/issues/2582)

0.24 is released yesterday, could you try 0.24?

**Comment by 1025KB** [comment]
[Keras Colab](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras) should work now
