### ISSUE TITLE
Prerequisites to taxi_pipeline_kubeflow_local.py

### ISSUE THREAD

**Issue by anineharto** [tensorflow/tfx#2512]
In the python script for running a pipeline on Kubeflow on-prem we have:

```
# This sample assumes a persistent volume (PV) is mounted as follows. To use
# InfraValidator with PVC, its access mode should be ReadWriteMany.
_persistent_volume_claim = 'my-pvc'
_persistent_volume = 'my-pv'
_persistent_volume_mount = '/mnt'

# All input and output data are kept in the PV.
_input_base = os.path.join(_persistent_volume_mount, 'tfx')
_output_base = os.path.join(_persistent_volume_mount, 'pipelines')
_tfx_root = os.path.join(_output_base, 'tfx')
_pipeline_root = os.path.join(_tfx_root, _pipeline_name)

# Training data is assumed to be in ./data/simple/*.csv in the PV.
_data_root = os.path.join(_input_base, 'data', 'simple')
```
Is it assumed that one has pre-created a PV with the corresponding name and mounting, or is the python scipt itself supposed to do this? And if that's the case, how do I give it access to my local data that I want the pipeline to train on? Because, as it stand now, this is not working.

I've managed to set up a PV where I've stored the data I need, but when running the pipeline it doesn't seem to get a hold of it. The documentation for running a pipeline on Kubeflow on-prem is unfortunately non-existent, so I have no idea how one is supposed to do this.

**Comment by anineharto** [comment]
I managed to solve this myself, so this issue can be closed.

**Comment by arghyaganguly** [comment]
Closing this based on above comment.
