### ISSUE TITLE
Support embeddings input in Trainer

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2517]
As a user I want to generate some embeddings in a separate components (and even a separate pipeline) and use them in Trainer. Currently I have no way to get those dependencies setup in Trainer.

**Comment by 1025KB** [comment]
if the side input is available before the pipeline run, you can consider using the [custom_config](https://github.com/tensorflow/tfx/blob/master/tfx/components/trainer/component.py#L121) to pass the information to Trainer

but if it's from a separate component in the same pipeline, you need to custom Trainer to support the new artifact Channel (e.g., like example channel) to make sure Trainer executed after that component (dependency).

**Comment by casassg** [comment]
Opening this discussion internally so I can provide more insights, but a bit more insights:

We hope to train the embeddings into either the same pipeline (and use cache to reuse embeddings if dataset needed has not changed) or across pipelines (cross pipeline resolver node). Using TF.Hub may work on sync pipelines as you just need the latest embeddings, but those dont get annotated on MLMD and therefore may lead to difficulty tracing model lineage as embedding is not an artifact in the metadata DB. 

The embedding requirement being more explicit is actually used as an example in the UDSL RFC for async pipelines: https://github.com/tensorflow/community/blob/master/rfcs/20200601-tfx-udsl-semantics.md#sub-pipeline but Trainer currently does not accept this, at least not the OSS version of it. 

Most of times, we have embeddings that are retrained regularly and reused across several models, leading in a reduce of compute resources needed to train some models.

**Comment by davidzats-eng** [comment]
Would storing / accessing embeddings through a savedmodel be sufficient? I think that would be a straightforward extension.

**Comment by casassg** [comment]
I think that could be beneficial indeed. Most embeddings just are parts of models. We sometimes store them into csv/tsv to decouple from model, but there's nothing stopping us from storing it as a side artifact of the model and load it that way as well.

**Comment by casassg** [comment]
Wondering also wether Model or maybe ModelRun which has artifacts generated by the model `output non-model related output` may be the best artifact type. Guessing Model and then loading it to the new model, but not sure. 

One use case internally tried to use TF.Transform to do the data transformation (entityId -> embedding) as the model was using estimator API but was unsucessful to do so. Would this be recommended?
