### ISSUE TITLE
Error while running StatisticsGen

### ISSUE THREAD

**Issue by shudhatma123** [tensorflow/tfx#2534]
while running statistics_gen = StatisticsGen(
    examples=example_gen.outputs['examples'])
context.run(statistics_gen)

following error was there

INFO:absl:Running driver for StatisticsGen
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Running executor for StatisticsGen
INFO:absl:Using 1 process(es) for Beam pipeline execution.
INFO:absl:Generating statistics for split train
---------------------------------------------------------------------------
TypeCheckError                            Traceback (most recent call last)
<ipython-input-12-9498d90b7869> in <module>()
      1 statistics_gen = StatisticsGen(
      2     examples=example_gen.outputs['examples'])
----> 3 context.run(statistics_gen)

35 frames
/usr/local/lib/python3.6/dist-packages/apache_beam/transforms/ptransform.py in type_check_inputs(self, pvalueish)
    871                   actual_type=bindings[arg],
    872                   arg=arg,
--> 873                   debug_str=type_hints.debug_str()))
    874 
    875   def _process_argspec_fn(self):

TypeCheckError: Type hint violation for 'ToTopKTuples': requires FrozenSet[FeaturePath] but got Set[Any] for bytes_features
Full type hint:
IOTypeHints[inputs=((Tuple[Union[NoneType, bytes, str], RecordBatch], FrozenSet[FeaturePath], FrozenSet[FeaturePath], Union[NoneType, str]), {}), outputs=((Tuple[Tuple[Union[NoneType, bytes, str], Tuple[Union[bytes, str], ...], Any], Union[Tuple[int, Union[float, int]], int]],), {})]
strip_iterable()

based on:
  IOTypeHints[inputs=((Tuple[Union[NoneType, bytes, str], RecordBatch], FrozenSet[FeaturePath], FrozenSet[FeaturePath], Union[NoneType, str]), {}), outputs=((Iterable[Tuple[Tuple[Union[NoneType, bytes, str], Tuple[Union[bytes, str], ...], Any], Union[Tuple[int, Union[float, int]], int]]],), {})]
  from_callable(_to_topk_tuples)
    signature: (sliced_record_batch:Tuple[Union[str, bytes, NoneType], pyarrow.lib.RecordBatch], bytes_features:FrozenSet[tensorflow_data_validation.types.FeaturePath], categorical_features:FrozenSet[tensorflow_data_validation.types.FeaturePath], weight_feature:Union[str, NoneType]) -> Iterable[Tuple[Tuple[Union[str, bytes, NoneType], Tuple[Union[bytes, str], ...], Any], Union[int, Tuple[int, Union[int, float]]]]]
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/statistics/generators/top_k_uniques_stats_generator.py", line 202

How can we solve this issue?

**Comment by MarkoDobrinic** [comment]
I've encountered the same error and downgraded TFX to 0.21.0 - seems to be working so far.

**Comment by gowthamkpr** [comment]
@shudhatma123 Can you please share the reproducible code for us to reproduce the issue. Also please share what version of tfx are you using? Thanks!

**Comment by zcikojevic** [comment]
I've encountered this issue while going through official tutorial on Colab: https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb. Same thing happens for tf estimator notebook tutorial.

**Comment by shudhatma123** [comment]
> I've encountered the same error and downgraded TFX to 0.21.0 - seems to be working so far.

Thanks Marko Dobrinic downgrading TFX had worked for me.

**Comment by shudhatma123** [comment]
> @shudhatma123 Can you please share the reproducible code for us to reproduce the issue. Also please share what version of tfx are you using? Thanks!

@gowthamkpr I just Downgraded TFX to version 0.21.0 and the whole code then worked fine for me
