### ISSUE TITLE
with protobuf 3.9.2, `import tensorflow_data_validation as tfdv` fails

### ISSUE THREAD

**Issue by emily-potyraj** [tensorflow/tfx#2547]
Currently trying to execute the TensorFlow Data Validation tutorial notebook (from source on my own Jupyter server)
https://github.com/tensorflow/tfx/blob/master/docs/tutorials/data_validation/tfdv_basic.ipynb

**Error:** 
Execute `import tensorflow_data_validation as tfdv`

```
...  
/opt/conda/lib/python3.7/site-packages/apache_beam/portability/api/endpoints_pb2.py in <module>
     19   syntax='proto3',
     20   serialized_options=b'\n!org.apache.beam.model.pipeline.v1B\tEndpointsZ\013pipeline_v1',
---> 21   create_key=_descriptor._internal_create_key,
     22   serialized_pb=b'\n\x0f\x65ndpoints.proto\x12!org.apache.beam.model.pipeline.v1\"r\n\x14\x41piServiceDescriptor\x12\x0b\n\x03url\x18\x01 \x01(\t\x12M\n\x0e\x61uthentication\x18\x02 \x01(\x0b\x32\x35.org.apache.beam.model.pipeline.v1.AuthenticationSpec\"2\n\x12\x41uthenticationSpec\x12\x0b\n\x03urn\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x42;\n!org.apache.beam.model.pipeline.v1B\tEndpointsZ\x0bpipeline_v1b\x06proto3'
     23 )

AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**End user fix:** 
1. `!pip install --upgrade protobuf` 
```
...
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.9.2
    Uninstalling protobuf-3.9.2:
      Successfully uninstalled protobuf-3.9.2
Successfully installed protobuf-3.13.0
```
2. restart the kernel/runtime

Now `import tensorflow_data_validation as tfdv` succeeds with no errors.

**Comment by gowthamkpr** [comment]
Yes. Please use protobuf version 3.12.x or greater, to fix this issue. Thanks!

**Comment by em-watkins** [comment]
Ok great, thanks. Where can I find that requirement documented? Sorry if I missed it somewhere... 
(or could tensorflow_data_validation check for that dependency?)

**Comment by gowthamkpr** [comment]
@em-watkins You can take a look at the versions [here](https://github.com/tensorflow/tfx/blob/r0.23.0/tfx/dependencies.py) as this is a part of tfx.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by brills** [comment]
Newer versions of TFX libraries will depend on a much newer protobuf library which should make this problem go away.
