### ISSUE TITLE
Support for customizable MLMD contexts setting 

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2553]
Related to discussion in #2516 

It would be good to have a way to add extra contexts to pipelines/component runs. Some ideas to extend the current MLMD setup:

1. Add user/group namespace Context to Pipeline (where id is user or group of users id)
2. Add experiment namespace for Pipeline (where we want to easily query several pipelines and artifacts around together)
3. Add stage namespace for pipelines. Sometimes you may want to avoid your runs to interfere with your production context.

Ideally 1. would allow us to go into a place where we can easily have a centralized MLMD instance and reduce potential name conflicts (or issues). Those can also be used to enforce write priviledges from a central managed MLMD service

**Comment by redramen** [comment]
As in have these contexts automatically created and associate executions with them? 1 should be possible to do manually atm. 2 & 3 should be possible to do as well I believe just with some client side filtering needed.

**Comment by casassg** [comment]
I think the idea is to make TFX more flexible allowing Platform owners to easily extend the default contexts associated with a pipeline run. Ideally this is added as part of the TFX ontology in MLMD.
