### ISSUE TITLE
ModuleNotFoundError in module file for tfx.components.Transform when running Kubeflow Pipelines

### ISSUE THREAD

**Issue by anineharto** [tensorflow/tfx#2556]
I've created my own code using both the TFX library and customized code. I've also created a pipeline on my on-prem minikube cluster resulting in a `tar.gz` file that I upload to Kubeflow Pipelines. I have created a Persistent Volume where I've stored my dataset, preprocessing module file: `module_file_transform.py` and train module file: `module_file_train.py`. My module files make use of other local modules (e.g config classes such as `tf_template.utils.configs.DataConfig`) which is where I run into trouble. The following stack-trace indicates that it can't locate my local code inside the module files:

```
INFO:absl:Running driver for Transform
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:Adding KFP pod name tf-template-pipeline-2nplz-2740531700 to execution
INFO:absl:Running executor for Transform
INFO:absl:Attempting to infer TFX Python dependency for beam
INFO:absl:Copying all content from install dir /tfx-src/tfx to temp dir /tmp/tmphwamj2jn/build/tfx
INFO:absl:Generating a temp setup file at /tmp/tmphwamj2jn/build/tfx/setup.py
INFO:absl:Creating temporary sdist package, logs available at /tmp/tmphwamj2jn/build/tfx/setup.log
INFO:absl:Added --extra_package=/tmp/tmphwamj2jn/build/tfx/dist/tfx_ephemeral-0.22.0.tar.gz to beam args
WARNING:tensorflow:From /tfx-src/tfx/components/transform/executor.py:511: Schema (from tensorflow_transform.tf_metadata.dataset_schema) is deprecated and will be removed in a future version.
Instructions for updating:
Schema is a deprecated, use schema_utils.schema_from_feature_spec to create a `Schema`
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/tfx-src/tfx/orchestration/launcher/base_component_launcher.py", line 205, in launch
    execution_decision.exec_properties)
  File "/tfx-src/tfx/orchestration/launcher/in_process_component_launcher.py", line 67, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/tfx-src/tfx/components/transform/executor.py", line 391, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/tfx-src/tfx/components/transform/executor.py", line 849, in Transform
    preprocessing_fn = self._GetPreprocessingFn(inputs, outputs)
  File "/tfx-src/tfx/components/transform/executor.py", line 785, in _GetPreprocessingFn
    'preprocessing_fn')
  File "/tfx-src/tfx/utils/import_utils.py", line 67, in import_func_from_source
    loader.exec_module(user_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/module_files/module_file_transform.py", line 3, in <module>
    from tf_template.utils.configs import DataConfig
ModuleNotFoundError: No module named 'tf_template'
```
where `tf_template` is the name of my local module. What is the reason for this, and how can I fix it?

* Do I have to use the `kfp` library to containerize my local python classes in order for this to work (even though these are only used indirectly in my module file)? If so, how do I do this? 
* Is a better option to add my local repo to the image used by my Persistent Volume?

**Comment by TobiasGoerke** [comment]
I am also interested in the best practices here and in how this problem is intended to be solved.
Sure, I can add files to a mounted PVC. This, however, does add a lot of overhead to creating a pipeline, since I do not only have to upload a yaml file but also provision and populate a PVC (with files that are a permanent part of the pipeline). 
Also, I'd have to use RWX so multiple pods can start simultaneously. 
This does not seem like a user-friendly way to deploy pipelines at all.
Alternatives, like creating a custom image, do not seem viable as well.

**Comment by ConverJens** [comment]
@TobiasGoerke @anineharto 
I've set up KubeFlow on-premise and we are running TFX pipelkines. The only way to achieve this is as @TobiasGoerke point out:

- host files on mounted volume or Minio/GCS/S3
- build custom images

We've opted with the latter. Just base your image of whichever TFX version you want, copy in your files and drop a 
ENV PYTHONPATH="/where-I-put-my-files:${PYTHONPATH}"
and you're done. If you also build your image on git push, then you have a mapping between commit and pipeline runtime image.

The complete lack of versioning is why mounted vols where a no go for us.

**Comment by sanatmpa1** [comment]
@anineharto,

Can you take a look at the above comment by @ConverJens and let us know if it helps in resolving your question? Thanks!

**Comment by pindinagesh** [comment]
Hi @anineharto 

Closing this issue based on @ConverJens's comment and lack of inactivity, Can you take a look at the workaround proposed in this [issue](https://github.com/kubeflow/pipelines/issues/4592) and see if it helps in resolving your issue? Also you can refer [doc](https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines). Please feel free to reopen if this still exist. Thanks
