### ISSUE TITLE
Request for OutputValuePlaceholder

### ISSUE THREAD

**Issue by FKSI** [tensorflow/tfx#2566]
## Use-case

**Step 2** needs a simple String (and UUID for instance) from **Step 1**.  

## Currently 

The only way to achieve such use-case is to write/push from **Step 1** to Google Storage a file with the UUID and Pull/Read from **Step 2**.

## Suggested solution

![image](https://user-images.githubusercontent.com/2216173/94275202-f582b900-ff46-11ea-95fd-5be15aa5724a.png)

Similar too [InputValuePlaceholder](https://www.tensorflow.org/tfx/api_docs/python/tfx/dsl/component/experimental/placeholders/InputValuePlaceholder) let's have a **OutputValuePlaceholder**

**Comment by singhniraj08** [comment]
@FKSI,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.

**Comment by Ark-kun** [comment]
This is a non-issue in KFPv1 which has a single concept of `Data` which can be produced by outputs and consumed by inputs (as value or as file). All values are output as files. Any constant value or output can be passed to any input.

In KFPv1 you should be able to pass any Output to any input regardless of whether `inputPath` or `inputValue` is used.

**Comment by FKSI** [comment]
Hi there, 
I'm no longer working with TFX so I can't answer :( so I guess we can close this one ;)
