### ISSUE TITLE
ExampleValidator fails in Keras Component Tutorial

### ISSUE THREAD

**Issue by LRSutton** [tensorflow/tfx#2582]
For the tutorial hosted here: https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb#scrollTo=znMoJj60ybZx

Running cell by cell, the ExampleValidator cell fails

`context.show(example_validator.outputs['anomalies'])`

with the following error:

```
Artifact at /tmp/tfx-interactive-2020-09-29T16_59_55.728176-j4sbvykm/ExampleValidator/anomalies/4

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-15-b340558eb54b> in <module>()
----> 1 context.show(example_validator.outputs['anomalies'])

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in _preread_check(self)
     77                                            "File isn't open for reading")
     78       self._read_buf = _pywrap_file_io.BufferedInputStream(
---> 79           self.__name, 1024 * 512)
     80 
     81   def _prewrite_check(self):

NotFoundError: /tmp/tfx-interactive-2020-09-29T16_59_55.728176-j4sbvykm/ExampleValidator/anomalies/4/anomalies.pbtxt; No such file or directory
```

Note:  To get this point in the tutorial, due to other versioning errors, the Install TFX cell was changed to:

`!pip install tensorflow==2.3.0 tfx==0.23.1`

(Runtime was restarted)

---

This behavior seems to be an ExampleValidator issue as opposed to a documentation error as other environments where I've used similar code fails with the same error.

**Comment by 1025KB** [comment]
could you try: 

artifact = example_validator.outputs['anomalies'].get()[0]
print(artifact.split_names, artifact.uri)

we added split in 0.23 version, but Colab is not updated in 0.23
Colab is fixed in 0.24 [here](https://github.com/tensorflow/tfx/blob/b01482442891a49a1487c67047e85ab971717b75/tfx/orchestration/experimental/interactive/standard_visualizations.py#L55)

**Comment by LRSutton** [comment]
Here are the results:

I excluded_splits=['eval'] on SchemaGen and StatisticsGen prior to the EV.

The ExampleValidator:

```
example_validator = ExampleValidator(
    statistics=statistics_gen.outputs['statistics'],
    schema=schema_gen.outputs['schema']
)
context.run(example_validator)
```

artifact = example_validator.outputs['anomalies'].get()[0]
print(artifact.split_names, artifact.uri)

`context.show(example_validator.outputs['output'])
`
---
Output:

["train"] /home/jovyan/pipeline/ExampleValidator/anomalies/17
**Artifact at /home/jovyan/pipeline/ExampleValidator/anomalies/17**

> NotFoundError: /home/jovyan/pipeline/ExampleValidator/anomalies/17/anomalies.pbtxt; No such file or directory

**Comment by LRSutton** [comment]
I then ran the same code against tfx 0.24 and it passed:

["train"] /home/jovyan/pipeline/ExampleValidator/anomalies/22
Artifact at /home/jovyan/pipeline/ExampleValidator/anomalies/22

'train' split:

No anomalies found.

---

Thank you for the insight to move to 0.24, @1025KB
