### ISSUE TITLE
Not able to change @component function signature after component execution

### ISSUE THREAD

**Issue by calvinleungyk** [tensorflow/tfx#2583]
Hi TFX team, we encountered "ValueError: missing or modified key in exec_properties comparing with existing execution type with the same type name."

If I am not mistaken, the reason is the name of the class is being used node_id in BaseNode, and once TFX registers execution of the component in MLMD, the class name and the exec_properties are set in stone and cannot be changed, unless we name the class differently, and a new component will then be registered in MLMD.

This is a bit counterintuitive since users go through iterations before they have fully tested and settle on a version of the component. There should be a way/ flag to indicate if the component properties should be updated or not (default to False), or offer a method to update the component properties.

**Comment by casassg** [comment]
This may be related to https://github.com/tensorflow/tfx/issues/2506. If we remove exec properties it breaks. Which is not expected. Would be nice to issue a fix for both of them.

**Comment by charlesccychen** [comment]
Yes, that is the case.  We hope to remove this limitation soon.

**Comment by gowthamkpr** [comment]
@calvinleungyk As mentioned in this [comment](https://github.com/tensorflow/tfx/issues/2506#issuecomment-756993246), this is fixed and should be working now. Please test it and let us know. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please reopen it if you have any updates. Thanks!!
