### ISSUE TITLE
Access TFX logger in module file

### ISSUE THREAD

**Issue by ianhellstrom** [tensorflow/tfx#26]
Is it possible to (re-)use the [TFX logger from the pipeline](https://github.com/tensorflow/tfx/blob/master/examples/chicago_taxi_pipeline/taxi_pipeline_simple.py#L77) in the [module file](https://github.com/tensorflow/tfx/blob/master/examples/chicago_taxi_pipeline/taxi_utils.py)?

I have adapted the taxi example for my own use case but I am using `print` to get additional entries for debugging. It works, but it's not as nice as there is no timestamp and log level. It would be great if we could reuse the TFX logger. If it's not possible, what is the preferred/recommended way of logging in the `@PipelineDecorator` function or module file: Python's `logging` module or `tf.logging`?

**Comment by ruoyu90** [comment]
If you want to log in the [module file](https://github.com/tensorflow/tfx/blob/master/examples/chicago_taxi_pipeline/taxi_utils.py), `tf.logging` should be a good choice.
If you want to log in the `@PipelineDecorator`, currently [TFX logger](https://github.com/tensorflow/tfx/blob/master/tfx/utils/logging_utils.py#L97) is not available to use there. You can use `tf.logging` or Python's `logging` module.

**Comment by ianhellstrom** [comment]
Yes, that works fine. Thanks!
