### ISSUE TITLE
TFX Advanced Cache

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2619]
I was wondering if there was any insights into the rebump cache for TFX story. We have been hearing about it for a while but not sure whats the state. is this coming in the IR based model?
It would be nice to have more per component control for cache similar to how Kubeflow works :D

**Comment by kennethyang404** [comment]
Hi Gerard,

I think this is definitely an important use case.
However, we are not sure if per-component cache is the best interface to expose this functionality. There are some ideas about pipeline partial run, which solves similar use case. No explicit timeline for it though. Sorry.

**Comment by casassg** [comment]
That makes sense! Thanks for the clarity. Should I leave this open to track progress (whenever that happens?)

**Comment by kennethyang404** [comment]
We can keep it open. Thanks!

**Comment by singhniraj08** [comment]
@casassg,

Currently TFX caching is enabled, If caching is enabled, the pipeline attempts to match the signature of each component, the component and set of inputs, to one of this pipeline's previous component executions. If there is a match, the pipeline uses the component outputs from the previous run. If there is not a match, the component is executed. 

Ref: [TFX Caching](https://www.tensorflow.org/tfx/guide/build_tfx_pipeline#caching). Thanks.
