### ISSUE TITLE
Loading training and validation data pairs into ExampleGen component for building Siamese network with TFX 

### ISSUE THREAD

**Issue by Jaydeemourg** [tensorflow/tfx#2635]
Hello, 

I have a Siamese deep learning model which I already developed as a standalone code. As i would like to deploy the model using Kubeflow, I now want to implement the siamese network with TFX components. 

Training data: 
I've got two csv data (named good samples and bad samples) with which i built training pairs for the siamese network. The build pair function in the standalone code can be found below.
 
My questions are:
As the Siamese network takes pairs of training data for building a model as shown in my code below, I wrote a function (build pair) to generate the training and validation pairs. Do i have to load the preprocessed training and validation pairs into the ExampleGen component? if yes, how can these pairs be loaded into the ExampleGen component of TFX? I know that ExampleGen component reads the data from a specified file path, Do I have to save the preprocessed training pairs on disk before loading them into TFX? 

training in standalone code:
`model.fit([tr_x[:,0], tr_x[:,1]], tr_y, batch_size=32, epochs=300, validation_data=([val_x[:,0], val_x[:,1]], santa.val_y), verbose=1, callbacks=[earlyStopping])` 

 Please note:  training pairs = `[tr_x[:,0], tr_x[:,1]]`, validation pairs = `[val_x[:,0], val_x[:,1]]`
`tr_x[:,0]` and `tr_x[:,1]` has shape (50000, 30), `tr_y` has shape (50000,) 
`val_x[:,0] `and `val_x[:,1]` has shape (15000, 30), `tr_y` has shape (15000,).
`[tr_x[:,0], tr_x[:,1]]` has shape (2, 50000, 30) and `[val_x[:,0], val_x[:,1]]` has shape (2, 15000, 30)

function to build pairs in standalone code
```
def _build_pairs(good, bad, pairs, reference=None):
    global ref
    fpairs = []
    lab = []
    good_samples = len(good)-2    #Element per class -1
    bad_samples = len(bad)-2
    pairs_to_gen = pairs
    if reference is None:
        for i in range(pairs_to_gen):
            r = randint(0, good_samples)
            z1, z2 = good.loc[randint(0, good_samples)], good.loc[randint(0, good_samples)]     #Good Pair (data, reference) l=0
            fpairs += [[z1, z2]]
            z1, z2 = bad.loc[randint(0, bad_samples)], good.loc[randint(0, good_samples)]         #Bad Pair (data, reference) l=1
            fpairs += [[z1, z2]]
            lab += [0, 1]
    else:
        ref = reference
        for i in range(pairs_to_gen):
            z1, z2 = good.loc[randint(0, good_samples)], reference     #Good Pair (data, reference) l=0
            fpairs += [[z1, z2]]
            z1, z2 = bad.loc[randint(0, bad_samples)], reference        #Bad Pair (data, reference) l=1
            fpairs += [[z1, z2]]
            lab += [0, 1] # ref good = 0,1 ref bad = 1,0
    return np.array(fpairs), np.array(lab)
```

**Comment by XintianS** [comment]
Hey, I am having a similar problem. I wonder if this issue is solved as it is close, and how did you solve it?
