### ISSUE TITLE
Value Error when executing SchemaGen. ValueError: Expected exactly one artifact with split 'train', but found matching artifacts [].

### ISSUE THREAD

**Issue by Jaydeemourg** [tensorflow/tfx#2638]
TensorFlow version: 2.2.0. TFX version: 0.22.0. Linux

 "ValueError: Expected exactly one artifact with split 'train', but found matching artifacts []" . How can i resolve this error? 

I want to implement TFX for a Siamese deep learning model which I already developed as a standalone code. the Siamese network takes pairs of training data for building a model. I created 2 training and 2 evaluation data pairs (train_pair1, train_pair2, eval_pair1, eval_pair2). These pairs were provided as input_config for ExampleGen component and it worked. The examplegen instance can be found below. The statisticsgen component also worked but on getting to the schemaGen, i created its instance as shown below but i received a ValueError.

train_pair1 has shape (50000, 31), train_pair2 has shape (50000, 31)
eval_pair1 has shape (15000, 31), eval_pair2 has shape (15000, 31)

Examplegen
```
input = example_gen_pb2.Input(splits=[
 example_gen_pb2.Input.Split(name='train_pair1', pattern='train_pair1/*'),
 example_gen_pb2.Input.Split(name='train_pair2', pattern='train_pair2/*'),
 example_gen_pb2.Input.Split(name='eval_pair1', pattern='eval_pair1/*'),
example_gen_pb2.Input.Split(name='eval_pair2', pattern='eval_pair2/*'),
])
```
```
examples = external_input(data_dir)
example_gen = CsvExampleGen(input=examples, input_config=input)
```

Statisticgen

```
statistics_gen = StatisticsGen(
    examples=example_gen.outputs['examples'])
context.run(statistics_gen)
```

Schemagen

```
schema_gen = SchemaGen(
    statistics=statistics_gen.outputs['statistics'],
    infer_feature_shape=True)
context.run(schema_gen) 
```

# ValueError

```
ValueError                                Traceback (most recent call last)
<ipython-input-35-3e5a14d670fd> in <module>
----> 1 context.run(schema_gen)

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     64       # __IPYTHON__ variable is set by IPython, see
     65       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 66       return fn(*args, **kwargs)
     67     else:
     68       absl.logging.warning(

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    166         component, pipeline_info, driver_args, metadata_connection,
    167         beam_pipeline_args, additional_pipeline_args)
--> 168     execution_id = launcher.launch().execution_id
    169 
    170     return execution_result.ExecutionResult(

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    203                          execution_decision.input_dict,
    204                          execution_decision.output_dict,
--> 205                          execution_decision.exec_properties)
    206 
    207     absl.logging.info('Running publisher for %s',

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/in_process_component_launcher.py in _run_executor(self, execution_id, input_dict, output_dict, exec_properties)
     65         executor_context)  # type: ignore
     66 
---> 67     executor.Do(input_dict, output_dict, exec_properties)

/usr/local/lib/python3.6/dist-packages/tfx/components/schema_gen/executor.py in Do(self, input_dict, output_dict, exec_properties)
     67     # constants.py.
     68     train_stats_uri = io_utils.get_only_uri_in_dir(
---> 69         artifact_utils.get_split_uri(input_dict[STATISTICS_KEY], 'train'))
     70     output_uri = os.path.join(
     71         artifact_utils.get_single_uri(output_dict[SCHEMA_KEY]),

/usr/local/lib/python3.6/dist-packages/tfx/types/artifact_utils.py in get_split_uri(artifact_list, split)
    106     raise ValueError(
    107         ('Expected exactly one artifact with split %r, but found matching '
--> 108          'artifacts %s.') % (split, matching_artifacts))
    109   return os.path.join(matching_artifacts[0].uri, split)
    110 

ValueError: Expected exactly one artifact with split 'train', but found matching artifacts [].
```

**Comment by rmothukuru** [comment]
@Jaydeemourg,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment]
@Jaydeemourg,
Can you please respond to the above comment. Thanks!

**Comment by Jaydeemourg** [comment]
Sorry for my late response. 
As i want to train a siamese network which requires 2 pairs of input data, i have created train_1 and train_2 for the training and eval_1 and eval_2 for validation. The train and eval data can be generated as follows for your debugging:

```
train_1= np.random.random((50000,31))
train_2= np.random.random((50000,31))
eval_1= np.random.random((15000,31))
eval_2= np.random.random((15000,31))
```

`tfx_root = os.getcwd() `
`data_dir = os.path.join( 'data'`) # Data directory
`pipeline_root = os.path.join(_tfx_root, 'pipeline_root') `# pipeline component directory
`data_root_train_1= os.path.join(data_dir, 'train_1')` # train_1 data directory
`data_root_train_2= os.path.join(data_dir, 'train_2')` # train_2 data directory
`data_root_eval_1= os.path.join(data_dir, 'eval_1')` # eval_1 data directory
`data_root_eval_2= os.path.join(data_dir, 'eval_2')` # eval_2 data directory
`serving_model_dir = os.path.join(_tfx_root, "model")`

`context = InteractiveContext()`

**Examplegen**
```
input = example_gen_pb2.Input(splits=[
 example_gen_pb2.Input.Split(name='train_1', pattern='train_1/*'),
 example_gen_pb2.Input.Split(name='train_2', pattern='train_2/*'),
 example_gen_pb2.Input.Split(name='eval_1', pattern='eval_1/*'),
example_gen_pb2.Input.Split(name='eval_2', pattern='eval_2/*'),
])
```

```
examples = external_input(data_dir)
example_gen = CsvExampleGen(input=examples, input_config=input)
```

**Statisticgen**

```
statistics_gen = StatisticsGen(
    examples=example_gen.outputs['examples'])
context.run(statistics_gen)
```

**SchemaGen**

```
schema_gen = SchemaGen(
    statistics=statistics_gen.outputs['statistics'],
    infer_feature_shape=True)
context.run(schema_gen) 
```
i got the value error message after executing the schemagen component. 
`Value Error when executing SchemaGen. ValueError: Expected exactly one artifact with split 'train', but found matching artifacts []`.

Thanks in advance

**Comment by chongkong** [comment]
Please try with the newer version of TFX. I confirmed 0.24.1 version works without error. Examples and Statistics artifacts are generated with correct `split_names` property, which is consumed as is on SchemaGen.

When the error occurs again, it is useful for us to debug if you can provide a
1) full list of installed packages (using `pip freeze` or `pip list` command)
2) A complete minimal reproducible code with no modification from us (possibly a colab link)

([internal repro link](https://colab.research.google.com/drive/1sQPMZ7_XnsjpkzHNCTezv5pamOfAQQuE?usp=sharing); sorry this is not publicly accessible)

**Comment by Jaydeemourg** [comment]
ok. thanks for your response. I have found a solution.
