### ISSUE TITLE
Example Validator updates in latest changes cause confusion in documentation 

### ISSUE THREAD

**Issue by nroberts1** [tensorflow/tfx#2718]
In at least this tutorial - https://www.tensorflow.org/tfx/tutorials/tfx/components
there is the documentation relating to running the example validator. The text suggests context.show() will display a table with an issue to the company and payment types being highlighted. I'm guessing the schema is now created using all the data and not just the training data which is a welcome update. But the documentation where the table should be now instead says 'no anomalies found'.

"After ExampleValidator finishes running, we can visualize the anomalies as a table.

```python
context.show(example_validator.outputs['anomalies'])
```

```python
'no anomalies found'


'no anomalies found'
```

> In the anomalies table, we can see that the company feature takes on new values that were not in the training split. This information can be used to debug model performance, understand how your data evolves over time, and identify data errors.
> 
> In our case, this company anomaly is innocuous, but the payment_type could be fixed. For now we move on to the next step of transforming the data."
> 

I've added below to confirm the validator works as before when setup to generate the schema from the training data only:

        eval_stats = statistics.load_statistics_from_artifact(stats_artifact, 'eval')
        train_stats = statistics.load_statistics_from_artifact(stats_artifact, 'train')
        train_schema = schema.infer_from_stats(train_stats)
        pp.pprint(statistics.validate_statistics(eval_stats, train_schema).anomaly_info.items())

**Comment by entrpn** [comment]
I'm having a similar issue. I'm updating the schema values to something ridiculous but when  I run the new schema through the example validator, none are found.

```
tfdv.set_domain(schema, 'difference', schema_pb2.FloatDomain(name='difference', min=-1000.0, max=-500.0,disallow_nan=True,disallow_inf=True, is_embedding=False))
```

**Comment by benmathes** [comment]
(product manager that supports the team working on this)

Thanks for catching this. We're going to discuss it soon.

**Comment by entrpn** [comment]
I found that the ExampleValidator works fine in a regular pipeline in the cloud. It only seems to have this issue with the local InteractiveContext in the notebooks.

**Comment by gowthamkpr** [comment]
@nroberts1 @entrpn Please try using latest version of tfx and let me know if its still an issue. Thanks!!

**Comment by gowthamkpr** [comment]
@nroberts1 Estimators are not recommended for new code. Estimators run [v1.Session](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session)-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. Estimators do fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities. See the [migration guide](https://tensorflow.org/guide/migrate) for details.

Closing this issue as it is expected. Thanks!!!
