### ISSUE TITLE
tf.Transform and keras.layers.experimental.preprocessing

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#2720]
TF 2.3.0 introduced the new preprocessing api in keras.layers.experimental.preprocessing. The tutorials recommend new user to not use the feature columns api.

How does this go together with Transform? Should Transform users keep using the feature columns api or is there a way to use the new keras.layers.experimental.preprocessing?

**Comment by rmothukuru** [comment]
@ConverJens,
Is the below statement present in `Tensorflow Tutorial` or `TFX Tutorial`? If it is present in `TFX Tutorial`, can you please share the respective link?

> The tutorials recommend new user to not use the feature columns api.

AFAIK, that statement applies to `Tensorflow`. But for `TFX`, we may have to use `Feature_Columns`, as shown in this [TFX Keras Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#trainer).

**Comment by ConverJens** [comment]
> @ConverJens,
> Is the below statement present in `Tensorflow Tutorial` or `TFX Tutorial`? If it is present in `TFX Tutorial`, can you please share the respective link?
> 
@rmothukuru Only in the tensorflow tutorial for feature columns (as far as I know):
https://www.tensorflow.org/tutorials/structured_data/feature_columns

> > The tutorials recommend new user to not use the feature columns api.
> 
> AFAIK, that statement applies to `Tensorflow`. But for `TFX`, we may have to use `Feature_Columns`, as shown in this [TFX Keras Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#trainer).
I suspected as much, this is what I've been using as well. Since TFX seems to be moving away from Estimator to Keras and feature columns were originally required by estimators, I was curious if the new preprocessing api is meant to be a replacement for feature columns for TFX as well, but I guess we'll just have to find out.

**Comment by rmothukuru** [comment]
@ConverJens,
Yes. Since the official  [TFX Keras Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras#trainer) uses `Feature_columns`, we can consider that as the recommended approach.

Can you please confirm if we can close this issue. Thanks!

**Comment by ConverJens** [comment]
Right, thanks! Feel free to close.
