### ISSUE TITLE
Restore an interactive Pipeline

### ISSUE THREAD

**Issue by albertnanda** [tensorflow/tfx#2737]
How to restore an interactive pipeline. Let's say I have completed some steps and then want to restore them in another notebook.
This is what I tried,
``` python
from ml_metadata.proto import metadata_store_pb2
import ml_metadata as mlmd
import tensorflow as tf
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext

connection_config = metadata_store_pb2.ConnectionConfig()
connection_config.sqlite.filename_uri = "/tmp/tfx-interactive-2020-10-31T06_26_30.753708-rh33v0vf/metadata.sqlite"
connection_config.sqlite.connection_mode = 3 # READWRITE_OPENCREATE
store = mlmd.metadata_store.MetadataStore(connection_config)

context = InteractiveContext(metadata_connection_config=store)

```
How then to restore, ExampleGen, StatisticsGen, SchemaGen etc.?

**Comment by zhitaoli** [comment]
I don't think we have this capability yet for interactive context, and I think interactive context is not really designed for this purpose yet. I would suggest you use a more suitable runner based on your requirement (Beam/Airflow/Kubeflow). 

See our [guide page](https://www.tensorflow.org/tfx/guide#creating_a_tfx_pipeline_with_airflow) for more details.

Feel free to reach out to use if you need more information.

**Comment by arghyaganguly** [comment]
Closing this based on above comment trace.Feel free to reopen.Thanks.
