### ISSUE TITLE
No mechanism for metrics at inference time

### ISSUE THREAD

**Issue by adriangay** [tensorflow/tfx#2748]
We want to emit some data to use for model metrics at inference time when serving an NLP model. A simple mechanism would be to log data and then use log-based metrics to recover the data from log entries. Logging while from, for example, Transform, works when training. When the TFX pipeline is saved as a SavedModel and served with Tensorflow Serving, logging from Transform is not output. Varying the TFS log level using TF_CPP_MIN_VLOG_LEVEL does output more detailed TFS messages, but not the message we log in TFX Transform. We have tried Python standard logger, tf.compat.v1.logging and tfx.utils.logging_utils, and these all 'work' during training runs. The latter isn't really an option as Transform doesn't have a class in which to create the logger once. 

After an enormous amount of Googling, we can't find anyone talking about inference-time custom metrics. Maybe we're missing something obvious about how to emit metrics when TFS is running a SavedModel?

**Comment by rmothukuru** [comment]
@adriangay,
I think you can write a function to capture the Metrics in the Client File of Tensorflow Serving. Example of such function can be found in [MNIST Client File](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L78-L82). Please let us know if that helps. Thanks!

**Comment by adriangay** [comment]
@rmothukuru thank you for the reply. the example you reference is measuring model performance, externally,  on 'test' data, ie. comparing the prediction with a known label. We have some metrics for our use case which collects data at inference time, when running on real unlabelled examples. We. collect the metric data in the pre- and post-processing steps, and it's this data we need to emit from inside the model graph execution.

**Comment by zhitaoli** [comment]
Sorry for the slow response. Are you asking to retrieve a metric which you defined in the TF transform graph part at inference time, or are you trying to creating metrics based on inference result?

Can you also maybe add some code snippet so we could better understand your request?

**Comment by singhniraj08** [comment]
@adriangay,

Please provide some code snippet to better understand the request. Thanks!
