### ISSUE TITLE
Getting run_id from Pipeline class or InteractiveContext and using it in components

### ISSUE THREAD

**Issue by calvinleungyk** [tensorflow/tfx#2773]
For a `Pipeline` class, the run_id is generated when `BeamDagRunner().run()` is called, and for `InteractiveContext`, the run_id is generated when `context.run()` is called each time and is not exposed as an instance attribute.

Is there a recommended way to use `run_id` within the components in the pipeline? We would like to use it as an identifier for some Artifacts (e.g. embeddings) that we push to a DB.

**Comment by casassg** [comment]
Specifically, we would like to access it from @component decorator. This allows us to push stuff to BigQuery (Driver doesn't know how to version it) and version our outputs there as well.

**Comment by singhniraj08** [comment]
@calvinleungyk,

When defining the pipeline's components, you can use `.with_id()` method and give the component a custom name which can be used as identifier for that component later as shown [here](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_local.py#L371-L372).
Thank you!

Example:
```

# Normal component definition:
stats_gen = tfx.components.StatisticsGen(...)
# Custom component definition:
stats_gen = tfx.components.StatisticsGen(...).with_id("raw_stats_gen")

```
