### ISSUE TITLE
Allow users to supply custom file patterns in Beam-based components

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/tfx#2776]
Most (all?) of the Beam-based components assume, in their executor, that all files in the given artifact URI should be read. See [StatisticsGen](https://github.com/tensorflow/tfx/blob/v0.24.1/tfx/components/statistics_gen/executor.py#L135) for example, which uses `all_files_pattern()` during the Beam IO. At Spotify, we often need to publish additional metadata alongside the data for a number of reasons, and this breaks a lot of components since these additional metadata files are not tfrecord files. We have had to work around this by copy-pasting some of the executor code which is of course not ideal.

Could TFX allow users to pass in custom file patterns for these components? Perhaps it could be done by setting a custom property on the artifact. Alternatively, maybe a more sensible default for the executors to use would be to just glob for `*tfrecord*`?

**Comment by andrewsmartin** [comment]
This also applies to some non-beam components as well - an example is in `SchemaGen`, which when reading the input statistics [assumes it is the only file in the directory](https://github.com/tensorflow/tfx/blob/v0.24.1/tfx/components/schema_gen/executor.py#L95-L96).

**Comment by charlesccychen** [comment]
Thank you for filing this -- I will look into making the file patterns more specific when possible.  If we make this change, would you still see a need for specifying a file pattern?  We are treating certain types of system-defined artifacts as of known structure for inputs and outputs, so it would be a little hard to have full customizability here.

CC: @zhitaoli @1025KB @ruoyu90

**Comment by andrewsmartin** [comment]
Yes, I think if the file patterns were just more specific (in both instances I mentioned, i.e. when globbing for tfrecords and looking up the only file in a URI), then it would eliminate the need to allow the user to customize.

**Comment by andrewsmartin** [comment]
Hi, I just wanted to check and see if there has been any movement on this.

**Comment by rcrowe-google** [comment]
Do you need to propagate the metadata through the artifact lineage?  For example, if you include an extra file which contains metadata next to the original data files which are read by ExampleGen, do you need to include that file along with the output of ExampleGen next to the payload tfrecord files?

**Comment by rcrowe-google** [comment]
Also, could this need be met with a new metadata artifact type, rather than a file which contains metadata?  Where is this data needed - in the execution, or context?

**Comment by andrewsmartin** [comment]
Hi @rcrowe-google, answers below:


> Do you need to propagate the metadata through the artifact lineage? For example, if you include an extra file which contains metadata next to the original data files which are read by ExampleGen, do you need to include that file along with the output of ExampleGen next to the payload tfrecord files?

The metadata itself does not need to be propagated in a way that is different than how artifact lineage is already propagated -  just the parent URI should continue to be propagated through MLMD. If a certain use case _would_ require propagating such files, for us it is OK to leave that logic to an individual component's executor if things need to be copied over. The important thing for us is just the ability to supply a file pattern to read specific files within that URI.

> Also, could this need be met with a new metadata artifact type, rather than a file which contains metadata? Where is this data needed - in the execution, or context?

Unfortunately, no. One example of this is that often, a Schema file needs to be published alongside TF Record files containing additional annotations describing features in order for our GDPR systems to work. Nothing in the TFX world would need to know about this file, it's just for external systems. It just means that we need to provide more specific file patterns in order to make the existing executors work without copying and pasting our own implementation.

**Comment by singhniraj08** [comment]
@andrewsmartin,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
