### ISSUE TITLE
Columns do not match specified csv headers

### ISSUE THREAD

**Issue by ashutosh-dev** [tensorflow/tfx#2782]
I was trying to load data to tfx CsvExamplegen where i am getting error like shown in the error.png image , I have just applied some basic processing on the data such as dropping the index column and converting the state column to int and have check none of the column contain the null value the dtype output of the dataframe is as follows:
```blurb object 
state int64 
dtype: object```
i am using the kaggle dataset which is at location "https://www.kaggle.com/oscarvilla/kickstarter-nlp" , any suggestion would be really helpful 
i am getting the following error while implementing the code 
```examples = external_input("data")
example_gen = CsvExampleGen(input=examples)
context.run(example_gen)```


error is as follows
WARNING:absl:The "input" argument to the CsvExampleGen component has been deprecated by "input_base". Please update your usage as support for this argument will be removed soon.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner.process()

62 frames
ValueError: Columns do not match specified csv headers: ['blurb', 'state'] -> [b'HELP LAUNCH CONQUEST IQ version 2 HELP LAUNCH CONQUEST IQ version 2 ']

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tfx_bsl/coders/csv_decoder.py in add_input(self, accumulator, cells)
    224     elif cells and len(cells) != len(self._column_names):
    225       raise ValueError("Columns do not match specified csv headers: %s -> %s" %
--> 226                        (self._column_names, cells))
    227 
    228     # Iterate over each feature value and update the type.

ValueError: Columns do not match specified csv headers: ['blurb', 'state'] -> [b'HELP LAUNCH CONQUEST IQ version 2 HELP LAUNCH CONQUEST IQ version 2 '] [while running 'InputToRecord/InferColumnTypes/KeyWithVoid']

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TFX version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by 1025KB** [comment]
Do you have multiple files in the folder and the header doesn't match?

**Comment by rmothukuru** [comment]
@ashutosh-dev,
Can you please respond to above comment. Thanks!

**Comment by ashutosh-dev** [comment]
@rmothukuru  sorry for the late reply
**System information**
i was using the google colab to run the code
TensorFlow version: 2.3.0
TFX version: 0.24.1
current behavior:
i am using the dataset from the "https://www.kaggle.com/oscarvilla/kickstarter-nlp"  i have cleaned the blurb column from the data as in to remove the character like "\n ,\t" and converting labels to numeric like 0 for the failed , 1 for successful and saved the data in csv format in a separate folder , the folder contains only one file that is the csv file. when i try to load the data in the tfx examplegen using  external input 

examples = external_input(folder_name)
example_gen = CsvExampleGen(input=examples)
context.run(example_gen)

entire error stack is as follows
Error                                     Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner.process()

42 frames

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.SimpleInvoker.invoke_process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common._OutputProcessor.process_outputs()

/usr/local/lib/python3.6/dist-packages/tfx_bsl/coders/csv_decoder.py in process(self, csv_line)
    173   def process(self, csv_line: CSVLine):
--> 174     line = self._reader.ReadLine(csv_line)
    175     yield (line, csv_line)

/usr/local/lib/python3.6/dist-packages/tfx_bsl/coders/csv_decoder.py in ReadLine(self, csv_line)
    454     self._line_iterator.SetItem(self._to_reader_input(csv_line))
--> 455     return [tf.compat.as_bytes(cell) for cell in next(self._reader)]
    456 

Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?


During handling of the above exception, another exception occurred:

Error                                     Traceback (most recent call last)

<ipython-input-8-e1581e125770> in <module>()
      5 example_gen = CsvExampleGen(input=examples)
      6 
----> 7 context.run(example_gen)

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     65       # __IPYTHON__ variable is set by IPython, see
     66       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 67       return fn(*args, **kwargs)
     68     else:
     69       absl.logging.warning(

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    180         telemetry_utils.LABEL_TFX_RUNNER: runner_label,
    181     }):
--> 182       execution_id = launcher.launch().execution_id
    183 
    184     return execution_result.ExecutionResult(

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    203                          execution_decision.input_dict,
    204                          execution_decision.output_dict,
--> 205                          execution_decision.exec_properties)
    206 
    207     absl.logging.info('Running publisher for %s',

/usr/local/lib/python3.6/dist-packages/tfx/orchestration/launcher/in_process_component_launcher.py in _run_executor(self, execution_id, input_dict, output_dict, exec_properties)
     65         executor_context)  # type: ignore
     66 
---> 67     executor.Do(input_dict, output_dict, exec_properties)

/usr/local/lib/python3.6/dist-packages/tfx/components/example_gen/base_example_gen_executor.py in Do(self, input_dict, output_dict, exec_properties)
    301          | 'WriteSplit[{}]'.format(split_name) >> _WriteSplit(
    302              artifact_utils.get_split_uri(output_dict[utils.EXAMPLES_KEY],
--> 303                                           split_name)))
    304       # pylint: enable=expression-not-assigned, no-value-for-parameter
    305 

/usr/local/lib/python3.6/dist-packages/apache_beam/pipeline.py in __exit__(self, exc_type, exc_val, exc_tb)
    566     try:
    567       if not exc_type:
--> 568         self.result = self.run()
    569         self.result.wait_until_finish()
    570     finally:

/usr/local/lib/python3.6/dist-packages/apache_beam/pipeline.py in run(self, test_runner_api)
    545         finally:
    546           shutil.rmtree(tmpdir)
--> 547       return self.runner.run_pipeline(self, self._options)
    548     finally:
    549       shutil.rmtree(self.local_tempdir, ignore_errors=True)

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in run_pipeline(self, pipeline, options)
    174 
    175     self._latest_run_result = self.run_via_runner_api(
--> 176         pipeline.to_runner_api(default_environment=self._default_environment))
    177     return self._latest_run_result
    178 

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in run_via_runner_api(self, pipeline_proto)
    184     # TODO(pabloem, BEAM-7514): Create a watermark manager (that has access to
    185     #   the teststream (if any), and all the stages).
--> 186     return self.run_stages(stage_context, stages)
    187 
    188   @contextlib.contextmanager

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in run_stages(self, stage_context, stages)
    344           stage_results = self._run_stage(
    345               runner_execution_context,
--> 346               bundle_context_manager,
    347           )
    348           monitoring_infos_by_stage[stage.name] = (

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in _run_stage(self, runner_execution_context, bundle_context_manager)
    532               input_timers,
    533               expected_timer_output,
--> 534               bundle_manager)
    535 
    536       final_result = merge_results(last_result)

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in _run_bundle(self, runner_execution_context, bundle_context_manager, data_input, data_output, input_timers, expected_timer_output, bundle_manager)
    570 
    571     result, splits = bundle_manager.process_bundle(
--> 572         data_input, data_output, input_timers, expected_timer_output)
    573     # Now we collect all the deferred inputs remaining from bundle execution.
    574     # Deferred inputs can be:

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py in process_bundle(self, inputs, expected_outputs, fired_timers, expected_output_timers, dry_run)
    850             process_bundle_descriptor.id,
    851             cache_tokens=[next(self._cache_token_generator)]))
--> 852     result_future = self._worker_handler.control_conn.push(process_bundle_req)
    853 
    854     split_results = []  # type: List[beam_fn_api_pb2.ProcessBundleSplitResponse]

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py in push(self, request)
    351       self._uid_counter += 1
    352       request.instruction_id = 'control_%s' % self._uid_counter
--> 353     response = self.worker.do_instruction(request)
    354     return ControlFuture(request.instruction_id, response)
    355 

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py in do_instruction(self, request)
    482       # E.g. if register is set, this will call self.register(request.register))
    483       return getattr(self, request_type)(
--> 484           getattr(request, request_type), request.instruction_id)
    485     else:
    486       raise NotImplementedError

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py in process_bundle(self, request, instruction_id)
    517         with self.maybe_profile(instruction_id):
    518           delayed_applications, requests_finalization = (
--> 519               bundle_processor.process_bundle(instruction_id))
    520           monitoring_infos = bundle_processor.monitoring_infos()
    521           monitoring_infos.extend(self.state_cache_metrics_fn())

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/bundle_processor.py in process_bundle(self, instruction_id)
    983           elif isinstance(element, beam_fn_api_pb2.Elements.Data):
    984             input_op_by_transform_id[element.transform_id].process_encoded(
--> 985                 element.data)
    986 
    987       # Finish all operations.

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/bundle_processor.py in process_encoded(self, encoded_windowed_values)
    219       decoded_value = self.windowed_coder_impl.decode_from_stream(
    220           input_stream, True)
--> 221       self.output(decoded_value)
    222 
    223   def monitoring_infos(self, transform_id, tag_to_pcollection_id):

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.Operation.output()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.Operation.output()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.SingletonConsumerSet.receive()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.SdfProcessSizedElements.process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.SdfProcessSizedElements.process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner.process_with_sized_restriction()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.PerWindowInvoker.invoke_process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common._OutputProcessor.process_outputs()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.SingletonConsumerSet.receive()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.DoOperation.process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/operations.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.worker.operations.DoOperation.process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner.process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner._reraise_augmented()

/usr/local/lib/python3.6/dist-packages/future/utils/__init__.py in raise_with_traceback(exc, traceback)
    444         if traceback == Ellipsis:
    445             _, _, traceback = sys.exc_info()
--> 446         raise exc.with_traceback(traceback)
    447 
    448 else:

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.DoFnRunner.process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common.SimpleInvoker.invoke_process()

/usr/local/lib/python3.6/dist-packages/apache_beam/runners/common.cpython-36m-x86_64-linux-gnu.so in apache_beam.runners.common._OutputProcessor.process_outputs()

/usr/local/lib/python3.6/dist-packages/tfx_bsl/coders/csv_decoder.py in process(self, csv_line)
    172 
    173   def process(self, csv_line: CSVLine):
--> 174     line = self._reader.ReadLine(csv_line)
    175     yield (line, csv_line)
    176 

/usr/local/lib/python3.6/dist-packages/tfx_bsl/coders/csv_decoder.py in ReadLine(self, csv_line)
    453     """Reads out bytes for PY2 and Unicode for PY3."""
    454     self._line_iterator.SetItem(self._to_reader_input(csv_line))
--> 455     return [tf.compat.as_bytes(cell) for cell in next(self._reader)]
    456 
    457   def __getstate__(self):

Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode? [while running 'InputToRecord/ParseCSVLine']

expected output:
i expected the data to get loaded into the interactive context for further processing 

@1025KB hello, the folder had only one single file i had already removed all the hidden files .

**Comment by UsharaniPagadala** [comment]
@ashutosh-dev 

Could you please refer the similar issues [link1](https://stackoverflow.com/questions/64118600/tfx-properties-for-csvcoder-in-csvexamplegen-columns-do-not-match-specified-c) and [link2](https://stackoverflow.com/questions/17315635/csv-new-line-character-seen-in-unquoted-field-error), hope it helps.Thanks

**Comment by gowthamkpr** [comment]
The above solution in link 1 should solve the issue. Closing this issue as it has been inactive for more than a year. Please update the issue with a comment and if its valid will open the issue. Thanks!!
