### ISSUE TITLE
StatisticsGen does not recognize missing fields 

### ISSUE THREAD

**Issue by dbustosp** [tensorflow/tfx#2802]
For some reason StatisticsGen is not recognizing the missing values in my file. 
I was expecting that StatisticsGen recognizes the missing fields in the last records. 
When I generate the statistics using [generate_statistics_from_csv](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/generate_statistics_from_csv) directly works perfectly fine. 

```
# Loading the Files
input_config = example_gen_pb2.Input(splits=[
    example_gen_pb2.Input.Split(name='train', pattern='train/*'),
    example_gen_pb2.Input.Split(name='eval', pattern='eval/*')
])

example_gen = CsvExampleGen(
    input_base=_data_root,
    input_config=input_config)

context.run(example_gen, enable_cache=False)

# Generating Stats
statistics_gen = StatisticsGen(examples=example_gen.outputs['examples'])
context.run(statistics_gen, enable_cache=False)

# Showing the Stats
context.show(statistics_gen.outputs['statistics'])
```

File being used: 

```
index,inputSurname,label
0,BALLADARAS NATE RAE,0
1,LABRANCHE TRACIE SURIANO,0
2,VENTURES LLC             TIERNAN RE,1
3,CHOU                     ABC,1
4,JENSEN DARREN RANEE,0
5,VANDERMOLEN DEBORA PATRICIA,0
6,ZAMBRANO YANGFANG SESE,0
7,IMAGE LLC                DENTAL,1
8,OFFICE                   S BRUCE             LAW,1
9,,
```

**Comment by rmothukuru** [comment]
@selknamintech,
Since your Input is in a File, can you please try [File-Based ExampleGen](https://www.tensorflow.org/tfx/guide/examplegen#file-based_examplegen) and let us know how it goes. Thanks!

**Comment by selknamintech** [comment]
@rmothukuru 
CSVExample is inheriting from [FileBasedExampleGen](https://github.com/tensorflow/tfx/blob/v0.24.1/tfx/components/example_gen/csv_example_gen/component.py#L32). 

Why should  be any difference?

**Comment by 1025KB** [comment]
In CSV executor, we treat those as a feature with [empty list](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/csv_example_gen/executor.py#L49), The feature exists but value might be [] or [sth]

**Comment by selknamintech** [comment]
Hi @1025KB thanks for answering. 
What is the point of having Missing percentage then? Is it my idea or will always be 0% then? 

Not sure why when I use [generate_statistics_from_csv](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/generate_statistics_from_csv) works and detects the missing values.

**Comment by 1025KB** [comment]
Note that you can use ImportExampleGen or custom ExampleGen, which you can choose how the empty value is handled.

**Comment by nmelche** [comment]
I stumbled upon the same behavior. When generating statistics directly with [generate_statistics_from_csv](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/generate_statistics_from_csv), [tfdv.visualize_statistics](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/visualize_statistics) shows me the missing values.
When generating statistics with [tfdv.generate_statistics_from_tfrecord](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/generate_statistics_from_tfrecord), tfdv.visualize_statistics shows me no missing values.
This is confusing.

**Comment by 1025KB** [comment]
it depends on the tf.example, [here](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/csv_example_gen/executor.py#L96) is how CSV convert to tf.Example

if the column type can be decided, then the empty csv value will be sth like "tf.train.Feature(bytes_list=tf.train.BytesList(value=[]))"
if the type can't be inferred, the missing value will be tf.train.Feature()

**Comment by arghyaganguly** [comment]
Closing this as it has been inactive with awaiting response for some time.Please feel free to reopen.

**Comment by aondra17** [comment]
I had same problem, and this worked as solution (i had only int):
