### ISSUE TITLE
TFX Pipeline with Native Keras: Using StatisticeGen to determine steps_per_epoch

### ISSUE THREAD

**Issue by suisenkotoba** [tensorflow/tfx#2810]
I am following chichago taxi example with native keras. I need to make the training steps dynamically adjust to the growing dataset. model.fit() will automatically use steps_per_epoch equal to the number of samples in dataset divided by batch size if steps_per_epoch is not set. But, since the input data came from _input_fn() which is recognized as infinite dataset, the steps_per_epoch must be set. I wonder if it is possible to get total samples from StatisticGen and divide it by batch size then pass it in Trainer train_args? If so how to acquire it? I haven't been able to find it from tfx guide.

**Comment by Mikehem** [comment]
You can try the following and see if it works

NUM_STEPS = statistics_gen.outputs['statistics'].datasets[0].num_examples

And use NUM_STEPS in your trainer definition passing it to the num_steps argument

**Comment by suisenkotoba** [comment]
> You can try the following and see if it works for training
> 
> statistics_gen.outputs['statistics'].datasets[0].num_/ batchsize
> And use it in your trainer definition passing it to the num_steps argument

how about the split configuration? I recall by default examplegen splits the whole dataset into train and eval. is statistics_gen.outputs['statistics'].datasets a list consists of train and eval?

**Comment by Mikehem** [comment]
> 
> 
> > You can try the following and see if it works for training
> > statistics_gen.outputs['statistics'].datasets[0].num_/ batchsize
> > And use it in your trainer definition passing it to the num_steps argument
> 
> how about the split configuration? I recall by default examplegen splits the whole dataset into train and eval. is statistics_gen.outputs['statistics'].datasets a list consists of train and eval?

Hi I had a go at it and this won't work as the StatGen object simply provides a URL to the artifacts and does not encase the values in itself.  context.show is able to pull the information from the artifacts and provide the visualization. so i do not see an option at this stage to make this dynamic. 
I have deleted my comments. Would be a good feature though if we could extract the  metadata more easily.

**Comment by 1025KB** [comment]
Note you can set the dataset from _input_fn to have only one epoch like [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L68)

**Comment by suisenkotoba** [comment]
> > > You can try the following and see if it works for training
> > > statistics_gen.outputs['statistics'].datasets[0].num_/ batchsize
> > > And use it in your trainer definition passing it to the num_steps argument
> > 
> > 
> > how about the split configuration? I recall by default examplegen splits the whole dataset into train and eval. is statistics_gen.outputs['statistics'].datasets a list consists of train and eval?
> 
> Hi I had a go at it and this won't work as the StatGen object simply provides a URL to the artifacts and does not encase the values in itself. context.show is able to pull the information from the artifacts and provide the visualization. so i do not see an option at this stage to make this dynamic.
> I have deleted my comments.
> 
> Have a look at the MLMD https://www.tensorflow.org/tfx/tutorials/mlmd/mlmd_tutorial maybe you might get some hint there.

hi, thank you for the suggestion. I already tried using MLMD. Unfortunately the StatisticGen artifact does not contain information about dataset size. 
![image](https://user-images.githubusercontent.com/32249565/99025218-e8736500-259a-11eb-96ef-e7710dda35b8.png)

**Comment by suisenkotoba** [comment]
> Note you can set the dataset from _input_fn to have only one epoch like [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L68)

umm I don't think training with only one epoch is what I am looking for. Because rarely the result at first epoch is good enough, moreover for production.

**Comment by Mikehem** [comment]
> 
> 
> > > > You can try the following and see if it works for training
> > > > statistics_gen.outputs['statistics'].datasets[0].num_/ batchsize
> > > > And use it in your trainer definition passing it to the num_steps argument
> > > 
> > > 
> > > how about the split configuration? I recall by default examplegen splits the whole dataset into train and eval. is statistics_gen.outputs['statistics'].datasets a list consists of train and eval?
> > 
> > 
> > Hi I had a go at it and this won't work as the StatGen object simply provides a URL to the artifacts and does not encase the values in itself. context.show is able to pull the information from the artifacts and provide the visualization. so i do not see an option at this stage to make this dynamic.
> > I have deleted my comments.
> > Have a look at the MLMD https://www.tensorflow.org/tfx/tutorials/mlmd/mlmd_tutorial maybe you might get some hint there.
> 
> hi, thank you for the suggestion. I already tried using MLMD. Unfortunately the StatisticGen artifact does not contain information about dataset size.
> ![image](https://user-images.githubusercontent.com/32249565/99025218-e8736500-259a-11eb-96ef-e7710dda35b8.png)

Yeah tried it and realized the same :( 
If you use the non pipeline approach such as generate_statistics_from_csv you get access to the details but if follow the pipeline process, i assume it provides the link to the metadata and not the actual metadata.

**Comment by suisenkotoba** [comment]
hmm we should be able to get the dataset statistics by accessing the StatisticsGen artifact. I don't know yet how to do so, the filename is stats_tfrecord, is this a tfrecord file? I tried to read the file with TFRecordDataset but got an empty TFRecordDatasetV2 object. Well, regardless, it would be nice if I can get the dataset size without a complicated workaround.

**Comment by 1025KB** [comment]
> > Note you can set the dataset from _input_fn to have only one epoch like [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L68)
> 
> umm I don't think training with only one epoch is what I am looking for. Because rarely the result at first epoch is good enough, moreover for production.


I mean you can have the dataset to be one epoch, and train multiple epoch instead of using steps_per_epoch?

**Comment by rmothukuru** [comment]
@suisenkotoba,
Can you please respond to the above comment. Thanks!

**Comment by suisenkotoba** [comment]
> > > Note you can set the dataset from _input_fn to have only one epoch like [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L68)
> > 
> > 
> > umm I don't think training with only one epoch is what I am looking for. Because rarely the result at first epoch is good enough, moreover for production.
> 
> I mean you can have the dataset to be one epoch, and train multiple epoch instead of using steps_per_epoch?

how can I get the `data_accessor`? do I need to pass something specific to `Trainer`?

**Comment by ferryvg** [comment]
@1025KB So, how can i use Statistics artifact inside eg. `run_fn`?

**Comment by ferryvg** [comment]
Currently i have to make a copy of Trainer and pass Statistics artifact in it, in order to calculate steps in Executor.
Is there another way to calculate steps without creating a copy of Trainer?

**Comment by SaschaHeyer** [comment]
I am also interested in a solution to this problem. 
We have a growing dataset that is automatically read by the ExampleGen component. 

We need a way to automatically calculate the number of training and eval examples in the pipeline. 
The information is generated by the StatisticsGen component but unfortunately not accessible in the trainer.

**Comment by 1025KB** [comment]
> > Note you can set the dataset from _input_fn to have only one epoch like [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L68)
> 
> umm I don't think training with only one epoch is what I am looking for. Because rarely the result at first epoch is good enough, moreover for production.

I mean you can change the dataset to one epoch, and during model training, set the epoch # you want

**Comment by axeltidemann** [comment]
@1025KB could you provide a more specific example?

**Comment by 1025KB** [comment]
like [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L68) dataset_options.RecordBatchesOptions(batch_size=batch_size, **num_epochs=1**)

and set model.fit(epochs=N) ([doc](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit))

Thus it will train the model with N epochs of the full dataset

**Comment by axeltidemann** [comment]
Thanks, @1025KB. This avoids having to set the `steps_per_epoch` in the `fit` function. And: using the same setting for the validation data, it will finish after one epoch (which is typically what you want), which removes the need for setting `validation_steps` in the `fit` function also. You are then completely removed from having to calculate anything. Elegant.

**Comment by gowthamkpr** [comment]
@suisenkotoba Can you please use the method provided [here](https://github.com/tensorflow/tfx/issues/2810#issuecomment-814267355) as it is not possible to set steps_per_epoch using StatisticsGen. Thanks!

**Comment by gowthamkpr** [comment]
@suisenkotoba Closing this issue as there is no response for a week. Please reply to the above comment and we can open this issue again. Thanks!!!
