### ISSUE TITLE
make `ensure_local` more robust to new schemas

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/tfx#2878]
Not a Contribution.

[ensure_local](https://github.com/tensorflow/tfx/blob/f6dae5f7915955d968e3d26e1f073983d771aeb1/tfx/utils/io_utils.py#L41) is a function which will download a module file to the local filesystem. However it will currently only do this for a hardcoded set of schemas (defined by [_REMOTE_FS_PREFIX](https://github.com/tensorflow/tfx/blob/f6dae5f7915955d968e3d26e1f073983d771aeb1/tfx/utils/io_utils.py#L38)). The TFX filesystem design allows registering new schemas which would not be handled appropriately by this function. Could this instead check if the path either uses the `file` or empty schema, and if not assumes that the resource is remote? This seems to be a more robust way of ensuring that the file is made available locally.

**Comment by singhniraj08** [comment]
@peteboothroyd,
Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
