### ISSUE TITLE
Import error in Trainer with TFX 0.25.0

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#2888]
When bumping my pipeline from TFX 0.24.0 to 0.25.0 the following error caused the Trainer to crash:

INFO:absl:tensorflow_ranking is not available: No module named 'tensorflow_ranking'
INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 315, in main
    component = json_utils.loads(args.serialized_component)
  File "/tfx-src/tfx/utils/json_utils.py", line 193, in loads
    return json.loads(s, cls=_DefaultDecoder)
  File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/tfx-src/tfx/utils/json_utils.py", line 167, in _dict_to_object
    jsonable_class_type = _extract_class(dict_data)
  File "/tfx-src/tfx/utils/json_utils.py", line 164, in _extract_class
    return getattr(importlib.import_module(module_name), class_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/tfx-src/tfx/components/base/executor_spec'

No changes was made to the UDF run_fn and Trainer is the canned TFX component.

Any help would be appreciated!

**Comment by numerology** [comment]
Thanks for reporting @ConverJens 

Do you mind sharing the version of container image you're using? It looks like you're running TFX on KFP, right?

**Comment by ConverJens** [comment]
@numerology No worries!

Yes, I'm running in kfp. I'm using a custom image based on the official tensorflow/tfx:0.25.0.

The other components, custom and canned, completed successfully.

**Comment by numerology** [comment]
@ConverJens Do you mind sharing your compiled yaml spec of the pipeline? 

I think only sharing the Trainer step suffice. Thanks!

**Comment by ConverJens** [comment]
@numerology  Is this sufficient?

- name: trainer
    container:
      args:
      - --pipeline_name
      - trace_model_pipeline
      - --pipeline_root
      - '{{inputs.parameters.pipeline-root}}'
      - --kubeflow_metadata_config
      - |-
        {
          "mysql_db_service_host": {
            "value": "mysql.kubeflow"
          },
          "mysql_db_service_port": {
            "value": "3306"
          },
          "mysql_db_name": {
            "value": "metadb"
          },
          "mysql_db_user": {
            "value": "<usr>"
          },
          "mysql_db_password": {
            "value": "<pwd>"
          },
          "grpc_config": {
            "grpc_service_host": {
              "value": "metadata-grpc-service.kubeflow"
            },
            "grpc_service_port": {
              "value": "8080"
            }
          }
        }
      - --beam_pipeline_args
      - '["--direct_running_mode=multi_processing", "--direct_num_workers=16"]'
      - --additional_pipeline_args
      - '{}'
      - --component_launcher_class_path
      - tfx.orchestration.launcher.in_process_component_launcher.InProcessComponentLauncher
      - --serialized_component
      - '{"__class__": "NodeWrapper", "__module__": "tfx.orchestration.kubeflow.node_wrapper",
        "__tfx_object_type__": "jsonable", "_exec_properties": {"custom_config": "{\"eval_batch_size\":
        16384, \"train_batch_size\": 16384, \"train_shuffle_size\": 10}", "eval_args":
        "{\"num_steps\": {{inputs.parameters.validation-frequency}}}", "module_file":
        null, "run_fn": "kubeflow.model.instance.train.run_fn", "train_args": "{\"num_steps\":
        {{inputs.parameters.train-epochs}}}", "trainer_fn": null}, "_id": "Trainer",
        "_inputs": {"__class__": "_PropertyDictWrapper", "__module__": "tfx.types.node_common",
        "__tfx_object_type__": "jsonable", "_compat_aliases": {"transform_output":
        "transform_graph"}, "_data": {"examples": {"__class__": "Channel", "__module__":
        "tfx.types.channel", "__tfx_object_type__": "jsonable", "artifacts": [], "output_key":
        "transformed_examples", "producer_component_id": "TransformMaster", "type":
        {"name": "Examples", "properties": {"span": "INT", "split_names": "STRING",
        "version": "INT"}}}, "schema": {"__class__": "Channel", "__module__": "tfx.types.channel",
        "__tfx_object_type__": "jsonable", "artifacts": [], "output_key": "schema",
        "producer_component_id": "SchemaGen.raw", "type": {"name": "Schema"}}, "transform_graph":
        {"__class__": "Channel", "__module__": "tfx.types.channel", "__tfx_object_type__":
        "jsonable", "artifacts": [], "output_key": "transform_graph", "producer_component_id":
        "TransformMaster", "type": {"name": "TransformGraph"}}}}, "_outputs": {"__class__":
        "_PropertyDictWrapper", "__module__": "tfx.types.node_common", "__tfx_object_type__":
        "jsonable", "_compat_aliases": {"output": "model"}, "_data": {"model": {"__class__":
        "Channel", "__module__": "tfx.types.channel", "__tfx_object_type__": "jsonable",
        "artifacts": [], "output_key": "model", "producer_component_id": "Trainer",
        "type": {"name": "Model"}}, "model_run": {"__class__": "Channel", "__module__":
        "tfx.types.channel", "__tfx_object_type__": "jsonable", "artifacts": [], "output_key":
        "model_run", "producer_component_id": "Trainer", "type": {"name": "ModelRun"}}}},
        "_type": "tfx.components.trainer.component.Trainer", "driver_class": {"__class__":
        "BaseDriver", "__module__": "tfx.dsl.components.base.base_driver", "__tfx_object_type__":
        "class"}, "executor_spec": {"__class__": "_NewClass", "__module__": "/tfx-src/tfx/components/base/executor_spec.py:34",
        "__tfx_object_type__": "jsonable", "executor_class": {"__class__": "GenericExecutor",
        "__module__": "tfx.components.trainer.executor", "__tfx_object_type__": "class"},
        "extra_flags": ["--direct_running_mode=multi_processing", "--direct_num_workers=16"]}}'
      - --component_config
      - 'null'
      command: [python, /tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py]
      env:
      - name: WORKFLOW_ID
        valueFrom:
          fieldRef: {fieldPath: 'metadata.labels[''workflows.argoproj.io/workflow'']'}
      - name: KFP_POD_NAME
        valueFrom:
          fieldRef: {fieldPath: metadata.name}
      - name: KFP_NAMESPACE
        valueFrom:
          fieldRef: {fieldPath: metadata.namespace}
      image: registry/model-pipeline-tfx/feature_obs-584:0.30.0-dev5_obs_584
      imagePullPolicy: Always
      resources:
        limits: {cpu: '16', ephemeral-storage: 4Gi}
        requests: {cpu: '16', ephemeral-storage: 100Mi}
      volumeMounts:
      - {mountPath: /mnt, name: pv-gluster}
    inputs:
      parameters:
      - {name: pipeline-root}
      - {name: train-epochs}
      - {name: validation-frequency}
    outputs:
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /mlpipeline-ui-metadata.json}
    metadata:
      labels:
        add-pod-env: "true"
        pipelines.kubeflow.org/pipeline-sdk-type: tfx
    volumes:
    - name: pv-gluster
      persistentVolumeClaim: {claimName: tfx-pvc-gluster}

**Comment by numerology** [comment]
> "executor_spec": {"class": "_NewClass", "module": "/tfx-src/tfx/components/base/executor_spec.py:34",
"tfx_object_type": "jsonable"

I believe this is likely the reason. Are you customizing the Trainer component using nonstandard executor spec.

Also /cc @zhitaoli is there some relevance to the failure caused by custom artifact type we've seen recently?

**Comment by ConverJens** [comment]
> > "executor_spec": {"class": "_NewClass", "module": "/tfx-src/tfx/components/base/executor_spec.py:34",
> > "tfx_object_type": "jsonable"
> 
> I believe this is likely the reason. Are you customizing the Trainer component using nonstandard executor spec.
> 
> Also /cc @zhitaoli is there some relevance to the failure caused by custom artifact type we've seen recently?

@numerology We actually use a canned Trainer with the generic executor. We do, however, use a custom Transform components because of multi-input issues (https://github.com/tensorflow/tfx/issues/2889) but the output is just standard artifacts. So there are no custom artifacts used by the trainer component. Below is the Trainer component used to generate the yaml for reference:

trainer = Trainer(
        run_fn=run_fn,
        custom_executor_spec=executor_spec.ExecutorClassSpec(GenericExecutor),
        examples=transform.outputs['transformed_examples'],
        transform_graph=transform.outputs['transform_graph'],
        schema=infer_raw_schema.outputs['schema'],
        train_args={'num_steps': train_steps_param},
        eval_args={'num_steps': eval_steps_param},
        custom_config={'train_batch_size': batch_size,
                       'eval_batch_size': batch_size,
                       'train_shuffle_size': shuffle_size}
    )

Thank you very much for troubleshooting this!

**Comment by zhitaoli** [comment]
@charlesccychen

**Comment by jiyongjung0** [comment]
Thank you for the report. It looks like our recent package restructuring is not working as intended.

### Quick fix
Change `from tfx.components.base import executor_spec` to `from tfx.dsl.components.base import executor_spec` in your pipeline definition.

### Why this happened.
We recently [moved all content in tfx.components.base to tfx.dsl.components.base](https://github.com/tensorflow/tfx/commit/b01482442891a49a1487c67047e85ab971717b75) and used [deperecation utilities in Tensorflow](https://github.com/tensorflow/tensorflow/blob/dc37ecf08b2909c8d2b4d7f8c95ef3a3091d4578/tensorflow/python/util/deprecation.py#L189) to let users know that we have moved. But it looks like there is a subtle issue with json serialization of these deprecation utilities.

### Simplified reproduction.
```
>>> from tfx.components.base import executor_spec
2020-11-27 09:16:45.438326: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-11-27 09:16:45.438355: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> from tfx.components.trainer.executor import GenericExecutor
>>> spec = executor_spec.ExecutorClassSpec(GenericExecutor)
WARNING:tensorflow:From <stdin>:1: The name tfx.components.base.executor_spec.ExecutorClassSpec is deprecated. Please use tfx.dsl.components.base.executor_spec.ExecutorClassSpec instead.

WARNING:tensorflow:From <stdin>:1: The name tfx.components.base.executor_spec.ExecutorClassSpec is deprecated. Please use tfx.dsl.components.base.executor_spec.ExecutorClassSpec instead.

>>> tfx.utils.json_utils.dumps(spec)
'{"__class__": "_NewClass", "__module__": "/<my_personal_path>/executor_spec/lib/python3.8/site-packages/tfx/components/base/executor_spec.py:31", "__tfx_object_type__": "jsonable", "executor_class": {"__class__": "GenericExecutor", "__module__": "tfx.components.trainer.executor", "__tfx_object_type__": "class"}, "extra_flags": []}'
```

**Comment by ConverJens** [comment]
@jiyongjung0 Replacing the import as you proposed solved it for me! Thank you very much for your help everyone! 
I consider this issue closed.

**Comment by charlesccychen** [comment]
Thank you for this report.  It looks like the current Tensorflow deprecated decorator is implicitly creating a subclass (see https://github.com/tensorflow/tensorflow/blob/42aab9b1f03713757d7c027b23f1113ea80f73ad/tensorflow/python/util/deprecation.py#L188), which conflicts with serialization.  We should fix this even when the deprecated symbol is used.

**Comment by pindinagesh** [comment]
@ConverJens 

Could you please move this to closed status as it is resolved. Thanks
