### ISSUE TITLE
Using docker image for preprocess and train

### ISSUE THREAD

**Issue by ganeshas** [tensorflow/tfx#2934]
Hello,

I am creating a TFX pipeline using `tfx.orchestration.pipeline.Pipeline` and running it on Airflow using `AirflowDagRunner`. However, for the `Transform` and `Trainer` components, I'm using module files containing `preprocessing_fn` and `trainer_fn` from a different directory which cannot be imported to the project with the Pipeline and AirflowDagRunner. Is there a way to specify the docker image with all the module files in one of AirflowDagRunner, Pipeline or Transform/Trainer? Or the only way currently supported is to have the module files in the same project as the Pipeline that contains the Transform and Trainer components?

Thanks in advance!

**Comment by zhitaoli** [comment]
Sorry for the slow response.

We don't explicitly support using docker images with AirflowDagRunner yet, or recommend a particular pattern for this. I would suggest you to take a look at the KubeflowDagRunner if using container images is necessary.

**Comment by pindinagesh** [comment]
@ganeshas 

Could you please respond on the above @zhitaoli comment. Thanks
