### ISSUE TITLE
Unable to feed Evaluator with custom tf.Example

### ISSUE THREAD

**Issue by YeskendirK** [tensorflow/tfx#298]
Hello!
I have trained model and dataset of images. Now I am trying to run Evaluator component of TFX:
```python
    model_analyzer = Evaluator(
        model_exports=channel.as_channel([types.TfxType(
            type_name='path/to/evalSavedModel]),
        examples=channel.as_channel([types.TfxType(examples)])
    )
```
where example is:
```python
def create_examples():
    cwd = '/path/to/dataset/with/two/classes'
    keys = ['0', '1']
    values = [0, 1]
    classes = dict(zip(keys, values))
    examples = []
    for name, label in classes.items():
        class_path = os.path.join(cwd, name)
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            img = Image.open(img_path)
            img_raw = img.tobytes()
            example = tf.train.Example(features=tf.train.Features(feature={
                "img_raw": tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_raw])),
                "label": tf.train.Feature(int64_list=tf.train.Int64List(value=[label]))}))
            examples.append(example)

    return examples
```
However I receive the following error:
```vim
TypeError: [features {
  feature {
    key: "img_raw"
    value {
      bytes_list {
        value: "\234z^\233 has type list, but expected one of: bytes, unicode
```
I've spent a lot of time on this issue. Please help!

Thank you!

**Comment by gowtham-kp** [comment]
@YeskendirK As mentioned [here ](https://www.tensorflow.org/tutorials/load_data/tf_records#data_types_for_tfexample) Byteslist doesn't accept list, it only accepts string and bytes as input.

How ever as mention [here](https://www.tensorflow.org/tutorials/load_data/tf_records#write_the_tfrecord_file), you can convert images to tf examples using this file and use those tf examples as the input to BytesList. Please let me know if this helps. thanks!

**Comment by YeskendirK** [comment]
> @YeskendirK As mentioned [here ](https://www.tensorflow.org/tutorials/load_data/tf_records#data_types_for_tfexample) Byteslist doesn't accept list, it only accepts string and bytes as input.
> 
> How ever as mentionioned [here](https://www.tensorflow.org/tutorials/load_data/tf_records#write_the_tfrecord_file), you can convert images to tfexamples using this file and use those tf examples as the input to BytesList. Please let me know if this helps. Thanks!

Thanks for the reply!
However, I face the same error message:
```vim
    examples=channel.as_channel([types.TfxType(examples)])
  File "/Users/user/tfx-env/lib/python3.7/site-packages/tfx/utils/types.py", line 67, in __init__
    artifact_type.name = type_name
TypeError: [features {
  feature {
    key: "depth"
    value {
      int64_list {
        value: 3
      }
    has type list, but expected one of: bytes, unicode
```
Here is my edited code after your suggestions:
```python
def image_examples():
    cwd = '/path/to/dataset/with/two/classes'
    keys = ['0', '1']
    values = [0, 1]
    classes = dict(zip(keys, values))
    examples = []
    for name, label in classes.items():
        class_path = os.path.join(cwd, name)
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            image_string = open(img_path, 'rb').read()
            #image_shape = tf.image.decode_jpeg(image_string).shape
            ## image shape returns None, for now I'll set it to [255,255,3]
            image_shape = [255,255,3]
            print('{} {} {}'.format(image_shape[0], image_shape[1], image_shape[2]))
            print(label)
            feature = {
                'height': _int64_feature(image_shape[0]),
                'width': _int64_feature(image_shape[1]),
                'depth': _int64_feature(image_shape[2]),
                'label': _int64_feature(label),
                'image_raw': _bytes_feature(image_string),
            }
            example = tf.train.Example(features=tf.train.Features(feature=feature))
            examples.append(example)
    return examples

```

**Comment by charlesccychen** [comment]
It looks like the error now is different: it refers to the line:

```python
                'depth': _int64_feature(image_shape[2]),
```

Can you check your implementation of `_int64_feature`?

**Comment by YeskendirK** [comment]
```python
def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
```

**Comment by rmothukuru** [comment]
> > @YeskendirK As mentioned [here ](https://www.tensorflow.org/tutorials/load_data/tf_records#data_types_for_tfexample) Byteslist doesn't accept list, it only accepts string and bytes as input.
> > How ever as mentionioned [here](https://www.tensorflow.org/tutorials/load_data/tf_records#write_the_tfrecord_file), you can convert images to tfexamples using this file and use those tf examples as the input to BytesList. Please let me know if this helps. Thanks!
> 
> @gowtham-kp Thanks for the reply!
> However, I face the same error message:
> 
> ```viml
>     examples=channel.as_channel([types.TfxType(examples)])
>   File "/Users/user/tfx-env/lib/python3.7/site-packages/tfx/utils/types.py", line 67, in __init__
>     artifact_type.name = type_name
> TypeError: [features {
>   feature {
>     key: "depth"
>     value {
>       int64_list {
>         value: 3
>       }
>     has type list, but expected one of: bytes, unicode
> ```
> 
> Here is my edited code after your suggestions:
> 
> ```python
> def image_examples():
>     cwd = '/path/to/dataset/with/two/classes'
>     keys = ['0', '1']
>     values = [0, 1]
>     classes = dict(zip(keys, values))
>     examples = []
>     for name, label in classes.items():
>         class_path = os.path.join(cwd, name)
>         for img_name in os.listdir(class_path):
>             img_path = os.path.join(class_path, img_name)
>             image_string = open(img_path, 'rb').read()
>             #image_shape = tf.image.decode_jpeg(image_string).shape
>             ## image shape returns None, for now I'll set it to [255,255,3]
>             image_shape = [255,255,3]
>             print('{} {} {}'.format(image_shape[0], image_shape[1], image_shape[2]))
>             print(label)
>             feature = {
>                 'height': _int64_feature(image_shape[0]),
>                 'width': _int64_feature(image_shape[1]),
>                 'depth': _int64_feature(image_shape[2]),
>                 'label': _int64_feature(label),
>                 'image_raw': _bytes_feature(image_string),
>             }
>             example = tf.train.Example(features=tf.train.Features(feature=feature))
>             examples.append(example)
>     return examples
> ```

@YeskendirK ,
Can you please provide the Error Message when you have tried the above code.

**Comment by YeskendirK** [comment]
@rmothukuru @gowtham-kp @charlesccychen Thanks for your help! I solved my problem by using ImportExampleGen, even though I wanted to use only Evaluator & ModelValidator components in the beginning.
