### ISSUE TITLE
Unable to set InfraValidator model serving container resources

### ISSUE THREAD

**Issue by adriangay** [tensorflow/tfx#2993]
Hi

We want to set container resources on the model serving container that InfraValidator creates to run the model in a 'sandbox'. We thought it necessary to ensure that the container uses the same resources that will be available when the model is served on a production serving instance.

We mistakenly thought ```component_config_overrides``` would be the mechanism, but of course that only applies to the TFX component itself. We have now found the code that creates the pod/container spec and request K8s to create a pod here:

https://github.com/tensorflow/tfx/blob/1db1358fcef2d0f5571e0ca68079f1401d7fb1ef/tfx/components/infra_validator/model_server_runners/kubernetes_runner.py#L236

It is clear that this is uses whatever default resources K8s chooses to assign when creating the pod. We cannot see any other configuration applied anywhere that might allow us to override this.

Maybe we misunderstand the intention or operation of InfraValidator? Or maybe this should be a feature request?

For info, this discussion started over on KF Github here:
https://github.com/kubeflow/pipelines/issues/4822

I would be willing to become a contributor and implement/test this feature. Reading the InfraValidator component code, my first thought is to add a new element to the Executor ```exec_properties``` which adheres to the K8s resource spec:

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ResourceRequirements.md

This would be passed as an Optional dict argument all the way down the call chain to ```KubernetesRunner```. There the dict would be validated according to:

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

and if ok, used to set the ```resources``` property of the V1Container:

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Container.md

here:
https://github.com/tensorflow/tfx/blob/1db1358fcef2d0f5571e0ca68079f1401d7fb1ef/tfx/components/infra_validator/model_server_runners/kubernetes_runner.py#L243

**Comment by ConverJens** [comment]
@adriangay This would be very useful! If this is implemented, perhaps the ability to specify a custom image could be added at the same time? https://github.com/tensorflow/tfx/issues/1871

**Comment by adriangay** [comment]
@ConverJens I see that issue has been open a while. I agree it should be straightforward to implement. Did anyone ever get back to you about doing a PR yourself?

**Comment by ConverJens** [comment]
@adriangay They did not. Actually, I attempted to create a custom InfraValidator to set the image but ended up with runtime errors relating to the istio side-car and left it at that. However, we are still interested and I could probably make another attempt sometime after christmas.

**Comment by chongkong** [comment]
Hi, I'm the author of the InfraValidator component. We didn't have configuration for specifying Pod/Container spec yet because we didn't have a customer use cases thus lacked the good understanding on which config shall be included or not. I'm glad to help your work on this, whether it is a discussion thread on here or from a PR. For adding configuration, we usually put configs on proto files (see tfx/proto/infra_validator.proto) and that might be a good starting point.

And @ConverJens sorry for not following up later from #1871, and I'm available to start working on this. Let's continue discussion on that particular thread.

**Comment by adriangay** [comment]
@chongkong Hi, thanks for getting in touch. I am on vacation this week, but I will make some time to write a bit more about want we [think] we want to configure with InfraValidator. I started playing with the code before Xmas to get a feel for what might be required, but some direction from you would be most welcome. I assume we can continue the discussion here until it gets to the point of creating a branch?

**Comment by chongkong** [comment]
Sure. I think we'd like to edit `KubernetesConfig` in tfx/proto/infra_validator.py which would be used in `tfx/components/infra_validator/model_server_runners/kubernetes_runner.py` (as you pointed).
Once implemented, we have e2e test at `tfx/examples/chicago_taxi_pipeline/taxi_pipeline_infraval_beam_e2e_test.py`.

**Comment by adriangay** [comment]
I started from the bottom up as I was not sure where the config would be specified. So I added an optional  argument ```odel_serving_container_resources_override: Optional[dict]``` to the  ```KubernetesRunner``` class allowing just ```limits``` or ```resources``` KV pairs for now. These are validated against a regex that allows all the K8s CPU and mem value formats like so:

```
_MODEL_SERVER_MODEL_CONTAINER_RESOURCE_MEMORY_REGEX = '^(?!0+).*^(?=([0-9]+)($|Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|K)|([0-9]+e[0-9]+))'
```
```
def _get_container_resources_override_or_error(model_serving_container_resources_override: dict) -> dict:
  keys = model_serving_container_resources_override.keys()
  if len(keys) <= 2:
    for key in keys:
      if key in ['limits','requests']:
        for value_key, value in model_serving_container_resources_override[key]:
          if value_key == 'cpu':
            if not (isinstance(value, int) and value > 0):
              raise ValueError(f'override container resource cpu value "{value}" is not a postive integer')
          elif value_key == 'mem':
            if not (re.match(_MODEL_SERVER_MODEL_CONTAINER_RESOURCE_MEMORY_REGEX, value)):
              raise ValueError(f'override container resource mem value "{value}" is not a valid Kubernetes memory string')
          else:
            raise ValueError(f'invalid override container resource key {value}')
      else: 
        raise ValueError(f'invalid override container resource key {key}')
  else:
    raise ValueError('too many resource keys')
  return model_serving_container_resources_override
```
and added to the ```V1PodSpec```  like so:
```
        spec=k8s_client.V1PodSpec(
            containers=[
                k8s_client.V1Container(
                    name=_MODEL_SERVER_CONTAINER_NAME,
                    image=self._serving_binary.image,
                    env=env_vars,
                    volume_mounts=[],
                    resources=self.model_serving_container_resources_override
                ),
            ],
```
Then I got stuck and was thinking maybe to pass this as an override config (hence the name) in ```KubeflowDagRunnerConfig```. However, now I see that adding it into ```infra_vaidator.proto``` as you explained makes more sense as it is automatically 'transported` to the right place(s) via the existing ```serving_spec``` argument of ```executor```... cool!

What do you suggest is the first next step. I'm happy to have a go at this - create a branch, write some tests, etc., but I feel a bit daunted by the thought of Bazel which I've only attempted to run once on my Mac, and running 'vast' TFX integration tests locally. Maybe that's not how it works.

**Comment by chongkong** [comment]
It is true that TFX lacks a good support for local development for external developers..😅 Assuming we have no other errors, ideally `pip install` would automatically run all the required bazel build steps (for TFX this is only for populating proto stub files). I'm not sure it's currently working, but you can install the local repository in editable mode (`pip install -e .`). After that you can start developing and testing.

You also don't have to run all integration tests, and in fact I think we don't have an integration test for InfraValidator for Kubernetes, and manual test is required. When we're reviewing your PR, we would do the same manual testing as well.
