### ISSUE TITLE
GPU out of memory for StatisticsGen

### ISSUE THREAD

**Issue by RaphRzb** [tensorflow/tfx#3002]
Hi tensorflowers,

I have an issue with the StatisticsGen when I run it with either Airflow or interactive context: CUDA runs out of memory in airflow and crashes the pipeline, or goes to 90%-ish of the memory in interactive context and does not offload it after context.run(statistics_gen).

I have this issue for both my code and the taxi pipeline and have it on 2 different machines.

The only change I made to the taxi pipeline is the import of executor_spec, which is not in tfx.dsl anymore

**GPU:** GeForce GTX 1060 6GB (1st machine) or GeForce GTX 1080 8GB (2nd machine)
**OS:** Ubuntu 18.04 and same error on 20.04
**TFX:** 0.24 and same error on 0.25
**Beam:** 2.25
**Airflow:** 1.10.14
**CUDA:** 10.1
**Nvidia Driver:** 460
**CuDNN:** 7.6

Thank you!

**Comment by gowthamkpr** [comment]
@RaphRzb This should be fixed in the latest version of tfx. Can you please check and get back to us. Thank you!!
