### ISSUE TITLE
Pass in runtime args to Airflow orchestrator

### ISSUE THREAD

**Issue by EKami** [tensorflow/tfx#3010]
With TFX `LocalDagRunner` I can do something like this:

```
    dag = LocalDagRunner()
    dag.run(create_pipeline(
        pipeline_name="eval_pipeline",
        pipeline_root=cur_dir,
        beam_pipeline_args=_beam_pipeline_args,
        metadata_path=_metadata_path,
        my_custom_args=args
    ))
```
Where `my_custom_args` are new args that I provide to my `__main__` function each time I run the TFX program.
but with the airflow runner, doing the same:

```
    DAG = AirflowDagRunner(AirflowPipelineConfig(_airflow_config)).run(
        create_pipeline(
            pipeline_name="eval_pipeline",
            pipeline_root=cur_dir,
            beam_pipeline_args=_beam_pipeline_args,
            metadata_path=_metadata_path,
            my_custom_args=args
        )
    )
```

wouldn't work since `DAG` is supposed to be discovered when the scheduler is started, so I need to give these parameters [when the airflow task is run](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#passing-parameters-when-triggering-dags):
```
airflow dags trigger --conf '{"conf1": "value1"}' my_dag
```

So now my question is: How do you manage to have a consistent code between the two runners where `create_pipeline` can receive the configuration the same way?

Thanks!

**Comment by casassg** [comment]
Related to: https://github.com/tensorflow/tfx/issues/2545

**Comment by EKami** [comment]
By the time I've got a response I moved to MlFLow, thanks for the help tho but TFX is not for me
