### ISSUE TITLE
TFX ML Metadata storage to PostgreSQL

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/tfx#3030]
I wanted to store my metadata information of ML artifacts to PostgreSQL but I couldn't find any libraries that support MLMD for PostgreSQL. Is there any API's that could support to PostgreSQL other than MySQL/SQLite?

**Comment by arghyaganguly** [comment]
@cah-aswini-jalla , there is currently an open issue for MLMD support for PostgreSQL. Please refer the below link :-
https://github.com/google/ml-metadata/issues/26

Can we please close this issue here and track it in a single place. Let me know if you think otherwise. Thanks!
