### ISSUE TITLE
How to pass RuntimeParameter to custom python function component

### ISSUE THREAD

**Issue by Clee681** [tensorflow/tfx#3041]
Hello 👋 ,

I'm trying to create a simple custom python function component that accepts a RuntimeParameter and prints it out. I'm struggling to find the correct type that the custom function component should accept. The below code generates the following error:

```
invalid spec: spec.arguments.parameters[1].name: 'Date parameter' is invalid: Parameter/Artifact name must consist of alpha-numeric characters, '_' or '-' e.g. my_param_1, MY-PARAM-1
```

```python
date_param = data_types.RuntimeParameter(
    name="Date parameter",
    default="2019-01-01",
    ptype=Text
)

@component
def print_date(date: Parameter[str]):
    print(date)

def create_pipeline(name: Text, root: Text, date_arg: data_types.RuntimeParameter):
    components = [print_date(date=date_arg)]

    return pipeline.Pipeline(
        pipeline_name=name,
        pipeline_root=root,
        components=components
    )

def run():
    # ....
    kubeflow_dag_runner.KubeflowDagRunner(config=runner_config, pod_labels_to_attach=pod_labels).run(
        create_pipeline(
            name=config.PIPELINE_NAME,
            root=config.PIPELINE_ROOT,
            date_arg=date_param
        )
    )
```

Any help would be greatly appreciated!

**Comment by numerology** [comment]
Hi @Clee681 the error is complaining that the name of the parameter is illegal in k8s.

Can you try using a name like `date-parameter`? Thanks

**Comment by Clee681** [comment]
@numerology That was indeed the issue! Thanks for the speedy response 🙏 . Let me know if there's an opportunity to document this somewhere. Thanks again!

**Comment by zhitaoli** [comment]
@numerology should we add some validation on the name when registering of the parameter from SDK?

**Comment by singhniraj08** [comment]
@Clee681,

Since changing the name parameter to argo compliant name resolves your issue. Please let us know if this issue can be closed. Thank you!
