### ISSUE TITLE
Caching in tfx and kfp

### ISSUE THREAD

**Issue by johnPertoft** [tensorflow/tfx#3049]
I'm confused about caching when running a TFX pipeline on KFP. 

- I have KFP 1.0.4 deployed via GCP AI platform and I've been using both TFX 0.25 and 0.26 when trying this.
- I created my pipeline with `enable_cache=False`.
- I ran it once and each component runs as expected and produces the expected artifacts (only checked the artifact buckets and not the sql database).
- I ran it again with no change in inputs or parameters and it's now using cached results even though I disabled the cache. The following images show the logs for the second run where I would have expected them to run again.
- I repeated this for an entirely new deployment of KFP for both cases.

**With TFX 0.25**
![image](https://user-images.githubusercontent.com/5158472/104297911-aba4eb00-54c3-11eb-9552-61e7f153728a.png)

**With TFX 0.26**
![image](https://user-images.githubusercontent.com/5158472/104287504-d63c7700-54b6-11eb-9b50-509137ff89eb.png)

Questions:
- Why is the `enable_cache=False` not respected?
- [KFP documentation](https://www.kubeflow.org/docs/pipelines/caching/) mentions that its caching mechanisms should not be used for TFX pipelines. Why am I seeing a message about a cached step from KFP in the TFX 0.26 case rather than from the TFX component drivers?
- Can you enable/disable caching on a per component basis?
- Is it possible to get some logs for why a cached result was used / not used?
- Is there anyway to get TFX to also consider if the docker image has changed when determining if a cached result is invalidated?
    - I'm guessing no since it's determined by the driver which would run inside the (updated) container?
    - Would the custom container based component handle this differently?
- Is there a better place to ask these kind of questions?

**Comment by easadler** [comment]
@johnPertoft did you figure this out? I am running into this problem.

**Comment by johnPertoft** [comment]
@easadler I didn't actually, but I stopped using TFX for now. I closed the issue since it didn't generate any responses so I figured it due to my mistake somewhere but didn't have time to look further into it. I will reopen it!

**Comment by easadler** [comment]
@johnPertoft this is also a blocker for me. We will have to pivot towards vanilla kubeflow, which really isn't that bad to use. I will miss the interactive runner, but using the kfp is pretty easy. It would be nice to have kubeflow components for each of the tfx steps. Probably will happen eventually.

**Comment by lyschoening** [comment]
@johnPertoft Were you at least able to make use the cache, e.g. if you change the inputs to the training step? What I've observed is that the cache mechanism seems broken altogether since ~0.25.

**Comment by johnPertoft** [comment]
@lyschoening I didn't test this unfortunately.

**Comment by nmelche** [comment]
Did anyone figure this out? The issue also occurs with tfx==0.28.0

**Comment by abin-thomas-by** [comment]
One can enable/disable caching at component level by updating pipeline.yaml 

set `pipelines.kubeflow.org/max_cache_staleness` attribute to `P0D` in the component metadata.

`metadata:
      annotations:
        "pipelines.kubeflow.org/max_cache_staleness": P0D`

**Comment by axeltidemann** [comment]
Could you give an example for a TFX pipeline, @abin-thomas-by ? I don't see a pipeline.yaml anywhere, which makes me think you are describing a vanilla Kubeflow pipeline. Please correct me if I am wrong.

**Comment by abin-thomas-by** [comment]
Unzip the tar.gz file produced by `KubeflowDagRunner` for pipeline.yaml

**Comment by axeltidemann** [comment]
I'd like to do this in code, not by manually unzipping and editing the YAML file. Is that possible?

**Comment by ssoudan** [comment]
Something like this works for me:
```python
  def dont_cache_components():
    def _dont_cache(pod_op):
      pod_op.add_pod_annotation('pipelines.kubeflow.org/max_cache_staleness', 'P0D')
      return pod_op

    return _dont_cache

  # ... 
  pipeline_op_funcs = kubeflow_dag_runner.get_default_pipeline_operator_funcs()
  pipeline_op_funcs.append(dont_cache_components())
  # ...

  runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
    pipeline_operator_funcs=pipeline_op_funcs,
    kubeflow_metadata_config=metadata_config,
    tfx_image=tfx_image)
```

**Comment by muhammadtehseenSystemsltd** [comment]
I am facing the same issue on my TFX Pipeline in Kubeflow, disabling cache in TFX pipeline has not effect on Kubeflow.

**Comment by entrpn** [comment]
Same issue for me running Kubeflow v2 on VertexAI. Since this is an issue for me only during development/experimentation and training, I can get around it by adding an extra field to the training args.

For example, the cached component had:

```
  train_custom_config = {
    'environment': ENVIRONMENT,
    'no_forecast_steps': NO_FORECAST_STEPS,
    'iqr_bound': IQR_BOUND,
  }
```

I added a new field:

```
  train_custom_config = {
    'environment': ENVIRONMENT,
    'no_forecast_steps': NO_FORECAST_STEPS,
    'iqr_bound': IQR_BOUND,
    'test': 'force cache'
  }
```

And it forces the training to kick off again. :/

**Comment by gaikwadrahul8** [comment]
@johnPertoft 

Apologies for the delay and I found similar issue #[5303](https://github.com/kubeflow/pipelines/issues/5303) and in that @Bobgy provided some workaround so could you please check this [comment](https://github.com/kubeflow/pipelines/issues/5303#issuecomment-851904651) and also check these references with [Upgrading](https://www.kubeflow.org/docs/distributions/gke/pipelines/upgrade/) and [Installation Options](https://www.kubeflow.org/docs/components/pipelines/v1/installation/overview/#choosing-an-installation-option) and let us know is it resolving your issue ?

If issue still persists please let us know ?

Thank you!

**Comment by johnPertoft** [comment]
@gaikwadrahul8 Thanks for getting back! Unfortunately I'm no longer using the TFX ecosystem.

**Comment by gaikwadrahul8** [comment]
Hi, @johnPertoft 

Apologize for the delay and thank you for the confirmation, since this issue is not valid for you because you're not using the TFX ecosystem now so we're closing this issue, if above resolution does not work for you, please feel free to post your queries/comments or re-open this issue. Thank you
