### ISSUE TITLE
Installing custom dependencies on AI Platform Training Trainer

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#3056]
Is it possible to specify a set of custom dependencies to be installed to AI Platform Training jobs that are scheduled from the TFX Trainer?

Example: I want to install tensorflow-text into the job as I use it on my model. Is there an easy way to do so (that does not involve having to create a new docker image every time I want a dependency in the trainer worker)?

It may be totally doable at the moment, but I can't seem to find an easy documentation for this.

**Comment by tgaddy** [comment]
Hey @casassg, I've run into this as well. As far as I know if you need to add more dependencies then yes, you'll need to create a new docker image. Not really sure how one would be able to get around having create a new docker image if you're updating the dependencies. 

Would be nice to get some confirmation on this though!

**Comment by casassg** [comment]
My question also came as it seems AI Platform Training does allow for dependency injection (if you don't use custom docker images and instead use base runtime), which makes me wonder if we can just install tfx as a dep and just use it bare instead of using a docker image. 

Given the only requirement from TFX is to have the TFX wheel installed, then TFX wrapper can pass the wheel for AI Platform Training and it should work? But wondering what the team has thought on this

**Comment by casassg** [comment]
- https://cloud.google.com/ai-platform/training/docs/packaging-trainer#adding_custom_dependencies

Another pro:
- Easier customizable environment. User can add custom wheels/sdists to workers as needed. 

This in my opinion is the main sell point. It's quite common to have to install tensorflow-text/tensorflow-addons onto the workers. We have a way to include those on Dataflow via custom packages, but in TFX AIP integration we need to generate new images if we want to have those dependencies available to the worker.

Another option is to parse an extra option with packages in the TFX entrypoint and install them on the worker before calling the Executor.

**Comment by singhniraj08** [comment]
@casassg,

Please refer to [Create a custom container image for training](https://cloud.google.com/vertex-ai/docs/training/create-custom-container) and let us know if this doc is useful. Thank you.
