### ISSUE TITLE
cannot import name 'csv_input'

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tfx#3078]
I followed this [tutorial (tfx - guide - examplegen)](https://www.tensorflow.org/tfx/guide/examplegen), but I cannot import `csv_input` from `tfx.utils.dsl_utils`.

To reproduce: [colab link](https://colab.research.google.com/drive/1v3lunZ213eoconNf_iY0OZghPphWT3Cy?usp=sharing) (`tfx==0.26.0`)

---

I found another [tutorial (tfx - tutorials - TFX Keras Component Tutorial)](https://tensorflow.google.cn/tfx/tutorials/tfx/components_keras) that explains proper usage. [example gen tutorial](https://www.tensorflow.org/tfx/guide/examplegen) should be fixed.

**Comment by arghyaganguly** [comment]
@jeongukjae , looking at : https://github.com/tensorflow/tfx/blob/v0.26.0/tfx/utils/dsl_utils.py

and comparing with earlier versions, it seems that csv_input has been depreciated in tfx==0.26.0.
try with :-

import os
import tfx
from tfx.utils.dsl_utils import external_input
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
_data_root = "address to data directory" #address till the directory where csv file is present
_data_filepath = os.path.join(_data_root,"data.csv") #data.csv being the csv file
example_gen = CsvExampleGen(input=external_input(_data_filepath))

Please confirm if this works for you.
Thanks.

**Comment by jeongukjae** [comment]
Thanks, @arghyaganguly. I checked CsvExampleGen works with external_input but not pointing directory, I passed filename (`external_input("PATH_TO_DIRECTORY")`). But external_input is also deprecated now.

Is there any best practice to ingest CSV files to TF Records without csv_input and external_input?

**Comment by rmothukuru** [comment]
@jeongukjae,
As per the [Arguments Documentation](https://tensorflow.google.cn/tfx/api_docs/python/tfx/components/CsvExampleGen?hl=en#args), the argument, **`input`** is deprecated and we should use **`input_base`**, instead. 

Working code is shown below:

```python
import os
import tfx
from tfx.utils.dsl_utils import external_input
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
import tempfile
import urllib

_data_root = tempfile.mkdtemp(prefix='tfx-data')
DATA_PATH = 'https://raw.githubusercontent.com/tensorflow/tfx/master/tfx/examples/chicago_taxi_pipeline/data/simple/data.csv'
_data_filepath = os.path.join(_data_root, "data.csv")
urllib.request.urlretrieve(DATA_PATH, _data_filepath)

example_gen = CsvExampleGen(input_base=(_data_filepath))
```

Please find the [Github Gist](https://colab.research.google.com/gist/rmothukuru/0829cd033d4cf3575d0c95cfbdf05145/tfx-bug.ipynb#scrollTo=fVLzxK0TvkYh) as well.

**Comment by jeongukjae** [comment]
@rmothukuru  Sorry for the late reply. Your comment was helpful.

But the [example gen tutorial docs](https://www.tensorflow.org/tfx/guide/examplegen#how_to_use_an_examplegen_component) is still not fixed for now. I found pull request #3087 can fix this issue.

**Comment by pindinagesh** [comment]
@jeongukjae 

Closing the issue as the [PR](https://github.com/tensorflow/tfx/pull/3087) is already merged which fixes the issue. Thanks
