### ISSUE TITLE
Adding multiple label outputs to tf estimator

### ISSUE THREAD

**Issue by kenviku** [tensorflow/tfx#310]
Can someone guide me to an example of using multiple outputs/labels in the tf estimator for tfx? I found some examples online for tensorflow but I am finding it hard to identify the changes required in the tfx setup. I am using the taxi pipeline as example and looking at `trainer_fn` and `_build_estimator`.

**Comment by ruoyu90** [comment]
The [multi_head](https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/multi_head) API seems to be the one you're looking for. You will also need to modify the input functions to emit multiple labels you'll use in the multi-head estimator.

**Comment by kenviku** [comment]
Thank you! Although the snippet provided is pretty clear, curious if there is any tfx example available?

**Comment by ruoyu90** [comment]
Chicago taxi is our current example to showcase TFX and we're working on more examples. However there is an [example multi-head trainer](https://github.com/tensorflow/model-analysis/blob/master/tensorflow_model_analysis/eval_saved_model/example_trainers/multi_head.py) in TFMA repository and feel free to take a look.

**Comment by ruoyu90** [comment]
Closing this issue for now. Feel free to reopen if you have further question :)
