### ISSUE TITLE
mock requirement for apache-beam 2.13.0

### ISSUE THREAD

**Issue by saifrahmed** [tensorflow/tfx#313]
Per the readme, I installed the following on Python 3.5:
```
tensorflow==1.13.1
tfx==0.13

```
Unfortunately there is one library which doesnt meet the apache-beam 2.13.0 requirement for mock<3.0.0

I get the following warning:

> apache-beam 2.13.0 has requirement mock<3.0.0,>=1.0.1, but you'll have mock 3.0.5 which is incompatible.

**Comment by zhitaoli** [comment]
These issues often comes from different python packages bringing conflict dependencies. Can you try to force downgrade 'mock==2.0.0' in your virtualenv before installing, then try again?

If that does not work, can you report an issue with Apache Beam project by following **https://beam.apache.org/contribute/#troubleshooting**? Mock 3.0 was only released early this year so maybe they haven't caught up yet.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
