### ISSUE TITLE
Use custom python functions in transform

### ISSUE THREAD

**Issue by apurva-sharma** [tensorflow/tfx#3178]
Opening here since it probably pertains to both transform and serving.

**System information** - TFX Version (you are using): 0.24
Environment in which you plan to use this: Linux

**Describe the feature and the current behavior/state.**
There are enough uses cases where we would like to use custom python functions during feature transformation - it is not possible to express all transformation using just library provided methods. Examples include features that incorporate domain knowledge of for example using a custom scaling function.

The closest thing to using these seems to be 

https://www.tensorflow.org/tfx/transform/api_docs/python/tft/apply_pyfunc
However as documented, this is not supported at serving.
Are there any pointers on what the recommended way of handling these use cases?
Is there a way to ensure these can be available at serving/ is it on the roadmap?

**Will this change the current API? How?** NA

**Who will benefit with this feature?**
Lots of developers would benefit with something like this. It's one of the main reasons we can't onboard to tfx.

**Do you have a workaround or are completely blocked by this?** :
No workarounds seem to exist.

**Comment by arghyaganguly** [comment]
@apurva-sharma,for serving related issues , please raise in :- https://github.com/tensorflow/serving/issues
This is to help with the  internal processes for triaging issues in tensorflow.
Thanks.

**Comment by zoyahav** [comment]
The pyfunc limitation is a limitation of the inference environment, if the inference environment has a python runtime then it can be used.

You mentioned a custom scaling function as a usecase, what's keeping you from writing this custom scaling logic using existing TF ops?

**Comment by apurva-sharma** [comment]
@zoyahav, @arghyaganguly  thanks for getting back.
Is it possible to make python runtime available for a tfx serving instance?
If so, are there any examples that illustrate this?
Here is an example of feature generation that I can't imagine working with native tfx transforms.

Imagine raw features which look like:
sports_links_clicked_2021-02-02 : 3
sports_links_clicked_2021-01-15 : 2
sports_links_clicked_2020-11-10 : 4

And my feature that I want to derive is:
sports_links_clicked_past_30_days
Then assuming a feature generation date of 2021-02-02, the computed feature value should be 5 (discarding the feature for 2020-11-10).
I don't quite like the idea of doing this at at TF.record making time since the same code then has to be duplicated at serving layer (which could be Java and not python) and the whole point is to encode this in the graph.
@zoyahav - what would be the recommended way of handling this use case?

**Comment by zoyahav** [comment]
@apurva-sharma I think this should be doable with existing machinery.

To better understand your example above:

What are the input features defined?
do you have 2 different feature, one is of type string that has the value "sports_links_clicked_2021-02-02", etc. and another which is an integer feature with the value?
Or are there actually different feature per date?

Generally speaking, it sounds like the above can be achieved using something similar to `tft.scale_to_z_score_per_key`, or `tft.ptransform_analyzer` if we want completely custom logic.

**Comment by apurva-sharma** [comment]
In this example, there's a different feature per date. 
How would this be achieved?

**Comment by zoyahav** [comment]
One more question before I can propose an option -
Would the value of sports_links_clicked_past_30_days be computed separately per instance/example, or would you need it to be somehow aggregated throughout the input instances? (i.e sum the values of the past 30 days)
It sounds like no aggregation is needed.


Re. python/pyfunc in the serving environment, I would really recommend against going down this path, in fact I actually don't think it's possible since it doesn't even get serialized as part of the resulting TF SavedModel.

**Comment by apurva-sharma** [comment]
@zoyahav 
It would be computed per instance/example.

**Comment by apurva-sharma** [comment]
@zoyahav were you able to think of how to model these requirements via native tfx transformations?

**Comment by zoyahav** [comment]
Unfortunately I don't think there are TF ops for handling dates/timestamps so I think this would be pretty challenging :/

To verify, this 30 day logic would have to happen during inference as well?

**Comment by apurva-sharma** [comment]
Yes, we would need to do this at inference time too. So looks like my options may be:
1. move the feature transformation logic outside of tfx pipeline to the TF.record generation stage
2. Alternatively, the documentation seems to suggest that the python functions are actually serialized in a pickled format when used with pyfunc eval- the issue seems to be a missing python environment on the c++ serving env, but your comments seem to indicate that they are not serialized at all. Can you confirm if this is not a path that can be pursued- where we try and make python available and invoke it to evaluate these functions? Alternatively Could we plug custom cpp implementations of these methods in a custom class?

**Comment by jashshah** [comment]
Can it thus be said that one cannot use tf.py_function(from TF 2.x) inside preprocessing_fn when using TFX Transform?

I am facing a related issue as mentioned in the StackOverflow question over [here](https://stackoverflow.com/questions/67887523/using-tf-py-function-in-preprocessing-fn-with-dataflow-results-in-valueerror-ca).

**Comment by singhniraj08** [comment]
@apurva-sharma,

You need to use [tft.apply_pyfunc](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/apply_pyfunc) to apply the custom functions to the input features. This function is for using inside a preprocessing_fn. It is a wrapper around `tf.py_func`.

The functions added this way can run in Transform, and during training but TensorFlow Serving will not be able to serve this graph. For saving the graph or using it at the serving stage, there should be no Pythonic operation in the preprocessing_fn function. All the Pythonic methods have to be replaced by TensorFlow tf_compat_v1 methods.

Thank you.
