### ISSUE TITLE
Imposing transform on the prediction in tf_serving

### ISSUE THREAD

**Issue by mshahriarish** [tensorflow/tfx#3206]
Hello,
I have an issue when producing the tf serving model in TFX. Let's say that I have a vector of features "x" and I have a vector of outputs "y". It is a regression model. So, I would like to rescale both my features and my output to [0,1]. Then, I train my model and I save a serving model for later predictions. However, in the evaluation stage, I have the two following steps:

read features--> transform feature --> predict model --> transform the output to the real scale

The first three steps are clear. However, is it a way to wrap the final step also to the serving model? If so, how would the signature look like? The following did not work and I got an assertion error:

def _get_serve_tf_examples_fn(model, tf_transform_output):
  """Returns a function that parses a serialized tf.Example and applies TFT."""

  model.tft_layer = tf_transform_output.transform_features_layer()

  @tf.function
  def serve_tf_examples_fn(serialized_tf_examples):
    """Returns the output to be used in the serving signature."""
    feature_spec = tf_transform_output.raw_feature_spec()
    feature_spec.pop(_Y_KEY)
    parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)
    transformed_features = model.tft_layer(parsed_features)
    output=model(transformed_features)
    output={_Y_KEY: output }
    output=model.tft_layer(output)

    return output

  return serve_tf_examples_fn

Thank you in advance.
Regards

**Comment by mshahriarish** [comment]
Hi,
I am using :
TensorFlow version: 2.3.2
TFX version: 0.26.1

For tft, it is the one that comes with TFX. I guess it is 0.27.0.

Thanks
Regards

**Comment by mshahriarish** [comment]
Hi, sorry my tft is 0.26.0
Regards

**Comment by ConverJens** [comment]
@mshahriarish I have done something similar, although not exactly the same. I have an auto-encoder model where I added the operation of computing the reconstruction error, which is based on the model prediction, in the actual model. My approach was to built my original model, create an extra auxiliary model where I added the extra op as keras layers and then trained my original model. In the end I just export the auxiliary model.
> Hello,
> I have an issue when producing the tf serving model in TFX. Let's say that I have a vector of features "x" and I have a vector of outputs "y". It is a regression model. So, I would like to rescale both my features and my output to [0,1]. Then, I train my model and I save a serving model for later predictions. However, in the evaluation stage, I have the two following steps:
> 
> read features--> transform feature --> predict model --> transform the output to the real scale
> 
> The first three steps are clear. However, is it a way to wrap the final step also to the serving model? If so, how would the signature look like? The following did not work and I got an assertion error:
> 
> def _get_serve_tf_examples_fn(model, tf_transform_output):
> """Returns a function that parses a serialized tf.Example and applies TFT."""
> 
> model.tft_layer = tf_transform_output.transform_features_layer()
> 
> @tf.function
> def serve_tf_examples_fn(serialized_tf_examples):
> """Returns the output to be used in the serving signature."""
> feature_spec = tf_transform_output.raw_feature_spec()
> feature_spec.pop(_Y_KEY)
> parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)
> transformed_features = model.tft_layer(parsed_features)
> output=model(transformed_features)
> output={_Y_KEY: output }
> output=model.tft_layer(output)

Note that what you have written here will not have the effect that you wanted. Here you are applying a transform layer (scale 0 to 1), set an output and then apply a transform layer again, applying the scaling transformation again.

What you need is an inverse of the transform layer and I'm not sure if that exists. Maybe looking into the optional pre/post-statistics and define the transformations yourself from the mean and std of your data.


> ```
> return output
> ```
> 
> return serve_tf_examples_fn
> 
> Thank you in advance.
> Regards



> Hello,
> I have an issue when producing the tf serving model in TFX. Let's say that I have a vector of features "x" and I have a vector of outputs "y". It is a regression model. So, I would like to rescale both my features and my output to [0,1]. Then, I train my model and I save a serving model for later predictions. However, in the evaluation stage, I have the two following steps:
> 
> read features--> transform feature --> predict model --> transform the output to the real scale
> 
> The first three steps are clear. However, is it a way to wrap the final step also to the serving model? If so, how would the signature look like? The following did not work and I got an assertion error:
> 
> def _get_serve_tf_examples_fn(model, tf_transform_output):
> """Returns a function that parses a serialized tf.Example and applies TFT."""
> 
> model.tft_layer = tf_transform_output.transform_features_layer()
> 
> @tf.function
> def serve_tf_examples_fn(serialized_tf_examples):
> """Returns the output to be used in the serving signature."""
> feature_spec = tf_transform_output.raw_feature_spec()
> feature_spec.pop(_Y_KEY)
> parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)
> transformed_features = model.tft_layer(parsed_features)
> output=model(transformed_features)
> output={_Y_KEY: output }
> output=model.tft_layer(output)
> 
> ```
> return output
> ```
> 
> return serve_tf_examples_fn
> 
> Thank you in advance.
> Regards

**Comment by mshahriarish** [comment]
@ConverJens  Thank you for your response. Regarding my mistake, you are definitely right. Thank you for pointing it out. Regarding your suggestion, I am also thinking the same and started to implement it yesterday. I think that is a good idea to proceed. Thanks again.

Best regards,

**Comment by pindinagesh** [comment]
@mshahriarish 

Could you please move this to closed status as it is resolved. Thanks
