### ISSUE TITLE
Trainer component crashed in execution on GCP due to missing `tfx:0.25.0-rc2` image

### ISSUE THREAD

**Issue by rafaelsf80** [tensorflow/tfx#3214]
Hi, looks like there is a similar error as #657 when running the Chicago taxi pipeline with `TFX 0.25.0-rc2` on GCP:
The error is: 
`
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://ml.googleapis.com/v1/projects/wXXXXXXX/jobs?alt=json returned "Field: master_config.image_uri Error: Failed to read the container uri [gcr.io/tfx-oss-public/tfx:0.25.0-rc2]. Please make sure that the image exists". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'master_config.image_uri', 'description': 'Failed to read the container uri [gcr.io/tfx-oss-public/tfx:0.25.0-rc2]. Please make sure that the image exists'}]}]">
`

The image `gcr.io/tfx-oss-public/tfx:0.25.0-rc2`does not exist in the [public image list]((https://console.cloud.google.com/gcr/images/tfx-oss-public/GLOBAL/tfx?tag=0.25.0&gcrImageListsize=30).  However,  `gcr.io/tfx-oss-public/tfx:0.25.0rc2` (without the -) is available

**Comment by zhitaoli** [comment]
Thanks for the report, I think we need to apply the same trick in https://github.com/tensorflow/tfx/blob/master/tfx/utils/version_utils.py#L31 to the cloud trailer runner, due to the gap from image version tag vs python version for RC case only.
