### ISSUE TITLE
AI Platform training job fails if you specify docker image for workers

### ISSUE THREAD

**Issue by junbopark** [tensorflow/tfx#3232]
**System information** 
- Have I specified the code to reproduce the issue (Yes/No): Yes 
- Environment in which the code is executed (e.g., Local
(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): Kubeflow
- TensorFlow version (you are using): 2.3.1 
- TFX Version: 2.6.1
- Python version: 3.6

**Describe the current behavior**
Training jobs on AI Platform will fail if you specify the docker image for workers (even if it's the same docker image as the master).  

**Describe the expected behavior**
Training jobs should not fail when you specify the docker image for workers.

**Standalone code to reproduce the issue** 
Add following options to the `ai_platform_training_args` option in `tfx/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_gcp.py` example file:
```
'masterConfig':{'imageUri': "gcr.io/tfx-oss-public/tfx:0.26.1"},
'workerConfig':{'imageUri': "gcr.io/tfx-oss-public/tfx:0.26.1"},
```
Create the pipeline with the `--distributed_training` flag, and the pipeline will fail during training.

**Name of your Organization (Optional)**
OpenX

**Other info / logs** 
We think the issue is related to entry_point of TFX docker images which changed recently. When we examine the Training Input in AI Platform training job, a "containerCommand" option is added to masterConfig, but not to workerConfig. If we don't specify workerConfig explicitly, it will just use the custom docker image used for the master node and work without error.

When the job fails it doesn't generate any helpful error message, which is a problem. The only message we get is "2021/02/10 02:07:19 No id provided." It is the same message that you get when you manually run the TFX docker image (`docker run -it ...`).

**Comment by revathijay** [comment]
is there any update on this issue ? i am getting the same error as well

**Comment by singhniraj08** [comment]
@junbopark,

Can you try using custom containers as workers nodes and ensure the entrypoint calls into TFX's run_executor script (tfx/scripts/run_executor.py) as shown [here](https://cloud.google.com/ai-platform/training/docs/using-containers#create_a_custom_container). Also, Please try using [Penguin TFX pipeline example](https://github.com/tensorflow/tfx/tree/master/tfx/examples/penguin) . Thank you!
