### ISSUE TITLE
InfraValidator fails in KubeFlow

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#3257]
**System information** 
- Have I specified the code to reproduce the issue: No, but standard TFX pipeline with InfraValidator in KubeFlow should reproduce this issue. 
- Environment in which the code is executed : On-prem KubeFlow cluster. KF v1.1.0. k8s 1.19 
- TensorFlowversion (you are using): 2.4.0 
- TFX Version: 0.27.0 
- Python version: 3.7

**Describe the current behavior**
InfraValidator seems to load and query model successfully but fails when cleaning up resources.

**Describe the expected behavior**
Successfully cleaning up resources.

**Standalone code to reproduce the issue** Providing a bare minimum test case or
step(s) to reproduce the problem will greatly help us to debug the issue. If
possible, please share a link to Colab/Jupyter/any notebook.
No, but standard TFX pipeline with InfraValidator in KubeFlow should reproduce this issue.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

InfraValidator fails when deleting the tf serving pod. It fails with an error from istio but noteworthy is that the pod name it tries to delete is None. Logs from failure:

```
INFO:absl:Starting infra validation (attempt 1/5).
INFO:absl:Starting KubernetesRunner(image: docker.vby.svenskaspel.se:8181/tensorflow/serving:2.3.0, pod_name: None).
INFO:absl:Stopping KubernetesRunner(image: docker.vby.svenskaspel.se:8181/tensorflow/serving:2.3.0, pod_name: None).
INFO:absl:Deleting Pod (name=None)
WARNING:absl:Error occurred while deleting the Pod. Please run the following command to manually clean it up:
kubectl delete pod --namespace admin None
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/infra_validator/executor.py", line 356, in _ValidateOnce
    runner.Start()
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/infra_validator/model_server_runners/kubernetes_runner.py", line 140, in Start
    body=self._BuildPodManifest())
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6115, in create_namespaced_pod
    (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6206, in create_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 344, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 178, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/api_client.py", line 387, in request
    body=body)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f16c63f3-113e-4eba-b50b-5f56f81c7599', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 17 Feb 2021 13:30:17 GMT', 'Content-Length': '457'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"sidecar-injector.istio.io\": Post \"
https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s
\": EOF","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"sidecar-injector.istio.io\": Post \"https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s\": EOF"}]},"code":500}
https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s
\": EOF"}]},"code":500}


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/infra_validator/model_server_runners/kubernetes_runner.py", line 178, in Stop
    self._DeleteModelServerPod()
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/utils/retry.py", line 260, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tfx/components/infra_validator/model_server_runners/kubernetes_runner.py", line 195, in _DeleteModelServerPod
    namespace=self._namespace)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 9788, in delete_namespaced_pod
    (data) = self.delete_namespaced_pod_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 9830, in delete_namespaced_pod_with_http_info
    raise ValueError("Missing the required parameter `name` when calling `delete_namespaced_pod`")
ValueError: Missing the required parameter `name` when calling `delete_namespaced_pod`
ERROR:absl:Infra validation (attempt 1/5) failed.
```

This then repeats five times. Weird is that even though errors are thrown, InfraValidator component still does not fail itself.

**Comment by chongkong** [comment]
Hi ConverJens. It seems like the root cause of the issue is that it fails to *create* the namespaced pod in the first place. Cleanup failure message is deceptive since the pod has never been created, and it IS a bug that cleanup process does not handle `name=None` case correctly. Will fix this.

Some other points:
* Even if the DeleteNamedspacedPod call fails, the validation Pod has an owner reference to the component execution Pod, which means it will be deleted anyway if the infra validator execution is finished. Calling DeleteNamespacedPod is the InfraValidator's best effort to cleanup the resource as soon as possible.
* Although confusing, when infra validation has not passed, InfraValidator should still be executed *successfully* with the validation result as "NOT BLESSED", which you can find at the output InfraBlessing artifact (it's custom property `blessed` is set to zero). This is currently working as intended, and it is still TFX's open question about how to clearly distinguish "successful result" from "successful execution". Currently "execution failure" means the component has run into an unexpected situation and raised an error; infra validation not passed is simply one of the valid result on the other hand.

**Comment by ConverJens** [comment]
Hi @chongkong 
> Hi ConverJens. It seems like the root cause of the issue is that it fails to _create_ the namespaced pod in the first place. Cleanup failure message is deceptive since the pod has never been created, and it IS a bug that cleanup process does not handle `name=None` case correctly. Will fix this.
>
> 
> Some other points:
> 
> * Even if the DeleteNamedspacedPod call fails, the validation Pod has an owner reference to the component execution Pod, which means it will be deleted anyway if the infra validator execution is finished. Calling DeleteNamespacedPod is the InfraValidator's best effort to cleanup the resource as soon as possible.
Great, so that is not an actual issue then.
> * Although confusing, when infra validation has not passed, InfraValidator should still be executed _successfully_ with the validation result as "NOT BLESSED", which you can find at the output InfraBlessing artifact (it's custom property `blessed` is set to zero). This is currently working as intended, and it is still TFX's open question about how to clearly distinguish "successful result" from "successful execution". Currently "execution failure" means the component has run into an unexpected situation and raised an error; infra validation not passed is simply one of the valid result on the other hand.
I figured as much and I understand why it's still an open question.

What about the issue with the tf serving pod not being created, how do we proceed with this? Can I supply anything else to help troubleshoot?

**Comment by chongkong** [comment]
All I can see from the log above is that the CreateNamespacedPod API call has failed with 500 Internal Error, so TFX is working as intended and probably nothing TFX can help with it 😢. Maybe you can dig more into the istio log.

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"sidecar-injector.istio.io\": Post \"
https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s
\": EOF","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"sidecar-injector.istio.io\": Post \"https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s\": EOF"}]},"code":500}
https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s
\": EOF"}]},"code":500}
```

**Comment by ConverJens** [comment]
@chongkong I think you're right. I will try to dig into the logs and probably post an issue on KubeFlow to see if anyone there has any pointers.

Thanks for the help!

**Comment by ConverJens** [comment]
@chongkong I finally managed to solve this. The issue was that the TF serving pod spawned by IV did not have the `sidecar.istio.io/inject=false` which is required for it to run in KubeFlow.

The solution is to allow a user to specify annotations for the serving pod that IV spawns. 

I can open a PR for this but I would like to discuss how it should be structured before I do so. My proposition would be to extend the KubernetesConfig proto to allow both annotations and extra env vars. The latter is needed when using a storage backend that needs env vars, most notably S3.

Please let me know how you would like to proceed.

**Comment by chongkong** [comment]
Sounds good to me. Maybe we can group pod overriding specs into a single proto message. FYI once you modify the infra_validator.proto file, you can run `python setup.py gen_proto` command to generate updated proto stubs (tfx/proto/infra_validator_pb.py).

**Comment by chongkong** [comment]
Thanks will take a look. Let's continue discussion from the PR.

**Comment by pindinagesh** [comment]
Hi @ConverJens 

Could you please verify this [PR](https://github.com/tensorflow/tfx/pull/3580) and let us know if this resolves your issue. Thanks!

**Comment by ConverJens** [comment]
@pindinagesh That is my submitted PR and indeed it works now. See this issue for others that had similar issue that was solved by this: https://github.com/tensorflow/tfx/issues/3893.
