### ISSUE TITLE
Move tensorflow_cloud to examples dependencies

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#3262]
TFX currently depends on tensorflow_cloud. Looking at the codebase, it doesn't seem to use it in its codebase. 

This creates a burden since tensorflow_cloud >=0.10.0 [depends on tensorboard<=2.3](https://github.com/tensorflow/cloud/blob/0.1.13/src/python/dependencies.py#L26) and several other transitive packages which complicates 3rdparty dep management.

Any chance we can get it moved to `[examples]` or is there a reason to keep it in the main dependency tree?

**Comment by arghyaganguly** [comment]
@casassg , found this [link](https://github.com/tensorflow/docs-l10n/blob/3c042ce8b43e4bde095385443a059a977c806f92/site/en-snapshot/tfx/guide/tuner.md) which documents the usage of tensorflow_cloud for Tuner component in google cloud ai platform.

**Comment by 1025KB** [comment]
> TFX currently depends on tensorflow_cloud. Looking at the codebase, it doesn't seem to use it in its codebase.
> 
> This creates a burden since tensorflow_cloud >=0.10.0 [depends on tensorboard<=2.3](https://github.com/tensorflow/cloud/blob/0.1.13/src/python/dependencies.py#L26) and several other transitive packages which complicates 3rdparty dep management.

you mean tensorboard >=2.3?
> 
> Any chance we can get it moved to `[examples]` or is there a reason to keep it in the main dependency tree?

**Comment by casassg** [comment]
Yup. Sorry, miswrote the comparison operator

**Comment by 1025KB** [comment]
I see, I confirmed with tensorflow-cloud team, they mention it can be a soft dependency, does that work for your case?

**Comment by casassg** [comment]
When you say soft dependency you mean tensorboard?

It would work. Tbh, we dont use much tensorflow-cloud yet, so its not super blocking as we can just leverage pinning 0.1.0 which does not depend on tensorboard.

**Comment by arghyaganguly** [comment]
@casassg , can we close this?

**Comment by casassg** [comment]
Sure
