### ISSUE TITLE
io_utils.write_string_file does not flush contents

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/tfx#3265]
This is not a contribution.

**System information**
TensorFlow version: 2.4.1 - TFX Version: 0.27.0 - Python version: 3.7

**Describe the current behavior**

`io_utils.write_string_file` currently opens a file produced by the filesystem abstraction, and writes some text to it, however the file is not closed. This causes an issue with the tensorflow filesystem because that data is never flushed to the backing filesystem.

```python
from tfx.utils import io_utils
dest = "some path which resolves to tensorflow filesystem, for example"
io_utils.write_string_file(dest, 'some content')
# now check dest, see it is not present
```

This pattern of opening and writing but not closing (or equivalently using as a context manager)  is repeated in a number of other places throughout the tfx code, eg. in the kubeflow_v2_dag_runner, kubeflow_v2_run_executor, value_artifact etc.

As far as I can tell this is a bug, because the [tensorflow docs](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile) state that the GFile instance should be closed for the data to be flushed.

**Describe the expected behavior**

Files opened with `fileio.open` and written to should be closed to ensure the data is flushed.

**Comment by 1025KB** [comment]
Thanks! will fix!

**Comment by 1025KB** [comment]
Fixed
