### ISSUE TITLE
Kubeflow support for export_to_pipeline 🍩

### ISSUE THREAD

**Issue by SaschaHeyer** [tensorflow/tfx#3274]
**System information** - TFX Version (you are using): - Environment in which you
plan to use the feature (e.g., Local (Linux/MacOS/Windows), Interactive
Notebook, Google Cloud, etc..): - Are you willing to contribute it (Yes/No):
Notebook / Colab
Yes

**Describe the feature and the current behavior/state.**
Support for Kubeflow when using `export_to_pipeline`
https://www.tensorflow.org/tfx/api_docs/python/tfx/orchestration/experimental/interactive/interactive_context/InteractiveContext#export_to_pipeline. 
Only beam, airflow are supported at the moment. 

From the proposal, I can see there was at least planned to support this
https://github.com/tensorflow/community/blob/master/rfcs/20190815-tfx-notebook.md

**Will this change the current API? How?**
/

**Who will benefit with this feature?**
All ML folks who are working with notebooks on a daily basis

**Do you have a workaround or are completely blocked by this?** :
/

**Name of your Organization (Optional)**
/

**Any Other info.**
/

**Comment by 1025KB** [comment]
We have [templates](https://github.com/tensorflow/tfx/blob/master/tfx/experimental/templates/penguin/README.md#content-of-the-template) for Kubeflow, the export_to_pipeline is experimental and currently there is not plan to move forward with that direction.

**Comment by arghyaganguly** [comment]
@SaschaHeyer , please confirm whether this can be closed based on previous comment from @1025KB.

**Comment by SaschaHeyer** [comment]
Hi @1025KB 
thanks a lot for your feedback. 
I am aware of templates but they add additional overhead when working with notebooks. 

Sad to see export_to_pipeline it not to planned to develop further, it was such a nice and well-thought feature. 

Closed this ticket. 

Thank you for your responses

**Comment by charlesccychen** [comment]
CC: @zhitaoli @rcrowe-google
