### ISSUE TITLE
components_keras.ipynb has an error in a code block using pusher

### ISSUE THREAD

**Issue by Shunpoco** [tensorflow/tfx#3275]
Hi there, I found an error in [components_keras.ipynb](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb).

**System information**
- Have I specified the code to reproduce the issue
(Yes/No): Yes
- Environment in which the code is executed (e.g., Local
(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): Interactive Notebook (Google Colab)
- TensorFlow version (you are using): 2.4.1 
- TFX Version: 0.27.0
- Python version: 3.6.9

**Describe the current behavior**
I ran the last part of code blocks in [components_keras.ipynb](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb) as below.
```
push_uri = pusher.outputs.model_push.get()[0].uri
model = tf.saved_model.load(push_uri)

for item in model.signatures.items():
  pp.pprint(item)
```

But I had an error like this:
```python
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tfx/types/node_common.py in __getattr__(self, key)
     53     try:
---> 54       return self._data[key]
     55     except KeyError:

KeyError: 'model_push'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
1 frames
/usr/local/lib/python3.6/dist-packages/tfx/types/node_common.py in __getattr__(self, key)
     54       return self._data[key]
     55     except KeyError:
---> 56       raise AttributeError
     57 
     58   def __repr__(self):

AttributeError: 
```

**Describe the expected behavior**
We can store the pusher's URI to `push_uri`, then load the saved model to `model`. 

**Standalone code to reproduce the issue** 
Run until the last part of `components_keras.ipynb` on [Colab](https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb)

**Name of your Organization (Optional)**

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Shunpoco** [comment]
In #3169 , the key of output_dict was changed from `model_push ` to `pushed_model`, so we should also change the code block in the notebook to use `pushed_model` instead of using `model_push`.

Can I fix this bug?

**Comment by arghyaganguly** [comment]
@Shunpoco , thanks for reporting this.I was able to reproduce the error and using pushed_model instead of  model_push resulted in no error.
