### ISSUE TITLE
Broken link in Transform Component docs

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tfx#3299]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/api_docs/python/tfx/components/Transform#providing_a_preprocessing_function

`user-supplied code` link is pointing to `https://www.tensorflow.org/tfx/api_docs/python/tfx/components/(https:/github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py)`.

### Clear description:

https://github.com/tensorflow/tfx/blob/4cb3bcbea1b5ccd16b5360cf11a95704129e2a7f/tfx/components/transform/component.py#L48

This line should be 

```text
  code](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py)
```

**Comment by arghyaganguly** [comment]
@jeongukjae , thanks for reporting this issue.A PR has been raised to correct this documentation. Will close this when the PR gets merged.

**Comment by digitalsimboja** [comment]
Hello @arghyaganguly is the issue still `open`? Could I fix this or the PR is still active?

**Comment by arghyaganguly** [comment]
@digitalsimboja , the pr is still active.Thanks.

**Comment by arghyaganguly** [comment]
Closing this as the fix is now available.Thanks.
