### ISSUE TITLE
TFX Transform in Jupyter producing missing files and failing

### ISSUE THREAD

**Issue by Kadri-Saal** [tensorflow/tfx#3306]
**System information** : 
- Windows OS
- Full admin rights for making/deleting/editing files and folders
- Conda env through Anaconda
- Python 3.7
- Jupyter Notebook, running interactively
- TensorFlow version: 2.4.1
- TFX version: 0.27.0
- Running the TFX tutorial ([components_keras.ipynb](https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb)) on local machine produces the error shown below, but runs correctly within Google Colab

**The Issue:**

The TFX components are run interactively, and ExampleGen, StatisticsGen, SchemaGen, and ExampleValidator all work properly.

Then Transform fails producing the following (full stack trace is attached):
`RuntimeError: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\k.mufti\\Desktop\\tfx1\\Transform\\transform_graph\\10\\.temp_path\\tftransform_tmp\\beam-temp-vocab_compute_and_apply_vocabulary_1_vocabulary-e7e34b0678f011eb8789fc7774edcabe\\5e8b473f-f071-47a7-9aa8-b419f3a6d5ff.vocab_compute_and_apply_vocabulary_1_vocabulary' [while running 'Analyze/VocabularyOrderAndWrite[compute_and_apply_vocabulary_1/vocabulary]/WriteToText/Write/WriteImpl/WriteBundles']`

[TFX_Transform_StackTrace.txt](https://github.com/tensorflow/tfx/files/6054427/TFX_Transform_StackTrace.txt)

The Jupyter notebook used:

[components_keras_km.zip](https://github.com/tensorflow/tfx/files/6054997/components_keras_km.zip)

**Comment by arghyaganguly** [comment]
Duplicate of #2156(python3.6)

**Comment by Kadri-Saal** [comment]
> Duplicate of #2156(python3.6)

Yes I realized it could practically be a duplicate, but #2156 was not resolved and it's a year old. I really need a solution or way forward.

**Comment by 1025KB** [comment]
Does it work [without](https://github.com/tensorflow/tfx/issues/2156#issuecomment-659426987) notebook?

**Comment by rcrowe-google** [comment]
@Kadri-Saal are you able to try the install using virtualenv instead of Conda? We don't officially support Conda.

**Comment by arghyaganguly** [comment]
@Kadri-Saal , please confirm on the above comment by @rcrowe-google.

**Comment by Kadri-Saal** [comment]
@rcrowe-google and @arghyaganguly , while using PyCharm and virtualenv instead of a Conda environment, I ran into a different error but which still occurs at the Transform component (something the stack trace suggests is related to apache-beam and failing to read files that failed to be written). I think I should not share it here to stay focused on one error at a time, and address it in the future, unless you think it might be relevant.

I will test in a Jupyter notebook again but using virtualenv, and will return with a result shortly. Thank you for your patience.

**Comment by Kadri-Saal** [comment]
@rcrowe-google and @arghyaganguly 

I can confirm that there is no issue encountered with Transform when the notebook is run using virtualenv environment instead of Conda environment. Thank you
