### ISSUE TITLE
Tensorboard is looking for wrong path on GCP AI Platform Pipeline

### ISSUE THREAD

**Issue by deep-diver** [tensorflow/tfx#3308]
**System information**
- Environment Setup: Taxi template code, on GCP AI Platform Pipeline, TFX: 0.27.0, TensorFlow: 2.4.0

**Describe the current behavior**
- The log path for Tensorboard is broken from the template generated code base.
  - template code saves TensorBoard logs in `fn_args.model_run_dir`
  - **It works when I copy the logs to `fn_args.serving_model_dir + '/logs`**
- **However** it still doesn't work for **combined tensorboard` for comparing multiple runs

**Describe the expected behavior**
- I should be able to see comparison between different runs on a single TensorBoard.

I need to know where the combined TensorBaord link is looking for the path of logs.

**Comment by 1025KB** [comment]
iiuc, if we provide a path to tensorboard, it will automatically find the model info and display it in tensorboard

thus if we have 2 model_run artifact, we just need to pass the common parent path to tensorboard, it should be able to find both model's info

for example, if we have penguin_pipeline/model_run/5/logs and penguin_pipeline/model_run/13/logs, we need to pass penguin_pipeline/model_run to tensorboard

**Comment by jiyongjung0** [comment]
Thank you for reporting this issue. There are two issues around here.

- https://github.com/tensorflow/tfx/commit/18055491d38604934a25d49c53d456b96da04c47 fixed the path that Kubeflow Pipelines looking for training logs. So it should be fixed from the next version(0.28.0).
- As you can see from the above commit, there is no good way to override the path to search tensorboard logs. Maybe you can launch a separate instance of tensorboard and search logs as @1025KB mentioned above.

**Comment by deep-diver** [comment]
@jiyongjung0 

Thanks for the quick fix!
You said `should be fixed from the next version(0.28.0)`, so I check out by pulling docker image tagged `0.29.0.dev20210303`?
Please let me know which tag I should use! Thanks for the help.

I will let you know how it goes soon!

**Comment by deep-diver** [comment]
@1025KB 

How to pass path to tensorboard? The URL is kind of encrypted? I mean in AI Platform

**Comment by jiyongjung0** [comment]
I think that the recent 0.28.0 rc version would be easier to use.

- https://pypi.org/project/tfx/0.28.0rc0/
- https://hub.docker.com/layers/tensorflow/tfx/0.28.0rc0/images/sha256-53bfeb9d00de40da6111bc2d3a151406c4b0712b82eb06863f22e7cd587022af?context=explore

Please make sure that your `Dockerfile` is using the latest image.

**Comment by jiyongjung0** [comment]
IIUC, you are mentioning [Tensorboard from Kubeflow Pipelines on AI Platform](https://www.kubeflow.org/docs/components/pipelines/sdk/output-viewer/#tensorboard)
Unfortunately, there is no way to change the path passed to tensorboard without changing TFX source code for now. So you might need another instance of tensorboard.

Launching tensorboard directly on AI Platform Notebook is not well supported yet. See https://github.com/tensorflow/tensorboard/issues/3152 for discussion.

**Comment by deep-diver** [comment]
@jiyongjung0 

In that case, I should wait? Or is there a workaround?

**Comment by jiyongjung0** [comment]
I think that we can add a new feature to aggregate pipeline runs and export it to tensorboard. Could you share more on your expectation about how it should look like?

I think that just gathering all logs in a tensorboard might not have much sense, so we might need some kind of mapping between pipeline runs and tensorboard logs. You probably need to request a feature on https://github.com/kubeflow/pipelines, too. Thanks!

**Comment by deep-diver** [comment]
@jiyongjung0 

I have tested the recent TFX image (0.28.0rc0), and it worked good! :) Thanks
About the aggregated tensorboard...
- We can compare two different `Run`s in kubeflow dashboard.
- When doing so, there is a card under the `Tensorboard` section called `Aggregated View`.
- When I click it, it shows nothing because it looks for the wrong path I guess.

So, Aggregated view is already built-in feature in kubeflow dashboard.
My intention was to report and ask helps fixing the bug.
- At least we need a way to compare different runs since TFX is a ML Pipeline framework!

Yeah, like you said, it might be great to add new features to compare different runs with better UI.
I have not thought about it yet though. I will give a thought about it, but my initial thought on this is to add just W&B callback or something.

**Comment by deep-diver** [comment]
@jiyongjung0 

Also it might be a good idea to bring `model card toolkit`'s result in Kubeflow pipeline's dashboard.

**Comment by arghyaganguly** [comment]
@deep-diver , please confirm if this issue can be closed.Thanks.
