### ISSUE TITLE
Can we use specify two different files for train and evaluation to CSVExampleGen Component

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/tfx#3314]
Is there any way that I can input two different files for train and evaluation to CSVExampleGen Components instead of splitting single file as train and eval?

**Comment by aybchan** [comment]
for a pre-split dataset you should be able to set the input config to read in each split with a path pattern:

```
from  tfx.proto import example_gen_pb2

# Input train split is 'input_dir/train/*', eval split is 'input_dir/eval/*'.
# Output splits are generated one-to-one mapping from input splits.
input = example_gen_pb2.Input(splits=[
                example_gen_pb2.Input.Split(name='train', pattern='train/*'),
                example_gen_pb2.Input.Split(name='eval', pattern='eval/*')
            ])
examples = csv_input(input_dir)
example_gen = CsvExampleGen(input=examples, input_config=input)

```

https://www.tensorflow.org/tfx/guide/examplegen

**Comment by arghyaganguly** [comment]
For the following configuration, let’s assume that our dataset has been split externally
and saved in subdirectories:
└── data
        ├── train
        │      └─ 20k-consumer-complaints-training.csv
        ├── eval
        │      └─ 4k-consumer-complaints-eval.csv
       └── test
                └─ 2k-consumer-complaints-test.csv
We can preserve the existing input split by defining this input configuration:
```
import os
from tfx.components import CsvExampleGen
from tfx.proto import example_gen_pb2
from tfx.utils.dsl_utils import external_input
base_dir = os.getcwd()
data_dir = os.path.join(os.pardir, "data")
input = example_gen_pb2.Input(splits=[
example_gen_pb2.Input.Split(name='train', pattern='train/*'),
example_gen_pb2.Input.Split(name='eval', pattern='eval/*'),
example_gen_pb2.Input.Split(name='test', pattern='test/*')
])
examples = external_input(os.path.join(base_dir, data_dir))
example_gen = CsvExampleGen(input=examples, input_config=input)

```
Set existing subdirectories.
Add the input_config argument.
After defining the input configuration, we can pass the settings to the ExampleGen
component by defining the input_config argument
