### ISSUE TITLE
Add support for dates in StaticRange

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#3354]
Current StaticRange only supports number spans. We would like to use date based span definition on range_config.

**Comment by arghyaganguly** [comment]
Date can be converted to span number to be processed using StaticRange.
Please check :- [link](https://github.com/tensorflow/tfx/blob/master/docs/guide/examplegen.md)

**Comment by casassg** [comment]
It won't work with dates that are inputed as RuntimeParam.

As a user I want to schedule my pipeline to run [periodically](https://github.com/tensorflow/community/blob/master/rfcs/20210115-tfx-periodic-training.md) with new data on every run. My data is partitioned by date. I want to use RuntimeParam to inject the pipeline execution date into StaticRange so ExampleGen can resolve for the specific dates. 

`utils.date_to_span_number` won't work since my RumtimeParam does not have a value on compilation time.

**Comment by casassg** [comment]
@1025KB we use Airflow or Kubeflow to run the job periodically. This means we can use RuntimeParam to configure to use either `[[ScheduledTime]]` or `{{ds}}` as you suggested to me in the RFC. However those are resolved on component execution time, so we need the driver to get the range_config as is so that orchestrator can replace the values on runtime

**Comment by 1025KB** [comment]
I think we need to be able to have some kind of code executed for generating the params, like a cron job or script.

Otherwise for all RuntimeParams, it need to support multiple format if the orchestrator can't provide the format it required.

I will check with Kubeflow team. A workaround can be using a cron/script to schedule the kubeflow instead of using the UI?

**Comment by casassg** [comment]
Most schedulers expose flexible format dates as runtime params (Kubeflow allows format config and Airflow does as well). Adding dates to RangeConfig seems like the easier path rather than asking each orchestrator to have a custom code hook.

**Comment by 1025KB** [comment]
being able to do some calculate before binary execution is a must I feel. E.g., if upstream has 2 day delay, then what we need is sth like to_span(timestamp-24*3600*2), and similar needs would happen for other params too. Solving them case by case is not ideal. We would need a cron equivalent for Kubeflow.

**Comment by casassg** [comment]
>E.g., if upstream has 2 day delay, then what we need is sth like to_span(timestamp-2436002)

If upstream is delayed, then we backfill, which effectively changes ScheduleDate/ds value on both Kubeflow or Airflow. Also if you just need the latest, you can use LatestSpan resolver instead of static range. 

Would it be useful to create a syncronous discussion on this? We can create mailing list thread and propose open meeting

**Comment by 1025KB** [comment]
> > E.g., if upstream has 2 day delay, then what we need is sth like to_span(timestamp-2436002)

oh, what I mean here is, for example

there is a input processing pipeline that takes 10h
thus at day2 10am, day1 data is ready.
Then you start pipeline at day2 11am, but it actually processing day1 instead of day2,  thus you need to process span-day1 instead of span-day2.

If we can't have cron equivalent and do some basic param processing, it will have a lot of similar issues in the future

> 
> If upstream is delayed, then we backfill, which effectively changes ScheduleDate/ds value on both Kubeflow or Airflow. Also if you 
just need the latest, you can use LatestSpan resolver instead of static range.
> 
> Would it be useful to create a syncronous discussion on this? We can create mailing list thread and propose open meeting

sure

**Comment by casassg** [comment]
Ooh I see, yeah, that makes more sense. 

Airflow does provide date modifiers on their template language already: https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html#airflow.macros.ds_add So that would be solved for Airflow. 

Wondering if we should add some pre_compute hooks in the driver then instead?

**Comment by singhniraj08** [comment]
@casassg,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
