### ISSUE TITLE
TFX CLI pipeline compile command does not support endpoint

### ISSUE THREAD

**Issue by SaschaHeyer** [tensorflow/tfx#3369]
**System information** 
- Have I specified the code to reproduce the issue (Yes/No): yes
- Environment in which the code is executed (e.g., Local (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): notebook
- TensorFlow version (you are using): /
- TFX Version: 0.28.0
- Python version: 3

**Describe the current behavior**
Regarding CLI documentation the command `tfx pipeline compile` has a parameter '--endpoint'
see https://github.com/tensorflow/tfx/blob/master/docs/guide/cli.md#tfx-pipeline

Using this parameter runs into an error
```
Error: no such option: --endpoint
```
**Describe the expected behavior**
compile command supports endpoint parameter as listed in the documentation

**Standalone code to reproduce the issue** 

```
!tfx template copy \
  --pipeline-name=test \
  --destination-path=./test \
  --model=taxi

!tfx pipeline compile  \
--pipeline-path=./test/kubeflow_runner.py \
--endpoint={ENDPOINT} \
--build-target-image={CUSTOM_TFX_IMAGE}

#removed other boilerplate code for better visibility
```

**Comment by jiyongjung0** [comment]
Thank you for the report.

The document was wrong. Because `compile` command builds the pipeline locally, it doesn't require any parameters about a remote Kubeflow pipeline cluster like `endpoint` or `namespace`. #3372 will fix the doc.

**Comment by SaschaHeyer** [comment]
Thanks @jiyongjung0 
Appreciate the quick fix
