### ISSUE TITLE
Kubeflow / AI Platform Pipelines visualization missing

### ISSUE THREAD

**Issue by SaschaHeyer** [tensorflow/tfx#3371]
**System information** 
- Have I specified the code to reproduce the issue
(Yes/No): No
- Environment in which the code is executed (e.g., Local
(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): AI Platform Pipelines
- TensorFlow version (you are using): /
- TFX Version: - Python version: 0.28.0

**Describe the current behavior**
Issue appears in **AI Platform Pipelines**
StatisticsGen component has missing static HTML and metadata

<img width="1211" alt="Screenshot 2021-03-14 at 21 17 18" src="https://user-images.githubusercontent.com/1991664/111082861-c539d180-850a-11eb-9224-bf6f9416eae2.png">

<img width="1201" alt="Screenshot 2021-03-14 at 21 17 55" src="https://user-images.githubusercontent.com/1991664/111082863-c8cd5880-850a-11eb-811e-35c205553dfd.png">

**Describe the expected behavior**
Visualization is displayed

**Standalone code to reproduce the issue** 
/

**Name of your Organization (Optional)**
/

**Other info / logs** I
There is a similar issue but unfortunately without a solution
https://github.com/tensorflow/tfx/issues/2346

* KFP version: 1.4.1

**Comment by SaschaHeyer** [comment]
Investigated further
* This issue can be reproduced only if the run output is taken from the cache. Runs not taken from cache work fine.

**Comment by arghyaganguly** [comment]
@SaschaHeyer , thanks for the report. We've reopened issue #2346 to make tracking easier.

**Comment by jiyongjung0** [comment]
It seems like a separate issue and more related to Kubeflow pipelines. These caching happens from Kubeflow Pipelines and TFX doesn't have access on them. Could you report this to https://github.com/kubeflow/pipelines instead?

**Comment by arghyaganguly** [comment]
@SaschaHeyer , please report this isssue to  https://github.com/kubeflow/pipelines as per @jiyongjung0's comment.Thanks.

**Comment by SaschaHeyer** [comment]
@jiyongjung0 
@arghyaganguly 

Thanks a lot. I report the issue to Kubeflow Pipelines.

**Comment by SaschaHeyer** [comment]
Kubeflow issue reference
https://github.com/kubeflow/pipelines/issues/5302
