### ISSUE TITLE
TFX nightly 0.29.0.dev20210328 create pipeline defs to large for KubeFlow

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#3459]
- Have I specified the code to reproduce the issue(Yes/No): Should be visible in a pipeline compile test
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Kubeflow 1.1.0
- TensorFlow version (you are using): Which ever bundles with the TFX  version
- TFX Version: 0.29.0.dev20210328
- Python version: 3.7.3

**Describe the current behavior**
After moving from TFX 0.28.0 to nightly build (to test fix for this issue https://github.com/tensorflow/tfx/issues/3272) the pipeline defs have grown by more than a factor 20. I have a pipeline with 29 components which was 272KB uncompressed when compiled with TFX 0.28.0 but with the nightly build this is now 6.2MB which is almost 23 times larger. This causes KubeFlow to fail because it exceeds the gRPC limit of the KFP apis.

From KubeFlow:
```{"error":"grpc: received message larger than max (5429408 vs. 4194304)","message":"grpc: received message larger than max (5429408 vs. 4194304)","code":8}```

This seems to stem from the fact that TFX now uses IR representation which seems to be extremely verbose in comparison.

**Describe the expected behavior**
Not a factor 20 increase in size.

**Standalone code to reproduce the issue**
Just compare sizes of the outputs from the kubeflow_dag_runner from TFX version 0.28.0 and latest nightly. 

Other info:
My 3 component pipeline increased in size from 21KB to 78KB and my 3 component pipeline increased in size from 36KB to 272KB.

It seems as the IR now saves all information about all components **for each component**. This means that size of the pipeline grows exponentially with the number of nodes.

**Comment by jiyongjung0** [comment]
Thank you so much for trying our nightly version and filing this report. We are working on reducing the footprint, but we couldn't include it in nightly yet.(including 0.29.0rc0 released today.).

Could you try older nightly versions which doesn't include IR representation like [tfx-0.29.0.dev20210318-py3-none-any.whl](https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-0.29.0.dev20210318-py3-none-any.whl#sha256=38b594467c69d1f3ac74d3df9fca52521ffdc6e5fe3b9bf9f87cb7cf84d86120) for a while? I'll get back to you once we resolve this.
Thanks.

**Comment by ConverJens** [comment]
@jiyongjung0 Thanks, I'll try that in the mean time!

**Comment by ConverJens** [comment]
@jiyongjung0 Any update on this? It would be great if this could be a part of the upcoming 0.30.0 release!

**Comment by axeltidemann** [comment]
I have the same issue on TFX 1.0.0-rc1. This is a blocker for anything but the simplest pipelines to run on Kubeflow, and a fix would be greatly appreciated.

**Comment by jiyongjung0** [comment]
Hi. Sorry for the late update. Unfortunately we couldn't make any progress on this in 0.30.0 and 1.0 release. We are trying to store the giant IR in a some external storage and load it as needed, but still finding solutions that can be applied across many supported environment.

**Comment by axeltidemann** [comment]
Any thoughts on a timeline to resolve this? This should probably be listed under **Breaking Changes** in the [release](https://github.com/tensorflow/tfx/blob/master/RELEASE.md) document.

**Comment by axeltidemann** [comment]
This is still a blocker on TFX 1.1.0.dev20210617.

**Comment by vaskozl** [comment]
I agree that this is a breaking change, I already had to reduce the number of splits I can run in one of my pipelines due to annotation size limits, this only compounds the problem and makes running with anything more than a few splits impossible:

https://github.com/kubeflow/kubeflow/issues/5701

I think I'll have to work around this by hacking the ExampleGen to not requires any serialized config in the yaml.

**Comment by ConverJens** [comment]
I feel like even that isn't enough (not to mention feasible!) since even the "vanilla" TFX taxi pipeline can no longer run in KubeFlow!

**Comment by jiyongjung0** [comment]
Thank you for your patience. TFX 1.0.0rc2 is out and we expect that the size issue should be resolved in most cases although we still need to reduce the payload size further.

**Comment by vaskozl** [comment]
@jindalshivam09 Do you have a solution for 0.30 and before? I'm unable to run 1.0.0 and newer due to being limited by Kubeflow and the mlmetadata  server version.

Is there a specific commit that we can patch in to handle this gracefully?

**Comment by vaskozl** [comment]
Looks like a fix was commited in https://github.com/tensorflow/tfx/commit/dd8e7cb8bc1837e88f66e2c1033ee418eead405d, which I have now backported to my containers.

**Comment by pindinagesh** [comment]
Hi @ConverJens! 
Could you refer to the above [comment ](https://github.com/tensorflow/tfx/issues/3459#issuecomment-896962635)to make changes in your containers.  
Thank you!
