### ISSUE TITLE
CNCF SIG-Runtime Discussion/Presentation?

### ISSUE THREAD

**Issue by raravena80** [tensorflow/tfx#3462]
Hello TFX team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. An overview of the project would be great.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by gowthamkpr** [comment]
@raravena80 Closing this issue as the event is already done and is published [here](https://www.youtube.com/watch?v=zCQ3gzEDdG4). Thanks!
