### ISSUE TITLE
Version update in Chicago Taxi Native Keras Example (tfx 0.21.1)

### ISSUE THREAD

**Issue by Arghya999** [tensorflow/tfx#3475]
In [link](https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi_pipeline), the version for subsection Chicago Taxi Native Keras Example is given as : (tfx 0.21.1).
taxi_utils_native_keras.py is successfully executed in tfx0.28.0.

Actual :- Chicago Taxi Native Keras Example (tfx 0.28.0).

**Comment by arghyaganguly** [comment]
@Arghya999 , a pr has been raised to address this issue.Will close once the review is completed.

**Comment by arghyaganguly** [comment]
Ideally when we mention a TF version we implicitly say that it will work for later versions as well. (unless they don't, and we call it as a bug).Following which this cannot be called a bug.Thanks.
