### ISSUE TITLE
Add ability to specify multiple date specs for input configs of ExampleGen components

### ISSUE THREAD

**Issue by aoen** [tensorflow/tfx#3476]
**System information**

- TFX Version (you are using):
0.26

- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..):
Google Cloud

- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Currently it's not possible to use a date spec multiple times in an input config pattern, e.g. for BigQueryExampleGen being able to specify a query like 'SELECT ... WHERE date_col > {YYYY}{MM}{DD} - 5 days and date < {YYYY}{MM}{DD}' or a join between two tables each which need to have a WHERE date_col = {YYYY}{MM}{DD}. It's not clear why this functionality isn't supported, seems like it may be possible to just [remove the exception TFX throws](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/utils.py#L300) when it detects multiple date specs.

**Will this change the current API? How?**
Yes, the API will be more permissive (can specify multiple date specs in an input config)

**Who will benefit with this feature?**
Users of ExampleGen.

**Do you have a workaround or are completely blocked by this?** :
For a workaround we will likely end up forking internally to include this change.

**Name of your Organization (Optional)**
Twitter

cc @1025KB

**Comment by casassg** [comment]
Note this refers to the Driver implemented in https://github.com/tensorflow/tfx/commit/8b6e3f12a0b3015ea3a02115abf6a18ce92400b8 by @1025KB

**Comment by 1025KB** [comment]
do you want to have a rolling window? e,g, day1-day5 the day2-day6 ... 

if so it would be good to set ExampleGen to process one span at a time but have a rolling window of spans feed to trainer using resolver

**Comment by casassg** [comment]
Let's focus more on the join use case, where you need to defined a where on 2 different columns to join it. 

Declare will not work due to query needing to be a single statement as described in https://github.com/tensorflow/tfx/issues/2119 (per restrictions on Beam BQReadImpl). The with proposal won't work when using partitioned tables as partitioned tables require the comparison to be made with a constant.

**Comment by 1025KB** [comment]
If you remove the check for detecting multiple date specs, will it work? 
if so I can refactor the code, currently querybased and filebased use the same verification check, I can split them to remove the check for querybased

**Comment by casassg** [comment]
CC @aoen for testing (since he was touching the Driver logic already)

**Comment by aoen** [comment]
Tested and confirmed removing the if block that raises the exception: https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/utils.py#L300 works (am able to include partial date spec (e.g. {YYYY}{MM} instead of {YYYY}{MM}{DD}) and multiple datespecs this way.

**Comment by 1025KB** [comment]
Note that partial date spec is not allow by the default querybase driver, as it would change the semantics (span is the days from 1970-01-01)

**Comment by aoen** [comment]
That's a good point, though not sure it would be an issue in practice since the underlying span would still be stored with a daily granularity, it would just mean that a query that consumed only {YYYY}{MM} wouldn't reuse a cached result from a different day in the same month. Checking >=1 doesn't guarantee that the day is used in the query anyways (e.g. a user could just add a comment to your query with the {DD} part).

I don't think we have a use-case for this at the moment anyways so if you prefer >=1 instead of removing the exception, that should be fine for now.

**Comment by 1025KB** [comment]
Hi, to make it more flexible, we plan to apply some change to querybased driver, we plan to have a timestamp placeholder instead of {YYYY}{MM}{DD}, and in the query that timestamp can be converted to any format needed.

**Comment by 1025KB** [comment]
> Hi, to make it more flexible, we plan to apply some change to querybased driver, we plan to have a timestamp placeholder instead of {YYYY}{MM}{DD}, and in the query that [timestamp](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_seconds) can be converted to any format needed.

**Comment by 1025KB** [comment]
https://github.com/tensorflow/tfx/pull/3524

**Comment by 1025KB** [comment]
> Hi, to make it more flexible, we plan to apply some change to querybased driver, we plan to have a timestamp placeholder instead of {YYYY}{MM}{DD}, and in the query that [timestamp](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_seconds) can be converted to any format needed.

https://github.com/tensorflow/tfx/pull/3524

**Comment by arghyaganguly** [comment]
Closing this as #3524 has been merged.Please reopen if required.Thanks.
