### ISSUE TITLE
Specify run name using tfx cli

### ISSUE THREAD

**Issue by axeltidemann** [tensorflow/tfx#3503]
When submitting a pipeline with `kfp`, you can specify a [run name](https://github.com/kubeflow/pipelines/blob/55b18779a7da9043e0257484999d8689b4f02afc/sdk/python/kfp/cli/run.py#L53). It would be super useful to have this in the `tfx`cli also, e.g. `tfx run create --run-name my-run` to easily distinguish runs in the Kubeflow UI.

**Comment by jiyongjung0** [comment]
+1 to this. Thank you for the great suggestion!

**Comment by singhniraj08** [comment]
@axeltidemann,

`--pipeline_name` flag is introduced in current `tfx run create` CLI command as shown [here](https://www.tensorflow.org/tfx/guide/cli#create_2). Please let us know if this issue can be closed. Thank you!

**Comment by axeltidemann** [comment]
No, the `--pipeline_name` is just that - the name of the pipeline. What I am looking for is a way to add a descriptive name to the run, e.g. "trying three hidden layers instead of four".

**Comment by AnuarTB** [comment]
After internal discussion unfortunately it seems like we won't add this feature to the OSS version of TFX in near future.
