### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by bdoohan-goog** [tensorflow/tfx#3530]
Thank you for submitting a TFX documentation issue. Per our GitHub policy, we
only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub and we welcome external contributions!

The TFX docs are open source! To get involved, please read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
This colab (https://colab.sandbox.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb)
references this link (https://www.tensorflow.org/tfx/tutorials/tfx/guide/build_tfx_pipeline) at this point: https://colab.sandbox.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb#scrollTo=8ONIE_hdkPS4.

This link give the attached 404 error. 
![Screenshot 2021-04-13 3 22 52 PM](https://user-images.githubusercontent.com/74371449/114608860-27056c80-9c6c-11eb-9e54-5dd586a02426.png)
Please provide correct link.

**Comment by arghyaganguly** [comment]
@bdoohan-goog , thank you for reporting this.A PR has been raised to fix it.
Will close once it is approved and merged.
Thanks.

**Comment by dhruvesh09** [comment]
@bdoohan-goog 

The link is now fixed, please give a try and let us know if you still face an issue.

**Comment by bdoohan-goog** [comment]
Link works now. Thank you very much!
