### ISSUE TITLE
Dead link for understanding_tfx_pipelines in build_tfx_pipeline.md

### ISSUE THREAD

**Issue by Arghya999** [tensorflow/tfx#3534]
Thank you for submitting a TFX documentation issue. Per our GitHub policy, we
only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub and we welcome external contributions!

The TFX docs are open source! To get involved, please read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
[build_tfx_pipeline.md](https://github.com/tensorflow/tfx/blob/master/docs/guide/build_tfx_pipeline.md) references [Understanding TFX Pipelines](https://github.com/tensorflow/tfx/blob/master/docs/guide/understanding_tfx_pipelines) which returns 404 error.

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/guide

## Description of issue (what needs changing):
Requirement :  Correct link for Understanding TFX Pipelines
### Clear description:

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,

https://www.tensorflow.org/tfx/guide/examplegen

### Request visuals, if applicable

Are there currently visuals? If so, do they look correct? If not, will it
clarify the content?

**Comment by arghyaganguly** [comment]
PR raised to correct this broken link.Will close once it is approved by reviewers.
