### ISSUE TITLE
Issue building Function-based Component where Input = Output

### ISSUE THREAD

**Issue by RossKohler** [tensorflow/tfx#3539]
I'm trying to build a component that takes an input and pipes it to the output unaltered. This is my first attempt at creating a custom component and I'm trying to use the python function-based component definition. This isn't what the final component will be doing, but I'm using this as a starting point to test my understanding of TFX components. In this example, I'm taking input from `CSVExampleGen` and passing it to my `CustomComponent` like so:
```@component
def CustomComponent(
    input_data: InputArtifact[Examples],
    examples: OutputArtifact[Examples],
    ) -> None:
    input_data.write_to(examples.uri)
    return
```

The relevant section of the pipeline is defined below:

```
    example_gen = CsvExampleGen(input_base=data_root, input_config=input_config)

    custom_gen = CustomComponent(input_data=example_gen.outputs['examples'])
    # # Computes statistics over data for visualization and example validation.
    statistics_gen = StatisticsGen(examples=custom_gen.outputs['examples'])

    # Generates schema based on statistics files.
    schema_gen = SchemaGen(
        statistics=statistics_gen.outputs['statistics'], infer_feature_shape=True)


    # # Performs anomaly detection based on statistics and data schema.
    example_validator = ExampleValidator(
        statistics=statistics_gen.outputs['statistics'],
        schema=schema_gen.outputs['schema'])

    # Performs transformations and feature engineering in training and serving.
    # The analysis is done on the train split, and transformed on all splits.
    # This requires that you cannot have unseen categorical variables in the eval/test splits.
    transform = Transform(
        examples=custom.outputs['examples'],
        schema=schema_gen.outputs['schema'],
        module_file=module_file)
```

During the build of the pipeline the error below is thrown:

```Traceback (most recent call last):
  File "/Users/Kohler/workspace/mml_projects/product_categorizer/categorizer_v2/tfx-python/local_runner.py", line 47, in <module>
    local_runner=True))
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/local/local_dag_runner.py", line 129, in run
    component_launcher.launch()
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 405, in launch
    executor_output = self._run_executor(execution_info)
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 306, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 110, in run_executor
    execution_info.exec_properties)
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/components/statistics_gen/executor.py", line 96, in Do
    examples = artifact_utils.get_single_instance(input_dict[EXAMPLES_KEY])
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/types/artifact_utils.py", line 67, in get_single_instance
    len(artifact_list)))
ValueError: expected list length of one but got 26
```

**System information**
- Have I specified the code to reproduce the issue(Yes/No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): MacOS
- TensorFlow version: ^2.4.1 
- TFX Version: 0.28.0
- Python version: 3.7.9

**Describe the current behavior**

During pipeline build my component is taking the output of `CsvExampleGen`:

```
Channel(
    type_name: Examples
    artifacts: []
    additional_properties: {}
    additional_custom_properties: {}
)
```

and modifying it to look like:

```
Channel(
    type_name: Examples
    artifacts: [Artifact(artifact: , artifact_type: name: "Examples"
properties {
  key: "span"
  value: INT
}
properties {
  key: "split_names"
  value: STRING
}
properties {
  key: "version"
  value: INT
}
)]
    additional_properties: {}
    additional_custom_properties: {}
)
```
**Describe the expected behavior**
The inputs and outputs of the code should be equivalent, namely (the output of `CSVExampleGen`):

```
Channel(
    type_name: Examples
    artifacts: []
    additional_properties: {}
    additional_custom_properties: {}
)
```

Any help in explaining what's going on here would be greatly appreciated, I'm sure my understanding is missing something. Could it perhaps be because I'm using a function-based component definition when I need to customize more than what is offered here?

**Comment by 1025KB** [comment]
The error means your custom_gen.outputs['examples'] contains 26 artifacts instead of one,
could you do some printing to see what is generated in the output Channel?

**Comment by RossKohler** [comment]
I'm inclined to agree with you, but here's the output of `custom_gen.outputs['examples']`:

```
Channel(
    type_name: Examples
    artifacts: [Artifact(artifact: , artifact_type: name: "Examples"
properties {
  key: "span"
  value: INT
}
properties {
  key: "split_names"
  value: STRING
}
properties {
  key: "version"
  value: INT
}
)]
    additional_properties: {}
    additional_custom_properties: {}
)
```
I'm don't understand where that length of 26 is coming from. I've placed breakpoints in the body of `CustomComponent` and they're not being hit yet, so I understand that to mean that it could only be the parameters of `CustomComponet` that could be causing this error. Which is as follows:

```
def ImageComponent(
    input_data: InputArtifact[Examples],
    examples: OutputArtifact[Examples],
    ) -> None:
    return
```
This component is the very next component after `CSVExampleGen`.

**Comment by 1025KB** [comment]
if you remove the custom component, StatisticsGen is fine, right?
as stats_gen takes custom_gen's output, it will be executed after custom_gen

**Comment by RossKohler** [comment]
Correct, if I remove the custom component and pipe the output of CSVExampleGen straight into StatisticsGen everything is fine again. I see the 26 artifacts in that dictionary but I don't understand what they represent? my dataset in question only has 200 examples (100 for training, 100 for evaluation). 

If I understand the process correctly the code I've posted above should just pipe the examples from CSVExampleGen unaltered through to StatisticsGen. Yet the error seems to suggest that there are 25 more artifacts in that dictionary than there should be. 

If I remove the custom component from the pipeline and revert to a working solution, the breakpoint in the `Do()` function of StatisticsGen component doesn't even get hit.  Any insight to help me understand what going on here? or is there anything else I could look at?

**Comment by 1025KB** [comment]
Is stats_gen works without custom component or not? If Do() is not hit, it's not working.

For example, if you run the penguin example, you can see stats_gen generate outputs under ~/tfx/pipelines/penguin/StatisticsGen, that's the result of that Do().

**Comment by 1025KB** [comment]
> Correct, if I remove the custom component and pipe the output of CSVExampleGen straight into StatisticsGen everything is fine again. I see the 26 artifacts in that dictionary but I don't understand what they represent? my dataset in question only has 200 examples (100 for training, 100 for evaluation).
> 
> If I understand the process correctly the code I've posted above should just pipe the examples from CSVExampleGen unaltered through to StatisticsGen. Yet the error seems to suggest that there are 25 more artifacts in that dictionary than there should be.
could you print those artifacts and paste here? it should contains uris, we can take a look
> 
> If I remove the custom component from the pipeline and revert to a working solution, the breakpoint in the `Do()` function of StatisticsGen component doesn't even get hit. Any insight to help me understand what going on here? or is there anything else I could look at?

**Comment by RossKohler** [comment]
Okay, I figured that out. It wasn't running because it must have been using a cached result from a previous run, I deleted the `pipelines` folder and re-ran. The `input_dict['examples']` WITHOUT the CustomComponent is this:

```
{'examples': [Artifact(artifact: id: 1
type_id: 6
uri: "./pipelines/mml-product-categorizer/CsvExampleGen/examples/1"
properties {
  key: "split_names"
  value {
    string_value: "[\"train\", \"eval\"]"
  }
}
custom_properties {
  key: "input_fingerprint"
  value {
    string_value: "split:train,num_files:1,total_bytes:1764690,xor_checksum:1618401024,sum_checksum:1618401024\nsplit:eval,num_files:1,total_bytes:1577742,xor_checksum:1618401046,sum_checksum:1618401046"
  }
}
custom_properties {
  key: "name"
  value {
    string_value: "mml-product-categorizer:2021-04-15T20:28:15.585910:CsvExampleGen:examples:0"
  }
}
custom_properties {
  key: "payload_format"
  value {
    string_value: "FORMAT_TF_EXAMPLE"
  }
}
custom_properties {
  key: "span"
  value {
    string_value: "0"
  }
}
state: LIVE
create_time_since_epoch: 1618511343076
last_update_time_since_epoch: 1618511343076
, artifact_type: id: 6
name: "Examples"
properties {
  key: "span"
  value: INT
}
properties {
  key: "split_names"
  value: STRING
}
properties {
  key: "version"
  value: INT
}
)]}
```

**Comment by RossKohler** [comment]
Actually, deleting the `pipelines` folder seems to have fixed everything. The pipeline is working now with the CustomComponent in place. Is it possible that the `pipelines` folder got corrupted somehow?

**Comment by 1025KB** [comment]
It might be the cache setup for function based component, @charlesccychen might know

**Comment by charlesccychen** [comment]
Thanks @RossKohler -- it sounds like the component code changed during development but the cache wasn't invalidated.  Does that sound right?  You can see more debug logging with "from absl import logging; logging.set_verbosity(logging.DEBUG)" and rerunning.  If so, this is a bug on our end because currently the cache signature of the component is not recomputed based on the function component's code.

CC: @1025KB

**Comment by RossKohler** [comment]
Yeah, so the first time I run it after deleting the `pipelines` and `metadata` folders it runs successfully and starts training. The second time obviously there's metadata and cache now and something about that is breaking it. Setting `enable_cache` to False in the pipeline.Pipeline() function doesn't seem to fix it.

I seem to be only able to run the pipeline once successfully before I start getting error messages like this:

```
Traceback (most recent call last):
  File "/Users/Kohler/workspace/mml_projects/product_categorizer/categorizer_v2/tfx-python/local_runner.py", line 47, in <module>
    local_runner=True))
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/local/local_dag_runner.py", line 129, in run
    component_launcher.launch()
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 405, in launch
    executor_output = self._run_executor(execution_info)
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 306, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 110, in run_executor
    execution_info.exec_properties)
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/components/statistics_gen/executor.py", line 96, in Do
    examples = artifact_utils.get_single_instance(input_dict[EXAMPLES_KEY])
  File "/Users/Kohler/Library/Caches/pypoetry/virtualenvs/product-categorizer-wqG8L-u7-py3.7/lib/python3.7/site-packages/tfx/types/artifact_utils.py", line 67, in get_single_instance
    len(artifact_list)))
ValueError: expected list length of one but got 3
```

**Comment by RossKohler** [comment]
Is there any update on this? or possibly an idea on how I can temporarily fix this and still work on my custom component? Can I submit anything to document this bug a bit better? Maybe submit a minimal demonstration or something?

**Comment by 1025KB** [comment]
Which DagRunner are you using? Does that issue exist with LocalDagRunner?

**Comment by RossKohler** [comment]
Yes, I'm using LocalDagRunner. Do you think the issue could be specific to that?

**Comment by 1025KB** [comment]
Is [this](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/local/local_dag_runner.py#L102) information available? could you post here? Thanks!!

**Comment by RossKohler** [comment]
So [here](https://gist.github.com/RossKohler/4a0c7fd9deebe022084283fdddbe57eb) is a gist that has the entire stack trace with `logging.set_verbosity(logging.DEBUG)`.

**Comment by RossKohler** [comment]
Perhaps it would be valuable for me just to create an entirely new TFX project and build a pipeline as a minimal example. If I can replicate it, I'll zip it and send it to you. If I can't then it's something else I've done.

**Comment by RossKohler** [comment]
I believe I might have been able to partially figure out the issue! I had forgotten to add the components to the `components` list in the `pipeline.Pipeline()` constructor. I imagine this must have really messed up something here. I think the cache made this really difficult to debug.

After going through the docs and combing over the tfx examples I think I've been looking at this wrong. If I wanted to have a component where the input is just passed through to the output, I would need to take all of the data that would be in the `CSVExampleGen` pipelines folder a copy it to the `CustomComponent` folder. Then adjust the `OutputArtifact` accordingly. I can't simply just make the properties of the `OutputArtifiact` equal to the `InputArtifact` as that would mean you would have URIs that point to a folder that is outside of your components folder, which feels wrong.

This has just been a way for me to understand how all of this fits together. My actual use case is to take image URLs that are within the `CSVExampleGen' TFRecords, download the images, convert them to tensors and then use these modified records as training examples in the rest of the pipeline. Any guidance here would be greatly appreciated, does it sound like I'm on the right track? 

I think we might be able to close this issue if that is the case :)

**Comment by 1025KB** [comment]
Note that the output artifact's uri should be prepared already in your function based component, you can directly use the provided uri instead of changing the uri.

Pointing uri to other artifact.uri is [doable](https://github.com/tensorflow/tfx/blob/master/tfx/components/experimental/data_view/binder_executor.py#L48) but not recommended
