### ISSUE TITLE
Broken link in Trainer component guide.

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tfx#3564]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/guide/trainer#configuring_the_trainer_component

### Clear description:

<img width="961" alt="Screen Shot 2021-04-19 at 4 47 46 PM" src="https://user-images.githubusercontent.com/8815362/115200261-fa9b9580-a12e-11eb-9013-8ca9c114b801.png">

The link in the above screenshot (`example module file`) is broken. That link points to `https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_utils.py`. I think `https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_utils_keras.py` is the correct link.

**Comment by arghyaganguly** [comment]
@jeongukjae , thanks for reporting the issue.A PR has been raised to address this bug,

**Comment by arghyaganguly** [comment]
Closing this as issue  has been fixed.
