### ISSUE TITLE
Penguin Example -> AttributeError: module 'user_module_0' has no attribute 'trainer_fn'

### ISSUE THREAD

**Issue by RossKohler** [tensorflow/tfx#3573]
**System information**

- Have I specified the code to reproduce the issue(Yes/No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): MacOS
- TensorFlow version (you are using): ^2.4.1
- TFX Version: 0.28.0
- Python version: 3.7.0

**Describe the current behavior**

Cloning the TFX repo (latest -> ce2fd6fbde9845cd837c47089c3d6db2f87007b9) and attempting to run the penguin example using the LocalDAGRunner at `penguin_pipeline_local.py` yields the following error:

```
AttributeError: module 'user_module_0' has no attribute 'trainer_fn'
```

**Describe the expected behavior**

Running the penguin example using the localDAGRunner completes successfully.

**Steps to resolve issue**

I believe there is a line missing in the instantiation of the `Trainer` component in the pipeline. An additional parameter of `custom_executor_spec=executor_spec.ExecutorClassSpec(GenericExecutor)` should be added. This fixes the issue.

**Comment by RossKohler** [comment]
I've created a PR to address this issue [here](https://github.com/tensorflow/tfx/pull/3574)

**Comment by jiyongjung0** [comment]
Thank you for reporting.

As I responded in the PR, we are currently preparing our next release 0.30.0, and the examples were changed a bit earlier. You can add cusotm_executor_spec by yourself, or use the nightly version until 0.30.0 release finalized.

Thanks!
