### ISSUE TITLE
Transform component fails when using S3 as storage and FlinkRunner as backend

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#3601]
Environment: On-prem kubeflow deployment
TensorFlow version (you are using): Which ever TFX 0.28.0 uses
TFX Version: 0.28.0
Python version: 3.7

**The issue:**
When running pipelines using Flink as runner, the job fails in the Transform component when using S3 as storage.

Using DirectRunner and S3 works ans using FlinkRunner and mounted pvc also works. 

The issue only arise when using both FlinkRunner and S3 in conjuction. Even in this case only Transform fails, ExampleGen, StatsGen and SchemaGen completes succesfully.

Transform fails with:
```
ERROR:root:java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error received from SDK harness for instruction 227: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1233, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 762, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 880, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1368, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py", line 416, in process
    lambda: self._make_graph_state(saved_model_dir))
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/shared.py", line 238, in acquire
    return _shared_map.acquire(self._key, constructor_fn, tag)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/shared.py", line 194, in acquire
    result = control_block.acquire(constructor_fn, tag)
  File "/usr/local/lib/python3.7/site-packages/tfx_bsl/beam/shared.py", line 89, in acquire
    result = constructor_fn()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py", line 416, in <lambda>
    lambda: self._make_graph_state(saved_model_dir))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py", line 380, in _make_graph_state
    self._exclude_outputs, self._tf_config)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py", line 214, in __init__
    saved_model_dir, {}))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 426, in partially_apply_saved_transform_internal
    saved_model_dir, logical_input_map, tensor_replacement_map)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 217, in _partially_apply_saved_transform_impl
    _load_transform_saved_model(saved_model_dir))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 97, in _load_transform_saved_model
    transform_savedmodel_dir)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_transform/saved/saved_model_loader.py", line 31, in parse_saved_model
    return loader_impl.parse_saved_model(saved_model_dir)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 114, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: s3://pipelines/tfx/trace_pipeline_e2e_flink/Transform/transform_graph/12480/.temp_path/tftransform_tmp/0171b59936af47528f84a7b304e0fd00/{saved_model.pbtxt|saved_model.pb}
```
When looking in Minio the specified path actually do exists.

**Expected behaviour:**
Transform should be able to handle any supported storage with any supported beam runner.

Setup:
I've tried this with Beam SDK 2.29.0rc1  and the latest supported version of Flink 1.12.

Images used:
apache/beam_python3.7_sdk:2.29.0_rc1
apache/flink:1.12.2-scala

Beam args used are:
```
"--runner=FlinkRunner",
"--flink_version=1.12",
"--flink_master=http://flink-jobmanager.default:8081",
"--environment_type=EXTERNAL",
"--environment_config=localhost:50000",
"--auto_balance_write_files_sharding_enabled",
"--faster_copy",
"--object_reuse",
"--flink_submit_uber_jar",
"--execution_mode_for_batch=BATCH_FORCED",
"--max_parallelism=5",
"--parallelism=5",
"--sdk_worker_parallelism=1",
"--worker_harness_container_image=none",
```

**Comment by ConverJens** [comment]
@ferryvg @vaskozl @MeTaNoV
Has anyone of you managed to get Transform to work with S3 and FlinkRunner?

**Comment by ConverJens** [comment]
Ping @ibzib

**Comment by ibzib** [comment]
> Ping @ibzib. Do you have any idea why this happens?

I haven't used the FlinkRunner with s3 before, but if it's working for the other components I have a couple guesses: it could be a bug in the Transform code, or it could be a bug with the `auto_balance_write_files_sharding_enabled` option.

**Comment by ConverJens** [comment]
@ibzib Thanks for the response!
I ran a test without `auto_balance_write_files_sharding_enabled` but got the exact same result.

How should we proceed with this?

**Comment by vaskozl** [comment]
I've been working on other system recently, so it took me some time to reproduce this. I was getting the exact same error together with some `Not found 400s`.

I was able to fix this by adding the following env variables to both the kubeflow/argo pipeline pod, taskmanager and the sdk worker_pool sidecar:
```
    S3_ENDPOINT: you.minio.endpoint
    BUCKET_NAME: yourbucket
    S3_USE_HTTPS: "1"
    S3_VERIFY_SSL: "1"
    AWS_ACCESS_KEY_ID: THISISHARD
    AWS_SECRET_ACCESS_KEY: IHOPEITSWORTHIT
```

I haven't had time to investigate whether it's necessary in in all 3 containers, but I'm confident it's necessary for the Kubeflow pod, and fairly certain the taskmanager pod needs it as well.

Adding it to the Kubeflow pod needs to be done with the container_ops so they are added to the argo config:

```
def _mount_required_secret_op(secret_name):
  def mount_secret(container_op):
    secret_ref = k8s_client.V1ConfigMapEnvSource(
        name=secret_name, optional=False)
    container_op.container.add_env_from(
        k8s_client.V1EnvFromSource(secret_ref=secret_ref))

  return mount_secret

runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(
    kubeflow_metadata_config=metadata_config,
    tfx_image=tfx_image,
    pipeline_operator_funcs=[
        _mount_required_secret_op('s3-env-secret'),
        kubeflow_dag_runner._mount_config_map_op('metadata-grpc-configmap'),
    ])
```

Hope that helps.

**Comment by ConverJens** [comment]
@vaskozl Thanks for your response!

Just to clarify, without setting the additional evn vars only Transform failed?

Seems a bit odd though, since I was able to run at least ExampleGen, StatsGen and SchemaGen (which all require beam) by only specifying beam args and env vars through container_ops, nothing in the job- or taskmanager. That was propagated nicely by beam, at least for beam 2.29 and flink 1.12.

I'll give this a try as soon as I have time and let you know if it worked for me as well.

Thanks for the help!

**Comment by vaskozl** [comment]
Yes, I seem to have experienced exactly the same, ExampleGen ran fine without the vars and even the some of Transform steps before the failure indicated that it was accessing the bucket. I think it comes down to to different libraries used across the entire setup not all using the beam args.

**Comment by ConverJens** [comment]
@vaskozl Very interesting! Again, thanks and I will get back to you when I have tested.

**Comment by ConverJens** [comment]
@vaskozl Setting the envs on the task-manger solves this. Great catch!

**Comment by ConverJens** [comment]
Ping @ibzib. From @vaskozl solution, this seems to be a bug in how TFX is inconsistent in its file system handling. Any ideas?

**Comment by singhniraj08** [comment]
@ConverJens,

This issue will be resolved by the commit https://github.com/tensorflow/transform/commit/265d23231fff56cd6f0599a864d81600ffc5ff47 as tensorflow_io import in TF Transform will unblock the S3 filesystem access. Kindly let us know if this issue can be closed. Thank you!
