### ISSUE TITLE
Parameterized pipelines using Kubeflow? 

### ISSUE THREAD

**Issue by htahir1** [tensorflow/tfx#362]
hi again! As you can see im a new and very excited user of the technology and have so many questions as I want to implement TFX in our company's workflows and want to convince everyone of it as well! (P.S. if theres a way for me not to bombard this board and just ask questions on another format, I would be do that).

This time I wanted to ask about Kubeflow pipelines. In Kubeflow, it is relatively easy to just specify parameters that can be changed on the UI (see image below). This lets you run the same pipeline with different configurations (i.e. different feature transforms, different hyper parameters, different model types even)

However, I am not sure how TFX solves this problem. It is surely an important point - If pipelines are not parameterized, how can we re-use them and run them again and again? Do we always have to edit our codebase (i.e. tf.transform preprocessing_fn, training_fn etc) and upload a new pipelines each time?  If that is the case, is the ML metadata shared across pipelines or is there a ML metadata store per pipeline? Specifically, if cache is enabled and we have two pipelines (A and B) with the same first examplegen, schemagen and statisticsgen code and then different transform and train code, and we run pipeline A, and then we run pipeline B on the same inputs, would pipeline B be 'aware' enough to skip the first three component steps?

I hope the example illustrates what im asking. If not, i can clarify. Thanks in advance!

![pipelines-start-xgboost-run](https://user-images.githubusercontent.com/4792082/61516319-0790cf80-aa05-11e9-8c70-07ee95f19383.png)

**Comment by neuromage** [comment]
Thanks for the detailed request. We are planning on adding pipeline level parameters that should ideally translate to both Kubeflow and Airflow configurable runtime parameters. We will update this issue once we have a more concrete plan on how to do this.

/cc @ruoyu90

**Comment by htahir1** [comment]
Okay thanks for the update. Is there a current workaround? How do we then re-run pipelines with slight different configurations?

**Comment by 1025KB** [comment]
as long as inputs are the same, component will be cached,

in our chicago taxi example, metadata is per pipeline as metadata path contains pipeline name in it, but it's not required

**Comment by htahir1** [comment]
i see. can you also please explain how the inputs are compared? So for example, if the input is a google storage bucket, will it go in and check what was in that storage bucket? or will it just see that the URL is the same and skip the whole thing

**Comment by 1025KB** [comment]
for kubeflow, cache isn't enabled yet,
for airflow or beam orchestrator (in 1.14 release), we check all input artifact, exec_properties to decide whether to skip a component, details can be found [here](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/metadata.py#L388)

for input, we check URL instead of content as component input artifact is immutable, for external input of example gen we add a fingerprint(1.14 release) to the input artifact to make sure we treat updated input as a new input artifact

**Comment by jinnovation** [comment]
@neuromage: Thanks for the updates. I'd be eager to hear about any news that comes out of this. My team at Twitter is looking into adopting TFX for our own Airflow-based workflow product and I think a story around runtime parametrization with Airflow support will be crucial moving forward.

I see, for instance, that #373 introduces `RuntimeParameter`. Looking forward to seeing what new developments arise.

**Comment by jiyongjung0** [comment]
We added runtime parameter support a while ago. For example, you can use runtime parameters including TFX CLI after 1.3.0. https://github.com/tensorflow/tfx/blob/master/RELEASE.md#version-130

Let me close this for now. Please reopen if you need.
