### ISSUE TITLE
Component Specific Cache

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [tensorflow/tfx#3646]
**System information**

- TFX Version (you are using): 0.28
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): GCP
- Are you willing to contribute it (Yes/No): nNo

Is there any way to cache specific components instead of caching all the components if setting `enable_cache=True`? We usually use `BigQueryExampleGen` as data input and use the `Transformation` component to do transformations. Oftentimes, we found that we have to try several ways of transformation during the pipeline building / experimentation. So more specifically, is there a way to cache the `BigQueryExampleGen` every time and run different `Transformation`, or fixing both `BigQueryExampleGen` / `Transformation` but run the Trainer with various setups?

**Comment by ruoyu90** [comment]
Hi @EdwardCuiPeacock , we are working on an enhanced version of cache to let you directly express which components to be cached directly, instead of "possibly being cached". Please stay tuned for that.

**Comment by EdwardCuiPeacock** [comment]
@ruoyu90 That sounds fantastic! Thanks for doing this.

**Comment by casassg** [comment]
Is there plans for RFC or code review for this? (could this solve the need for a custom driver on ExampleGen?)
