### ISSUE TITLE
Tensorflow_text not found when pipeline run in KubeFlow

### ISSUE THREAD

**Issue by RossKohler** [tensorflow/tfx#3679]
**System information**

- Have I specified the code to reproduce the issue(Yes/No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): KubeFlow
- TensorFlow version (you are using): ^2.4.1
- TFX Version: 0.28.0
- Python version: 3.7.9

**Describe the current behavior**

When trying to run my pipeline using the LocalDAGRunner everything runs correctly, the below issues only appear when attempting to run the pipeline in KubeFlow. 

Info messages stating `INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'`. When trying to use ops/functions associated with the library I receive `ModuleNotFoundError: No module named 'tensorflow_text'` notably when I try and register the ops through TensorFlow by `import tensorflow_text as text`.

I've made sure to install the packages with the code below before an attempt is made to try and import them:
```
for package in ["tensorflow-text==2.4.3", "python-dotenv", "kfp", "bs4"]:
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
```
.

I've noticed that in the logs of every component the following info messages are printed:
```
INFO:absl:tensorflow_ranking is not available: No module named 'tensorflow_ranking'
INFO:absl:tensorflow_text is not available: No module named 'tensorflow_text'
```
This seems like it may be related to my problem. How can I get around this? Any advice would be greatly appreciated.

**Comment by arghyaganguly** [comment]
@RossKohler , thanks for reporting the issue.Is your Kubernetes cluster running on GCP(GKE) or a local machine?
If so, please provide the pip freeze output using [link.](https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies)

**Comment by RossKohler** [comment]
@arghyaganguly thanks for the response. I'm working on a Kubernetes cluster running in GCP.  I'm managed to resolve the issue by using the latest TFX image. The logs complaining about `tf-ranking` and `tf-text` being missing in every component appears to be gone and my model is now training. There must have been some issue around this in the 0.28.0 image.

**Comment by dimitreOliveira** [comment]
Hi @RossKohler , I am also having this same issue but using different versions with GCP tools.

Kubeflow Pipelines version: 1.4.1
TensorFlow version (you are using): 2.5.0
TFX Version:  1.0.0-rc1

How did you managed to change the TFX image at the Kubernetes cluster? My code is similar to this example (https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines#7_run_your_first_tfx_pipeline_on_kubeflow), but I am using a BERT model that requires `tensorflow-text`
