### ISSUE TITLE
"Page not found" error for "deploying the Kubeflow cluster" in TFX User Guide

### ISSUE THREAD

**Issue by Arghya999** [tensorflow/tfx#3684]
Thank you for submitting a TFX documentation issue. Per our GitHub policy, we
only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub and we welcome external contributions!

The TFX docs are open source! To get involved, please read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: 
https://www.kubeflow.org/docs/started/getting-started-gke/

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/guide#creating_a_tfx_pipeline_with_kubeflow
### Clear description:
"Page not found" error for "deploying the Kubeflow cluster" in TFX User Guide

For example, why should someone use this method? How is it useful?

### Correct links
Replacement link?
https://www.kubeflow.org/docs/started/installing-kubeflow/

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,

https://www.tensorflow.org/tfx/guide/examplegen

### Request visuals, if applicable

Are there currently visuals? If so, do they look correct? If not, will it
clarify the content?

**Comment by arghyaganguly** [comment]
A PR has been raised to address this issue.Thanks.
