### ISSUE TITLE
Serialized EvalConfig too large in some circumstances

### ISSUE THREAD

**Issue by rclough** [tensorflow/tfx#3692]
Pardon if you'd rather this be committed to TFMA repo, but the issue is at least partially the responsibility of TFX (input serialization/running on k8s/kubeflow), although the other part of it is the issue of default metrics implementation in TFMA.

**System information**

- Have I specified the code to reproduce the issue(Yes/No):
Yes (see below)
- Environment in which the code is executed:
MacOS -> Kubeflow
- TensorFlow version (you are using):
2.4.1
- TFX Version:
0.27
- Python version:
3.6

**Describe the current behavior**

There are some TFMA metrics that, depending on the inputs, when serialized, prevent k8s pods from being started because the YAML/pod definition is too large, resulting in the following error in kubeflow:

```
This step is in Error state with this message: Pod "tfx-simple-pipeline-bpmv9-4151802195" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

As a concrete example, if you include AUC or ROC in your `MetricsSpec`, the default number of thresholds is 10,000 and the individual thresholds are enumerated in an array that gets serialized into the input, making the input size inordinately long (see the last section, "other info/logs"). TFMA has convenience functions that create default metrics for various problem types which include AUC at default values, such as `tfma.metrics.default_binary_classification_specs()`. Similarly, you will get the same issue with `tfma.default_multi_class_classification_specs()` because it also includes metrics from the aforementioned binary classification specs function.

This error has also been reported once before, but was closed by the reporter without explanation in #2079

The issue is particularly problematic because the resulting error gives no indication that the metrics spec/eval config would be the cause - many of our users are not experts in k8s or kubeflow, and in some extreme cases, the size of the resulting YAML makes it impossible to view the info in the kubeflow UI, making it vey difficult to pinpoint the issue even if you do know what to look at. 

**Describe the expected behavior**

Ideally there would be a better method of serializing metrics like AUC without enumerating the 10,000 thresholds in the input config, so that such an issue would be nearly impossible to encounter. Alternatively, it might be better to make the default number of thresholds something more tenable for a k8s serialized pipeline, like 100-200, but this would make the ticket a TFMA issue (and of course would be a breaking change).

**Workarounds**

We've had a few of our users run into this issue over the past 6 months. Our current workaround is to have them copy-paste the `default_binary_classification_specs` implementation locally, and include a smaller number of thresholds for the relevant metrics. 

**Standalone code to reproduce the issue**

We've tested this with the taxi pipeline as a binary classification with an Estimator, and using KubeflowDAGRunner. The relevant portion for testing is the following example Evaluator configuration:

```python

    test_eval_config_binary = tfma.EvalConfig(
        metrics_specs=tfma.metrics.default_binary_classification_specs(),
        slicing_specs=[
            tfma.SlicingSpec(),
            tfma.SlicingSpec(feature_keys=["trip_start_hour"]),
        ],
    )

    evaluator = Evaluator(
        examples=example_gen.outputs["examples"],
        model=trainer.outputs["model"],
        eval_config=test_eval_config_binary,
    )
```

**Name of your Organization (Optional)**
Spotify

**Other info / logs**

Here's what the resulting serialized pod/component definition ends up looking like. It's lightly sanitized. Had to upload to a gist sincee its too long to include in a github issue: https://gist.github.com/rclough/8f8bfaa2997f163b2c45ea2628f1f1df

**Comment by embr** [comment]
This was fixed in Keras in https://github.com/keras-team/keras/commit/99820e70d7d42100437441c975ff726feca53d32 which is available in the `tf-nightly` package but not yet in the `tensorflow` package. Keras is in the middle of (or possibly just finished) being split out from the main TF repo / pypi package, so I'm not certain about the timeline for when this will be available in the `tensorflow` package.

**Comment by gowthamkpr** [comment]
@rclough Can you use the latest version of tfx as this issue should be fixed by now. Please let me know if you run into any issues. Thanks!!

**Comment by zhitaoli** [comment]
Suggesting to close this issue since new version of TF(X) are available now.

Please discuss with @1025KB if more work is necessary.
