### ISSUE TITLE
CsvExampleGen does not adhere to spec: FileBaseExampleGen has required parameter output_data_format, but CsvExampleGen does not have it at all

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tfx#3725]
The following commit has added required parameter `output_data_format` to spec and FIleBasedExampleGen.
https://github.com/tensorflow/tfx/commit/8896c1a4bb06f0499b5c73eac85ecc91d25cb1d1
```
## Breaking changes
*   Added required 'output_data_format' execution property to FileBaseExampleGen.
```

But the CsvExampleGen was not updated accordingly.

`output_data_format` should be added to `CsvExampleGen`

Update: I see more discrepancies:

CsvExampleGen:
```
      input: Optional[types.Channel] = None,  # pylint: disable=redefined-builtin
      input_base: Optional[Text] = None,
      input_config: Optional[Union[example_gen_pb2.Input, Dict[Text, Any]]] = None,
      output_config: Optional[Union[example_gen_pb2.Output, Dict[Text, Any]]] = None,
      range_config: Optional[Union[range_config_pb2.RangeConfig, Dict[Text, Any]]] = None,
      example_artifacts: Optional[types.Channel] = None,
```
FileBasedExampleGenSpec
```
  PARAMETERS = {
      'input_base': ExecutionParameter(type=(str, Text)),
      'input_config': ExecutionParameter(type=example_gen_pb2.Input),
      'output_config': ExecutionParameter(type=example_gen_pb2.Output),
      'output_data_format': ExecutionParameter(type=int),  # example_gen_pb2.PayloadType enum.
      'custom_config': ExecutionParameter(type=example_gen_pb2.CustomConfig, optional=True),
      'range_config': ExecutionParameter(type=range_config_pb2.RangeConfig, optional=True),
  }
  INPUTS = {}
  OUTPUTS = {
      'examples': ChannelParameter(type=standard_artifacts.Examples),
  }
```

CsvExampleGen has extra input `input`, but does not have `output_data_format` and `custom_config`. Also the output is called `example_artifacts` instead of `examples`.

**Comment by singhniraj08** [comment]
@Ark-kun,

Referring to out latest [code](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/csv_example_gen/component.py#L75), I don't see extra `input` parameter in `CsvExampleGen`. 
And could you please share with us the use-case for implementing `output_data_format` and `custom_config` parameter in CsvExampleGen, so we can discuss this internally and work on implementing this. Thanks.
