### ISSUE TITLE
Component interfaces may not match the declared specs

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tfx#3726]
See issue https://github.com/tensorflow/tfx/issues/3725

Perhaps BaseComponent should check whether derived component interface follows the declared spec.

More examples:

StatisticsGen.stats_options vs StatisticsGenSpec.stats_options_json

**Comment by DanielKim0** [comment]
Hello! I would like to handle this issue.

**Comment by singhniraj08** [comment]
@Ark-kun,

You can follow the steps as shown [here](https://www.tensorflow.org/tfx/guide/custom_component#component_interface), to create a custom component interface. 
When an instance of the custom component is created, type checking logic in the `base_component.BaseComponent` class will be invoked to ensure that the arguments which were passed in are compatible with the type info defined in the `ComponentSpec` class.

Kindly let us know if this works for you. Thank you!
