### ISSUE TITLE
TFX log level is incompatible with GCP AI Platform Training service

### ISSUE THREAD

**Issue by glenxiao** [tensorflow/tfx#3734]
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),Linux
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version: 2.4.1
- TFX Version: 0.29.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**
AI Platform training service takes TFX INFO log as ERROR. 
<img width="1031" alt="Screen Shot 2021-05-13 at 12 53 00 PM" src="https://user-images.githubusercontent.com/72097584/118179471-32be8d00-b3ea-11eb-9249-e2b1b974a0a5.png">

**Describe the expected behavior**
AI Platform training service should use the same log level as TFX log. 

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by gaikwadrahul8** [comment]
@glenxiao 

Apologies for the delay and We highly recommend to test all the components of TFX pipeline in local environment whether they're running as expected with the help of `InteractiveContext()` as mentioned [here](https://blog.tensorflow.org/2019/11/introducing-tfx-interactive-notebook.html) and even you can create your own helper functions with the help of python to track all the logs, you can refer this official documentation [here](https://docs.python.org/2/library/logging.html) and GCP AI platform also handles some common errors in training service, you can refer official documentation [here](https://cloud.google.com/ai-platform/training/docs/understanding-training-service#common-errors)

I hope it will help you to resolve your issue if issue still persists please let us know ?

Thank you!
