### ISSUE TITLE
Update TFX python dependency constraint to allow TensorFlow 2.5.0 

### ISSUE THREAD

**Issue by emveee** [tensorflow/tfx#3794]
Please update TFX python dependency constraint to allow TensorFlow 2.5.0. As of right now only TensorFlow 2.4.1 and below are supported but TensorFlow 2.4.1 has many critical/high vulnerabilities which have been patched in TensorFlow 2.5.0

```
[jovyan@2b08f11f4755 venv]$ poetry add tfx --python ">=3.8,<3.9"
Using version ^0.30.0 for tfx

Updating dependencies
Resolving dependencies... (0.1s)

  SolverProblemError

  Because tfx (0.30.0) depends on tensorflow (>=1.15.2,<2.0.0 || >=2.4.0,<2.5.0 || >=2.6.0,<3)
   and no versions of tfx match >0.30.0,<0.31.0, tfx (>=0.30.0,<0.31.0) requires tensorflow (>=1.15.2,<2.0.0 || >=2.4.0,<2.5.0 || >=2.6.0,<3).
  So, because venv depends on both tensorflow (2.5.0) and tfx (^0.30.0), version solving failed.

  at /opt/jupyter/venv/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by dhruvesh09** [comment]
Thank you @emveee for reporting this issue, we are in the process of updating the TF version in the upcoming TFX release. You can also use the nightly package of TFX which has TF==2.5.0 by running
pip install -i https://pypi-nightly.tensorflow.org/simple/ tfx and let us know if you still face an issue.

**Comment by emveee** [comment]
@dhruvesh09 have you tested this? I am getting dependency conflicts..
`docker-bash python:3.8.10
root@1673b2a5c11c:/# pip install -i https://pypi-nightly.tensorflow.org/simple/ tfx
Looking in indexes: https://pypi-nightly.tensorflow.org/simple/
Collecting tfx
  Downloading https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-0.30.0-py3-none-any.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 1.4 MB/s
Collecting grpcio<2,>=1.28.1
  Downloading grpcio-1.37.1-cp38-cp38-manylinux2014_x86_64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 2.9 MB/s
Collecting keras-tuner<1.0.2,>=1
  Downloading keras-tuner-1.0.1.tar.gz (54 kB)
     |████████████████████████████████| 54 kB 1.6 MB/s
Collecting tfx
  Downloading https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-0.29.0-py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.1 MB/s
  Downloading https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-0.26.4-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 2.5 MB/s
  Downloading https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-0.26.3-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 1.3 MB/s
ERROR: Cannot install tfx==0.26.3, tfx==0.26.4, tfx==0.29.0 and tfx==0.30.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    tfx 0.30.0 depends on tensorflow-data-validation<0.31 and >=0.30
    tfx 0.29.0 depends on ml-metadata<0.30 and >=0.29
    tfx 0.26.4 depends on tensorflow-transform<0.27 and >=0.26
    tfx 0.26.3 depends on tensorflow-transform<0.27 and >=0.26

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

**Comment by emveee** [comment]
specifying 1.0.0.rc0 also does not work..
`root@1673b2a5c11c:/# pip install -i https://pypi-nightly.tensorflow.org/simple/ tfx==1.0.0rc0
Looking in indexes: https://pypi-nightly.tensorflow.org/simple/
Collecting tfx==1.0.0rc0
  Downloading https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-1.0.0rc0-py3-none-any.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 1.2 MB/s
Collecting click<8,>=7
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting pyyaml<6,>=3.12
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow-transform<0.31,>=0.30 (from tfx) (from versions: 0.26.0.dev20201122, 0.26.0.dev20201123, 0.26.0.dev20201124, 0.26.0.dev20201125, 0.26.0.dev20201126, 0.26.0.dev20201127, 0.26.0.dev20201128, 0.26.0.dev20201129, 0.26.0.dev20201130, 0.26.0.dev20201201, 0.26.0.dev20201202, 0.26.0.dev20201203, 0.26.0.dev20201204, 0.26.0.dev20201205, 0.26.0.dev20201206, 0.26.0.dev20201207, 0.26.0.dev20201208, 0.26.0.dev20201209, 0.26.0.dev20201210, 0.26.0.dev20201211, 0.26.0.dev20201215, 0.26.0.dev20201216, 0.27.0.dev20201216, 0.27.0.dev20201217, 0.27.0.dev20201218, 0.27.0.dev20201219, 0.27.0.dev20201220, 0.27.0.dev20201221, 0.27.0.dev20201223, 0.27.0.dev20201224, 0.27.0.dev20201225, 0.27.0.dev20201226, 0.27.0.dev20201227, 0.27.0.dev20201228, 0.27.0.dev20201229, 0.27.0.dev20201230, 0.27.0.dev20201231, 0.27.0.dev20210101, 0.27.0.dev20210102, 0.27.0.dev20210103, 0.27.0.dev20210104, 0.27.0.dev20210105, 0.27.0.dev20210106, 0.27.0.dev20210107, 0.27.0.dev20210108, 0.27.0.dev20210109, 0.27.0.dev20210110, 0.27.0.dev20210111, 0.27.0.dev20210112, 0.27.0.dev20210113, 0.27.0.dev20210114, 0.27.0.dev20210115, 0.27.0.dev20210116, 0.27.0.dev20210117, 0.27.0.dev20210118, 0.27.0.dev20210119, 0.27.0.dev20210120, 0.27.0.dev20210121, 0.27.0.dev20210122, 0.27.0.dev20210123, 0.27.0.dev20210124, 0.27.0.dev20210125, 0.27.0.dev20210126, 0.27.0.dev20210127, 0.28.0.dev20210128, 0.28.0.dev20210129, 0.28.0.dev20210130, 0.28.0.dev20210201, 0.28.0.dev20210202, 0.28.0.dev20210203, 0.28.0.dev20210204, 0.28.0.dev20210205, 0.28.0.dev20210206, 0.28.0.dev20210207, 0.28.0.dev20210208, 0.28.0.dev20210209, 0.28.0.dev20210210, 0.28.0.dev20210211, 0.28.0.dev20210212, 0.28.0.dev20210213, 0.28.0.dev20210214, 0.28.0.dev20210215, 0.28.0.dev20210216, 0.28.0.dev20210217, 0.28.0.dev20210218, 0.28.0.dev20210219, 0.28.0.dev20210220, 0.28.0.dev20210221, 0.28.0.dev20210222, 0.28.0.dev20210223, 0.29.0.dev20210224, 0.29.0.dev20210225, 0.29.0.dev20210226, 0.29.0.dev20210227, 0.29.0.dev20210228, 0.29.0.dev20210301, 0.29.0.dev20210302, 0.29.0.dev20210303, 0.29.0.dev20210304, 0.29.0.dev20210305, 0.29.0.dev20210306, 0.29.0.dev20210307, 0.29.0.dev20210308, 0.29.0.dev20210309, 0.29.0.dev20210310, 0.29.0.dev20210311, 0.29.0.dev20210312, 0.29.0.dev20210313, 0.29.0.dev20210314, 0.29.0.dev20210315, 0.29.0.dev20210316, 0.29.0.dev20210317, 0.29.0.dev20210318, 0.29.0.dev20210319, 0.29.0.dev20210320, 0.29.0.dev20210321, 0.29.0.dev20210322, 0.29.0.dev20210323, 0.29.0.dev20210324, 0.29.0.dev20210325, 0.30.0.dev20210326, 0.30.0.dev20210327, 0.30.0.dev20210328, 0.30.0.dev20210329, 0.30.0.dev20210330, 0.30.0.dev20210331, 0.30.0.dev20210401, 0.30.0.dev20210402, 0.30.0.dev20210403, 0.30.0.dev20210404, 0.30.0.dev20210405, 0.30.0.dev20210406, 0.30.0.dev20210407, 0.30.0.dev20210408, 0.30.0.dev20210409, 0.30.0.dev20210410, 0.30.0.dev20210411, 0.30.0.dev20210412, 0.30.0.dev20210413, 0.30.0.dev20210414, 0.30.0.dev20210415, 0.30.0.dev20210416, 0.30.0.dev20210417, 0.30.0.dev20210418, 0.30.0.dev20210419, 0.30.0.dev20210420, 0.30.0.dev20210421, 0.30.0.dev20210422, 0.30.0.dev20210423, 0.30.0.dev20210424, 0.30.0.dev20210425, 0.30.0.dev20210426, 0.31.0.dev20210427, 0.31.0.dev20210428, 0.31.0.dev20210429, 0.31.0.dev20210430, 0.31.0.dev20210501, 0.31.0.dev20210502, 0.31.0.dev20210503, 0.31.0.dev20210504, 0.31.0.dev20210505, 0.31.0.dev20210506, 0.31.0.dev20210507, 0.31.0.dev20210508, 0.31.0.dev20210511, 0.31.0.dev20210512, 0.31.0.dev20210513, 0.31.0.dev20210514, 0.31.0.dev20210515, 0.31.0.dev20210516, 0.31.0.dev20210517, 0.31.0.dev20210518, 0.31.0.dev20210519, 0.31.0.dev20210520)
ERROR: No matching distribution found for tensorflow-transform<0.31,>=0.30`

**Comment by emveee** [comment]
poetry has the same issue, still showing tensorflow <2.5.0 as a constraint on the nighly TFX 0.30.0 and 1.0.0rc0 

```
[jovyan@2b08f11f4755 venv]$ poetry add https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-0.30.0-py3-none-any.whl --python ">=3.8,<3.9"

Updating dependencies
Resolving dependencies... (1.9s)

  SolverProblemError

  Because tfx (0.30.0) depends on tensorflow (>=1.15.2,<2.0.0 || >=2.4.0,<2.5.0 || >=2.6.0,<3)
   and venv depends on tensorflow (2.5.0), tfx is forbidden.
  So, because venv depends on tfx (0.30.0), version solving failed.

  at /opt/jupyter/venv/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
[jovyan@2b08f11f4755 venv]$ poetry add https://pypi-nightly.tensorflow.org/api/package/tfx/tfx-1.0.0rc0-py3-none-any.whl --python ">=3.8,<3.9"

Updating dependencies
Resolving dependencies... (2.6s)

  SolverProblemError

  Because tfx (1.0.0rc0) depends on tensorflow (>=1.15.2,<2.0.0 || >=2.4.0,<2.5.0 || >=2.6.0,<3)
   and venv depends on tensorflow (2.5.0), tfx is forbidden.
  So, because venv depends on tfx (1.0.0rc0), version solving failed.

  at /opt/jupyter/venv/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by dhruvesh09** [comment]
Can you try to pip install -i https://pypi-nightly.tensorflow.org/simple/ tfx==20210519

This worked for me

**Comment by suryaavala** [comment]
hey @emveee i've had a similar issue, for some reason poetry is not able to add tfx 0.3.0 with python ">=3.8".

However, when I used tfx==1.0.0-rc0 with python ">=3.8", it seems to be working.

Could you please try `poetry add tfx==1.0.0-rc0 --python ">=3.8,<3.9"`?

**Comment by dhruvesh09** [comment]
Closing the issue due to inactivity.
