### ISSUE TITLE
No serving_model_dir exported when using BoostedTreesClassifier

### ISSUE THREAD

**Issue by rclough** [tensorflow/tfx#3804]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes
- Environment in which the code is executed: Compiled on Mac, executed on kubeflow
- TensorFlow version: 2.4.1
- TFX Version: 0.27
- Python version: 3.6

**Describe the current behavior**
Apologies if this is more of a tensorflow issue, I can move the issue there, but I suspect it may have to do with how the TFX component handles managing Estimator training.

When training a `BoostedTreesClassifier` using the **Estimator** Trainer executor, there are certain circumstances that seem to result in a saved_model.pb not being published to the `serving_model_dir`. In this particular case, it could be when the maximum number of trees is reached before training hits the allotted `training_steps`, because the model will stop training early, [per documentation](https://www.tensorflow.org/tutorials/estimator/boosted_trees). Indeed, if you do not set the `train_steps`, which would otherwise train indefinitely if theres no early stop, training will stop when max trees are reached, but the model is still not exported.

I'm not sure if there's a workaround for cases like this or other early stopping methods that may exist for other models, if there is, then the solution isn't clear/should be documented.

**Describe the expected behavior**
I expect a saved_model.pb to be exported to `serving_model_dir` regardless of when training stops.

**Standalone code to reproduce the issue**

This can be replicated with the [taxi example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_utils.py) by simply replacing the model (ie `_build_estimator`) with a `BoostedTreesClassifier`, something like:

```python
def _build_estimator(config, warm_start_from=None):
    # ... feature columns stuff

   
    n_batches_per_layer: int = 5
    n_trees: int = 5 # Set a small number of trees to ensure you hit this before hitting the train steps
    max_depth: int = 7
    learning_rate: float = 0.01
    l1_regularization: float = 0.0
    l2_regularization: float = 0.0

    estimator = tf.estimator.BoostedTreesClassifier(
        config=config,
        feature_columns=real_valued_columns,
        n_batches_per_layer=n_batches_per_layer,
        n_trees=n_trees,
        max_depth=max_depth,
        center_bias=True,
        learning_rate=learning_rate,
        l1_regularization=l1_regularization,
        l2_regularization=l2_regularization,
    )
```

And making sure you have a high enough number of train steps (5000 is plenty in my testing).

I'm not sure if this is reproducible in local or notebook mode.

**Name of your Organization (Optional)**
Spotify

**Comment by AlirezaSadeghi** [comment]
Hey! 

I also had to deal with these irregular behaviors of the BoostedTreesClassifier, also posted a _SO_ question on it [here](https://stackoverflow.com/questions/65564663/using-tensorflow-estimators-with-dataset-api-results-in-strange-steps-behavior).

Due to this behavior that training will stop when max trees is reached (in my experience, it always stopped before MAX_DEPTH * NUM_TREES steps), I had to increase the batch_size to include all my training data, so that I'm sure at every step, all the data is being considered. I'm not sure if it's the correct way, but would be keen on how you guys are using it and if it trains above a certain number of steps.

**Comment by revathijay** [comment]
I had the same issue while training BoostedTreesClassifier.@rclough  is there some way to get around this atm?

**Comment by rclough** [comment]
@AlirezaSadeghi Thanks for the insight! I've seen docs on TF that single batch is the best approach

@revathijay take  look at the comment above for how to get around it - you just need to set your num steps based on your expected max trees and ideally batch all or most of the dataset (make sure you have enough memory)

It has since been revealed to me that this is unfortunately a limitation with the `Estimator` API in general - [indeed the TFX docs state](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate?hl=en#:~:text=Stop%20condition%3A%20In,of%20one%20epoch.):
> Stop condition: In order to support both distributed and non-distributed configuration reliably, the only supported stop condition for model training is train_spec.max_steps. If train_spec.max_steps is None, the model is trained forever. Use with care if model stop condition is different.

This makes the design of the BoostedTreesClassifier seem at odds with Estimator API, since it has a built in stop condition, but such is life. The Estimator API is old now and not really actively maintained beyond actual bug reports

**Comment by gaikwadrahul8** [comment]
@rclough 

Apologies for the delay and Estimators are not recommended for new code. Estimators run [v1.Session](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session)-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. You can refer this official documentation [here](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#:~:text=Warning%3A%20Estimators,guide%20for%20details.)

You can refer these Github issues which are related to memory while using `BoostedTreesClassifier` here [[1](https://github.com/tensorflow/tensorflow/issues/34118)] [[2](https://github.com/tensorflow/tensorflow/issues/30319)] and I would suggest you to please have look in the migration guide [here](https://www.tensorflow.org/guide/migrate?_gl=1*1f7c140*_ga*MTQ3MDY0NjMzNS4xNjY1NzUyMDY1*_ga_W0YLR4190T*MTY3MDQwNTI3NC44OS4xLjE2NzA0MDcyODIuMC4wLjA.) 

Could you please let us know if it helps to resolve your issue ?

Thank You!
