### ISSUE TITLE
Some updates in the README file 

### ISSUE THREAD

**Issue by Kareem-negm** [tensorflow/tfx#3814]
Hi, I added some updates in the README file and waiting for merge it or feedback at lest 
you can see my updates in the pull requests or [here](https://github.com/Kareem-negm/tfx)
I want to get feedback about my contributions from the community here
is this good? what can I do too? and more advice 
I learn and contribute to the TFX project because I love it and want to be a part of its community 

Thanks

**Comment by arghyaganguly** [comment]
@Kareem-negm , thanks for your interest in contributing to tfx.Please raise PRs in [link](https://github.com/tensorflow/tfx/pulls).
Thanks.

**Comment by Kareem-negm** [comment]
Hi @arghyaganguly  I made a pull request and raise it, you can find it [here]( https://github.com/tensorflow/tfx/pull/3805)
