### ISSUE TITLE
Upgrade to manylinux2014 to support AArch64 wheels

### ISSUE THREAD

**Issue by odidev** [tensorflow/tfx#3829]
Problem
---------
On aarch64, pip install ml-metadata builds the wheels from source code and then install it which takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
For building ml-metadata wheels for x86_64, cr.io/tfx-oss-public/manylinux2010-bazel image is getting used. As mentioned in [comment](https://github.com/google/ml-metadata/issues/114#issuecomment-833162455), we need similar image for aarch64.

Please let me know your interest on adding tfx image support for aarch64. I can help with this.

**Comment by dheaney** [comment]
Definitely interested in getting wheels for aarch64. Building manually from source (`python3.8 setup.py bdist_wheel`) on aarch64 succeeds, but the import causes Python to crash:

```bash
$ python3.8 setup.py bdist_wheel
# ...
$ python3.8 -m pip install dist/ml_metadata-1.1.0.dev0-cp38-cp38-linux_aarch64.whl
$ python3.8
Python 3.8.0 (default, Feb 25 2021, 22:10:10) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ml_metadata
free(): invalid pointer
Aborted
```

My build log is [here](https://gist.github.com/dheaney/9ad86a3437dbf38528affac48e3fce4e). Do you know if this fix would help? I'm guessing that it's an issue with TensorFlow or TCMalloc.

**Comment by dheaney** [comment]
Came here from a link on an issue in the the ml-metadata repo. Sorry if it's the wrong place.

**Comment by hughmiao** [comment]
@dheaney hey, DJ, recently we dropped tf dependency in the latest release. please try the manual build in aarch64 env again and see the error goes away.

**Comment by arghyaganguly** [comment]
@odidev ,  seems like this is fixed. Please reopen if required.
