### ISSUE TITLE
ML Metadata (MLMD) tutorial broken link

### ISSUE THREAD

**Issue by demoven** [tensorflow/tfx#3852]
Hello! I tried to follow "Better ML Engineering with ML Metadata" tutorial (https://github.com/tensorflow/tfx/blob/master/docs/tutorials/mlmd/mlmd_tutorial.ipynb), however when it comes to the dataset download step, it fails because the dataset path is broken.

**Code:**
```
DATA_PATH = 'https://raw.githubusercontent.com/tensorflow/tfx/master/tfx/examples/penguin/data/penguins_processed.csv'
_data_root = tempfile.mkdtemp(prefix='tfx-data')
_data_filepath = os.path.join(_data_root, "penguins_processed.csv")
urllib.request.urlretrieve(DATA_PATH, _data_filepath)
```

**Error:**
```
HTTPError                                 Traceback (most recent call last)

<ipython-input-32-ce58167a931c> in <module>
      2 _data_root = tempfile.mkdtemp(prefix='tfx-data')
      3 _data_filepath = os.path.join(_data_root, "penguins_processed.csv")
----> 4 urllib.request.urlretrieve(DATA_PATH, _data_filepath)

6 frames

/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found
```

I think that this link was moved, so I replaced it with the [new one](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/data/labelled/penguins_processed.csv) and it worked.

**Solution** (just change the link):

```
DATA_PATH = 'https://raw.githubusercontent.com/tensorflow/tfx/master/tfx/examples/penguin/data/labelled/penguins_processed.csv'
_data_root = tempfile.mkdtemp(prefix='tfx-data')
_data_filepath = os.path.join(_data_root, "penguins_processed.csv")
urllib.request.urlretrieve(DATA_PATH, _data_filepath)
```

This corrects the problem and rest of the tutorial runs in normal way. It may be useful for others who wants to run the tutorial without errors.

Thank you!

**Comment by arghyaganguly** [comment]
@demoven , thanks for reporting this bug.
[PR](https://github.com/tensorflow/tfx/pull/3830) has already been raised to address this issue.
