### ISSUE TITLE
Page Not Found for TFX 1.0 Tutorials : Adding Featuring Engineering

### ISSUE THREAD

**Issue by DARK-art108** [tensorflow/tfx#3857]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/tfx/tutorials/tfx/penguin_transform

**Comment by arghyaganguly** [comment]
@DARK-art108 , please use [link](https://www.tensorflow.org/tfx/tutorials/tfx/penguin_tft) to access Adding Feature Engineering.
Please let me know the location of the broken [link.][https://www.tensorflow.org/tfx/tutorials/tfx/penguin_transform]
