### ISSUE TITLE
Path to penguins_processed.csv

### ISSUE THREAD

**Issue by r-matsuzaka** [tensorflow/tfx#3859]
In https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/penguin_simple.ipynb, there is a mistake about path to `penguins_processed.csv`.
The correct path is `https://raw.githubusercontent.com/tensorflow/tfx/master/tfx/examples/penguin/data/labelled/penguins_processed.csv`

BTW, when I tried to do PR but I have no permission so I could not do it.
May I have a permission or I need to just raise issues?

**Comment by arghyaganguly** [comment]
Thanks for reporting the bug.You can raise PRs at [link.](https://github.com/tensorflow/tfx/pulls)

**Comment by arghyaganguly** [comment]
Closing this based on comment trace from [PR.](https://github.com/tensorflow/tfx/pull/3867)

**Comment by r-matsuzaka** [comment]
Thank you so much for fixing.
