### ISSUE TITLE
components_keras.ipynb: FileNotFoundError

### ISSUE THREAD

**Issue by r-matsuzaka** [tensorflow/tfx#3860]
**System information**

- Have I specified the code to reproduce the issue (Yes, No):Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows), Google Colab https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb#scrollTo=eZ4K18_DN2D8
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version:2.4.1
- TFX Version:
- Python version:3.7.10
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**
When I run ,
```
import os
import pprint
import tempfile
import urllib

import absl
import tensorflow as tf
import tensorflow_model_analysis as tfma
tf.get_logger().propagate = False
pp = pprint.PrettyPrinter()

from tfx import v1 as tfx
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext

%load_ext tfx.orchestration.experimental.interactive.notebook_extensions.skip
```

I got this error,

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in _dep_map(self)
   3015         try:
-> 3016             return self.__dep_map
   3017         except AttributeError:

23 frames
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in _get(self, path)
   1609 
   1610     def _get(self, path):
-> 1611         with open(path, 'rb') as stream:
   1612             return stream.read()
   1613 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/grpcio-1.34.1.dist-info/METADATA'
```
**Describe the expected behavior**

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by arghyaganguly** [comment]
@r-matsuzaka , I've tried reproducing in [gist](https://colab.research.google.com/gist/arghyaganguly/703f424418f497f8c69caec6a4f042a8/components_keras.ipynb#scrollTo=YrMj-ygOcUnP) but encountered no error.
Have you restarted the runtime after installing tfx?

**Comment by arghyaganguly** [comment]
@r-matsuzaka , please update.Thanks.

**Comment by r-matsuzaka** [comment]
@arghyaganguly 
Sorry for replying late.
I study tfx privately.
I will try again.

**Comment by r-matsuzaka** [comment]
@arghyaganguly 
The error does not occur after I restart runtime.
I did not read the caution.
Thank you so much.
