### ISSUE TITLE
Does anyone has example for with_beam_pipeline_args usage(TFX V 0.30 and above) ?

### ISSUE THREAD

**Issue by revathijay** [tensorflow/tfx#3863]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/guide
https://github.com/tensorflow/tfx/blob/2194c5cebe93b5e53666877fd7f9f747490cbe54/docs/guide/beam.md
Does anyone have an example with the .with_beam_pipeline_args per component

### Clear description:

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,

https://www.tensorflow.org/tfx/guide/examplegen

### Request visuals, if applicable

Are there currently visuals? If so, do they look correct? If not, will it
clarify the content?

**Comment by chongkong** [comment]
Many TFX components (including ExampleGen, StatisticsGen, StatisticsGen, Transform, Evaluator, BulkInferrer etc.) uses Apache Beam internally. In fact, Beam is almost the standard way of processing examples data. `beam_pipeline_args` is used to configure option for pipeline or per component, such as kind of runner (DirectRunner for local mode, DataflowRunner for cloud Dataflow, etc.), parallelism (numWorkers), and many others [1]. Some options are only meaningful when it is applied to the pipeline level, while some options are useful to apply per component (such as parallelism).

[1] https://cloud.google.com/dataflow/docs/guides/setting-pipeline-options#setting-other-cloud-dataflow-pipeline-options

**Comment by 1025KB** [comment]
Check this [guide](https://github.com/tensorflow/tfx/blob/master/docs/guide/beam.md#beam-pipeline-arguments )

**Comment by revathijay** [comment]
i am looking for examples where with the component level pipeline args can we switch between bigueryexamplegen direct runner and then run some of the other components in dataflow

**Comment by jacorelogic** [comment]
I believe you will need to create a custom component that runs BigQuery locally.

**Comment by 1025KB** [comment]
> i am looking for examples where with the component level pipeline args can we switch between bigueryexamplegen direct runner and then run some of the other components in dataflow

Different component can set its own with_beam_pipeline_args, it will overwrite the pipeline level beam_pipeline_args that set when creating tfx pipeline

**Comment by revathijay** [comment]
I tried with setting component level with_beam_pipeline_args but it was not overriding the pipeline level. Let me add the sample code

**Comment by 1025KB** [comment]
> > i am looking for examples where with the component level pipeline args can we switch between bigueryexamplegen direct runner and then run some of the other components in dataflow
> 
> Different component can set its own with_beam_pipeline_args, it will overwrite the pipeline level beam_pipeline_args that set when creating tfx pipeline

My bad, the component level args will extend the pipeline level args, not overwrite

**Comment by Eric-Le-Ge** [comment]
As a bit more context, the compiler does not determine overriding relationships because beam_pipeline_args is supplied as list of strings.
It is recommended to use pipeline level args only if it is the same across beam components.

> > > i am looking for examples where with the component level pipeline args can we switch between bigueryexamplegen direct runner and then run some of the other components in dataflow
> > 
> > 
> > Different component can set its own with_beam_pipeline_args, it will overwrite the pipeline level beam_pipeline_args that set when creating tfx pipeline
> 
> My bad, the component level args will extend the pipeline level args, not overwrite
> Resolution would be setting all conflicting args to be per component

**Comment by revathijay** [comment]
For some reason its just picking up pipeline level beam arguments and not the component level when I try to override at the component

**Comment by revathijay** [comment]
Does that mean that the whole pipeline will just work with one runner type and the only thing we can change is different options for that runner per component.  I was imagining I can set the runner option per component. 
Specifically, I want some components like examplegen to run with direct runner and transform to run with dataflowrunner in the same pipeline. It seems like this is not possible

**Comment by chongkong** [comment]
Can't you specify different runners for every component manually for a workaround?

**Comment by arghyaganguly** [comment]
@revathijay , closing this as there has been no response for sometime.
Please feel free to reopen based on @chongkong's comment.Thank you.

**Comment by axeltidemann** [comment]
@chongkong I tried not to have any pipeline-level beam arguments, instead specifying it for each component. Similar to @revathijay , I wanted the Transform component to run with DataflowRunner, the others with DirectRunner. However, the Transform component would still run with DirectRunner. Re-opening in case anyone can shed some more light on this.
