### ISSUE TITLE
Footprint/checksum for caching when additional user dependency is used

### ISSUE THREAD

**Issue by zhitaoli** [tensorflow/tfx#388]
Several components of TFX takes a user defined functions (preprocessing for transform and train_fun for trainer). Currently they come from a single python file so caching is still doable, but once the component is launched with additional dependencies (pip package or multiple files).

One idea is that additional user dependency should only be supported through docker image, and use image finger print (digest) or name:tag to make sure the cache is sound.

(This is a follow up discussion with Spotify)

**Comment by singhniraj08** [comment]
@zhitaoli,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
