### ISSUE TITLE
CsvExampleGen - 'tfx.utils.dsl_utils' module missing to load data from aws s3

### ISSUE THREAD

**Issue by nli045** [tensorflow/tfx#3891]
Hi,
According to the tfdv documentation, CsvExampleGen supports loading data from s3. I also found a blog post which shows doing so is as simple as running the following lines of command in Python:
`from tfx.utils.dsl_utils import external_input 
examples = external_input("s3://bucket/key/x.csv") 
example_gen = CsvExampleGen(input=examples)`

But I received this error: ModuleNotFoundError: No module named 'tfx.utils.dsl_utils'
My tfx version is 0.30.0

Appreciate if I can get some help on this.

**Comment by 1025KB** [comment]
external_input is removed in recent version, here is the [latest example](https://www.tensorflow.org/tfx/tutorials/tfx/penguin_simple)

**Comment by arghyaganguly** [comment]
Closing this as the issue has been lying stale without any update.Please feel free to reopen.
