### ISSUE TITLE
issue using tfx.proto to have customized split as input to CsvExampleGen 

### ISSUE THREAD

**Issue by nli045** [tensorflow/tfx#3892]
Hi,
According to the official documentation (https://www.tensorflow.org/tfx/guide/examplegen) I can split the input data by doing

```
from  tfx.proto import example_gen_pb2
output = proto.Output(
             split_config=example_gen_pb2.SplitConfig(splits=[
                 proto.SplitConfig.Split(name='train', hash_buckets=3),
                 proto.SplitConfig.Split(name='eval', hash_buckets=1)
             ]))
```

However I encountered this error: "NameError: name 'proto' is not defined"
My tfx version is 0.30.0

Appreciate that if someone can point out what I did wrong.

**Comment by arghyaganguly** [comment]
@nli045 ,thank you for reporting this bug.
I tried with this colab [gist.](https://colab.research.google.com/gist/arghyaganguly/afa457a8266fba07843cb870e1696415/copy-of-tfx-lab-1-pipeline-in-a-colab-notebook.ipynb#scrollTo=bRbSCw-U-h_F) and got the following errors:-

1)before restarting the runtime 

```
ERROR: pandas-gbq 0.13.3 has requirement google-cloud-bigquery[bqstorage,pandas]<2.0.0dev,>=1.11.1, but you'll have google-cloud-bigquery 2.20.0 which is incompatible.
ERROR: multiprocess 0.70.11.1 has requirement dill>=0.3.3, but you'll have dill 0.3.1.1 which is incompatible.
ERROR: jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 3.0.18 which is incompatible.
ERROR: google-colab 1.0.0 has requirement ipython~=5.5.0, but you'll have ipython 7.24.1 which is incompatible.
ERROR: google-cloud-storage 1.38.0 has requirement google-cloud-core<2.0dev,>=1.4.1, but you'll have google-cloud-core 1.0.3 which is incompatible.
ERROR: google-cloud-bigquery 2.20.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.29.0, but you'll have google-api-core 1.26.3 which is incompatible.
ERROR: google-cloud-bigquery 2.20.0 has requirement google-cloud-core<2.0dev,>=1.4.1, but you'll have google-cloud-core 1.0.3 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: google-cloud-spanner 1.19.1 has requirement google-cloud-core<2.0dev,>=1.4.1, but you'll have google-cloud-core 1.0.3 which is incompatible.
ERROR: google-cloud-bigtable 1.7.0 has requirement google-cloud-core<2.0dev,>=1.4.1, but you'll have google-cloud-core 1.0.3 which is incompatible.
ERROR: apache-beam 2.29.0 has requirement future<1.0.0,>=0.18.2, but you'll have future 0.16.0 which is incompatible.
ERROR: apache-beam 2.29.0 has requirement requests<3.0.0,>=2.24.0, but you'll have requests 2.23.0 which is incompatible.
```

2)after restarting runtime 

```
ERROR: google-cloud-bigquery 2.20.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.29.0, but you'll have google-api-core 1.26.3 which is incompatible.
ERROR: apache-beam 2.29.0 has requirement requests<3.0.0,>=2.24.0, but you'll have requests 2.23.0 which is incompatible. 
```

3)At the second cell, 

```
ModuleNotFoundError: No module named 'tfx.utils.dsl_utils'
```

**Comment by 1025KB** [comment]
> Hi,
> According to the official documentation (https://www.tensorflow.org/tfx/guide/examplegen) I can split the input data by doing
> 
> ```
> from  tfx.proto import example_gen_pb2
> output = proto.Output(
>              split_config=example_gen_pb2.SplitConfig(splits=[
>                  proto.SplitConfig.Split(name='train', hash_buckets=3),
>                  proto.SplitConfig.Split(name='eval', hash_buckets=1)
>              ]))
> ```
> 
> However I encountered this error: "NameError: name 'proto' is not defined"
> My tfx version is 0.30.0

The doc import is wrong, I will fix it,
the import should be `from tfx.v1 import proto`
you can check this for [latest tutorials](https://www.tensorflow.org/tfx/tutorials/tfx/penguin_simple)

> 
> Appreciate that if someone can point out what I did wrong.

**Comment by arghyaganguly** [comment]
Closing this as it has been fixed.
