### ISSUE TITLE
tensorflow_text operations not registered in BulkInferrer component

### ISSUE THREAD

**Issue by RossKohler** [tensorflow/tfx#3901]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/macOS/Windows),
  Interactive Notebook, Google Cloud, etc): Kubeflow
- TensorFlow version: 2.4.1
- TFX Version: 1.0.0rc0
- Python version: 3.7.1

I'm trying to use the `BulkInferrer` component in my TFX pipeline. My model has a BERT component and this relies on `tensorflow-text`. Components that require this module to run i.e. the `Transform` and `Trainer` components complete successfully. The exported model is passed directly to the `BulkInferrer` component at which point the following error is received, `Op type not registered 'RegexSplitWithOffsets' in binary `.  This is an operation that is imported with `tensorflow-text` so I feel like something is going wrong here. `tensorflow-text` is installed in the image using the following dockerfile:

```
FROM tensorflow/tfx:1.0.0rc0
WORKDIR /pipeline
COPY ./ ./
ENV PYTHONPATH="/pipeline:${PYTHONPATH}"
RUN /usr/bin/python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install tensorflow-text --no-dependencies
RUN python -c 'import tensorflow_text # Registers the ops.'
```
I see in the executor of `BulkInferrer` there's this line [here](https://github.com/tensorflow/tfx/blob/10ed4337b2e4bd2223912db495b8bffdc9c3e5b2/tfx/components/bulk_inferrer/executor.py#L40), this `import tensorflow_text as _` should be all that is required to register the operations with tensorflow. I've looked at the logs of my component and I don't see any exception raised signaling that this failed.

I'm fairly sure this isn't a TFX version issue as I've experienced the same error using TFX 0.27.0.

Could anyone from the TFX team please advise where I can look to try and figure out this issue? At this point, I'm stumped, since this has worked throughout the rest of my pipeline.

**Comment by jiyongjung0** [comment]
@RossKohler Thank you for the report!

This might be the issue from the difference between TF and TF-text. Could you let us know the exact version of tensorflow-text used? By the way, it might be a little better to install all python packages with a single pip command to make them more compatible. For example, `pip install tensorflow-text -r requirements.txt`.

Thanks!

**Comment by RossKohler** [comment]
@jiyongjung0 thanks for the speedy response!

I changed the dockerfile to include your suggestion and no luck :(

Running pip freeze in the container I get:

```
tensorflow-text==2.5.0
tensorflow==2.5.0
```
as far as I am aware those packages should be compatible. Like I said, `tensorflow-text` is clearly available in my `Transform` component as it's needed in a preprocessing step for my model. It's strange that it's suddenly not available in the `BulkInferrer`.

Anything else I can try?

**Comment by jiyongjung0** [comment]
Thank you for the information. Yes. TF and TF-text should be compatible as long as they have the same minor version.

Do you use Dataflow or other Beam-runner for the BulkInferrer? Or use the DirectRunner which is the default? Could you share more error traces or pod log?

**Comment by RossKohler** [comment]
@jiyongjung0 here's how I include the `BulkInferrer` in my pipeline:
```
    bulk_inferrer = BulkInferrer(
        examples=example_gen.outputs['examples'],
        model=trainer.outputs.model,
        data_spec=bulk_inferrer_pb2.DataSpec(example_splits=['eval'])
    )
    bulk_inferrer.with_id('bulk_infer_test_set')
```
I'm using the DirectRunner.

I've saved the logs from the pod into this gist [here](https://gist.github.com/RossKohler/3e75de11f9ec906616559f3360875e17)

**Comment by pjlast** [comment]
I can confirm this, I have a similar issue. The Ops generated by tensorflow-text is not saved with the transform graph in the final model, so when the BulkInferrer tries to use the model its not there. This can also be confirmed by downloading the trained model (in the SavedModel format) and then trying to load it on my local machine, the same "Op type not registered" error appears.

This used to be an issue in the Transform graph as well, but the tensorflow-transform team kind of hack-fixed it here: https://github.com/tensorflow/transform/blob/2e0b876c33d2a7a1202c8ec5ad7a3b315d9ce112/tensorflow_transform/saved/saved_transform_io.py#L158 , which doesn't seem like a long-term solution.

I'm guessing something similar would have to be done for the BulkInferrer, where the kernel can import `tensorflow_text` and register the Ops before the graph is executed.

**Comment by axeltidemann** [comment]
That means serving the model does not work. This sounds like it should be an obvious use case and a prioritised fix.

**Comment by jiyongjung0** [comment]
tensorflow_text support in tensorflow/serving is a different story and it seems like supported. Please see https://github.com/tensorflow/serving/issues/1490

The problem in BulkInferrer is that 'tensorflow_text' package is not loaded well in the bulk inferrer workers although it is imported in the BulkInferrer executor.

**Comment by RossKohler** [comment]
@jiyongjung0 I believe the import should happen [here](https://github.com/tensorflow/tfx-bsl/blob/3bd30634cfb8eea1e25be010fbc5ee988edb676a/tfx_bsl/beam/run_inference.py#L528)

**Comment by charlesccychen** [comment]
CC: @brills @rose-rong-liu

**Comment by RossKohler** [comment]
I believe I've fixed the issue by forking the `tfx-bsl` repo and adding the changes outlined here [here](https://github.com/RossKohler/tfx-bsl/commit/9a7b524ac7ed44ba22f550806452f54e074ab1bd). This is identical to how it's done in the transform component as pointed out by @pjlast. @jiyongjung0 a review of this fix would be appreciated, would this be acceptable as a PR into `tfx-bsl`?

**Comment by chrisTripla** [comment]
@jiyongjung0 Sorry, to hijack this thread. I ran into the issue you referenced with using dataflow in conjuction with tensorflow_text ops and tfx a while back now. Is this currently being worked on, or does a work around exist?

**Comment by rose-rong-liu** [comment]
It seems the PR is not on tfx-bsl repo (https://github.com/tensorflow/tfx-bsl). @RossKohler Do you mind to file the PR on tfx-bsl repo so that I can move it forward from that?
Thanks

**Comment by RossKohler** [comment]
@rose-rong-liu sure thing. I'll let you know when it's done.

**Comment by RossKohler** [comment]
@rose-rong-liu here's the PR into the `tfx-bsl` repo https://github.com/tensorflow/tfx-bsl/pull/34.

**Comment by rose-rong-liu** [comment]
Thanks @RossKohler , the change is in master now.
