### ISSUE TITLE
TFX and Explainable AI SDK

### ISSUE THREAD

**Issue by robinvanschaik** [tensorflow/tfx#3902]
**System information**

- TFX Version (you are using): 0.30.0
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..):
AI Platform notebooks. 
- Are you willing to contribute it (Yes/No): Yes.

**Describe the feature and the current behavior/state.**
Add documentation on how to use the explainable AI SDK with TFX.

**Will this change the current API? How?**
No. Only additional documentation.

**Who will benefit with this feature?**
Everyone who looking to incorporate the explainable AI SDK in their workflow. 

**Do you have a workaround or are completely blocked by this?** :
I am blocked because I don't know how to proceed.

**Any Other info.**

I am currently in the process of setting up a TFX + KFP pipeline based on the Chicago Taxi Dataset. 

The stakeholders involved would like to get a sense of the model that we are deploying from time to time. 
They would like to get a feeling what factors are important to the model. This can be done via the Explainable AI SDK (XAI) by Google. 

Currently I am following the Chicago Taxi pipeline example of TFX and an Explainable AI SDK tutorial found on the repo page. 

However, I am struggling at the moment to test my TFX model locally. The current example regarding the use of serialized TF.Examples are doable in terms of formatting the input data, but I fail to be able to get a prediction from the model. 

```
raw_dataset = tf.data.TFRecordDataset("gs://XXX/staging/tfx_pipeline_output/model/CsvExampleGen/examples/1/Split-eval/data_tfrecord-00000-of-00001.gz", compression_type="GZIP")

# Get a serialized TF.EXAMPLE
for raw_record in raw_dataset.take(1):
    example_input = raw_record.numpy()

# Based on the Chicago Taxi pipeline local serving.
# https://github.com/tensorflow/tfx/blob/10ed4337b2e4bd2223912db495b8bffdc9c3e5b2/tfx/examples/chicago_taxi_pipeline/taxi_utils_native_keras.py#L101
json_request = {"signature_name": "serving_default", 
                "instances": [{"examples": {"b64": base64.b64encode(raw_record.numpy()).decode('utf-8')}}]
               }

# Get a model from the pusher directory
model_path = "gs://XXX/staging/tfx_pipeline_output/model/Pusher/pushed_model/10"

model = tf.keras.models.load_model(model_path)

# Here is where it gets sketchy. The serving default contains the necessary logic for preprocessing using the TFT layer.
# But I have no clue if this is the right way. 
infer = model.signatures["serving_default"]

# Returns a type error. 
# TypeError: signature_wrapper(*, examples) missing required arguments: examples
infer(json_request)

```

In my mind there are two approaches how we can use the XAI SDK. 

* Use in AI Platform Notebook and run locally, just like the TFDV & TFMA. 
* Deploy in AI Platform Endpoints and send a batch to get feature importances.

In order to proceed I will need to know two things: 
* How to test my models locally with unpreprocessed data.
* If it makes sense to continue with this serving default that requires a serialized TF.example. 

In essence, I need some pointers if this makes sense or is going to work at all, or that we need to include a different serving function to make it easier to use with the SDK. 

Any help would be appreciated!

**Comment by jiyongjung0** [comment]
Hi, thank you for the question.

We have a related section in [Feature engineering tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/penguin_tft#run_the_pipeline). Could you take a look?

Basically, you have to pass the type you used when defining the serving function. JSON format might be relevant for the tensorflow serving, but it is not always the case for local environment.

**Comment by robinvanschaik** [comment]
@jiyongjung0 This looks really promising. Thanks! 

I will check it out and let you know if this helped me out.

**Comment by robinvanschaik** [comment]
@jiyongjung0 Thanks for the example. I managed to use my model for local inference. I hope that I can continue on the XAI module with this in place. 

<img width="1041" alt="Screenshot 2021-06-09 at 13 12 00" src="https://user-images.githubusercontent.com/46967558/121344707-5a8b0d00-c924-11eb-9088-6ff751bd1660.png">

**Comment by arghyaganguly** [comment]
hi @robinvanschaik , please confirm if we can close this issue.Thanks.

**Comment by robinvanschaik** [comment]
@arghyaganguly we can close this for now.
