### ISSUE TITLE
Provide type hints via PEP561

### ISSUE THREAD

**Issue by jinnovation** [tensorflow/tfx#3918]
**System information**

- TFX Version (you are using): 0.27.0
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): macOS; GCP; etc.
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

TFX looks to have pretty extensive type hint coverage, but as a consumer of TFX I cannot take advantage of these type hints in my own project, e.g. via static type checking with mypy.

[PEP561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information) describes a packaging mechanism by which package authors can distribute their type annotations for consumers' use. As a user of TFX, I'd appreciate it if the TFX authors could set up the TFX package with the mechanism described in PEP561 to expose type annotations to mypy in my own downstream project(s).

**Will this change the current API? How?**

No.

**Who will benefit with this feature?**

All users of TFX, but particularly those who use TFX as the foundations of their own products (as my team does).

**Do you have a workaround or are completely blocked by this?** :

Yes. I can generate type stubs, or simply disable type checking for `tfx` like any other package dependency that lacks type information.

**Name of your Organization (Optional)**

Spotify

**Any Other info.**

**Comment by jiyongjung0** [comment]
Thank you for suggestion!

I've tested your suggestion, and it seems working in most cases. However, I found that we don't have type information for proto-generated files.(https://github.com/protocolbuffers/protobuf/issues/2638) And I'm a bit hesitant to add more tools like [mypy-protobuf](https://github.com/dropbox/mypy-protobuf) in our build stack.

If users use types wrong, the error message will looks like below:
```
.../lib/python3.8/site-packages/tfx/components/bulk_inferrer/prediction_to_example_utils.py:21: error: Cannot find implementation or library stub for module named "tfx.proto"
.../lib/python3.8/site-packages/tfx/v1/proto/__init__.py:16: error: Cannot find implementation or library stub for module named "tfx.proto"
.../lib/python3.8/site-packages/tfx/v1/orchestration/experimental/__init__.py:16: error: Cannot find implementation or library stub for module named "tfx.orchestration.kubeflow.v2"
<snip...>
.../lib/python3.8/site-packages/tfx/extensions/google_cloud_ai_platform/bulk_inferrer/component.py:27: error: Cannot find implementation or library stub for module named "tfx.proto"
a.py:6: error: "bool" has no attribute "__iter__" (not iterable)   <--- The real error message here.
Found 46 errors in 43 files (checked 1 source file)
```
So users should see many unrelated error messages, although this [can be turned off](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library). @jinnovation , do you think this would be useful without type information of protobuf generated files?

**Comment by jinnovation** [comment]
> However, I found that we don't have type information for proto-generated files.

I'd happily consider this the user's responsibility to account for in their own mypy configurations. TFX providing its own type information is IMO separable from the protobuf type info, which—with mypy ignore configurations—can all be treated as `Any`.
