### ISSUE TITLE
input_configs for BigQueryExampleGen crashes unexpectedly

### ISSUE THREAD

**Issue by gilbblig** [tensorflow/tfx#393]
I'm orienting myself on the official chicago_taxi examples. To avoid syntactical errors, I use the query from the example for my train as well as the eval set at this point.

My call of the function looks like this, with both queries being same:

```
  input_pb2 = example_gen_pb2.Input(splits=[
                  example_gen_pb2.Input.Split(name='train', pattern=query_train),
                  example_gen_pb2.Input.Split(name='eval', pattern=query_val)])

  example_gen = BigQueryExampleGen(input_config=input_pb2)
```

In the Big_Query_Example_Gen component, input_config is described as follows:

>       input_config: An example_gen_pb2.Input instance with Split.pattern as
>         BigQuery sql string. If set, it overwrites the 'query' arg, and allows
>         different queries per split.

I can built the pipeline, but the runner quickly produces the following error:

> INFO:tensorflow:Using workflow id chicago-taxi-pipeline-kubeflow-bmw6q
> INFO:tensorflow:Starting Executor execution.
> INFO:tensorflow:Inputs for Executor is: {}
> INFO:tensorflow:Using workflow id chicago-taxi-pipeline-kubeflow-bmw6q
> INFO:tensorflow:Starting Executor execution.
> INFO:tensorflow:Inputs for Executor is: {}
> INFO:tensorflow:Outputs for Executor is: {"examples": [{"artifact_type": {"name": "ExamplesPath", "properties": {"span": "INT", "name": "STRING", "type_name": "STRING", "state": "STRING", "split": "STRING", "producer_component": "STRING", "pipeline_name": "

... shortened this part...

> Traceback (most recent call last):
>   File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 102, in <module>
>     main()
>   File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 98, in main
>     runner.run()
>   File "/tfx-src/tfx/orchestration/kubeflow/container_runners.py", line 103, in run
>     self._exec_properties)
>   File "/tfx-src/tfx/components/example_gen/base_example_gen_executor.py", line 112, in Do
>     json_format.Parse(exec_properties['output'], output_config)
> KeyError: 'output'

I'm using tf-nightly and tfx-0.14dev. Please tell if any additional logs could be of use.

Edit: In fact, it appears like I'm using tfx-0.14 when building the pipeline, but not when running the job, since this line shouldn't exist anymore. I will reconfigure my image and expect it to work then. I'll update with more infos then.

**Comment by 1025KB** [comment]
Yep, it should be version issue, let me know if head or 0.13 works or not

**Comment by rmothukuru** [comment]
@gilbblig ,
Can you please confirm if using `head` or `0.13` resolves your issue?

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
