### ISSUE TITLE
Kubeflow Visualizations Have all Become Broken as of 0.29

### ISSUE THREAD

**Issue by vaskozl** [tensorflow/tfx#3933]
With recent release of TFX, artifacts paths have been changing and no longer work in Kubeflow. 
Shouldn't the changes be communicated with the Kubeflow maintainers? They are still hard-coded to the old paths:

https://github.com/kubeflow/pipelines/blob/master/frontend/src/lib/OutputArtifactLoader.ts#L273-L274

Ideally both old and new paths should be supported.

I'm currently on Kubeflow 1.4.0 with TFX 0.30.0 and all visualizations (including evaluator given there is a baseline (though patched in master))  are broken.

As I upgraded from 0.27, and the tensorboard visualization doesn't seem to work either as it seems to not be included in the `ml-pipeline-ui-metadata.tgz` anymore for some reason.

https://github.com/tensorflow/tfx/blob/e43ee84f973ec63c8af5ee18a8508b1d5adb7abf/tfx/orchestration/kubeflow/container_entrypoint.py#L354

As I just mentioned `ml-pipeline-ui-metadata`: Can you also please consider moving `/ml-pipeline-ui-metadata.json` out of the root folder to say `/output/ml-pieline-ui-metadata.json`?

Writing to `/ml-pipeline-ui-metadata.json`makes it impossible to use non `docker` (which as you all know is deprecated now) kubeflow deployments:

https://github.com/kubeflow/pipelines/issues/1654

**Comment by axeltidemann** [comment]
It would be awesome to get this fixed. On another [thread](https://github.com/kubeflow/pipelines/issues/5303#issuecomment-851904651), it was reported that Kubeflow Pipelines 1.6.0 will fix the missing visualisations.

**Comment by Bobgy** [comment]
Thanks for the report!
I'll prioritize a fix on Kubeflow Pipelines side. I just added it to kfp 1.7.0 release tracker.

**Comment by zijianjoy** [comment]
https://github.com/kubeflow/pipelines/pull/5999 has merged to fix this issue, expect to be included in the next KFP release. After upgrade, KFP requires all users to upgrade TFX to be >0.30.0 for adopting this change.

**Comment by Bobgy** [comment]
@jiyongjung0 can we close the issue?
