### ISSUE TITLE
TFX Official demo issues on pipeline's RuntimeError error

### ISSUE THREAD

**Issue by mxie622** [tensorflow/tfx#3942]
This issue has been discussed here: https://github.com/tensorflow/tfx/issues/2197
The error details stated: "files in the same split '/home/...' have different header"

That solution given by that link mentioned: "Just to clarify, it does not have to be a CSV file, any arbitrary file will be picked by the TFX IO logic. And to prevent this, my best bet will be to ensure base_dir does not contain any .ipynb file. " 

Not sure if this could fix the issue that user met, my issue cannot be fixed yet and I don't know how to mine the errors to fix.

Basically my attempt simply focuses on https://www.tensorflow.org/tfx/tutorials/tfx/penguin_simple and **I want to run everything locally.** I think the issue raised in pipeline definition part as below :
```

def _create_pipeline(pipeline_name: str, pipeline_root: str, data_root: str,
                     module_file: str, serving_model_dir: str,
                     metadata_path: str) -> tfx.dsl.Pipeline:

```
```
  """Creates a three component penguin pipeline with TFX."""
  # Brings data into the pipeline.

  example_gen = tfx.components.CsvExampleGen(input_base=data_root)

  # Uses user-provided Python function that trains a model.
  trainer = tfx.components.Trainer(
      module_file=module_file,
      examples=example_gen.outputs['examples'],
      train_args=tfx.proto.TrainArgs(num_steps=100),
      eval_args=tfx.proto.EvalArgs(num_steps=5))

  # Pushes the model to a filesystem destination.
  pusher = tfx.components.Pusher(
      model=trainer.outputs['model'],
      push_destination=tfx.proto.PushDestination(
          filesystem=tfx.proto.PushDestination.Filesystem(
              base_directory=serving_model_dir)))

  # Following three components will be included in the pipeline.
  components = [
      example_gen,
      trainer,
      pusher,
  ]

  return tfx.dsl.Pipeline(
      pipeline_name=pipeline_name,
      pipeline_root=pipeline_root,
      metadata_connection_config=tfx.orchestration.metadata
      .sqlite_metadata_connection_config(metadata_path),
      components=components)
```
- TensorFlow version: 2.4.1
- TFX Version: 0.30.0
- Python version:3.6.9
- Jupyter notebook, k8s Linux, Gcloud

Error details:

...
...
INFO:absl:MetadataStore with DB connection initialized
**ERROR:absl:Execution 7 failed**
INFO:absl:Cleaning up stateless execution info
------------------------------------------------------------------------
RuntimeError                                            Traceback (most recnet call last)
.....
....

```RuntimeError: Files in the same split '/home/...' have different header```

What is more, it is for running locally now. If I connect GCP BQ, the way to connect db should be also different. The method (In ```tfx.dsl.Pipeline()```, ```metadata_connection_config``` 
to be changed ?) provided only cover MySQL db seemingly as is shown in official doc. What should I do? 
Thanks..

**Comment by arghyaganguly** [comment]
@mxie622, I tried reproducing this issue locally in colab [gist](https://colab.research.google.com/gist/arghyaganguly/3f65c234fc3993ba3f045b2ea3ebdf14/penguin_simple.ipynb) with  below config, but faced no error :- 
a)TensorFlow version: 2.4.2
     TFX version: 0.30.0
      Python 3.7.10

**Comment by mxie622** [comment]
> @mxie622, I tried reproducing this issue locally in colab [gist](https://colab.research.google.com/gist/arghyaganguly/3f65c234fc3993ba3f045b2ea3ebdf14/penguin_simple.ipynb) with below config, but faced no error :-
> a)TensorFlow version: 2.4.2
> TFX version: 0.30.0
> Python 3.7.10

The version is not what causing the issue. 
There are actually 2 issues. The 1st one is fixed that the reason comes from hidden files which are created accidentally and quietly...
The answer in https://github.com/tensorflow/tfx/issues/2197  is correct that for the data.csv, it just needs such a 100% clean environment to store for safety. 

But the 2nd issue is not fixed yet. 

I assume that any user who applies for open source TFX to his/her work and doesn't use MySQL DB may have to develop customized API for its own business, EX: for BigQuery, then the user probably have to develop such an API like ```metadata_connection_config = tfx.orchestration.metadata.bigquery_metadata_connection_config``` (Currently not existing) , either pay for such an API which is already hold by official TFX developers.

So...I am not sure if we do have to improve the open source codes and that would be not friendly for general users.
Hope there could be any user who got experience like me can bring some tips or hints...

**Comment by 1025KB** [comment]
The connection_config is limited to what's supported by MLMD, bigquery database is not supported

**Comment by arghyaganguly** [comment]
@mxie622 , please confirm whether this issue can be closed based on the comment trace.Thanks.

**Comment by mxie622** [comment]
So, to use BQ as the data source to import, we can only apply for tensorflow.io as the api to do data query?

**Comment by gowthamkpr** [comment]
@mxie622 ExampleGen Consumes: Data from external data sources such as CSV, TFRecord, Avro, Parquet and BigQuery. You can look at it [here](https://www.tensorflow.org/tfx/guide/examplegen)
