### ISSUE TITLE
tfx.types.standard_artifacts.Examples argument error

### ISSUE THREAD

**Issue by PyoJunCode** [tensorflow/tfx#3976]
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Colab notebook
- TFX Version:0.30.0
- Python version:3.7.10
- Python dependencies (from `pip freeze` output):

**Describe the current behavior** Construct tfx.type.channel
```
tfx.types.Channel(
        type=standard_artifacts.Examples,
        artifacts=[standard_artifacts.Examples(split_names="train"),
                   standard_artifacts.Examples(split_names="eval")])
```
but error occured :  

```ValueError: The "mlmd_artifact_type" argument must not be passed for Artifact subclass <class 'tfx.types.standard_artifacts.Examples'>.```

or

```__init__() got an unexpected keyword argument 'split_names'```

```
<ipython-input-151-bd49a0b7ff7b> in __init__(self, examples, max_rotation_angle, num_augmented_per_image, augmented_data, instance_name)
    124     augmented_data = augmented_data or tfx.types.Channel(
    125         type=standard_artifacts.Examples,
--> 126         artifacts=[standard_artifacts.Examples(split_names="train"),
    127                    standard_artifacts.Examples(split_names="eval")])
    128     spec = DataAugmentationComponentSpec(

/usr/local/lib/python3.7/dist-packages/tfx/types/standard_artifacts.py in __init__(self, *args, **kwargs)
     77       raise Exception('The full "tfx" package must be installed to use this '
     78                       'functionality.')
---> 79     super(_TfxArtifact, self).__init__(*args, **kwargs)
     80 
     81 

TypeError: __init__() got an unexpected keyword argument 'split_names'
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by arghyaganguly** [comment]
@PyoJunCode , please provide some more code for us to expedite the debugging process.
Also, could you please try the approach as below: 

```
from tfx.types.standard_artifacts import Examples

 tfx.types.Channel(
 type=Examples,
 artifacts=[Examples(split="train"), Examples(split="eval")]
 ```

**Comment by arghyaganguly** [comment]
@PyoJunCode , closing this as there has been no update on this issue.Please feel free to reopen based on the above comment.Thanks.
