### ISSUE TITLE
Example to send beam jobs to cloud dataflow and training on Cloud ML Engine

### ISSUE THREAD

**Issue by josekidengan** [tensorflow/tfx#40]
Example shows the bare metal running of ml pipeline using airflow/kubeflow. 
However there is no information regarding how to launch the beam jobs to cloud data-flow  and training on ML engine to scale. Also how to serve model on google Cloud ML Engine.

**Comment by 1025KB** [comment]
Hi, Jose, we are working on an example of data-flow and CLME, it will be released in Q2

**Comment by krazyhaas** [comment]
Hi Jose.  

Take a look at https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py.  You'll see it sets the beam runner to run on Dataflow via beam_pipeline_args, CMLE training via _ai_platform_training_args, and pushes to CMLE serving with _ai_platform_serving_args.  While it uses the KFP runner, the same will work with Airflow.  Is that what you're looking for?

**Comment by andrewlarimer** [comment]
Does setting the `executor_class=ai_platform_trainer_executor.Executor` in Trainer allow AI Platform to do hyperparameter tuning? That to me seems like the biggest thing missing from TFX at the moment is any mention of hyperparameter tuning (so far as I can find).

**Comment by zhitaoli** [comment]
@andrewlarimer Hyper parameter tuning definitely deserves its own thread to discuss, as the this one mainly tracks how to do normal training and data processing using dataflow.

To answer your question:

Assuming https://cloud.google.com/ml-engine/docs/tensorflow/using-hyperparameter-tuning is what you are looking for, I think the work happened so far can be used as a stepping stone, but we need more work to plumbing the additional command line arguments generated by the HParam tuning process, and also make sure it fits with our trainer executor.

If this is something useful for you, can you file a separate Github feature request? We'll discuss the best strategy to implement this.
