### ISSUE TITLE
Other ML packages in TFX Vertex AI pipelines

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/tfx#4000]
Hi,

Can someone please clarify, Can we use other machine learning packages like sklearn, nltk, xgboost, pandas in TFX pipelines when used with Vertex AI custom model building.

If there is any way please provide some documentation or steps to model build.

Thanks.

**Comment by 1025KB** [comment]
We have an [sklearn example](https://github.com/tensorflow/tfx-addons/tree/main/examples) here

**Comment by pindinagesh** [comment]
Hi @cah-aswini-jalla 

Please confirm the comment from @1025KB and suggest whether this can be closed. Thank you!

**Comment by pindinagesh** [comment]
Hi @cah-aswini-jalla 

Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again and can you look at these examples [sklearn_penguins](https://github.com/tensorflow/tfx-addons/tree/main/examples/sklearn_penguins). Thank you!
