### ISSUE TITLE
Need better documentation for TFMA's MetricConfig for TFX's Evaluator

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tfx#4022]
## URL(s) with the issue:
- https://www.tensorflow.org/tfx/model_analysis/api_docs/python/tfma/MetricConfig 

- https://github.com/tensorflow/model-analysis/blob/4ea7d16125d26aa469dc2c5199bbb5f588586fef/tensorflow_model_analysis/proto/config.proto#L407-L414

## Description of issue (what needs changing):
For TFX's `Evaluator`, it seems like the config does not rely on the `__init__` method; and relies on the `get_config` and `from_config` method of the (custom) metrics class.

### Clear description:
It seems like the config does not rely on the `__init__` method; and relies on the `get_config` and `from_config` method of the (custom) metrics class. This distinction is important as TFX's `Evaluator` serialize and deserialize the metric and `__init__` is not used during the final metrics evaluation.

### Correct links
It seems like the config does not rely on the `__init__` method; and relies on the `get_config` and `from_config` method of the (custom) metrics class. This distinction is important as TFX's `Evaluator` serialize and deserialize the metric and `__init__` is not used during the final metrics evaluation.

### Parameters defined
Yes. However, the definition of the `config` breaks for TFX Evaluator

### Returns defined
Yes.

### Raises listed and defined
No

### Request visuals, if applicable
No

**Comment by sumitbinnani** [comment]
**Link to TFMA Issue**: https://github.com/tensorflow/model-analysis/issues/134

**Comment by mdreves** [comment]
Closing, will track in tensorflow/model-analysis#134
