### ISSUE TITLE
getting issue running importing TFX on colab 

### ISSUE THREAD

**Issue by shubham-ai** [tensorflow/tfx#4073]
<img width="1680" alt="Screenshot 2021-07-21 at 11 39 27 PM" src="https://user-images.githubusercontent.com/5429496/126541027-98fa8ac8-b377-4747-85f5-a83e3511790f.png">
<img width="1680" alt="Screenshot 2021-07-21 at 11 45 00 PM" src="https://user-images.githubusercontent.com/5429496/126541040-17ddc8ae-4f99-42d0-8939-141e1156a45a.png">
<img width="1680" alt="Screenshot 2021-07-21 at 11 47 13 PM" src="https://user-images.githubusercontent.com/5429496/126541043-a556a0d1-4738-42b0-a5ef-87b5bf852837.png">

Getting error, no module name tfx while running this command "from tfx import v1 as tfx"

**Comment by arghyaganguly** [comment]
@shubham-ai , i tried reproducing this issue but have faced no error in the [attempt.](https://colab.research.google.com/gist/arghyaganguly/f24678617959dcfac5c32f2291aaa6d9/penguin_simple.ipynb?hl=vi)
a)Have you restarted the runtime before importing tfx?
b)Are you using the latest tfx version?

**Comment by arghyaganguly** [comment]
@shubham-ai , please update on your status or close this issue if you are successful in resolving it.Thanks.

**Comment by arghyaganguly** [comment]
Please feel free to reopen if required.Thanks.
