### ISSUE TITLE
404 on TFX components Documentation page

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [tensorflow/tfx#4089]
I cannot visit the component documentation page since Friday, Jul 23. Please advise if this documentation is moved to somewhere else.

![Screen Shot 2021-07-26 at 9 15 32 AM](https://user-images.githubusercontent.com/80276234/126995010-6d2c89c8-24e3-484f-aa37-625927517185.png)

**Comment by arghyaganguly** [comment]
@EdwardCuiPeacock, please use [link](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components).Thanks for catching this bug.

**Comment by EdwardCuiPeacock** [comment]
Thanks for the quick response. Is this link for v1 version of `tfx`? I am still currently on 0.30.0. I have noticed that the `components` are now under `tfx.v1` rather than directly under `tfx`. Is this going to be a persistent change for the v1 release?

**Comment by arghyaganguly** [comment]
@EdwardCuiPeacock , more on v1 in release [link](https://github.com/tensorflow/tfx/releases) from version 1.0.0 onwards.

**Comment by arghyaganguly** [comment]
@EdwardCuiPeacock , please let me know if you are satisfied with the previous comment so that i can close this issue.Thank you.

**Comment by EdwardCuiPeacock** [comment]
@arghyaganguly Yes. Please close this issue.
