### ISSUE TITLE
[Discussion] Discrepancy between 1.0.0rc2 and 1.0.0

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#4100]
Hi folks, this is not a major issue, but it caused some headaches on our side.

Seems 1.0.0rc2 had some changes when it was promoted to 1.0.0. My assumption was that the latest rc should contain the same code as the end release. 

Not major issue, but would be nice if in the future we can enforce it better :D 

Diff: https://github.com/tensorflow/tfx/compare/v1.0.0-rc2...v1.0.0 (this added a new transitive dependency that broke our CI)

**Comment by chongkong** [comment]
Thanks for the suggestion Gerard. AFAIK there were some issues during 1.0RC -> 1.0 promotion due to the long time gap, and maybe that caused some drift.

@dhruvesh09 can we enforce this for the future RC promotions?

**Comment by dhruvesh09** [comment]
Ack

**Comment by casassg** [comment]
I would say it would be nice to have. Ty for this. It's not a major issue. Mostly been a surprise for us

**Comment by casassg** [comment]
ty for response, closing for now :D
