### ISSUE TITLE
Regarding configuring GPU options

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tfx#4102]
Thank you for submitting a TFX documentation issue. Per our GitHub policy, we
only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub and we welcome external contributions!

The TFX docs are open source! To get involved, please read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_simple

### Clear description:

How do I configure the hardware environment on which the pipeline is gonna run on Vertex AI?

**Comment by UsharaniPagadala** [comment]
@sayakpaul 

Could you please check if this [document](https://cloud.google.com/vertex-ai/docs/training/configure-compute#specifying_gpus) would suffice.Thanks

**Comment by sayakpaul** [comment]
Nope, it does not. This is how a pipeline is submitted to Vertex AI for execution:

```python
pipelines_client = client.AIPlatformClient(
    project_id=GOOGLE_CLOUD_PROJECT,
    region=GOOGLE_CLOUD_REGION,
)

_ = pipelines_client.create_run_from_job_spec(PIPELINE_DEFINITION_FILE)
```
Where do I get to configure the hardware spec?

**Comment by sayakpaul** [comment]
Sorry. It's likely specified here: https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_vertex_training.

**Comment by UsharaniPagadala** [comment]
@sayakpaul 

Please confirm if this issue can be closed. Thanks
