### ISSUE TITLE
Issues with Vertex AI upload as a custom component

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tfx#4104]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Google Cloud (Vertex AI)
- TensorFlow version: 2.4.2
- TFX Version: 0.30.0
- Python version: 3.8
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**

I have written a custom component to upload a model to Vertex AI referring from [here](https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/blob/main/src/tfx_pipelines/components.py#L74). Currently I am running into:

```
workerpool0-0
AttributeError: module '__main__' has no attribute 'vertex_model_uploader_Executor'
```

Full logs:

[null__logs__2021-07-31T12-07.json.zip](https://github.com/tensorflow/tfx/files/6910815/null__logs__2021-07-31T12-07.json.zip)

**Describe the expected behavior**

The model should upload successfully to Vertex AI. 

**Standalone code to reproduce the issue**

[Colab Notebook](https://colab.research.google.com/gist/sayakpaul/60b0972ce318831b5f2b35efa6751cd4/custom_model_tfx.ipynb)

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by sayakpaul** [comment]
After referring to https://github.com/tensorflow/tfx/issues/3900, I did build a custom image with the custom components, but those components are not discoverable anymore. Here's the updated [Colab Notebook](https://colab.research.google.com/github/sayakpaul/Dual-Deployments-on-Vertex-AI/blob/main/notebooks/Custom_Model_TFX.ipynb).

**Comment by jiyongjung0** [comment]
Thank you for the report! Unfortunately, we don't have enough information to troubleshoot your issues.

It seems like the "image" field is not properly specified when I see the [other comment](https://github.com/tensorflow/tfx/issues/3900#issuecomment-890465744). But your code in the colab looks fine.
```
runner = tfx.orchestration.experimental.KubeflowV2DagRunner(
    config=tfx.orchestration.experimental.KubeflowV2DagRunnerConfig(default_image=TFX_IMAGE_URI),
    output_filename=PIPELINE_DEFINITION_FILE)
```

The "image" field of the generated json should become the value of `TFX_IMAGE_URI` which is `gcr.io/fast-ai-exploration/flowers:tfx-1-0-0`.

By the way, it is better to use the same TFX version for the image and the client. Could you try again with tfx 1.0.0 in all environment by upgrading your working environment?

**Comment by sayakpaul** [comment]
Yeah right. We were able to solve this problem sorry forgot to update here. We used what you just mentioned. 

Now, we are stuck with the deployment part (issue detailed here: https://github.com/googleapis/python-aiplatform/issues/584). I know this is not related to TFX but I am asking in a good spirit. I understand if you don't have the bandwidth to check it :)

**Comment by sayakpaul** [comment]
Figured it out: https://colab.research.google.com/github/sayakpaul/Dual-Deployments-on-Vertex-AI/blob/main/notebooks/Custom_Model_TFX.ipynb.
