### ISSUE TITLE
Paginating when loading cached results

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#4108]
After having several runs for a pipeline (we reached this by stresstesting our setup), you reach a state where KFP shared MLMD instance is returning too large of response via GRPC when loading previous executions for a certain component.

This could be fixed by instead paginating the `get_cached_outputs` or just allowing to limit the query to latest 1000 records - https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/metadata.py#L822

See stacktrace: https://gist.github.com/casassg/c67371a2cd1d000db7ade50748aed5b6

**Comment by casassg** [comment]
CC @zhitaoli we should try to figure out a way to limit the artifacts pulled by TFX to reduce risks when a pipeline has had several runs

**Comment by zhitaoli** [comment]
Can you share which version of TFX (and KFP) are you observing this? Just want to double check that this is post IR migration.

**Comment by casassg** [comment]
TFX - 0.26.3 (we haven't finished upgrading yet)
KFP - 1.6.0 (checking whats the cluster version atm)

We use KubeflowDagRunner here (since Kubeflow v2 is not yet released to OSS afaik)

**Comment by singhniraj08** [comment]
@casassg,

`MAX_EXECUTIONS_FOR_CACHE` [parameter](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/metadata.py#L44) is introduced to cap the maximum number of executions we look at for previous result and default is set to 100. [This](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/metadata.py#L847-L848) logic will make sure we look at executions of previous 100 results. Please let us know if this implementation resolves this issue. Thank you!
