### ISSUE TITLE
Passing wildcard name with fixed extension to FileBasedExampleGen; not sure if bug or intentional

### ISSUE THREAD

**Issue by dwsmith1983** [tensorflow/tfx#4121]
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

https://github.com/tensorflow/tfx/blob/a894cf3659556aa5ddd3325ca7400738050ed4b9/tfx/components/example_gen/import_example_gen/executor.py#L97

**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Jupyter, databricks notebook on GCP
- TensorFlow version: 2.5.0
- TFX Version: 1.0.0
- Python version: 3.7 and 3.8
- Python dependencies (from `pip freeze` output): Unnecessary

**Describe the current behavior**
`example_gen_tf = ImportExampleGen(input_base="/path/to/tfrecord/")`
From your code linked, you append split_pattern which seems to only pass `*` so Beam looks through `/path/to/tfrecord/*`

However, I created my tfrecords using LinkedIns spark to tfrecord code and it produces additional artifacts.
https://github.com/linkedin/spark-tfrecord

I dont see away to override split_pattern and passing `/path/to/tfrecord/*.tfrecord` is useless since it will be convert up to `/path/to/tfrecord/*.tfrecord/*`

**Describe the expected behavior**
I would like to be able to override split_pattern or it should follow the same behavior as TF data validator where beam just takes the data_location parameter allowing me to wildcard the name with fixed extension.
https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/utils/stats_gen_lib.py

**Standalone code to reproduce the issue**
Add `_SUCESS` 0 byte size file to your tfrecord directory and run this your ImportExampleGen
`example_gen_tf = ImportExampleGen(input_base="/path/to/tfrecord/")`

As a counter example, TF data validator as much better design.
`tfdv.generate_statistics_from_tfrecord("/path/to/tfrecord/*.tfrecord")`
This works well since there is no split_pattern and Beam receives the data_location as user specified.

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**
True Digital Group

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by codesue** [comment]
Have you tried using an [input_config](https://github.com/tensorflow/tfx/blob/master/tfx/proto/example_gen.proto) for this? An input config lets you specify the split pattern. The [examples in the docs](https://www.tensorflow.org/tfx/guide/examplegen#custom_inputoutput_split) show you how to do this for a train/eval split, but it's a similar process to do this for a single split, like in this [example pipeline](https://github.com/tensorflow/tfx/blob/master/tfx/examples/tfjs_next_page_prediction/tfjs_next_page_prediction_pipeline.py#L79).

For the use case you've described here, something like the following could work. It's the same concept, but more convenient:
```
from tfx.components.example_gen.utils import make_default_input_config

example_gen = FileBasedExampleGen(
  input_base='/path/to/tfrecord/',
  input_config=make_default_input_config('*.tfrecord')
)
```

Incidentally, [make_default_input_config()](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/utils.py#L215) is where that `'*'` split pattern originally comes from.

**Comment by dwsmith1983** [comment]
> Have you tried using an [input_config](https://github.com/tensorflow/tfx/blob/master/tfx/proto/example_gen.proto) for this? An input config lets you specify the split pattern. The [examples in the docs](https://www.tensorflow.org/tfx/guide/examplegen#custom_inputoutput_split) show you how to do this for a train/eval split, but it's a similar process to do this for a single split, like in this [example pipeline](https://github.com/tensorflow/tfx/blob/master/tfx/examples/tfjs_next_page_prediction/tfjs_next_page_prediction_pipeline.py#L79).
> 
> For the use case you've described here, something like the following could work. It's the same concept, but more convenient:
> 
> ```
> from tfx.components.example_gen.utils import make_default_input_config
> 
> example_gen = FileBasedExampleGen(
>   input_base='/path/to/tfrecord/',
>   input_config=make_default_input_config('*.tfrecord')
> )
> ```
> 
> Incidentally, [make_default_input_config()](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/utils.py#L215) is where that `'*'` split pattern originally comes from.

@codesue thanks. It would be helpful if split_pattern was defined a bit better and how to access it.

**Comment by 1025KB** [comment]
[Here](https://www.tensorflow.org/tfx/guide/examplegen#custom_inputoutput_split) is an instruction for custom input/output config

**Comment by UsharaniPagadala** [comment]
@dwsmith1983 

Could you please respond on @1025KB  comment and move this to closed status if this resolved.Thanks
