### ISSUE TITLE
Kubeflow pipeline fails with ValueError: ...KubeflowMetadataConfig in TFX 1.0.0

### ISSUE THREAD

**Issue by nroberts1** [tensorflow/tfx#4126]
Using:

```
metadata_config = kubeflow_dag_runner.get_default_kubeflow_metadata_config()
runner_config = kubeflow_dag_runner.KubeflowDagRunnerConfig(kubeflow_metadata_config=metadata_config, tfx_image=BASE_IMAGE)
```
when I run the pipeline in TFX 0.30.0 the pipeline runs fine, but once I update to 1.0.0 the pipeline fails with:
`ValueError: metadata_connection_config is expected to be in type ml_metadata.ConnectionConfig, but got type type.googleapis.com/tfx.orchestration.kubeflow.proto.KubeflowMetadataConfig`

Stacktrace from pod's log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 470, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 428, in main
    deployment_config = runner_utils.extract_local_deployment_config(tfx_ir)
  File "/usr/local/lib/python3.7/site-packages/tfx/orchestration/local/runner_utils.py", line 39, in extract_local_deployment_config
    return _to_local_deployment(result)
  File "/usr/local/lib/python3.7/site-packages/tfx/orchestration/local/runner_utils.py", line 99, in _to_local_deployment
    input_config.metadata_connection_config.type_url))
ValueError: metadata_connection_config is expected to be in type ml_metadata.ConnectionConfig, but got type type.googleapis.com/tfx.orchestration.kubeflow.proto.KubeflowMetadataConfig
```

Kubeflow is running on GCP

0.30.0:
![Screenshot from 2021-08-06 08-08-29](https://user-images.githubusercontent.com/8723585/128471880-f65c603d-012a-4143-b80a-5a2b881e51eb.png)

1.0.0:
![Screenshot from 2021-08-06 08-18-53](https://user-images.githubusercontent.com/8723585/128472237-47822279-bfc0-4c27-9856-8a48bf194d9e.png)

Obviously the BeamDagRunner uses metadata_connection_config of type ml_metadata.ConnectionConfig as this seems to work fine in both 0.30.0 and 1.0.0.

**Comment by 1025KB** [comment]
In your dsl.pipeline, is metadata_connection_config still set?

Here is an [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_kubeflow.py#L369) we have

**Comment by SMesser** [comment]
Am facing the same error using a variant of the [bigquery_ml example](https://github.com/tensorflow/tfx/blob/v1.0.0/tfx/examples/bigquery_ml/taxi_pipeline_kubeflow_gcp_bqml.py).  In my variant, import statements and most code in kubeflow_dag_runner.py & the pipeline-creation function are the same as in the example. There are a differences for the ExampleGen component, which is reading an existing BQ table rather than the usual Taxi upload.  I've also changed the file structure a bit, based on structures used in the 0.26.0 documentation. I also used "pip freeze > requirements.txt" from within the `tensorflow/tfx:1.0.0` image and made sure my environment matched versions of TFX, tensorboard, requests, and kfp-pipeline-spec.

(I apparently don't have locally-available copies of aiohttp>=3.7.4 referenced in the TFX image, but don't know if that's important.)

**Comment by nroberts1** [comment]
Thanks to @1025KB's linked example I was able to get it working. I believe the change was from using:

`tfx.ochestration.experimental.kubeflow...`

rather than: 

`tfx.orchestration.kubeflow...`

So I now have:
```

        metadata_config = (tfx.orchestration.experimental.get_default_kubeflow_metadata_config())

        runner_config = tfx.orchestration.experimental.KubeflowDagRunnerConfig(
            kubeflow_metadata_config=metadata_config,
            tfx_image=BASE_IMAGE)
```

Not convinced this doesn't mean there's a problem as I'd imagine the non experimental version should work, but this did get it working okay. Hope that helps you @SMesser

**Comment by SMesser** [comment]
Thanks @nroberts1 , but I still have the same errors.  The first variant I tried was:
```
from tfx import v1 as tfx

# Then reference the following
tfx.orchestration.experimental.get_default_kubeflow_metadata_config
tfx.orchestration.experimental.KubeflowDagRunner
tfx.orchestration.experimental.KubeflowDagRunnerConfig
```
The above and the first of the following both still gave the "metadata_connection_config is expected to be in type ..." error. Other things I tried:
```
from tfx.v1.orchestration.experimental import get_default_kubeflow_metadata_config, KubeflowDagRunner, KubeflowDagRunnerConfig
# Source code also mentions a couple "V2" classes, and the setup of them had to be tweaked in a couple obvious ways,
# but I eventually got the error "Cannot find KubeflowDagRunner.run() in kubeflow_dag_runner.py()
# so I assume these are not yet part of the public API
from tfx.v1.orchestration.experimental import get_default_kubeflow_metadata_config, KubeflowV2DagRunner, KubeflowV2DagRunnerConfig
# The following are all import errors
from tfx.orchestration.experimental import get_default_kubeflow_metadata_config
from tfx.orchestration.experimental.kubeflow import get_detault_kubeflow_metadata_config
from tfx.v1.orchestration.experimental.kubeflow import get_default_kubeflow_metadata_config, KubeflowDagRunner, KubeflowDagRunnerConfig
```

**Comment by SMesser** [comment]
I also tried replacing `tfx.orchestration.pipeline.Pipeline` with `tfx.v1.dsl.Pipeline` as per @1025KB 's suggestion. No joy.

**Comment by zhitaoli** [comment]
@1025KB @rcrowe-google  Can you help to coordinate relevant imports?

**Comment by rcrowe-google** [comment]
Given that the last comment is over a year old I'm closing this bug.
