### ISSUE TITLE
fails to use RuntimeParameter with Vertex pipelines

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tfx#4129]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): linux
- TensorFlow version: 2.5
- TFX Version: 1.0.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**
```
from tfx.extensions.google_cloud_big_query.example_gen import component as big_query_example_gen_component
from tfx.orchestration import pipeline
from tfx.orchestration.data_types import RuntimeParameter
from tfx.orchestration.kubeflow.v2.kubeflow_v2_dag_runner import KubeflowV2DagRunner, KubeflowV2DagRunnerConfig
from kfp.v2.google import client

from pipelines.constants import GCS_BUCKET_NAME, PROJECT_ID, GCP_REGION


def create_full_training_pipeline(pipeline_root: str, _beam_args: dict) -> pipeline.Pipeline:
    query = RuntimeParameter(
        name="query",
        ptype=str
    )
    input_config = {
        "splits":
            [
                {
                    'name': 'train',
                    'pattern': query
                },
            ]
    }

    example_gen = big_query_example_gen_component.BigQueryExampleGen(input_config=input_config) \
        .with_id('ExampleGenR')
    return pipeline.Pipeline(
        beam_pipeline_args=_beam_args,
        pipeline_name="full-training",
        pipeline_root=pipeline_root,
        components=[
            example_gen,
        ],
    )
_temp_location = 'gs://{}/pipeline_tmp/{}'.format(GCS_BUCKET_NAME, 'test')
_beam_pipeline_args = [
    '--runner=DirectRunner',
    '--direct_running_mode=in_memory',
    '--direct_num_workers=0',
    '--temp_location=' + _temp_location,
    '--project=' + PROJECT_ID,
    '--region=' + GCP_REGION
]
training_pipeline = create_full_training_pipeline(
    pipeline_root=_temp_location,
    _beam_args=_beam_pipeline_args
)
PIPELINE_DEFINITION_FILE = '/tmp/test'
runner = KubeflowV2DagRunner(
    config=KubeflowV2DagRunnerConfig(),
    output_filename=PIPELINE_DEFINITION_FILE)
_ = runner.run(training_pipeline)

pipelines_client = client.AIPlatformClient(
    project_id=PROJECT_ID,
    region="europe-west4",
)

pipelines_client.create_run_from_job_spec(PIPELINE_DEFINITION_FILE,
                                          parameter_values={'query': 'select 1'}
                                          )
```
raises with:
`ValueError: The pipeline parameter query is not found in the pipeline job input definitions.`
 If we look in the pipeline definition file we dont see any parameter exposed and we just see the json version of the object.  

If instead of using parameter_values from create_run_from_job_spec we use the one in run method from KubeflowV2DagRunner it first makes no sense (since we would need to pass runtime parameters while defining the pipeline...) and breaks with another error. 

If we go inside the pipeline definition we dont see anything in:
`job_spec['pipelineSpec']['root'].get(
        'inputDefinitions', {}).get('parameters', {})` code from  https://github.com/kubeflow/pipelines/blob/f9d47d0ef99422932656f1c63379259633408056/sdk/python/kfp/v2/google/client/runtime_config_builder.py#L56 which seems to be responsible to know if it's a RuntimeParameter. That makes us think the issue is before when compiling the pipeline with KubeflowV2DagRunner: we did not test if setting it manually in the json works. 

**Describe the expected behavior**
We expect to be able to use RuntimeParameters with Vertex Pipelines. We followed the tutorial from https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_simple#run_the_pipeline_on_vertex_pipelines to know how to start a pipeline in TFX with Vertex. 

We also saw those commits 

**Standalone code to reproduce the issue**
See above

**Name of your Organization (Optional)**
Tinyclues

cc @rcrowe-google thanks !

**Comment by 1025KB** [comment]
Hi, we don't support nested runtime param (query nested in input_config, and input_config is passed to BigQueryExampleGen as exec_properties).

You need to pass [input_config](https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_big_query/example_gen/component.py#L48) as a runtime param, similar to [this](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_kubeflow.py#L168) example

**Comment by tanguycdls** [comment]
Hello @1025KB Thanks ! 
It works now with the following script if I also specify output_config, it does not work otherwise because make_default_output_config does not support RuntimeParameters. (I'll open another issue on that).
```
import json
from typing import Text

from tfx.extensions.google_cloud_big_query.example_gen import component as big_query_example_gen_component
from tfx.orchestration import pipeline
from tfx.orchestration.data_types import RuntimeParameter
from tfx.orchestration.kubeflow.v2.kubeflow_v2_dag_runner import KubeflowV2DagRunner, KubeflowV2DagRunnerConfig
from kfp.v2.google import client
from tfx.proto import example_gen_pb2

from pipelines.constants import GCS_BUCKET_NAME, GCP_REGION, GOOGLE_CLOUD_PROJECT


def create_full_training_pipeline(pipeline_root: str, _beam_args: dict) -> pipeline.Pipeline:
    input_config = RuntimeParameter(
        name="input_config",
        ptype=Text
    )
    output_config = example_gen_pb2.Output(
        split_config=example_gen_pb2.SplitConfig(splits=[
            example_gen_pb2.SplitConfig.Split(name='test', hash_buckets=1),
            example_gen_pb2.SplitConfig.Split(name='train', hash_buckets=1)
        ], partition_feature_name='split_id')
    )

    example_gen = big_query_example_gen_component.BigQueryExampleGen(input_config=input_config,
                                                                     output_config=output_config) \
        .with_id('ExampleGenR')
    return pipeline.Pipeline(
        beam_pipeline_args=_beam_args,
        pipeline_name="full-training",
        pipeline_root=pipeline_root,
        components=[
            example_gen,
        ],
    )


_temp_location = 'gs://{}/pipeline_tmp/{}'.format(GCS_BUCKET_NAME, 'test')
_beam_pipeline_args = [
    '--runner=DirectRunner',
    '--direct_running_mode=in_memory',
    '--direct_num_workers=0',
    '--temp_location=' + _temp_location,
    '--project=' + GOOGLE_CLOUD_PROJECT,
    '--region=' + GCP_REGION
]
training_pipeline = create_full_training_pipeline(
    pipeline_root=_temp_location,
    _beam_args=_beam_pipeline_args
)
PIPELINE_DEFINITION_FILE = '/tmp/test'
runner = KubeflowV2DagRunner(
    config=KubeflowV2DagRunnerConfig(),
    output_filename=PIPELINE_DEFINITION_FILE)
_ = runner.run(training_pipeline)

pipelines_client = client.AIPlatformClient(
    project_id=GOOGLE_CLOUD_PROJECT,
    region="europe-west4",
)

pipelines_client.create_run_from_job_spec(PIPELINE_DEFINITION_FILE,
                                          parameter_values={'input_config': json.dumps({
                                              "splits":
                                                  [
                                                      {
                                                          'name': 'train',
                                                          'pattern': "select 1 as split_id"
                                                      },
                                                  ]
                                          })}
                                          )

```

Thanks a lot, closing.

**Comment by 1025KB** [comment]
We don't have plan for that currently. Nest runtime param has it's limitation, e.g., proto/dict structure change or calculation to runtimeparam like "days from 1970-01-01 is what's needed while current time is the runtime param provided". We are looking for a more decent way of supporting advanced runtime param, e.g., a runtime param conversion which allows converting from what user provides to what tfx takes. Stay tuned!
