### ISSUE TITLE
`ImporterNode` to import `Model` artifact

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tfx#4152]
While using `ImporterNode` to specify `Model` artifact, the model needs to be placed under `serving_model_dir` within the source_uri. Using the actual model path, the importer node fails to recognize the model.

Corresponding doc issue: #4151

**Comment by arghyaganguly** [comment]
hi @sumitbinnani , could we please close this ticket and track the bug and doc issues together at one place?: [4151](https://github.com/tensorflow/tfx/issues/4151)

**Comment by sumitbinnani** [comment]
Is this a documentation issue or code bug?

**Comment by arghyaganguly** [comment]
@sumitbinnani , this can be classified as both.It will be better to track the debugging attempts and the doc update clubbed in one ticket.

**Comment by sumitbinnani** [comment]
Closing and tracking in #4151.

**Comment by sumitbinnani** [comment]
Closing and tracking in #4151
