### ISSUE TITLE
[Discussion] Relaxing TFT (and  therefore TF) pin

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#4167]
This a discussion followup from https://github.com/tensorflow/community/pull/372 

So my current understanding is that TFT is tied to a specific version of Tensorflow. Because of this and TFX being tied to 1 version of TFT, TFX is tied to 1 version of Tensorflow.

The question is, if TFX uses public TFT interfaces and TFT 1.X has a stable public API. Could we come up w a more relaxed system for TFT dependency which allowed us to support more versions of TF (and of TFT) per version of TFX?

This is due to the pain it is to upgrade tensorflow in a lot of systems (specially in monorepos)

@zhitaoli has context on this. Wanted to start this here to see if this may be a feasible option.

**Comment by casassg** [comment]
Rebumping this. I realize Transform component is being actively worked upon, but wondering if the API will be stable at some point between TFX -> TFT so that we can decouple a bit better this dependency

**Comment by zhitaoli** [comment]
Sorry for the slow response, but @jiyongjung0 is looking at piloting a process of extending supported TF version on old TFT minor release trains. The first one we will look at is to add TF 2.7 support to TFT/TFX 1.4.0 which currently only supports TF 2.6

@jiyongjung0 can comment on more

@casassg Do you have a particular TF / TFT combo desired?

**Comment by casassg** [comment]
I think from my side, the interesting thing would be to keep TFX compatible for ~3-4 versions since release. So Keep TFX 1.5 compatible w TF 2.7, 2.8 and 2.9 (ideally also 2.10).

We are at TFX 1.2.1 atm, and hoping to jump to TF 2.7 soon. But after that most likely we would need a bit more relaxed requirements for TFX and TF since we cant afford upgrading TF on production models so often.

**Comment by singhniraj08** [comment]
@casassg,

Please refer [TensorFlow 2.x in TFX](https://www.tensorflow.org/tfx/guide/keras) guide for Tensorflow and TFX compatibility. Transform currently has experimental support for Keras models.
The Transform component itself can be used for native Keras without change. The preprocessing_fn definition remains the same, using [TensorFlow](https://www.tensorflow.org/api_docs/python/tf) and [tf.Transform](https://www.tensorflow.org/tfx/transform/api_docs/python/tft) ops.

Please let us know if this issue can be closed. Thank you.
