### ISSUE TITLE
Taxi example in Azure platform

### ISSUE THREAD

**Issue by dineshvelmuruga** [tensorflow/tfx#4173]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows), Linux
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version: 2.6.0
- TFX Version: 1.0.0
- Python version: 3.8
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**
I am trying tfx taxi model example in azure platform using kubeflow in AKS as the orchestrator. I have placed the file in Azure blob storage and created a directory for tfx outputs. It is throwing me 

**az filesystem scheme not implemented**

**Describe the expected behavior**
How it will work in azure?

**Standalone code to reproduce the issue**

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by gowthamkpr** [comment]
You could run it either in a VM or in a containerized environment like [Kubernetes on Azure 9](https://azure.microsoft.com/en-us/overview/kubernetes-on-azure/). You could probably also run it on [Airflow 9](https://azure.microsoft.com/en-us/blog/deploying-apache-airflow-in-azure-to-build-and-run-data-pipelines/). However I haven’t tried either of these things. Please take a look at the solution provided [here](https://discuss.tensorflow.org/t/tfx-pipeline-on-azure/8353). I am closing this issue for now but if you run into issues, please reopen it.Thanks!!
