### ISSUE TITLE
Remove examples that are not updated to version 1+

### ISSUE THREAD

**Issue by grofte** [tensorflow/tfx#4179]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): No, you have
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Local Linux - Colab seems updated
- TensorFlow version: 2.5.1
- TFX Version: 1.2
- Python version: 3.8
- Python dependencies (from `pip freeze` output):

> absl-py==0.12.0
alembic==1.6.5
anyio==3.3.0
apache-airflow==2.1.2
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-sqlite==2.0.0
apache-beam==2.31.0
apispec==3.3.2
argcomplete==1.12.3
argon2-cffi==20.1.0
astunparse==1.6.3
attrs==20.3.0
avro-python3==1.9.2.1
Babel==2.9.1
backcall==0.2.0
bleach==4.0.0
blinker==1.4
cachetools==4.2.2
cattrs==1.5.0
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
click==7.1.2
clickclick==20.10.2
colorama==0.4.4
colorlog==5.0.1
commonmark==0.9.1
crcmod==1.7
croniter==1.0.15
cryptography==3.4.7
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
dill==0.3.1.1
dnspython==2.1.0
docker==4.4.4
docopt==0.6.2
docutils==0.16
email-validator==1.1.3
entrypoints==0.3
fastavro==1.4.4
fasteners==0.16.3
Flask==1.1.4
Flask-AppBuilder==3.3.2
Flask-Babel==1.0.0
Flask-Caching==1.10.1
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
flatbuffers==1.12
future==0.18.2
gast==0.4.0
google-api-core==1.31.2
google-api-python-client==1.12.8
google-apitools==0.5.31
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.5
google-cloud-aiplatform==0.7.1
google-cloud-bigquery==2.20.0
google-cloud-bigtable==1.7.0
google-cloud-core==1.7.2
google-cloud-datastore==1.15.3
google-cloud-dlp==1.0.0
google-cloud-language==1.3.0
google-cloud-profiler==3.0.5
google-cloud-pubsub==1.7.0
google-cloud-spanner==1.19.1
google-cloud-storage==1.42.0
google-cloud-videointelligence==1.16.1
google-cloud-vision==1.0.0
google-crc32c==1.1.2
google-pasta==0.2.0
google-resumable-media==1.3.3
googleapis-common-protos==1.53.0
graphviz==0.17
grpc-google-iam-v1==0.12.3
grpcio==1.34.1
grpcio-gcp==0.2.2
gunicorn==20.1.0
h11==0.12.0
h5py==3.1.0
hdfs==2.6.0
httpcore==0.13.6
httplib2==0.19.1
httpx==0.19.0
idna==3.2
importlib-metadata==4.6.4
importlib-resources==1.5.0
inflection==0.5.1
ipykernel==6.2.0
ipython==7.26.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
iso8601==0.1.16
isodate==0.6.0
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.11.3
joblib==0.14.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
keras-tuner==1.0.1
kubernetes==12.0.1
lazy-object-proxy==1.6.0
lockfile==0.12.2
Mako==1.1.4
Markdown==3.3.4
MarkupSafe==1.1.1
marshmallow==3.13.0
marshmallow-enum==1.5.1
marshmallow-oneofschema==3.0.1
marshmallow-sqlalchemy==0.23.1
matplotlib-inline==0.1.2
mistune==0.8.4
ml-metadata==1.2.0
ml-pipelines-sdk==1.2.0
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.3
numpy==1.19.5
oauth2client==4.1.3
oauthlib==3.1.1
openapi-schema-validator==0.1.5
openapi-spec-validator==0.3.1
opt-einsum==3.3.0
packaging==20.9
pandas==1.3.2
pandocfilters==1.4.3
parso==0.8.2
pendulum==2.1.2
pexpect==4.8.0
pickleshare==0.7.5
portpicker==1.4.0
prison==0.1.3
prometheus-client==0.11.0
prompt-toolkit==3.0.19
proto-plus==1.19.0
protobuf==3.17.3
psutil==5.8.0
ptyprocess==0.7.0
pyarrow==2.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pydot==1.4.2
Pygments==2.10.0
PyJWT==1.7.1
pymongo==3.12.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-daemon==2.3.0
python-dateutil==2.8.2
python-editor==1.0.4
python-nvd3==0.15.0
python-slugify==4.0.1
python3-openid==3.2.0
pytz==2021.1
pytzdata==2020.1
PyYAML==5.4.1
pyzmq==22.2.1
requests==2.26.0
requests-oauthlib==1.3.0
rfc3986==1.5.0
rich==10.7.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.7.1
Send2Trash==1.8.0
setproctitle==1.2.2
six==1.15.0
sniffio==1.2.0
SQLAlchemy==1.3.24
SQLAlchemy-JSONField==1.0.0
SQLAlchemy-Utils==0.37.8
swagger-ui-bundle==0.0.8
tabulate==0.8.9
tenacity==6.2.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.1
tensorflow-data-validation==1.2.0
tensorflow-estimator==2.5.0
tensorflow-hub==0.12.0
tensorflow-metadata==1.2.0
tensorflow-model-analysis==0.33.0
tensorflow-serving-api==2.5.1
tensorflow-transform==1.2.0
termcolor==1.1.0
terminado==0.11.1
terminaltables==3.1.0
testpath==0.5.0
text-unidecode==1.3
tfx==1.2.0
tfx-bsl==1.2.0
threadpoolctl==2.2.0
tornado==6.1
tqdm==4.62.1
traitlets==5.0.5
typing-extensions==3.7.4.3
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
WTForms==2.3.3
zipp==3.5.0

**Describe the current behavior**

Most of the examples do not seem to have been updated to TFX v1 (unless they are running in Colab). Could you perhaps retire the examples that are not updated ( at least until they are)? Or put a README in the `examples` folder listing the examples that are compatible with the most recent version?

It is very tricky as a beginner since Airflow will list the run as a success even though there isn't any `serving_model`. And the tutorial says to copy the example from the pip folder but that doesn't have the .sh scripts. But code from did actually create a `serving_model` despite looking the same and being from the same TFX version. But a model that I obviously don't have much confidence in. And where I then would need to get the scripts for serving from another source.

Others also seem to have problems with these examples
https://github.com/tensorflow/tfx/issues/3563
https://github.com/tensorflow/tfx/issues/4173

I was specifically working with the Chicago Taxi Pipeline examples but when I browse through the code of the other examples it seems very inconsistent whether they are importing tfx.v1 or not. Quite often they will import things with the `_pb2` suffix which are not in the [current API for version 1.2](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1).

**Standalone code to reproduce the issue**

https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi_pipeline

**Comment by singhniraj08** [comment]
@grofte,

I tried running the [TFX Estimator Component Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/components) in colab and the issue is fixed. Please try running the code with `TFX release 1.10`.
Also a warning has been added on top of tutorial stating estimators compatibility with TF 2 code. Hope this helps. Thank you!

> Warning: Estimators are not recommended for new code. Estimators run [v1.Session](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session)-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. Estimators do fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities. See the [migration guide](https://tensorflow.org/guide/migrate) for details.

**Comment by grofte** [comment]
Thank you!
