### ISSUE TITLE
Suspicious use of split_name in example_gen/component.py

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tfx#418]
This isn't necessarily a bug, but I am suspicious of some code. in:
https://github.com/tensorflow/tfx/blob/a412076f2d802d91511729992eedbab5c5992661/tfx/components/example_gen/component.py#L107

```
>>> tfx.__version__
'0.14.0dev'
```
The variable `split_name` is used, but I don't see where it's defined, other than after its usage.

Can you confirm that the code is correct?  And, I apologize if it's just that I missed something.  This report is only based on reading the code.  I don't see a failure when using the code (I'm guessing it isn't being touched).

@googlebot I signed it!

**Comment by 1025KB** [comment]
split_name is from your input and output config[[1](https://github.com/tensorflow/tfx/blob/a412076f2d802d91511729992eedbab5c5992661/tfx/components/example_gen/component.py#L109)], which can do some custom split[[2](https://github.com/tensorflow/tfx/blob/a412076f2d802d91511729992eedbab5c5992661/docs/guide/examplegen.md#custom-inputoutput-split)], default is no input split, and output will be split into train:eval=2:1

**Comment by robertlugg** [comment]
Hi @1025KB, @rmothukuru.  This issue is my misunderstanding.  I will explain why I made the mistake.
The code is:
```
    example_artifacts = example_artifacts or channel.as_channel([
        types.Artifact('ExamplesPath', split=split_name)
        for split_name in utils.generate_output_split_names(
            input_config, output_config)
    ])
```
Although correct, it is confusing because there is so much going on in that single assignment.  If it was written as:
```
    if example_artifacts is not None:
        split_names = utils.generate_output_split_names(input_config, output_config)
        example_artifacts = [types.Artifact('ExamplesPath', split=_sn) for _sn in split_names]
```
, then it would have been more understandable at first glance for me.  List comprehensions that span several lines generally make them less readable I think.  Still, the logic was correct.  I will close the issue.  I think it would be worth changing but I'm not sure how important "style" concerns are to you seeing how new the code is. Thank you for your time looking at this.
