### ISSUE TITLE
Add *.proto files to tfx python wheel package

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tfx#419]
Understanding the output of [protoc](https://github.com/protocolbuffers/protobuf) is difficult.  Those files reference source.  For instance:
```
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/example_gen.proto
```
, yet I don't see those files in this project.

Reading the *.proto files is a lot easier than the *_pb2.py files.  Would you consider adding those files?  Or at least reference another location where they can be examined?

**Comment by robertlugg** [comment]
The problem is that they **do** exist in this project:
https://github.com/tensorflow/tfx/tree/master/tfx/proto
, but aren't included after the python installation (ie after python setup.py install).  I guess it's reasonable to not have them in the install.

**Comment by zhitaoli** [comment]
We can use 'package_data' to include the protos. It's worth to include them for debugging purpose, IMO.

**Comment by robertlugg** [comment]
If there is a clean way to supply them, I think library users would benefit from having them in the install.  I'll reopen for visibility but I totally understand if you don't feel a change is warranted.

**Comment by singhniraj08** [comment]
@robertlugg,

You can refer to [tfx.v1.proto API](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/proto) for more info on TFX protos and the proto files are placed at [tfx/proto](https://github.com/tensorflow/tfx/tree/master/tfx/proto). Thank you!

**Comment by robertlugg** [comment]
If I recall the intent of this request it isn't resolved but would also take me effort to review and revise.  It is a low-priority request, so I'll just close.
