### ISSUE TITLE
Option to generate sample_weight from data_accessor

### ISSUE THREAD

**Issue by junbopark** [tensorflow/tfx#4198]
**System information**

- TFX Version: 0.30.0
- Environment in which you plan to use the feature: Google Cloud

**Describe the feature and the current behavior/state.**
We recently switched from estimator to Keras model, and we would like an option to get sample_weight from the dataset. 
Currently, since we are using a tf.dataset, we can only use sample_weight if it is provided by the dataset itself. However, the dataset is produced by `DataAccessor` (tfxio) so we cannot manually add sample weights to the dataset.

**Will this change the current API? How?**
```
    return data_accessor.tf_dataset_factory(
        file_pattern,
        tfxio.TensorFlowDatasetOptions(
            batch_size=batch_size, label_key=_transformed_name(label_key)),
        tf_transform_output.transformed_metadata.schema)
```

The `tfxio.TensorFlowDatasetOptions()` might include a `sample_weight_key` as a key-word option.

**Who will benefit with this feature?**
Users who need sample weights and want to use Keras model.

**Do you have a workaround or are completely blocked by this?** :
It works with our Estimator based pipeline. We can't migrate to Keras model.

**Name of your Organization (Optional)**
OpenX

**Comment by andylou2** [comment]
Hi Junbo,

We could consider adding an argument to TensorFlowDatasetOptions() to get the sample_weight.

In the meantime, would a dataset map_fn work for you? I.e.

without label_key:
```
ds = tfxio.TensorFlowDataset().map(lamba x: (x, x.pop('sample_weights')))
```
with label_key:
```
ds = tfxio.TensorFlowDataset().map(lamba x: (x[0], x[0].pop('sample_weights', x[1])))
```

Thanks,
Andy

**Comment by junbopark** [comment]
Yes, that worked for us. Thank you! 

For reference, I'm attaching the changes that we made to`_input_fn()`:
```
    return data_accessor.tf_dataset_factory(
        file_pattern,
        tfxio.TensorFlowDatasetOptions(
            batch_size=batch_size, label_key=_transformed_name(label_key)),
        tf_transform_output.transformed_metadata.schema)\
            .map(lambda x, y: (x, x.pop("sample_weight"), y))
```
