### ISSUE TITLE
Capability to define output key for Importer

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tfx#4251]
**Describe the feature and the current behavior/state.**
Currently, the output dict of the importer defaults to `result`. It will be good to let the user specify the output dict.

**Will this change the current API? How?**
Adding a new arg, `output_key='result'` to the [Importer](https://github.com/tensorflow/tfx/blob/master/tfx/dsl/components/common/importer.py#L247) API.

**Who will benefit with this feature?**
This will enable reusing the existing code snippet.
e.g. Current behavior requires the output dict to be updated everywhere:
```
schema_gen = Importer(...)
# schame_gen = SchemaGen(...)

trainer = Trainer(..., schema=schema_gen['result'], ...)
# trainer = Trainer(..., schema=schema_gen['schema_gen'], ...)

evalutor = Evaluator(..., schema=schema_gen['result'], ...)
# evalutor = Evaluator(..., schema=schema_gen['schema_gen'], ...)
```

**Do you have a workaround or are completely blocked by this?** :
Refactor the code

**Name of your Organization (Optional)**
Twitter, Inc.

**Comment by jiyongjung0** [comment]
Hi, thank you for the report.

Do you have any specific usages other than SchemaGen? Because we are thinking about adding a new component for importing a schema, and it will have the same output key with the existing SchemaGen. (WIP PR is at https://github.com/tensorflow/tfx/pull/4246 )

**Comment by UsharaniPagadala** [comment]
@sumitbinnani 
Could you please have a look on @jiyongjung0  comment.Thanks

**Comment by sumitbinnani** [comment]
In addition to SchemaGen, also ExampleGen. Reusing a transformed training dataset is also a common use case. Similarly, if one have multiple trained models that they would like to use for evaluation, one might want to also import channel of type Model. etc.

**Comment by 1025KB** [comment]
You can do like below thus you don't need to change all downstream components.

schema_gen = Importer(...)
schema=schema_gen.output['result']
# schame_gen = SchemaGen(...)
# schema=schema_gen.output['schema_gen']

trainer = Trainer(..., schema=schema, ...)
evalutor = Evaluator(..., schema=schema, ...)

**Comment by sumitbinnani** [comment]
Thanks for the suggestion, @1025KB! This works. However, it adds more code (and might require updating the complete code base we have). Sure! I can work on a PR to make this configurable.

**Comment by UsharaniPagadala** [comment]
@sumitbinnani 

Could you please move this to closed status if it is resolved.Thanks
