### ISSUE TITLE
{SPAN} doesn't work as expected with GCS

### ISSUE THREAD

**Issue by deep-diver** [tensorflow/tfx#4273]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): **Yes**
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): **Vertex AI Pipeline**, **Vertex AI Notebook**, **GCS storage**
- TensorFlow version: **2.6**
- TFX Version: **1.2.0**
- Python version: **3.7**
- Python dependencies (from `pip freeze` output): **None**

**Describe the current behavior**
First of all, I have CIFAR10 dataset in the following location 
- `gs://cifar10-csp-public/cifar10/span-1/train/train.tfrecord`
- `gs://cifar10-csp-public/cifar10/span-1/test/test.tfrecord`

With `ImportExampleGen` as defined below, it failed to get the dataset from the specified `pattern` paths. 

```python

data_path = "gs://cifar10-csp-public"

input_config = example_gen_pb2.Input(splits=[
              example_gen_pb2.Input.Split(name='train',
                                          pattern='cifar10/span-{SPAN}/train/*'),
              example_gen_pb2.Input.Split(name='val',
                                          pattern='cifar10/span-{SPAN}/test/*')
          ])

example_gen = tfx.components.ImportExampleGen(input_base=data_path, input_config=input_config)
```

As inspecting the logs, it complains the files don't exist.

```bash
OSError: No files found based on the file pattern gs://cifar10-csp-public/cifar10/span-{SPAN}/train/*
```

**Describe the expected behavior**

The expected behaviour is that `ImportExampleGen` can correctly retrieve the data with `{SPAN}` specified. As it didn't work as expected, I have tried out the code below

```python
data_path = "gs://cifar10-csp-public"

splits = [
  example_gen_pb2.Input.Split(name='train',pattern='span-{SPAN}/train/*'),
  example_gen_pb2.Input.Split(name='val',pattern='span-{SPAN}/test/*')
]
_, span, version = utils.calculate_splits_fingerprint_span_and_version(data_path, splits)
  
input_config = example_gen_pb2.Input(splits=[
    example_gen_pb2.Input.Split(name='train', pattern=f'span-{span}/train/*'),
    example_gen_pb2.Input.Split(name='val', pattern=f'span-{span}/test/*')
])

example_gen = tfx.components.ImportExampleGen(input_base=data_path, input_config=input_config)
```

With the utility function `calculate_splits_fingerprint_span_and_version`, it works fine now. However, I just wonder why it didn't work in the first place. Doesn't `ImportExampleGen` use `calculate_splits_fingerprint_span_and_version` function internally?

**Comment by UsharaniPagadala** [comment]
@deep-diver 
Could you please have a look at @1025KB  comment and let us know if this resolved.Thanks

**Comment by deep-diver** [comment]
@1025KB @UsharaniPagadala 

sorry about the inconsistency. I have experimented with many different configurations, so I mistakenly wrote the issue. sorry about that

please assume `cifar10/span-{SPAN}/train/*` is the correct pattern everywhere.

**Comment by 1025KB** [comment]
Does your code work on local env?

**Comment by deep-diver** [comment]
Let me share the actual notebook and the error messages. Please wait for a day or so.

Thank you

**Comment by deep-diver** [comment]
@1025KB @UsharaniPagadala 

here is the [notebook](https://colab.research.google.com/drive/1XHOB7pkFictdyk014_7oSUATrwwiwWXF?usp=sharing) that I am using.

I have tested out two different code snippet. As the first attempt, I have used only `ImportExampleGen` component and it's `input_config` capability.

```python
input_config = example_gen_pb2.Input(splits=[
    example_gen_pb2.Input.Split(name='train', pattern='span-{SPAN}/train/*'),
    example_gen_pb2.Input.Split(name='eval',pattern='span-{SPAN}/test/*')
])

data_root = 'gs://cifar10-csp-public'
example_gen = tfx.components.ImportExampleGen(input_base=data_root,
                                              input_config=input_config)
```

and this code gives me an error when running on Vertex AI. Here is the screenshot of the error message.

![Screen Shot 2021-10-05 at 11 08 36 PM](https://user-images.githubusercontent.com/26025527/136040816-b1420dc2-8d8b-494b-87fd-b85353b5919e.png)

It seemed like it can not find the GCS location at all even though the **Output Parameters** from the **Vertex Pipeline's Node Info** shows the correct signs. Here is the screenshot.

![Screen Shot 2021-10-05 at 11 17 19 PM](https://user-images.githubusercontent.com/26025527/136041188-a91eeba7-29c8-459f-bb81-0bdd45af76b8.png)

So, in the second trial, I have used `utils.calculate_splits_fingerprint_span_and_version` function directly. You can see the actual code snippet in the [notebook](https://colab.research.google.com/drive/1XHOB7pkFictdyk014_7oSUATrwwiwWXF?usp=sharing). They are commented out for now to show the error.

```python
splits = [
  example_gen_pb2.Input.Split(name='train',pattern='span-{SPAN}/train/*'),
  example_gen_pb2.Input.Split(name='val',pattern='span-{SPAN}/test/*')
]
_, span, version = utils.calculate_splits_fingerprint_span_and_version(data_root, splits)

input_config = example_gen_pb2.Input(splits=[
  example_gen_pb2.Input.Split(name='train', pattern=f'span-{span}/train/*'),
              example_gen_pb2.Input.Split(name='val', pattern=f'span-{span}/test/*')
])

data_root = 'gs://cifar10-csp-public'
example_gen = tfx.components.ImportExampleGen(input_base=data_root,
                                            input_config=input_config)
```

This second trial works good. Please let me know if you need any further information.

**Comment by 1025KB** [comment]
So when you used only ImportExampleGen, it shows some error in log, but component finished without crash and it outputs correct results?

Do you have the full error trace? I code search "No files found based on the file pattern" but found nothing

**Comment by deep-diver** [comment]
>  but component finished without crash and it outputs correct results?

No, it crashes, and no further downstream components got started 

> I saw "f'span-{span}/train/'" is used for the second trial while "'span-{SPAN}/train/'" is used for first trial, I think we only allow '{SPAN}'

please note that `f'span-{span}/train/*'` is something I have manually found by using `utils.calculate_splits_fingerprint_span_and_version`

> Do you have the full error trace? I code search "No files found based on the file pattern" but found nothing

here is more of the logs (too long for the full trace, and don't know how to effectively share the logs from GCP)

![Screen Shot 2021-10-06 at 1 48 52 AM](https://user-images.githubusercontent.com/26025527/136067123-6101b7cf-4e6c-4e08-92ff-f9445a76971a.png)

**Comment by 1025KB** [comment]
I noticed the input_fingerprint, it shows the num of files is zero, what is under span-2/train/?
It seems even for you second trial, which has fixed pattern f'span-{span}/train/' -> 'span-2/train/', it might not actually found anything under span-2/train/

**Comment by deep-diver** [comment]
@1025KB 

actually, there is nothing under `span-2`, but I have seen error still occurs even with `span-1` which has tfrecord file. let me run it and share the result (just wait for minutes)

**Comment by 1025KB** [comment]
It will try to find the latest span unless range_config is specified, but if the target span folder is empty, it might has errors

**Comment by deep-diver** [comment]
@1025KB 

what about now? I have specified RangeConfig with span number 1. and there is `.tfrecord` files in the specified span.

<img width="844" alt="Screen Shot 2021-10-06 at 2 44 18 AM" src="https://user-images.githubusercontent.com/26025527/136075489-63ae2fcd-0eb6-4956-9604-6563c2d91e39.png">

<img width="1345" alt="Screen Shot 2021-10-06 at 2 44 25 AM" src="https://user-images.githubusercontent.com/26025527/136075505-0bd9742c-931c-48df-96d8-b619fef4e97b.png">

**Comment by 1025KB** [comment]
Thanks, it seems a bug in KFPV2DagRunner (LocalDagRunner should work), let me check

**Comment by deep-diver** [comment]
@1025KB 

yes I have successfully run the same code in a local environment (with interactive context)

**Comment by deep-diver** [comment]
@1025KB 

and if you don't mind, let me ask one more question about the behaviour of `RangeConfig`. I am the guy who wrote email to @rcrowe-google, and he forwarded that email to you.

what is the reason behind [this condition](https://github.com/tensorflow/tfx/blob/00571387b7b006e2ebb0c1277380e5a47d8f0ffa/tfx/components/example_gen/input_processor.py#L40)?

"Range" sounds like we should be able to choose multiple datasets from multiple spans, but it only allows single span number. In my current project, I was going to use datasets from `span-1` and `span-2 (drifted)` to train a new model from scratch, but this is not a possible approach with the current TFX's implementation.

I have come up with an alternate solution, but this is something that some ML practitioners want I guess. Let me know your thought if you don't mind.

**Comment by 1025KB** [comment]
Range_config is also used in Resolver, which can resolve multiple spans from multiple ExampleGen's execution, here is an [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_local_e2e_test.py#L285)

Also we might support multiple executions within a (ExampleGen) component in the future

**Comment by deep-diver** [comment]
@1025KB 

It still confuses me because the internal source code says like [this](https://github.com/tensorflow/tfx/blob/00571387b7b006e2ebb0c1277380e5a47d8f0ffa/tfx/components/example_gen/input_processor.py#L48)
```python
      elif range_config.HasField('rolling_range'):
        if range_config.rolling_range.num_spans != 1:
          raise ValueError(
              'ExampleGen only support single span for RangeConfig.RollingRange.'
          )
```

meaning only a single span is allowed for `ExampleGen`. Am I correct?

**Comment by 1025KB** [comment]
Yep, only single span is allowed for ExampleGen currently, 
ExampleGen and SpanResolver shares the same range_config proto.

**Comment by deep-diver** [comment]
so I can achieve desired result (accept range of spans(`span-1` and `span-2`) as a training dataset) if I combine `ExampleGen` and `Resolver` together?

It seems like so by looking at the [official doc](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/dsl/Resolver?hl=th)
```python
example_gen = ImportExampleGen(...)
examples_resolver = Resolver(
      strategy_class=SpanRangeStrategy,
      config={'range_config': range_config},
      examples=Channel(type=Examples, producer_component_id=example_gen.id)
      ).with_id('Resolver.span_resolver')
trainer = Trainer(
    examples=examples_resolver.outputs['examples'],
    ...)
```}

**Comment by deep-diver** [comment]
I am scratching my head to understand its behaviour.

```python
  examplegen_range_config = proto.RangeConfig(
      static_range=proto.StaticRange(
          start_span_number=2, end_span_number=2))

  example_gen = tfx.components.CsvExampleGen(
      input_base=os.path.join(data_root, 'labelled'),
      input_config=examplegen_input_config,
      range_config=examplegen_range_config)

    resolver_range_config = proto.RangeConfig(
        rolling_range=proto.RollingRange(num_spans=2))

    examples_resolver = tfx.dsl.Resolver(
        strategy_class=tfx.dsl.experimental.SpanRangeStrategy,
        config={
            'range_config': resolver_range_config
        },
        examples=tfx.dsl.Channel(
            type=tfx.types.standard_artifacts.Examples,
            producer_component_id=example_gen.id)).with_id('span_resolver')
```

with this setting, whenever I run the pipeline, span 1 and 2 will be consumed by TFT and Trainer? 

in the [material](https://github.com/tensorflow/community/blob/master/rfcs/20210115-tfx-periodic-training.md#rolling-window) that you shared confuses me because it looks like the the number of `span`s grows when we run the pipeline (span-1 for run1, span-1 and 2 for run2, ..., up to window size)

**Comment by sayakpaul** [comment]
@1025KB hi. I am one of the other collaborators on the project for which @deep-diver raised this doubt. 

If we were to implement the following scenario:

![image](https://user-images.githubusercontent.com/22957388/136156463-6376cf4b-2ba0-414e-90b3-2068d1d76fcf.png)


What changes do we need to make to the `ExampleGen` and `Resolver` components? Could you help us with some demo code or template?

**Comment by 1025KB** [comment]
> I am scratching my head to understand its behaviour.
> 
> ```python
>   examplegen_range_config = proto.RangeConfig(
>       static_range=proto.StaticRange(
>           start_span_number=2, end_span_number=2))
> 
>   example_gen = tfx.components.CsvExampleGen(
>       input_base=os.path.join(data_root, 'labelled'),
>       input_config=examplegen_input_config,
>       range_config=examplegen_range_config)
> 
>   resolver_range_config = proto.RangeConfig(
>       rolling_range=proto.RollingRange(num_spans=2))
> 
>   examples_resolver = tfx.dsl.Resolver(
>       strategy_class=tfx.dsl.experimental.SpanRangeStrategy,
>       config={
>           'range_config': resolver_range_config
>       },
>       examples=tfx.dsl.Channel(
>           type=tfx.types.standard_artifacts.Examples,
>           producer_component_id=example_gen.id)).with_id('span_resolver')
> ```
> 
> with this setting, whenever I run the pipeline, span 1 and 2 will be consumed by TFT and Trainer?
> 
> in the [material](https://github.com/tensorflow/community/blob/master/rfcs/20210115-tfx-periodic-training.md#rolling-window) that you shared confuses me because it looks like the the number of `span`s grows when we run the pipeline (span-1 for run1, span-1 and 2 for run2, ..., up to window size)

when you run this pipeline, ExampleGen will process span 2, and Resolver will try to get 2 spans from MLMD for downstream (e.g., one of the span is from current ExampleGen execution, the other span is from previous ExampleGen execution for span 1)

**Comment by deep-diver** [comment]
Meaning previous ExampleGen had to be run in a separate pipeline run beforehand, then the second run will look it up

Correct?

**Comment by 1025KB** [comment]
> Meaning previous ExampleGen had to be run in a separate pipeline run beforehand, then the second run will look it up
> 
> Correct?

Yep for this example, it's for [periodic training](https://github.com/tensorflow/community/blob/master/rfcs/20210115-tfx-periodic-training.md#rolling-window) use case, e.g., for each day, pipeline process yesterday's new available span, but trainer needs a whole week of data to train.

if you want to have them in the same pipeline, you can:
1. ExampleGen treat all data as a single span:
     data block 1,2,3... -> single ExampleGen (file pattern covers all needed input) -> single example artifact (default as span 0) -> trainer
2. multiple examplegen instances with resolver:
      data1 -> EG -> example artifact span 1 ------> resolver -> [span1, span2] -> trainer
      data2 -> EG -> example artifact span 2 ---^
   (we will have channel.union for merging such channels in the future)

**Comment by 1025KB** [comment]
Sure, that would be great, Robert and I can help take a look.

**Comment by 1025KB** [comment]
FYI, https://github.com/tensorflow/tfx/pull/4347 this PR should fix the {SPAN} for Vertex (KubeflowV2DagRunner)

**Comment by sayakpaul** [comment]
@1025KB 

```
multiple examplegen instances with resolver:
data1 -> EG -> example artifact span 1 ------> resolver -> [span1, span2] -> trainer
data2 -> EG -> example artifact span 2 ---^
(we will have channel.union for merging such channels in the future)
```

For `data1` how come `span2` is already available there if EG has artifact for `span1` only?

**Comment by deep-diver** [comment]
@1025KB 

Correct me I am wrong.

in `data1 -> EG -> example artifact span 1 ------> resolver -> [span1, span2] -> trainer`, Resolver's `range_config`'s `num_spans` is set  to `2`, so you expressed like `[span1, span2]`. But `Resolver` will notice there is only `span1` available to consume, and the one `span1` will be processed. 

However, in the second pipeline run `data2 -> EG -> example artifact span 2 ---`, we both have artifacts for `span1` and `span2`, and Resolver's 'range_config`'s `num_spans` is set to `2`, so both spans will be processed.

This is periodic training training use case that you showed, but we will leverage this feature to select the range of spans as needed when the pipeline run get launched. We will hand over range information through `RuntimeParameter`.

**Comment by deep-diver** [comment]
@1025KB 

Oh I see, what you are saying is to treat multiple spans as a single span using **file pattern**, is that correct?

What I am trying to figure out is this
- passing two `RuntimeParameter` s. one for starting span number (`end_span`), and the other one for number of spans (`num_spans`). 
- use those to configure `RangeConfig` and `RollingConfig`

But what you were saying is
- passing `RuntimeParameter` for `input_config` including glob patterns to match all the needed spans

right?

**Comment by 1025KB** [comment]
It's totally depends on your use case [single span for training](https://github.com/tensorflow/community/blob/master/rfcs/20210115-tfx-periodic-training.md#single-span) vs [rolling window for training](https://github.com/tensorflow/community/blob/master/rfcs/20210115-tfx-periodic-training.md#rolling-window)

The Span's semantic/meaning is user-defined based on the use case.

single span for training, e.g.,
pipeline run every **week**, takes whole week's data as a single span, train a model based on the span generated from whole week's data. span 0 is day1-7, span 1 is day 8-14 etc. Trainer only needs single span for training.
week1, ExampleGen processes span1 (data of day1-7),  Trainer takes span1, no Resolver.
week2, ExampleGen processes span2 (data of day8-14),  Trainer takes span2, no Resolver.

rolling window for training, e.g.,
pipeline run every **day**, each pipeline takes a single day's data as a single span, train a model based on 7 rolling spans.
day6, ExampleGen processes span 6 (data of day6), Resolver gets span 1-6 (not a full week) for Trainer
day7, ExampleGen processes span 7 (data of day7), Resolver gets span 1-7 for Trainer
day8, ExampleGen processes span 8 (data of day8), Resolver gets span 2-8 for Trainer
day9, ExampleGen processes span 9 (data of day9), Resolver gets span 3-9 for Trainer

If it's periodic training, I would suggest to use RangeConfig as a runtimeparam (json format), instead of change the fixed pattern in input_config (in this method, all data will be treated/marked as span 0 in mlmd, and for rolling window use case, you will have a lot of duplicated calculation: ExampleGen will process data 1-7  then 2-8  then 3-9, instead of a single data block each run)

**Comment by deep-diver** [comment]
@1025KB 

Sorry to bother you many times 😅

We are using span to represent different dataset from different distribution. For instance, when data drift happens, we would like to those data in the successive span (let's say 2)

For this scenario, I thought we could leverage ExampleGen and Resolver with rolling window just like periodic training (assuming one wants to retrain the model from scratch with span 1 and 2 to get the best model)

I understand it is the choice of implementation details, so I guess we can achieve the goal in two different approaches (one with pattern matching), and it is the matter of our decision on how to implement. 

In any cases, I think we need RuntimeParameter to determine the arbitrary range of spans whenever pipeline run gets launched. I have seen I can use RuntimeParameter for input_config(for the choice of using file pattern matching), but I have no idea how to configure range_config for the ExampleGen and Resolver with RuntimeParameter. I have tried out with ptype=Text, but I get an error, and I can't resolve the issue. Is it possible?

**Comment by 1025KB** [comment]
we don't have example for RangeConfig proto + runtime param, but we have an [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_kubeflow.py#L167) for other proto

you just need to config ExampleGen's range_config, Resolver is normally fixed rolling range for rolling window use case

**Comment by deep-diver** [comment]
@1025KB 

I just realized that the main issue is not merged yet, so I was using `calculate_splits_fingerprint_span_and_version` manually. And `calculate_splits_fingerprint_span_and_version` doesn't take the `RuntimeParameter` for `range_config`. In this case, should I wait until the PR is merged (+next TFX release)?

**Comment by deep-diver** [comment]
@1025KB 

Let me check what's not possible without the PR to fix this issue.
- We can configure `RollingRange` 's `range_config` with `num_spans` for `Resolver`. 
- However, in order to leverage `Resolver` 's `RollingRange` capability, we should use `{SPAN}` pattern for `input_config` + `StaticRange` config for `ExampleGen`.
- In this case, since we can not use `{SPAN}` pattern before the PR is merged in the next release, we also can not use `Resolver` as well yet.

Am I right? 

As a workaround, I just string engineered to get an appropriate glob pattern manually.

**Comment by 1025KB** [comment]
Yep, those features are available in LocalDagRunner and KFPDagRunner, but KFPV2DagRunner needs that PR.

Before release, You can use our nightly packages instead of released package once that PR is merged
pip install -i https://pypi-nightly.tensorflow.org/simple tfx
https://github.com/tensorflow/tfx/blob/master/tfx/tools/docker/README.md

**Comment by deep-diver** [comment]
@1025KB 

I have tried out `1.4.0.dev20211010` nightly build version, and it didn't fix the issue.
I assume the PR (merged 9 hours ago as I am writing this) is not affected yet, and I look forward to using the next nightly build version. 

I just wanted to confirm that my assumption is right with you :)

**Comment by 1025KB** [comment]
I think you need to build the container with the nightly release to make it work

**Comment by deep-diver** [comment]
@1025KB @jiyongjung0 

I guess docker image for nightly build is pushed to the `docker hub`, but it didn't happen yesterday.
- https://hub.docker.com/r/tensorflow/tfx/tags

I am waiting for the next build

**Comment by jiyongjung0** [comment]
@deep-diver @1025KB The nightly build passed yesterday(Or should we call it today for KST? 😄 ).

https://hub.docker.com/layers/tensorflow/tfx/1.4.0.dev20211013/images/sha256-7759ea95c4a83c4e2b8d210994ca4c15556d13cc2c2c83b57f943e9a1e444d01?context=explore

**Comment by deep-diver** [comment]
@jiyongjung0 thanks for the update!! So excited about this :)

**Comment by deep-diver** [comment]
@1025KB yes rolling window is what I need 😀

**Comment by deep-diver** [comment]
@1025KB 

OK, I got it. 
I can not use `SpanRangeStrategy` for Vertex AI then.

In this case, I would like to have an advice how to form a `glob pattern` matching for multi-span data input for `ImportExampleGen`. 
I have tried out below, but none of them worked out.
- `span-(span1 | span2)/train/*` and `span-(span1 | span2)/test/*`
- `span-{span1, span2}/train/*` and `span-{span1, span2}/test/*`

or if you have a better suggestion, please let us know as well. Thank you so much

**Comment by deep-diver** [comment]
ok so, I did this `	{ "splits": [ { "name": "train", "pattern": "span-[12]/train/*" }, { "name": "val", "pattern": "span-[12]/test/*" } ] }`, and it seems passed.

But, how would I know which files are processed? is there a way to see like log?

**Comment by 1025KB** [comment]
If you are using ImportExampleGen, you should find [this](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/import_example_gen/executor.py#L50) log

similar for CSVExampleGen [log](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/csv_example_gen/executor.py#L178)

Also you can fine the [log](https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/base_example_gen_executor.py#L252) for executor's input/output/exec_properties, this contains the resolved input_config, e.g.,

even you have "span-{SPAN}/train/*" in the pattern, this `{SPAN}` will be replaced to real value before execution (before executor.do function), so you should be able to see sth like "span-5/train/*" in the logged input_config.

**Comment by deep-diver** [comment]
@1025KB 

Yes what you are saying sounds reasonable, but I still want to keep files in different directories like span-1 and span-2.

In this case I can use pattern like span-[12] right?

**Comment by 1025KB** [comment]
if it's valid, then it will glob files under both span-1 and span-2, but tfx won't know what span those input belong to, so tfx will treat them as span 0, tfx use `{SPAN}` to detect span

**Comment by deep-diver** [comment]
@1025KB 

Let me just clarify the problem me and @sayakpaul are facing.
1. we want to dynamically choose the range of spans to train on Vertex AI platform
2. however, `SpanRangeStrategy` for `Resolver` does not work on Vertex AI as mentioned [here](https://github.com/tensorflow/tfx/issues/4273#issuecomment-943571644)
3. Also, `ExampleGen` without `Resolver` can only choose a single span number even with `range_config`
4. so, instead of using `{SPAN}` with `range_config`, we chose to use just glob pattern without `{SPAN}`.

Dose it make sense?
