### ISSUE TITLE
Mention enabling Vertex AI API and adding GCP IAM permissions when running vertex_pipelines_simple.ipynb

### ISSUE THREAD

**Issue by davidxia** [tensorflow/tfx#4313]
## URL(s) with the issue:

github source https://github.com/tensorflow/tfx/blob/8abbc4bb3b3e06aa8aca201195e4995f39146a2f/docs/tutorials/tfx/gcp/vertex_pipelines_simple.ipynb
rendered page https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_simple

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_simple

## Description of issue (what needs changing):

The last cell on the page above has `pipelines_client.create_run_from_job_spec(PIPELINE_DEFINITION_FILE)`. In order for this to succeed, the **user must enable the Vertex AI API in their project and add the following GCP IAM roles for the GCE default service account for the  Vertex pipeline to succeed**.

* roles/storage.admin on the specific GCS bucket
* roles/aiplatform.user

### Clear description:

The first time I ran the Colab notebook, I had to carefully read the error response and enable the Vertex AI API.
Then I got the error

![image](https://user-images.githubusercontent.com/480621/134931919-455f6229-f213-48b3-a188-da496575ebcc.png)

After adding an IAM policy for the GCE default Service Account `381087845752-compute@developer.gserviceaccount.com` with role `roles/aiplatform.serviceAgent`, the pipeline errored with

![image](https://user-images.githubusercontent.com/480621/134932151-fc807a6a-b398-40e7-87ab-f60108c8a8fe.png)

So I replaced the role with `roles/aiplatform.user`. The next errors were

![image](https://user-images.githubusercontent.com/480621/134933159-e7c7458d-a7f8-4534-919f-1b9a2a5ff904.png)

`381087845752-compute@developer.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.`

So I also needed to add roles/storage.admin for the same service account on that specific GCS bucket.

Then another pipeline invocation succeeded. The notebook could mention these or even better have commands as pre-requisites so that users don't have to understand the errors and fix themselves.

Great tutorial otherwise. Thanks!

**Comment by singhniraj08** [comment]
@davidxia,

In the official tutorial, the enable Vertex AI and Cloud storage API step has been mentioned in [setup section](https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_simple#set_up). Also, the [vertex documentation](https://cloud.google.com/vertex-ai/docs/pipelines/configure-project) link in setup section guides us to grant permissions for pipeline run and cloud storage access. Thank you!

**Comment by davidxia** [comment]
I see. I must've missed those steps. Thanks
