### ISSUE TITLE
VertexAI training accelerator_type with NVIDIA_TESLA_A100 string doesn't work, needs to update documentation

### ISSUE THREAD

**Issue by entrpn** [tensorflow/tfx#4340]
Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_vertex_training#write_a_pipeline_definition

## Description of issue (what needs changing):

The documentation explains that you can use a string value to set the GPU type. 

```
vertex_job_spec['worker_pool_specs'][0]['machine_spec'].update({
        'accelerator_type': 'NVIDIA_TESLA_K80',
        'accelerator_count': 1
    })
```

This works for the string `NVIDIA_TESLA_K80` but not when you use the string `NVIDIA_TESLA_A100`. It looks like the reason why it works for one and not the other is because the version of google-cloud-ai-platform being used with tfx1.2 is 0.7.1 and NVIDIA_TESLA_A100 was only added to the enum list in v1.2.0 on july 15.

Unit tests sort of confirm this:

https://github.com/googleapis/python-aiplatform/blob/main/tests/unit/aiplatform/test_utils.py#L278

The change in the documentation is to instead of using the string enum value `NVIDIA_TESLA_A100`, use the enum value, `8`. Or for any other GPU that can be used, it should use the enum int value instead.

For example:

```
vertex_job_spec = {
        'project': PROJECT_ID,
        'worker_pool_specs': [
        {
          'machine_spec': {
            'machine_type': 'a2-highgpu-2g',
            'accelerator_type' : 8,#'NVIDIA_TESLA_A100',
            'accelerator_count': 2
          },
          'replica_count': 1,
          'container_spec': {
            'image_uri': 'gcr.io/tfx-oss-public/tfx:{}'.format(tfx.__version__),
          }
        }
        ],
      }
```

### Clear description:

This is useful because anyone trying to use a GPU that is not a K80 will not be able to run vertex ai custom training jobs.

**Comment by entrpn** [comment]
I created a pr to update the documentation https://github.com/tensorflow/tfx/pull/4353

**Comment by UsharaniPagadala** [comment]
@entrpn 
Thanks for creating PR once the [PR](https://github.com/tensorflow/tfx/pull/4353) merged, this issue will be closed.Thanks!

**Comment by singhniraj08** [comment]
@entrpn, Could you please try with latest TFX release 1.10.0 and see if the string value works of your GPU works in 'accelerator_type' param. Thank you!

**Comment by entrpn** [comment]
@singhniraj08 it works with 1.9.0. I'm not able to run my pipeline with 1.10.0. Getting some other errors. Thanks
