### ISSUE TITLE
Can I use Trino instead of Presto as custom component?

### ISSUE THREAD

**Issue by FernandoDorado** [tensorflow/tfx#4410]
**Describe the feature and the current behavior/state.**
Some time ago we migrated from Presto to Trino, as we believe that the latter has more potential and retains the original developers of Presto, while maintaining its functionality. I would like to know if using the Presto custom component I could use Trino, or if it would be possible to create a custom component specifically for Trino. 

**Will this change the current API? How?**
No

**Who will benefit with this feature?**
All users that implement Trino instead of Presto (owned by Facebook)

**Do you have a workaround or are completely blocked by this?** :
No

**Name of your Organization (Optional)**
Idener

**Comment by 1025KB** [comment]
Yep, You can implement your own custom example gen

**Comment by FernandoDorado** [comment]
I mean, Trino is similar to Presto. I want to know if the connector to presto works with Trino without making any change. 
It is just in order to know if you/your team had done some tests to check this feature. 
Thanks!

**Comment by 1025KB** [comment]
No, our team didn't test with Trino in the past
