### ISSUE TITLE
Vertex AI with TFX Training got stuck

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [tensorflow/tfx#4419]
**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Linux, tfx 1.0.0 docker image
- TensorFlow version: 2.5.0 from tfx 1.0.0 docker image
- TFX Version: tfx 1.0.0 docker image
- Python version: 3.7.10
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**
* Kubeflow job is submitted by following examples provided here (only used the code to submit the job, training `run_fn` is custom): https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_simple
* Custom docker images is built using tfx 1.0.0 image as base.

As shown in the following image. The Trainer component imported from `tfx.v1.extensions.google_cloud_ai_platform` creates 2 jobs, 1 for the Trainer component (ID 47xxx), and the other is the model training job (ID 84xxx) submitted by this component. The model training job finishes relatively quickly. However, the Trainer component job is stuck at `Job is running` (almost an hour), so long to a point that I had to cancel the job.

![Screen Shot 2021-10-30 at 1 42 19 PM](https://user-images.githubusercontent.com/80276234/139543515-dea22d77-30bf-4c22-9b98-84a02758ae35.png)

Logs associated with the Trainer component. No show-stopping errors.
![Screen Shot 2021-10-30 at 1 48 38 PM](https://user-images.githubusercontent.com/80276234/139543694-618d577e-328c-4056-aed5-29580282f456.png)

**Describe the expected behavior**

Trainer component should report "Done" right after the training job is finished, within reasonable delay.

**Comment by 1025KB** [comment]
we are working on a release with fix in it

**Comment by EdwardCuiPeacock** [comment]
Hi, @1025KB, is this release going to be a new version of the TFX or an internal release on Vertex AI (so that no TFX version changes are needed)?

**Comment by 1025KB** [comment]
TFX 1.3.2

**Comment by EdwardCuiPeacock** [comment]
Thanks, I will close this issue for now, as we seem to have a solution to this in the upcoming release.
