### ISSUE TITLE
Do we have examples of using ELWC with Transform/Evaluator?

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tfx#4457]
Do we have examples of using ELWC with Transform/Evaluator?

**Comment by casassg** [comment]
https://github.com/tensorflow/tfx/tree/master/tfx/examples/ranking

**Comment by UsharaniPagadala** [comment]
@sumitbinnani 
Could you please confirm if this issue can be  closed as it is resolved.Thanks
