### ISSUE TITLE
add conda package

### ISSUE THREAD

**Issue by yonil7** [tensorflow/tfx#4462]
Please add a `conda` package for installing `tfx` easily on scientific python stacks that use `conda` package management instead of `pip`.

My setup:
* I would like to run `tfx` pipelines on GCP Vertex AI
* I have a `conda` virtual env with ~300 `conda-forge` packages and no `pypi` packages
* I create the virtual env with [`mamba`](https://github.com/mamba-org/mamba) instead of `conda` but this issue also apply when creating a virtual env with `conda`
* When installing `tfx` using `pip` it has a lot of conflicts with the `conda` packages versions, and does a lot of `uninstall` for uninstalling and changing many of them to come from `pypi` instead of `conda` channels. That cause the packages in the environment to be in inconsistent state and unusable
* Side note: I use [`mamba`](https://github.com/mamba-org/mamba) cause building a virtual env with it is x100 faster than `conda` / `pip` as it uses `libsolv` for much faster dependency solving

I'm sure there are a lot of people in the scientific python ecosystem that would love to be able to install `tfx` with `conda`

**Comment by singhniraj08** [comment]
@yonil7,

Similar feature request #4978 is already in development. Requesting you to close this issue and follow similar issue thread for updates. Thank you!
