### ISSUE TITLE
Dataflow worker not respecting `no_use_multiple_sdk_containers `

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tfx#4465]
While using TFX 1.0 and specifying beam pipeline args with `--experiments=no_use_multiple_sdk_containers`, the job is still starting with experiment args containing `use_multiple_sdk_containers`. In particular, these are the args displayed on dataflow platform:
```
['no_use_multiple_container_images', 'shuffle_mode=service', 'use_runner_v2',
'use_unified_worker', 'beam_fn_api', 'use_fastavro', 'use_multiple_sdk_containers']
```

**Comment by andrewsmartin** [comment]
Hey @sumitbinnani, from the [Dataflow docs](https://cloud.google.com/dataflow/docs/reference/pipeline-options#resource_utilization) it looks like this flag should be `no_use_multiple_container_images`, not `no_use_multiple_sdk_containers`. Does that work for you?

**Comment by andrewsmartin** [comment]
Actually, I just tried with both flags and am getting the same issue as you.

**Comment by venkat2469** [comment]
No Active issues found. will reopen if any issues found in future.
