### ISSUE TITLE
Pusher does not ensure `saved_model.pb` is written last

### ISSUE THREAD

**Issue by meowcakes** [tensorflow/tfx#4466]
**Describe the current behavior**

When pushing the model to the serving filesystem, `Pusher` just uses `io_utils.copy_dir` without ensuring the files are written in a specific order.
https://github.com/tensorflow/tfx/blob/1060a73c2855de3f86963d1c22fea6f33a4e917a/tfx/components/pusher/executor.py#L199

This breaks the assumption noted here: https://github.com/tensorflow/tensorflow/blob/d5b3c79b4804134d0d17bfce9f312151f6337dba/tensorflow/python/saved_model/save.py#L1445

When testing, I observed that `saved_model.pb` was written before `variables/variables.index`.
This can cause Tensorflow Serving to load the model without any variables, causing the following error when the prediction API is called:
```
OP_REQUIRES failed at resource_variable_ops.cc:650 : Not found: Resource X does not exist.
```
Also see: https://github.com/tensorflow/serving/issues/1086

**Describe the expected behavior**

`saved_model.pb` is written last.

**Comment by kev1n11** [comment]
@pindinagesh Is there a rough timeline on this? 🙏

**Comment by chongkong** [comment]
I'd say technically the model is not completely pushed until all files are copied, and from `Pusher` component aspect the assumption holds as it only publishes `PushedModel` artifact after all files copied. It seems you can rely on TFX information (i.e. its `PushedModel` artifact) to switch serving model safely?

I can change the Pusher to enforce the file copy order, but I need more evidence that it is really required.
