### ISSUE TITLE
How to implement tf.data.Dataset.window into_get_serve_tf_examples_fn

### ISSUE THREAD

**Issue by FernandoDorado** [tensorflow/tfx#4491]
Good work, 

I am working on a pipeline to put into production a model focused on time series. My question is, given that in the transform module I have only normalised my variables, and in the trainer module I have converted this data to sequences, how can I complete the _get_serve_tf_examples_fn function so that I don't get the following error: 
`ValueError: Input 0 of layer sequential_24 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 1)`

The transformation I have done is inside the _input_fn function inside the trainer module: 

```python
def _input_fn(file_pattern,
              tf_transform_output,
              num_epochs=None,
              batch_size=BATCH_SIZE) -> tf.data.Dataset:
    '''Create batches of features and labels from TF Records

    Args:
    file_pattern - List of files or patterns of file paths containing Example records.
    tf_transform_output - transform output graph
    num_epochs - Integer specifying the number of times to read through the dataset. 
            If None, cycles through the dataset forever.
    batch_size - An int representing the number of records to combine in a single batch.

    Returns:
    A dataset of dict elements, (or a tuple of dict elements and label). 
    Each dict maps feature keys to Tensor or SparseTensor objects.
    '''
    
    
    # Instantiate a tf.data.TFRecordDataset passing in the appropiate path
    # Get the URI of the transformed examples
    print(file_pattern[:-2])
    tfrecord_files = os.listdir(file_pattern[:-2])[0]
    
    # Full path string to the training tfrecord files
    path_to_tfrecord_files = os.path.join((file_pattern[:-2]), tfrecord_files)
    
    # print(path_to_tfrecord_files)

    dataset = tf.data.TFRecordDataset(path_to_tfrecord_files, compression_type="GZIP")

    # Use the dataset's map method to map the parse_function
    #  This function help in getting the transformed features and rearranging them so that the label values (T (degC)) is at the end of the tensor.
    def parse_function(example_proto):
        # Get the index of the label key
        feature_spec = tf_transform_output.transformed_feature_spec()
        index_of_label = list(tf_transform_output.transformed_feature_spec().keys()).index(LABEL_KEY)
        # Define features with the example_proto (transformed data) and the feature_spec using tf.io.parse_single_example 
        features = tf.io.parse_single_example(example_proto, feature_spec)
        values = list(features.values())
        values[index_of_label], values[len(features) - 1] = values[len(features) - 1], values[index_of_label]
        # Stack the values along the first axis
        stacked_features = tf.stack(values, axis=0)
        return stacked_features
    
    dataset = dataset.map(parse_function)
    # Use the window method with expected total size. Define stride and set drop_remainder to True
        # The shift argument controls how much each window moves over.
    dataset = dataset.window(HISTORY_SIZE + FUTURE_TARGET, shift=SHIFT, stride=OBSERVATIONS_PER_HOUR, drop_remainder=True)
    # The Dataset.flat_map method can take a dataset of datasets and flatten it into a single dataset
    dataset = dataset.flat_map(lambda window: window.batch(HISTORY_SIZE + FUTURE_TARGET))
    # Use the map method passing in the previously defined add_mode function
    dataset = dataset.map(map_features_target) 
    dataset = dataset.batch(BATCH_SIZE)
    #dataset = dataset.padded_batch(BATCH_SIZE, padded_shapes=([HISTORY_SIZE,3],[1]), drop_remainder=True)
    dataset = dataset.repeat()
    
    return dataset
```

Using this code, I can train without problems, my error comes when I save it using signatures. How can I modify the dimension of the input vector in signatures to match the dimensions I get from my model during training?

Thanks!

**Comment by UsharaniPagadala** [comment]
@FernandoDorado 
Could you please refer to the similar issues [#63760734](https://stackoverflow.com/questions/63760734/valueerror-input-0-of-layer-sequential-is-incompatible-with-the-layer-expect) and [#50804](https://github.com/tensorflow/tensorflow/issues/50804). Let us know if this helps.Thanks!

**Comment by FernandoDorado** [comment]
Hello @UsharaniPagadala, thanks for the help. 

The solutions you provide do not reflect the question of this issue. Those solutions are due to dimensionality to train the model, not to save it using signatures. My problem comes when modifying the dimensionality of the function inside signatures, since in all the examples out there (including the notebook in Colab that you sent me), it uses data_accessor.tf_dataset_factory to read the data, and I read it manually and change the dimensionality (using tf.dataset.window) inside the _input_fn function.

**Comment by FernandoDorado** [comment]
I solve on my own, but I think that the method tf.data.Dataset.window needs more examples and documentation. The tutorials use the class WindowGenerator, and there is no tutorial for the other class. The solution that I tried to consist in to access to the dict "transformed_features" and where the key is the output (name) of the serving module and the values are the input tensor (a sequence). I have to access to the value of this tensor and I have to expand_dims and reshape this tensor to avoid errors during the save the model using singatures.
