### ISSUE TITLE
Can't set num_steps to None in Trainer component

### ISSUE THREAD

**Issue by loiccordone** [tensorflow/tfx#45]
Hello,

In my Airflow pipeline, I can't set num_steps in TrainArgs to None. According to the doc of TrainSpec, max_steps can be set to None (useful for training exactly one epoch)

> max_steps: Int. Positive number of total steps for which to train model. If None, train forever.

`trainer = Trainer(module_file=_module_file,  transformed_examples=transform.outputs.transformed_examples, schema=infer_schema.outputs.output, transform_output=transform.outputs.transform_output, train_args=trainer_pb2.TrainArgs(num_steps=None), eval_args=trainer_pb2.EvalArgs(num_steps=None))`

At execution I get "'ERROR - Must specify max_steps > 0, given: 0". 
In my utils.py, the trainer_fn takes hparams in parameter, sent by TrainArgs and EvalArgs above, but inside trainer_fn hparams.train_steps is set to 0, not None. 

The problem seems to come from tfx/proto/trainer_pb2.py :

`_TRAINARGS = _descriptor.Descriptor(
  name='TrainArgs',
  ...
      has_default_value=False, default_value=0,
...`

However, changing the default_value to None didn't seem to help my case. I hard-codded None in my trainer_fn for the moment. Can you allow us to pass None ?

I'm using TFX 0.12 and TF 1.12.0
Thanks

**Comment by krazyhaas** [comment]
That's a bug.  I'll work on a fix (second in my queue).

**Comment by krazyhaas** [comment]
Hi Loic -- what are you using as the stop condition for your estimator?  I'm curious how a "runs forever" Trainer configuration behaves in airflow/kubeflow.  If you're raising an error after _n_ passes through the data, the error should abort the remainder of the pipeline execution as well.

**Comment by loiccordone** [comment]
Well I'm not raising an error, I'm simply defining the num_epoch in my inputs with the Estimator API (I can add precisions tomorrow), and the training stops exactly after num_epoch epochs.

**Comment by krazyhaas** [comment]
To confirm, your TrainSpec looks something like
```
  train_spec = tf.estimator.TrainSpec( 
      train_input_fn,
      # max_steps=hparams.train_steps,
      max_steps=None,
      num_epochs=1)
```
?

**Comment by loiccordone** [comment]
Yes that's it
