### ISSUE TITLE
KeyValue Error Coming from TFX pipeline ran on kubeflow

### ISSUE THREAD

**Issue by SamWoodruf** [tensorflow/tfx#4501]
I have a simple pipeline taken from a tutorial that I've created a kubeflow runner for. The components in use are csvexamplegen, trainer, and pusher. The data, training module, and pipeline root is stored in S3. When I run this on kubeflow I'm getting a key error after the training component is finished:
```
INFO:absl:MetadataStore with gRPC connection initialized
INFO:root:Adding KFP pod name penguin-simple-t4qcl-924568338 to execution
INFO:absl:MetadataStore with gRPC connection initialized
INFO:root:Component Trainer is finished.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 477, in <module>
    main(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 473, in main
    _dump_ui_metadata(pipeline_node, execution_info, args.metadata_ui_path)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 345, in _dump_ui_metadata
    output_model = execution_info.output_dict[name][0]
KeyError: 'model_run'
```
The code I'm using can be found [here](https://github.com/SamWoodruf/penguin-simple).
It seems that model_run is missing from the output of the training step and thus fails. Any insight would be appreciated and thanks for your time.

**Comment by DgXRo** [comment]
I have exactly the same problem. Is there any news?

**Comment by jiyongjung0** [comment]
Thank you for the report. Could you share the TFX versions used for both of "job submission" and the "container image"? I can see "tensorflow/tfx:latest" from the docker file but the pipeline is referencing another container image path.

**Comment by gaikwadrahul8** [comment]
Hi, @DgXRo , @SamWoodruf 

Can you take a look at this [article](https://neptune.ai/blog/deep-dive-into-ml-models-in-production-using-tfx-and-kubeflow) and please follow all instructions mentioned in that article. As per your project do necessary changes and see if it helps in resolving your issue?

I would also suggest you to check compatibility matrix for Kubeflow and TFX [here](https://www.kubeflow.org/docs/components/pipelines/v1/installation/compatibility-matrix/) if possible please try to go with compatibility matrix versions and see if it works for you

If issue still persists please let us know

Thanks!

**Comment by gaikwadrahul8** [comment]
@SamWoodruf 

Closing this issue due to lack of recent activity. Please feel free to reopen the issue with more details if the problem still persists after trying above workaround. Thank you!
