### ISSUE TITLE
Evaluator Error: Fail to call signature func with signature_name: serving_default

### ISSUE THREAD

**Issue by jarmstrongcorus** [tensorflow/tfx#4505]
**System information**
Tensorflow - 2.7.0
TFX - 1.4.0
Python - 3.7

I'm running into and issue with the Evaluator, when I run it as part of a pipeline. I have updated and switched BigQuery queries, and strangely the pipeline continues to work with the old query on BigQueryExampleGen. But I've gone through and compared the queries and their outputs from each of the features and labels are formatted exactly the same.

When I run my pipeline with the new query the Evaluator crashes with with error (I am using Dataflow in GCP but all the workers exit with an error):

**Describe the current behavior**
> Error message from worker: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1717, in _call_impl cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1794, in _call_with_structured_signature self._structured_signature_check_missing_args(args, kwargs) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1815, in _structured_signature_check_missing_args ", ".join(sorted(missing_arguments)))) TypeError: signature_wrapper(*, examples) missing required arguments: examples During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 969, in _batch_reducible_process outputs = signature(tf.constant(inputs, dtype=tf.string)) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1707, in __call__ return self._call_impl(args, kwargs) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1721, in _call_impl cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1774, in _call_with_flat_signature return self._call_flat(args, self.captured_inputs, cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 122, in _call_flat cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat ctx, args, cancellation_manager=cancellation_manager)) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call ctx=ctx) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute inputs, attrs, num_outputs) tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,1] = 10795 is not in [0, 8000) [[{{node StatefulPartitionedCall/model/embedding/embedding_lookup}}]] [Op:__inference_signature_wrapper_4644] Function call stack: signature_wrapper The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 769, in process result = self._batch_reducible_process(element) File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 975, in _batch_reducible_process input_specs)) from e ValueError: Fail to call signature func with signature_name: serving_default. the inputs are: [b'\n\xcc\x05\n\xc4\x01\n\x06counts\x12\xb9\x01\n\xb6\x01\n\xb3\x011;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2;2;2;2;2;2;2\n\xdb\x03\n\x07indices\x12\xcf\x03\n\xcc\x03\n\xc9\x035111;10795;2562;5915;7018;6435;398;4787;3681;769;3729;11299;3894;3048;4582;4076;4610;9399;9289;1662;1520;4918;6436;8452;8200;10870;10209;9452;4091;724;11003;9451;697;6562;10846;9635;7019;11083;5091;3357;6259;4397;9937;8614;10205;10599;1307;4978;774;3329;7209;4451;8539;10811;3585;2357;3848;5506;8428;857;4136;6990;10615;460;397;3280;4658;10036;7308;7602;7858;9832;1793;5916;11078;7479;11049;5081;2633;5809;3793;3723;2626;7340;5871;11235;7472;10509;1604;7746\n%\n\x0bgrouping_id\x12\x16\n\x14\n\x12Family_Fun_Moments']. The input_specs are: {'examples': TensorSpec(shape=(None,), dtype=tf.string, name='examples')}. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1717, in _call_impl cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1794, in _call_with_structured_signature self._structured_signature_check_missing_args(args, kwargs) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1815, in _structured_signature_check_missing_args ", ".join(sorted(missing_arguments)))) TypeError: signature_wrapper(*, examples) missing required arguments: examples During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 969, in _batch_reducible_process outputs = signature(tf.constant(inputs, dtype=tf.string)) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1707, in __call__ return self._call_impl(args, kwargs) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1721, in _call_impl cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1774, in _call_with_flat_signature return self._call_flat(args, self.captured_inputs, cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 122, in _call_flat cancellation_manager) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat ctx, args, cancellation_manager=cancellation_manager)) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 596, in call ctx=ctx) File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute inputs, attrs, num_outputs) tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,1] = 10795 is not in [0, 8000) [[{{node StatefulPartitionedCall/model/embedding/embedding_lookup}}]] [Op:__inference_signature_wrapper_4644] Function call stack: signature_wrapper The above exception was the direct cause of the following exception: Traceback (most recent call last): File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 790, in process result.extend(self._batch_reducible_process(unbatched_element)) File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 975, in _batch_reducible_process input_specs)) from e ValueError: Fail to call signature func with signature_name: serving_default. the inputs are: [b'\n\xcc\x05\n\xc4\x01\n\x06counts\x12\xb9\x01\n\xb6\x01\n\xb3\x011;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2;2;2;2;2;2;2\n\xdb\x03\n\x07indices\x12\xcf\x03\n\xcc\x03\n\xc9\x035111;10795;2562;5915;7018;6435;398;4787;3681;769;3729;11299;3894;3048;4582;4076;4610;9399;9289;1662;1520;4918;6436;8452;8200;10870;10209;9452;4091;724;11003;9451;697;6562;10846;9635;7019;11083;5091;3357;6259;4397;9937;8614;10205;10599;1307;4978;774;3329;7209;4451;8539;10811;3585;2357;3848;5506;8428;857;4136;6990;10615;460;397;3280;4658;10036;7308;7602;7858;9832;1793;5916;11078;7479;11049;5081;2633;5809;3793;3723;2626;7340;5871;11235;7472;10509;1604;7746\n%\n\x0bgrouping_id\x12\x16\n\x14\n\x12Family_Fun_Moments']. The input_specs are: {'examples': TensorSpec(shape=(None,), dtype=tf.string, name='examples')}. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 284, in _execute response = task() File "/usr/local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 357, in <lambda> lambda: self.create_worker().do_instruction(request), request) File "/usr/local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 603, in do_instruction getattr(request, request_type), request.instruction_id) File "/usr/local/lib/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 640, in process_bundle bundle_processor.process_bundle(instruction_id)) File "/usr/local/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 997, in process_bundle element.data) File "/usr/local/lib/python3.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 222, in process_encoded self.output(decoded_value) File "apache_beam/runners/worker/operations.py", line 351, in apache_beam.runners.worker.operations.Operation.output File "apache_beam/runners/worker/operations.py", line 353, in apache_beam.runners.worker.operations.Operation.output File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 823, in apache_beam.runners.worker.operations.SdfProcessSizedElements.process File "apache_beam/runners/worker/operations.py", line 832, in apache_beam.runners.worker.operations.SdfProcessSizedElements.process File "apache_beam/runners/common.py", line 1240, in apache_beam.runners.common.DoFnRunner.process_with_sized_restriction File "apache_beam/runners/common.py", line 732, in apache_beam.runners.common.PerWindowInvoker.invoke_process File "apache_beam/runners/common.py", line 870, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1299, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 571, in apache_beam.runners.common.SimpleInvoker.invoke_process File "apache_beam/runners/common.py", line 1395, in apache_beam.runners.common._OutputProcessor.process_outputs File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 712, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 713, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1234, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1315, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1232, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 572, in apache_beam.runners.common.SimpleInvoker.invoke_process File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 790, in process result.extend(self._batch_reducible_process(unbatched_element)) File "/usr/local/lib/python3.7/site-packages/tensorflow_model_analysis/utils/model_util.py", line 975, in _batch_reducible_process input_specs)) from e ValueError: Fail to call signature func with signature_name: serving_default. the inputs are: [b'\n\xcc\x05\n\xc4\x01\n\x06counts\x12\xb9\x01\n\xb6\x01\n\xb3\x011;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2;2;2;2;2;2;2\n\xdb\x03\n\x07indices\x12\xcf\x03\n\xcc\x03\n\xc9\x035111;10795;2562;5915;7018;6435;398;4787;3681;769;3729;11299;3894;3048;4582;4076;4610;9399;9289;1662;1520;4918;6436;8452;8200;10870;10209;9452;4091;724;11003;9451;697;6562;10846;9635;7019;11083;5091;3357;6259;4397;9937;8614;10205;10599;1307;4978;774;3329;7209;4451;8539;10811;3585;2357;3848;5506;8428;857;4136;6990;10615;460;397;3280;4658;10036;7308;7602;7858;9832;1793;5916;11078;7479;11049;5081;2633;5809;3793;3723;2626;7340;5871;11235;7472;10509;1604;7746\n%\n\x0bgrouping_id\x12\x16\n\x14\n\x12Family_Fun_Moments']. The input_specs are: {'examples': TensorSpec(shape=(None,), dtype=tf.string, name='examples')}. [while running 'ExtractEvaluateAndWriteResults/ExtractAndEvaluate/ExtractPredictions/Predict-ptransform-598']

**Describe the expected behavior**
I expect the component to run without error.

**Comment by pindinagesh** [comment]
@jarmstrongcorus 

Could you please have a look at the similar [issue](https://github.com/MaybeShewill-CV/CRNN_Tensorflow/issues/275) and [link](https://www.tensorflow.org/guide/saved_model#identifying_a_signature_to_export) let us know if it helps? Thank you!

**Comment by pindinagesh** [comment]
@jarmstrongcorus 

Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!

**Comment by Asphalt2017** [comment]
Has the issue resolved?
