### ISSUE TITLE
Multiple Evaluators in a single pipeline

### ISSUE THREAD

**Issue by jarmstrongcorus** [tensorflow/tfx#4510]
I noticed that in the Evaluator code there isn't an attribute for instance_name which allows one to have multiple instance of a components of the same type. Could this feature be added to TFX? I would like to run evaluation on a model for various datasets. If there is some other way of operating on multiple sets in a single component, please explain how that might work. Thanks.

**Comment by 1025KB** [comment]
instance_name is deprecated, please use [with_id](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_local.py#L198) when there are multiple instances
