### ISSUE TITLE
assertDictContainsSubset was removed in Python 3.11

### ISSUE THREAD

**Issue by tirkarthi** [tensorflow/tfx#4542]
**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version:
- TFX Version: master
- Python version: 3.11
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**

The deprecated unittest aliases were removed in python/cpython#28268 in Python 3.11 . Something like change from below could be used

https://github.com/pytest-dev/unittest2pytest/commit/44ea6916f0a2290641cee16e007129b8fd1f009b#diff-81d91975b2e0c0c35f9575e76be3763f82c94c3365f016ed71aa39e567762630R276

```
tfx/tfx/components/infra_validator/model_server_runners/local_docker_runner_test.py:    self.assertDictContainsSubset(dict(
tfx/tfx/extensions/google_cloud_ai_platform/runner_test.py:    self.assertDictContainsSubset(
tfx/tfx/extensions/google_cloud_ai_platform/runner_test.py:    self.assertDictContainsSubset(
tfx/tfx/extensions/google_cloud_ai_platform/runner_test.py:    self.assertDictContainsSubset(
tfx/tfx/extensions/google_cloud_ai_platform/runner_test.py:    self.assertDictContainsSubset(
tfx/tfx/extensions/google_cloud_ai_platform/runner_test.py:    self.assertDictContainsSubset(
tfx/tfx/extensions/google_cloud_ai_platform/runner_test.py:    self.assertDictContainsSubset(user_provided_labels, body['labels'])
```

**Describe the expected behavior**

**Comment by pindinagesh** [comment]
@tirkarthi 

Can you elaborate more about this issue clearly?

**Comment by tirkarthi** [comment]
The method `assertDictContainsSubset` from unittest.TestCase was deprecated and removed in Python 3.11 . So running these tests in Python 3.11 will give AttributeError.

**Comment by zhitaoli** [comment]
Recent commit 010e94d731fe3a90a048cb0c4fdc31a8f7ec5648 should have fixed this
