### ISSUE TITLE
local dag runner TFX pipeline run create ERROR Failed to make stateful working dir ; Protocol error

### ISSUE THREAD

**Issue by miroC911** [tensorflow/tfx#4559]
OS : Linux Ubuntu 21.04.
TensorFlow version: 2.6.2
TFX version: 1.4.0 
Python 3.8.0

Hello,
I am following Building a TFX Pipeline Locally (https://www.tensorflow.org/tfx/guide/build_local_pipeline). I am only running CsvExampleGen component and I am getting the following error:

ERROR:absl:Failed to make stateful working dir: ./my_pipeline_output/CsvExampleGen/.system/stateful_working_dir/2022-01-05T11:04:16.463569 Traceback (most recent call last):........ File "/home/mc/anaconda3/envs/tfx_linux/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 514, in recursive_create_dir_v2 _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path)) tensorflow.python.framework.errors_impl.UnknownError: ./my_pipeline_output/CsvExampleGen/.system/stateful_working_dir/2022-01-05T11:04:16.463569; Protocol error

I  looked into tensorflow/python/lib/io/file_io.py -> function recursive_create_dir_v2() but that is it!  :-).
I would appreciate any suggestion. I am certainly missing something ...
Thanks

**Comment by sanatmpa1** [comment]
@miroC911,

Can you share the complete error trace and the line which triggered this error in the example program? Thanks!

**Comment by miroC911** [comment]
Hello,
please see below. If you need more info please let me know. with thanks

Error trace:
NFO:absl:MetadataStore with DB connection initialized
INFO:absl:select span and version = (0, None)
INFO:absl:latest span and version = (0, None)
INFO:absl:MetadataStore with DB connection initialized
INFO:absl:Going to run a new execution 2
ERROR:absl:Failed to make stateful working dir: ./my_pipeline_output/CsvExampleGen/.system/stateful_working_dir/2022-01-11T13:41:58.037527
Traceback (most recent call last):
  File "/home/mc/anaconda3/envs/tfx_linux/lib/python3.8/site-packages/tfx/orchestration/portable/outputs_utils.py", line 220, in get_stateful_working_directory
    fileio.makedirs(stateful_working_dir)
  File "/home/mc/anaconda3/envs/tfx_linux/lib/python3.8/site-packages/tfx/dsl/io/fileio.py", line 78, in makedirs
    _get_filesystem(path).makedirs(path)
  File "/home/mc/anaconda3/envs/tfx_linux/lib/python3.8/site-packages/tfx/dsl/io/plugins/tensorflow_gfile.py", line 71, in makedirs
    tf.io.gfile.makedirs(path)
  File "/home/mc/anaconda3/envs/tfx_linux/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 514, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.UnknownError: ./my_pipeline_output/CsvExampleGen/.system/stateful_working_dir/2022-01-11T13:41:58.037527; Protocol error

triggers:
  File "/home/mc/git/TFX_Tutorials/TFX_tutorial/example_TFX_pipeline/my_pipeline.py", line 53, in run_pipeline
    tfx.orchestration.LocalDagRunner().run(my_pipeline)
  File "/home/mc/git/TFX_Tutorials/TFX_tutorial/example_TFX_pipeline/my_pipeline.py", line 57, in <module>
    run_pipeline()

**Comment by sanatmpa1** [comment]
@miroC911,

Can you share a simple standalone code or colab gist to reproduce the issue? Thanks!

**Comment by aurelienmorgan** [comment]
@see [issues/4474](https://github.com/tensorflow/tfx/issues/4474)
In tfx\orchestration\portable\outputs_utils.py, `self._pipeline_run_id**.replace(':', '_')**` fixes the issue in the `get_stateful_working_directory `function

**Comment by aurelienmorgan** [comment]
> 

@see [tfx/issues/4474](https://github.com/tensorflow/tfx/issues/4474)
In tfx\orchestration\portable\outputs_utils.py, self._pipeline_run_id.replace(':', '_') fixes the issue in the get_stateful_working_directory function

**Comment by gowthamkpr** [comment]
@miroC911 As mentioned [above](https://github.com/tensorflow/tfx/issues/4559#issuecomment-1160433081), this issue is specific to windows path and a workaround is mentioned [here](https://github.com/tensorflow/tfx/issues/4474#issuecomment-1160428019). Lets close this issue and track it [here](https://github.com/tensorflow/tfx/issues/4474). Thanks!!

**Comment by zhitaoli** [comment]
Agree to close the issue. Please send any follow up request to @ruoyu90

**Comment by riyaj8888** [comment]
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
c:\Users\ratar\OneDrive - Cornerstone OnDemand\local_repos\MLOps-Lifecycle-course-notebook\tfx_notebooks\tfx-1.ipynb Cell 12 in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/Users/ratar/OneDrive%20-%20Cornerstone%20OnDemand/local_repos/MLOps-Lifecycle-course-notebook/tfx_notebooks/tfx-1.ipynb#X13sZmlsZQ%3D%3D?line=0) tfx.orchestration.LocalDagRunner().run(
      [2](vscode-notebook-cell:/c%3A/Users/ratar/OneDrive%20-%20Cornerstone%20OnDemand/local_repos/MLOps-Lifecycle-course-notebook/tfx_notebooks/tfx-1.ipynb#X13sZmlsZQ%3D%3D?line=1)     pipeline
      [3](vscode-notebook-cell:/c%3A/Users/ratar/OneDrive%20-%20Cornerstone%20OnDemand/local_repos/MLOps-Lifecycle-course-notebook/tfx_notebooks/tfx-1.ipynb#X13sZmlsZQ%3D%3D?line=2) )

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\local\local_dag_runner.py:90, in LocalDagRunner.run(self, pipeline)
     82 component_launcher = launcher.Launcher(
     83     pipeline_node=pipeline_node,
     84     mlmd_connection=metadata.Metadata(connection_config),
   (...)
     87     executor_spec=executor_spec,
     88     custom_driver_spec=custom_driver_spec)
     89 logging.info('Component %s is running.', node_id)
---> 90 component_launcher.launch()
     91 logging.info('Component %s is finished.', node_id)
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\portable\launcher.py:545, in Launcher.launch(self)
    542     self._executor_operator.with_execution_watcher(
    543         executor_watcher.address)
    544     executor_watcher.start()
--> 545   executor_output = self._run_executor(execution_info)
    546 except Exception as e:  # pylint: disable=broad-except
    547   execution_output = (
    548       e.executor_output if isinstance(e, _ExecutionFailedError) else None)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\portable\launcher.py:420, in Launcher._run_executor(self, execution_info)
    418 outputs_utils.make_output_dirs(execution_info.output_dict)
    419 try:
--> 420   executor_output = self._executor_operator.run_executor(execution_info)
    421   code = executor_output.execution_result.code
    422   if code != 0:

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\portable\python_executor_operator.py:133, in PythonExecutorOperator.run_executor(self, execution_info)
    123 context = base_executor.BaseExecutor.Context(
    124     extra_flags=self.extra_flags,
    125     tmp_dir=execution_info.tmp_dir,
    130     pipeline_info=execution_info.pipeline_info,
    131     pipeline_run_id=execution_info.pipeline_run_id)
    132 executor = self._executor_cls(context=context)
--> 133 return run_with_executor(execution_info, executor)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\orchestration\portable\python_executor_operator.py:58, in run_with_executor(execution_info, executor)
     55       artifact.read()
     57 output_dict = copy.deepcopy(execution_info.output_dict)
---> 58 result = executor.Do(execution_info.input_dict, output_dict,
     59                      execution_info.exec_properties)
     60 if not result:
     61   # If result is not returned from the Do function, then try to
     62   # read from the executor_output_uri.
     63   if fileio.exists(execution_info.execution_output_uri):

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\trainer\executor.py:174, in GenericExecutor.Do(self, input_dict, output_dict, exec_properties)
    171 self._log_startup(input_dict, output_dict, exec_properties)
    173 fn_args = self._GetFnArgs(input_dict, output_dict, exec_properties)
--> 174 run_fn = udf_utils.get_fn(exec_properties, 'run_fn')
    176 # Train the model
    177 absl.logging.info('Training model.')
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py:56, in get_fn(exec_properties, fn_name)
     54 if has_module_path:
     55   module_path = exec_properties[_MODULE_PATH_KEY]
---> 56   return import_utils.import_func_from_module(module_path, fn_name)
     57 elif has_module_file:
     58   if has_fn:

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\utils\import_utils.py:55, in import_func_from_module(module_path, fn_name)
     53   wheel_context_manager = udf_utils.TempPipInstallContext([wheel_path])
     54   with _imported_modules_from_source_lock:
---> 55     wheel_context_manager.__enter__()
     56 if module_path in sys.modules:
     57   importlib.reload(sys.modules[module_path])

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py:307, in TempPipInstallContext.__enter__(self)
    305 self.temp_directory = tempfile.mkdtemp()
    306 for dependency in self.pip_dependencies:
--> 307   install_to_temp_directory(dependency, temp_dir=self.temp_directory)
    308 sys.path = sys.path + [self.temp_directory]
    309 os.environ['PYTHONPATH'] = ':'.join(sys.path)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py:339, in install_to_temp_directory(pip_dependency, temp_dir)
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tfx\components\util\udf_utils.py:339, in install_to_temp_directory(pip_dependency, temp_dir)
    334 install_command = [
    335     sys.executable, '-m', 'pip', 'install', '--target', temp_dir,
    336     pip_dependency
    337 ]
    338 logging.info('Executing: %s', install_command)
--> 339 subprocess.check_call(install_command)
    340 logging.info('Successfully installed %r.', pip_dependency)
    341 return temp_dir

File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py:364, in check_call(*popenargs, **kwargs)
    362     if cmd is None:
    363         cmd = popenargs[0]
--> 364     raise CalledProcessError(retcode, cmd)
    365 return 0
