### ISSUE TITLE
ImportExampleGen on Kubeflow not working

### ISSUE THREAD

**Issue by valeriano-manassero** [tensorflow/tfx#457]
After building tfx image on latest master, I just discovered using ImportExampleGen on Kubeflow results in:
```
usage: container_entrypoint.py [-h] --exec_properties EXEC_PROPERTIES
                               --outputs OUTPUTS --executor_class_path
                               EXECUTOR_CLASS_PATH
                               {CsvExampleGen,BigQueryExampleGen,StatisticsGen,SchemaGen,ExampleValidator,Transform,Trainer,Evaluator,ModelValidator,Pusher}
                               ...
container_entrypoint.py: error: argument executor: invalid choice: 'ImportExampleGen' (choose from 'CsvExampleGen', 'BigQueryExampleGen', 'StatisticsGen', 'SchemaGen', 'ExampleValidator', 'Transform', 'Trainer', 'Evaluator', 'ModelValidator', 'Pusher')
```

**Comment by valeriano-manassero** [comment]
I proposed a quick fix for that https://github.com/tensorflow/tfx/pull/459 while waiting for b/132197968 implementation.

Do you think it's useful?

**Comment by krazyhaas** [comment]
+neuromage, WDYT?  How close is your CL to completing?

**Comment by neuromage** [comment]
It's pretty close, but I think it's fine to merge this for now. I've gone ahead and done so.

**Comment by valeriano-manassero** [comment]
@krazyhaas do I need to do something more for merging or it's enough? (Sorry, these are my first steps here in tensorflow repos).

**Comment by neuromage** [comment]
@valeriano-manassero sorry for the delay. We're having some issues with the automation for this. I'll get it merged by today for sure.

**Comment by valeriano-manassero** [comment]
ok, ty guys!
