### ISSUE TITLE
transform wheel gets added to a tmp folder rather than GCP kubeflowpipeline-default (tfx_user_code_Transform-0.0[...]-py3-none-any.whl)

### ISSUE THREAD

**Issue by armand-sauzay** [tensorflow/tfx#4583]
**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Tensorflow 2.6 instance on GCP
- TensorFlow version: 2.7
- TFX Version: 1.5.0
- Python version: 3.7.12 
- Python dependencies (from `pip freeze` output):
absl-py==0.11.0
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1637087016127/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1636093929600/work
ansiwrap==0.8.4
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1637703203932/work/dist
apache-beam==2.34.0
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
argcomplete @ file:///home/conda/feedstock_root/build_artifacts/argcomplete_1619128689661/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1636021379047/work
arrow @ file:///home/conda/feedstock_root/build_artifacts/arrow_1635261338479/work
asn1crypto @ file:///home/conda/feedstock_root/build_artifacts/asn1crypto_1595949944546/work
astunparse==1.6.3
async-generator==1.10
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1637092647930/work
asynctest==0.13.0
attrs==20.3.0
avro-python3==1.9.2.1
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1619719576210/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.entry-points-selectable==1.1.1
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beatrix-jupyterlab @ file:///tmp/beatrix_jupyterlab-latest.tar.gz
binaryornot==0.4.4
black @ file:///home/conda/feedstock_root/build_artifacts/black-recipe_1639405010350/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
blinker==1.4
Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1636024210459/work
brotlipy==0.7.0
cached-property==1.5.2
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1633010882559/work
certifi==2021.10.8
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1636046052501/work
chardet @ file:///tmp/build/80754af9/chardet_1607706768982/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1638815705608/work
clang==5.0
click==7.1.2
cloud-tpu-client==0.10
cloud-tpu-profiler==2.4.0
cloudpickle==1.6.0
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
conda==4.11.0
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1618262151086/work
confuse @ file:///home/conda/feedstock_root/build_artifacts/confuse_1638044079768/work
cookiecutter @ file:///home/conda/feedstock_root/build_artifacts/cookiecutter_1621252513699/work
crcmod==1.7
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1639699266208/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1636043256745/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
Deprecated==1.2.13
dill==0.3.1.1
distlib==0.3.4
dm-tree==0.1.6
docker==4.4.4
docker-pycreds==0.4.0
docopt==0.6.2
docstring-parser==0.13
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
explainable-ai-sdk @ file:///opt/conda/conda-bld/dlenv-tf-2-6-cpu_1639877225671/work/explainable_ai_sdk-1-py3-none-any.whl
explainers @ file:///opt/conda/conda-bld/dlenv-tf-2-6-cpu_1639877225671/work/explainers-1-cp37-cp37m-linux_x86_64.whl
fastavro==1.4.7
fasteners==0.16.3
filelock==3.4.0
fire==0.4.0
flatbuffers==1.12
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1639683782923/work
frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1636286792720/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1637975854575/work
future @ file:///home/conda/feedstock_root/build_artifacts/future_1635819510385/work
gast==0.4.0
gcsfs @ file:///home/conda/feedstock_root/build_artifacts/gcsfs_1638029766547/work
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1635085722655/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1632423794953/work
google-api-core==1.31.5
google-api-python-client==1.12.8
google-apitools==0.5.31
google-auth==1.35.0
google-auth-httplib2 @ file:///home/conda/feedstock_root/build_artifacts/google-auth-httplib2_1617387471894/work
google-auth-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/google-auth-oauthlib_1630497468950/work
google-cloud-aiplatform==1.8.1
google-cloud-appengine-logging==1.1.0
google-cloud-audit-log==0.2.0
google-cloud-bigquery==2.31.0
google-cloud-bigquery-storage==2.10.1
google-cloud-bigtable==1.7.0
google-cloud-core==1.7.2
google-cloud-dataproc==3.1.1
google-cloud-datastore==1.15.3
google-cloud-dlp==1.0.0
google-cloud-firestore==2.3.4
google-cloud-kms==2.10.1
google-cloud-language==1.3.0
google-cloud-logging==2.7.0
google-cloud-monitoring==2.8.0
google-cloud-pubsub==1.7.0
google-cloud-recommendations-ai==0.2.0
google-cloud-scheduler==2.5.0
google-cloud-spanner==1.19.1
google-cloud-speech==2.11.1
google-cloud-storage @ file:///home/conda/feedstock_root/build_artifacts/google-cloud-storage_1638482791995/work
google-cloud-tasks==2.7.1
google-cloud-translate==3.6.1
google-cloud-videointelligence==1.16.1
google-cloud-vision==1.0.0
google-crc32c @ file:///home/conda/feedstock_root/build_artifacts/google-crc32c_1636020892126/work
google-pasta==0.2.0
google-resumable-media @ file:///home/conda/feedstock_root/build_artifacts/google-resumable-media_1635195007097/work
googleapis-common-protos @ file:///home/conda/feedstock_root/build_artifacts/googleapis-common-protos-feedstock_1636053079787/work
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1635836788663/work
grpc-google-iam-v1==0.12.3
grpcio==1.43.0
grpcio-gcp @ file:///home/conda/feedstock_root/build_artifacts/grpcio-gcp_1635875856259/work
grpcio-status==1.43.0
gviz-api==1.10.0
h5py==3.1.0
hdfs==2.6.0
horovod==0.23.0
htmlmin==0.1.12
httplib2==0.19.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1609836280497/work
ImageHash @ file:///home/conda/feedstock_root/build_artifacts/imagehash_1626361020540/work
imageio==2.13.3
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1639804645172/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1635615662634/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1638555490606/work/dist/ipykernel-6.6.0-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1638470218926/work
ipython-genutils==0.2.0
ipython-sql @ file:///home/conda/feedstock_root/build_artifacts/ipython-sql_1636816912182/work
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1631590360471/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1637175076767/work
jeepney==0.7.1
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1612119311452/work
jinja2-time==0.2.0
joblib==0.14.1
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1637611911738/work
jupyter-console==6.4.0
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1636814264288/work
jupyter-http-over-ws==0.0.8
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1639084645710/work
jupyter-server-mathjax @ file:///home/conda/feedstock_root/build_artifacts/jupyter-server-mathjax_1622646097887/work
jupyter-server-proxy @ file:///home/conda/feedstock_root/build_artifacts/jupyter-server-proxy_1638279709332/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1639150690547/work
jupyterlab-git @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab-git_1636807056042/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1639404907821/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1631590465624/work
jupytext @ file:///home/conda/feedstock_root/build_artifacts/jupytext_1639338369247/work
keras==2.7.0
Keras-Preprocessing==1.1.2
keras-tuner==1.1.0
keyring==23.4.0
keyrings.google-artifactregistry-auth==1.0.0
kfp==1.8.1
kfp-pipeline-spec==0.1.13
kfp-server-api==1.7.1
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1635836699543/work
kt-legacy==1.0.4
kubernetes==12.0.1
libclang==12.0.0
libcst==0.3.23
llvmlite==0.37.0
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1637220118004/work
markdown-it-py @ file:///home/conda/feedstock_root/build_artifacts/markdown-it-py_1620659057741/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1610127564475/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1639358971400/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mdit-py-plugins @ file:///home/conda/feedstock_root/build_artifacts/mdit-py-plugins_1639763187273/work
missingno==0.4.2
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1635844677043/work
ml-metadata==1.5.0
ml-pipelines-sdk==1.5.0
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1636019089722/work
multimethod @ file:///home/conda/feedstock_root/build_artifacts/multimethod_1603129052241/work
munkres==1.1.4
mypy-extensions @ file:///home/conda/feedstock_root/build_artifacts/mypy_extensions_1635839681723/work
nb-conda @ file:///home/conda/feedstock_root/build_artifacts/nb_conda_1611345550379/work
nb-conda-kernels @ file:///home/conda/feedstock_root/build_artifacts/nb_conda_kernels_1636999991206/work
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1635436909771/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1637327213451/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1636897213317/work
nbdime @ file:///home/conda/feedstock_root/build_artifacts/nbdime_1635269257164/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1638419302549/work
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1635253012265/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1637122013008/work
notebook-executor @ file:///opt/conda/conda-bld/dlenv-base_1639875985139/work/packages/notebook_executor
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1633674394352/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1626681927231/work
oauth2client==4.1.3
oauthlib @ file:///home/conda/feedstock_root/build_artifacts/oauthlib_1622563202229/work
olefile @ file:///home/conda/feedstock_root/build_artifacts/olefile_1602866521163/work
opt-einsum==3.3.0
orjson==3.6.5
packaging==20.9
pandas==1.3.5
pandas-profiling @ file:///home/conda/feedstock_root/build_artifacts/pandas-profiling_1620781969337/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
papermill @ file:///home/conda/feedstock_root/build_artifacts/papermill_1634840867048/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pathspec @ file:///home/conda/feedstock_root/build_artifacts/pathspec_1626613672358/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1632667180946/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
phik @ file:///home/conda/feedstock_root/build_artifacts/phik_1636795276417/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1636558793805/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1630400214373/work
pluggy==1.0.0
portpicker==1.5.0
poyo==0.5.0
prettytable @ file:///home/conda/feedstock_root/build_artifacts/prettytable_1635956428808/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1635538335951/work
promise==2.3
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1639065841292/work
proto-plus==1.19.8
protobuf==3.19.1
psutil==5.8.0
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycosat==0.6.3
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic @ file:///home/conda/feedstock_root/build_artifacts/pydantic_1636021129189/work
pydot==1.4.2
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1638819640841/work
pymongo==3.12.3
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1633192417276/work
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1636052607582/work
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-slugify @ file:///home/conda/feedstock_root/build_artifacts/python-slugify_1620267765676/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1633452062248/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
PyWavelets @ file:///home/conda/feedstock_root/build_artifacts/pywavelets_1638209732773/work
PyYAML==5.4.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1635877395563/work
qtconsole==5.2.2
QtPy==1.11.3
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1637771257551/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1595492159598/work
requests-toolbelt==0.9.1
retrying==1.3.3
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1637781155505/work
ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016701961/work
scikit-image==0.19.1
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1639497488246/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1637806658031/work
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1629095986539/work
SecretStorage==3.3.1
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
simpervisor @ file:///home/conda/feedstock_root/build_artifacts/simpervisor_1609865618711/work
six @ file:///tmp/build/80754af9/six_1623709665295/work
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1611376390914/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1635844655971/work
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1639086017078/work
sqlparse @ file:///home/conda/feedstock_root/build_artifacts/sqlparse_1631317292236/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1636765227291/work
strip-hints==0.1.10
tabulate==0.8.9
tangled-up-in-unicode @ file:///home/conda/feedstock_root/build_artifacts/tangled-up-in-unicode_1632832610704/work
tenacity @ file:///home/conda/feedstock_root/build_artifacts/tenacity_1626090218611/work
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-profile==2.4.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.7.0
tensorflow-cloud==0.1.14
tensorflow-data-validation==1.5.0
tensorflow-datasets==4.3.0
tensorflow-decision-forests==0.2.2
tensorflow-estimator==2.7.0
tensorflow-hub==0.12.0
tensorflow-io==0.21.0
tensorflow-io-gcs-filesystem==0.23.1
tensorflow-metadata==1.5.0
tensorflow-model-analysis==0.36.0
tensorflow-probability==0.14.1
tensorflow-serving-api==2.7.0
tensorflow-transform==1.5.0
termcolor==1.1.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1636052203143/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
text-unidecode==1.3
textwrap3==0.9.2
tfx==1.5.0
tfx-bsl==1.5.0
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1633102299089/work
tifffile==2021.11.2
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1635181214134/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1635819587639/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1632160078689/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1635260543454/work
typed-ast @ file:///home/conda/feedstock_root/build_artifacts/typed-ast_1638670782934/work
typing-extensions==3.10.0.2
typing-inspect==0.7.1
ujson @ file:///home/conda/feedstock_root/build_artifacts/ujson_1639784827898/work
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1637177680285/work
Unidecode @ file:///home/conda/feedstock_root/build_artifacts/unidecode_1631795222793/work
uritemplate==3.0.1
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1632350318291/work
virtualenv==20.10.0
visions @ file:///home/conda/feedstock_root/build_artifacts/visions_1612743227238/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1638949723239/work
Werkzeug==2.0.2
whichcraft==0.6.1
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1637174133839/work
witwidget==1.8.0
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1635836382399/work
wurlitzer==3.0.2
xai-tabular-widget @ file:///opt/conda/conda-bld/dlenv-tf-2-6-cpu_1639877225671/work/xai_tabular_widget-1-py3-none-any.whl
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1636046815749/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1633302054558/work

**Describe the current behavior**
I have no trouble running the components on with an interactive context. However, when I build the image, the wheel for the transform component seems to be added to a different location than the one it is read from on the run. -->
When building the image, 'tfx_user_code_Transform-0.0[...]-py3-none-any.whl' gets added to a tmp folder. When trying to run the pipeline on GCP, the file 'tfx_user_code_Transform-0.0[...]-py3-none-any.whl'  cannot be found on 'gs://[...]' which leads to a failing Transform compoenent. 

**Describe the expected behavior**
tfx_user_code_Transform-0.0[...]-py3-none-any.whl to be found by when running the pipeline.

**Standalone code to reproduce the issue**
!tfx pipeline create  \
--pipeline-path=kubeflow-runner.py \
--endpoint={ENDPOINT} \
--build-image

!tfx run create  \
--pipeline-name={PIPELINE_NAME} \
--endpoint={ENDPOINT}

--> logs in the kubeflow --> error on the transform component. 

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/io/plugins/tensorflow_gfile.py", line 43, in copy
    tf.io.gfile.copy(src, dst, overwrite=overwrite)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 584, in copy_v2
    compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.NotFoundError: Error executing an HTTP request: HTTP response code 404 with body '<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: [...]kubeflowpipelines-default/[...]/[...]/_wheels/tfx_user_code_Transform-0.0+2eb1144d7e0977ead3dbc4d224be0048e9fa2217ea9227ecadc263a02ffdfe8f-py3-none-any.whl</Details></Error>'
	 when reading gs://[...]/[...]/[...]/_wheels/tfx_user_code_Transform-0.0+2eb1144d7e0977ead3dbc4d224be0048e9fa2217ea9227ecadc263a02ffdfe8f-py3-none-any.whl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 477, in <module>
    main(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 469, in main
    execution_info = component_launcher.launch()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 545, in launch
    executor_output = self._run_executor(execution_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 420, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/beam_executor_operator.py", line 98, in run_executor
    return python_executor_operator.run_with_executor(execution_info, executor)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 59, in run_with_executor
    execution_info.exec_properties)
  File "/opt/conda/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 494, in Do
    local_pip_package_path = io_utils.ensure_local(pip_package_path)
  File "/opt/conda/lib/python3.7/site-packages/tfx/utils/io_utils.py", line 44, in ensure_local
    copy_file(file_path, local_path, True)
  File "/opt/conda/lib/python3.7/site-packages/tfx/utils/io_utils.py", line 55, in copy_file
    fileio.copy(src, dst, overwrite=overwrite)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/io/fileio.py", line 46, in copy
    src_fs.copy(src, dst, overwrite=overwrite)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/io/plugins/tensorflow_gfile.py", line 45, in copy
    raise filesystem.NotFoundError() from e
tfx.dsl.io.filesystem.NotFoundError

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by singhniraj08** [comment]
@armand-sauzay,

[Building TFT from source](https://github.com/tensorflow/transform#build-tft-from-source) by default builds the TFT wheel in the dist directory and you have to change directory to dist and then pip install tensorflow_transform.

Alternatively, you can directly `!pip3 install tensorflow-transform` in notebook cell or VM terminal and make sure pip is updated by this command. `sudo pip3 install --upgrade pip`

Kindly try the above steps and let us know if the issue persists. Thank you!
