### ISSUE TITLE
SCHEMA_EMPTY message in transform is truncated

### ISSUE THREAD

**Issue by jaraco** [tensorflow/tfx#463]
In [this code](https://github.com/tensorflow/tfx/blob/617bc5f3276700682920996e922fdd9486b857bf/tfx/components/transform/messages.py#L16-L17), the second portion of the error message is omitted from the message.

**Comment by gowthamkpr** [comment]
@jaraco Please create this pull request in the [tensorflow/transform](https://github.com/tensorflow/transform/pulls) repo as this PR is more suited to the Transform repo instead of TFX. Thanks!
