### ISSUE TITLE
resolver strategies' examples using the `instance_name` parameter should be updated.

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tfx#4660]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/dsl/experimental/SpanRangeStrategy
https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/dsl/experimental/LatestArtifactStrategy
https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/dsl/experimental/LatestBlessedModelStrategy
https://github.com/tensorflow/tfx/blob/30691627766b4da7ac9e30fe68cac6db04f26a9e/tfx/dsl/input_resolution/strategies/span_range_strategy.py#L36-L50

### Clear description:

Because the docs of above links are using `instance_name` parameter, so it should be updated to use `with_id` method. 

For example, `tfx/dsl/input_resolution/strategies/latest_artifact_strategy.py` should be updated as follows.

````diff
diff --git a/tfx/dsl/input_resolution/strategies/latest_artifact_strategy.py b/tfx/dsl/input_resolution/strategies/latest_artifact_strategy.py
index 7a64c98f..e1d190c5 100644
--- a/tfx/dsl/input_resolution/strategies/latest_artifact_strategy.py
+++ b/tfx/dsl/input_resolution/strategies/latest_artifact_strategy.py
@@ -31,9 +31,9 @@ class LatestArtifactStrategy(resolver.ResolverStrategy):
   Don't construct LatestArtifactStrategy directly, example usage:
   ```
     model_resolver = Resolver(
-        instance_name='latest_model_resolver',
         strategy_class=LatestArtifactStrategy,
-        model=Channel(type=Model))
+        model=Channel(type=Model)
+        ).with_id('latest_model_resolver')
     model_resolver.outputs['model']
   ```
   """
````

**Comment by chongkong** [comment]
Oops I made a mistake on PR description; it is closed by #4668.
