### ISSUE TITLE
ValueError: memoryview assignment: lvalue and rvalue have different structures

### ISSUE THREAD

**Issue by MsAlEhR** [tensorflow/tfx#4667]
System information

- Python : 3.7.11
- TensorFlow version: 2.3.1
- TFX Version: 1.3.1
- Apache Beam : 2.34.0

Describe the current behavior

I run my pipeline on a spark cluster which stores each pipeline's component data on the HDFS; I see the following error when I increase the  size of my data. In first component (ImportExampleGen), I handle to overcome this issue by increasing the number of partitions of tfrecords( each tfrecords have size less than 30MB, and I have more than 10 of them). But in other complements(Statistics,...), because the pipeline stores the result of the ImportExampleGen  in 2 portions(shards) , I faced with this error.

```
_ValueError: memoryview assignment: lvalue and rvalue have different structures
 [while running 'Run[ImportExampleGen]']_
```
This error may not relate to the tfx ( I think it is related to Apache-beam SDK workers).

Thoughts:

I think if there are some options in output_config of  ImportExampleGen component to determine the output size of each tfrecords ,then I will pass this issue.

I will be happy if you help me to solve this problem. 

Here is my incomplete  sample code to run tfx on a spark cluster.

[tfx-spark](https://github.com/MsAlEhR/tfx_horovod_spark)

**Comment by pindinagesh** [comment]
@MsAlEhR 

We recommend you to install TF 2.4 or later. Older versions are no longer supported and since it's not related to TFX, could you please post this issue to Apache-beam SDK repo?

**Comment by pindinagesh** [comment]
@MsAlEhR 

Can you have a look at this [Gist](https://github.com/aaronlelevier/apache_beam_examples/blob/3afa0e411676c22734e7a2189602eda611938597/notebooks/MNIST-all-data-and-partition-fn.ipynb) about tfrecords with apache_beam. Thanks

**Comment by pindinagesh** [comment]
@MsAlEhR 

Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!

**Comment by MsAlEhR** [comment]
Thank you for your response @pindinagesh 

I solved my problem by creating a new component to increase the number of partitions .


`
from tfx.dsl.component.experimental.decorators import component
import apache_beam as beam
from tfx.types import artifact_utils
from tfx.utils import io_utils
from apache_beam.options.pipeline_options import PipelineOptions


@component
def TFRPartitionorComponent(
    input_tf: tfx.dsl.components.InputArtifact[tfx.types.standard_artifacts.Examples],
    examples:  tfx.dsl.components.OutputArtifact[tfx.types.standard_artifacts.Examples],
    num_shards: tfx.dsl.components.Parameter[int] = 30
    ):
             
        
        
        
                  # Get a list of the splits in input_data
                splits_list = artifact_utils.decode_split_names(split_names=input_tf.split_names)
                  # We could also just use input_data.split_names.
                examples.split_names = artifact_utils.encode_split_names(
                      splits=splits_list)
                  # TODO(b/168616829): Remove populating payload_format after tfx 0.25.0.
                examples.set_string_custom_property(
                      "payload_format",
                      input_tf.get_string_custom_property("payload_format"))


                for split in splits_list:
                        input_dir = artifact_utils.get_split_uri([input_tf], split)
                        output_dir = artifact_utils.get_split_uri([examples], split)
                        tf.io.gfile.mkdir(output_dir)
                        output_path=os.path.join(output_dir,'data_tfrecord')

                        with beam.Pipeline(options=PipelineOptions(
                            [               
                                '--hdfs_full_urls',
                                '--hdfs_host=YOUR_HOST',
                                '--hdfs_port=YOURPORT',
                            ])) as p:

                                ( p |'ReadExamples'>> beam.io.tfrecordio.ReadFromTFRecord(os.path.join(input_dir, '*')) \
                                    | "WriteTFR" >> beam.io.WriteToTFRecord(output_path,num_shards=num_shards,                                                        file_name_suffix='.gz'))
`
