### ISSUE TITLE
Skew/Drift Calculation is unclear.

### ISSUE THREAD

**Issue by The-Grand-Zand** [tensorflow/tfx#4685]
## Description of issue (what needs changing):
I have been receiving odd skew results even though the data has a normal standard deviation as well as similar mean, median, missing. From what I have read, the skew is calculated using the L-Infinity norm and Jensen-Shannon Divergence. I have tried to use these two equations to manually calculate the skew/drift of specific features to try and derive the same answer as TFDV returns to no avail. 

Would it be possible to explain what variables go into calculating the skew/drift with an example? This would greatly help my understanding and trust for utilizing TFDV for data validation and modeling pipelines. 

### Current Links to skew/drift explanations
Here are the links I have found with descriptions of the calculation. Unfortunately, none give the granularity that I am looking for.

- https://github.com/tensorflow/tfx/blob/cf04e1c99e7faf644bc91e498cf5cc58ea044eae/docs/tutorials/data_validation/tfdv_basic.ipynb
- https://www.tensorflow.org/tfx/guide/tfdv
- https://stackoverflow.com/questions/59528660/understanding-l-infinity-norm-which-is-used-in-tfdv

### visual example of odd skew calculation
![Policy_tenure_custom_graphs](https://user-images.githubusercontent.com/99690050/154071729-70e54f6d-fd67-46b9-afcc-e5092ce8b453.PNG)
![Policy_tenure_tfdv_graphs](https://user-images.githubusercontent.com/99690050/154071739-251560b0-1f50-413d-a432-78a2649a35c3.PNG)

**Comment by jiyongjung0** [comment]
This seems like an issue in [Data Validation](https://github.com/tensorflow/data-validation). @caveness could you take a look?

**Comment by The-Grand-Zand** [comment]
Thank you for looking into it, I am happy to help with more granular graphs/data if need be.

**Comment by jiyongjung0** [comment]
Or it might be better to report the issue to [Data Validation repository](https://github.com/tensorflow/data-validation/issues) directly. Because TFX itself is a thin wrapper over various Data Validation APIs.

Thanks!

**Comment by The-Grand-Zand** [comment]
I'll do that. Thanks anyways!
