### ISSUE TITLE
Passing results from a custom component to Transform component

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [tensorflow/tfx#4705]
I want to use the size of the vocabularies as a parameter for my transformations. For example, 

```python
def preprocessing_fn(inputs, custom_config):
    ...
    outputs["labels"] = tf.sparse.to_indicator(inputs["id_feature"], vocab_size)
    ...
```

This `vocab_size` needs to be predetermined. Therefore, it's probably not possible to use `tft.compute_and_apply_vocabulary` inside the `preprocessing_fn` to determine the vocabulary and then the vocabulary size. So I created a custom component that extracts the size of the vocabularies from `StatisticsGen`.  

```python
@component
def compute_vocab_size(
    statistics: InputArtifact[standard_artifacts.ExampleStatistics],
    vocab_size: OutputArtifact[standard_artifacts.Integer],
):
    # extract vocab_size from statistics
    ...
    # Write to file
    setattr(vocab_size, "value", size)
```

What I am not clear is how to pass the `vocab_size` result from my custom component into the `preprocessing_fn` or the `Transform` component. I have tried to pass the output channel `vocab_size` into the `custom_config` argument, but the uri of the output channel shows as `None` when being retrieved inside the `preprocessing_fn`. Apparently, the component haven't run and therefore, the real uri wasn't set yet. In Airflow, there is `xcom` push and pull between each nodes, but I am not sure something equivalent exists in TFX.

**Comment by OmarAlsaqa** [comment]
I am not sure if this would help but you can pass anything to Transform using `custom_config`. see [docs](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/Transform)

```python
transform = tfx.components.Transform(
    examples=example_gen.outputs['examples'],
    schema=schema_importer.outputs['result'],
    materialize=False,
    module_file=module_file,
    custom_config = {'size': vocab_size}
)
```

**Comment by EdwardCuiPeacock** [comment]
> I am not sure if this would help but you can pass anything to Transform using `custom_config`. see [docs](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/Transform)
> 
> ```python
> transform = tfx.components.Transform(
>     examples=example_gen.outputs['examples'],
>     schema=schema_importer.outputs['result'],
>     materialize=False,
>     module_file=module_file,
>     custom_config = {'size': vocab_size}
> )
> ```

This would require vocab_size to be computed outside of the pipeline / before pipeline deployment. The goal is to pass the computed result from another component to the Transform component, much like the “example” or “schema” channel, which are lazily evaluated. This means, the uri of these channels won’t be materialized until runtime. As I described in the main description, I tried to pass the artifact itself but it won’t be parsed as the runtime value, only the temporary value at deployment time showed up.

**Comment by OmarAlsaqa** [comment]
I used the same idea (if i understood right) but in the Trainer component. In this [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/experimental/penguin_utils_sklearn.py#L49) I passed the Transformed Schema as an input to `run_fn`, `_input_fn` as:

See, `custom_config` here:
```python
from tfx.proto import trainer_pb2

trainer = tfx.components.Trainer(
    module_file=os.path.abspath(_trainer_module_file),
    examples=transform.outputs['transformed_examples'],
    transform_graph=transform.outputs['transform_graph'],
    schema=schema_gen.outputs['schema'],
    train_args=tfx.proto.TrainArgs(),
    eval_args=tfx.proto.EvalArgs(),
    custom_config = {'s': transform.outputs['post_transform_schema']._artifacts[0].uri}###HERE###
)

context.run(trainer, enable_cache=False)
```
You can see down here how it is passed to `run_fn` first which is passed to `_input_fn`:

```python
from tfx.components.trainer.fn_args_utils import FnArgs

def _input_fn(
    file_pattern: str,
    data_accessor: DataAccessor,
    schema: schema_pb2.Schema,
    tschema: schema_pb2.Schema, ###HERE###
    batch_size: int = 32,
) -> Tuple[np.ndarray, np.ndarray]:
    """Generates features and label for tuning/training.
    Args:
    file_pattern: input tfrecord file pattern.
    data_accessor: DataAccessor for converting input to RecordBatch.
    schema: schema of the input data.
    tschema: schema of the transformed data.
    batch_size: An int representing the number of records to combine in a single
      batch.
    Returns:
    A (features, indices) tuple where features is a matrix of features, and
      indices is a single vector of label indices.
    """
    record_batch_iterator = data_accessor.record_batch_factory(
      file_pattern,
      dataset_options.RecordBatchesOptions(batch_size=batch_size, num_epochs=1),
      tschema) ###HERE###

    feature_list = []
    label_list = []
    for record_batch in record_batch_iterator:
        record_dict = {}
        for column, field in zip(record_batch, record_batch.schema):
            record_dict[field.name] = column.flatten()

        label_list.append(record_dict[_LABEL_KEY])
        features = [record_dict[key] for key in _FEATURE_KEYS]
        feature_list.append(np.stack(features, axis=-1))

    return np.concatenate(feature_list), np.concatenate(label_list)


# TFX Trainer will call this function.
def run_fn(fn_args: FnArgs): ###HERE, Notice FnArgs###
    """Train the model based on given args.
    Args:
    fn_args: Holds args used to train the model as name/value pairs.
    """
    schema = io_utils.parse_pbtxt_file(fn_args.schema_file, schema_pb2.Schema())
    
    # transformed schema
    tschema = io_utils.parse_pbtxt_file(fn_args.custom_config['s']+'/schema.pbtxt', schema_pb2.Schema()) ###HERE###

    x_train, y_train = _input_fn(fn_args.train_files, fn_args.data_accessor, schema, tschema) ###HERE###
    x_eval, y_eval = _input_fn(fn_args.eval_files, fn_args.data_accessor, schema, tschema) ###HERE###

    # The rest of this function is not important to your case but to give you the full idea.
    steps_per_epoch = _TRAIN_DATA_SIZE / _TRAIN_BATCH_SIZE

    randomForestModel = RandomForestClassifier(n_estimators = 100, random_state = 42, max_features=None, verbose=True)
    
    model = Pipeline([
      ('estimator', randomForestModel),
    ])
    model.feature_keys = _FEATURE_KEYS
    model.label_key = _LABEL_KEY
    model.fit(x_train, y_train)
    absl.logging.info(model)
    
    score = model.score(x_eval, y_eval)
    print('Eval Accuracy: %f', score)
    absl.logging.info('Accuracy: %f', score)

    # Export the model as a pickle named model.pkl. AI Platform Prediction expects
    # sklearn model artifacts to follow this naming convention.
    os.makedirs(fn_args.serving_model_dir)

    model_path = os.path.join(fn_args.serving_model_dir, 'model.pkl')
    with fileio.open(model_path, 'wb+') as f:
        pickle.dump(model, f)
```


So, I think you can create:
```python
def _vocab_fn(feature):
    # Do something
```
and pass it to Transform component. using:
```python
transform = tfx.components.Transform(
    examples=example_gen.outputs['examples'],
    schema=schema_importer.outputs['result'],
    materialize=False,
    module_file=module_file,
    custom_config = {'vocab_size_calculator': _vocab_fn}
)
```

```python
def preprocessing_fn(inputs, fn_args: FnArgs):
    ...
    vocab_function = fn_args.custom_config['vocab_size_calculator']
    vocab_size = vocab_function(inputs["id_feature"]) ## for example
    outputs["labels"] = tf.sparse.to_indicator(inputs["id_feature"], vocab_size)
    ...
```
Take a look at [FnArgs docs](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/FnArgs) might help you.

Also, You can use `tft.compute_and_apply_vocabulary` inside `preprocessing_fn` and thin use ` tft.experimental.get_vocabulary_size_by_name` but you will need TFX >= 1.6.0 [see docs](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/experimental/get_vocabulary_size_by_name)

Hopefully, this helps.

**Comment by jiyongjung0** [comment]
I think that there is no clean and recommended way to pass an additional data to Trainer as of now.

However, IIUC, the vocab_size value is also needed to calculate `inputs["id_feature"]`. So I think that it should be fixed even before the input data is generated. How about converting your raw data input `inputs["id_feature"]` inside `preprocessing_fn` with `tft.compute_and_apply_vocabulary` or something similar?

**Comment by EdwardCuiPeacock** [comment]
@jiyongjung0 @OmarAlsaqa Thank you both for the suggestions. 

The difficulty is still due to the fact that each component is lazily evaluated and it won't run until it is deployed and a run is triggered. The `context.run` approach would only work if we are using interactive mode to run locally, which a lot of TFX tutorial uses. In production, we have to deploy the model to GCP and run inside Google's environment. 

My understanding of how `Transform` component works is that `preprocessing_fn` will be first turned into a computation graph and saved as an artifact (`transform_graph`), then Beam pipeline will partition the data by batch and apply the `preprocessing_fn` on each of it's individual workers. Therefore, `tft.compute_and_apply_vocabulary` or any function (e.g. `_vocab_fn`) we use inside `preprocessing_fn` will just  be one of those functions that will be exposed to each batch of the data. In another word, it won't be able to get the vocab size for the entire dataset within `preprocessing_fn`.

**Comment by jiyongjung0** [comment]
@zoyahav @varshaan Could you give some advice on the correct use of TFT regarding the above answer? I think that `tft.compute_and_apply_vocabulary` will compute the vocab_size more efficiently, but wanted to get a correct answer. 😄

**Comment by zoyahav** [comment]
Yes, please have a look at [`tft.experimental.get_vocabulary_size_by_name
`](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/experimental/get_vocabulary_size_by_name) and [`tft.get_num_buckets_for_transformed_feature`](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/get_num_buckets_for_transformed_feature), both of these should help achieve what you're looking for, which is obtaining vocabulary size from within a `preprocessing_fn`.

The difference between the two is that `tft.experimental.get_vocabulary_size_by_name` will simply lookup a vocabulary by name and provide its size, while `tft.get_num_buckets_for_transformed_feature` will work specifically on the output of `tft.compute_and_apply_vocabulary` and will produce essentially the vocabulary size + number of OOV buckets.

See a usage example here:
https://github.com/tensorflow/transform/blob/9ba9c4134b3092ac52d10db254f14a6ce52b820c/examples/census_example_common.py#L144-L145

**Comment by singhniraj08** [comment]
@EdwardCuiPeacock,

Kindly let us know if the above answer by @zoyahav helps in resolving your problem. Thank you.

**Comment by EdwardCuiPeacock** [comment]
Hi, I am revisiting this issue more recently. I briefly looked at the solution provided by @zoyahav (thank you), and it seems like it can be a partial workaround to the issue I am having. But I am also trying to obtain a vocabulary from the union of 2 or more features.

In my specific use case, I have two features called `history` and `session`. Both are variable length sequences (represented as sparse tensors) of item ids. I am essentially running an auto-regressive model, using `history` to predict `session`. Not all ids showing up in `history` will show up in `session`, and vice versa, although they have significant overlaps. I would like both of these two features use the same system of vocabulary to index mapping in my model.

Another use case I am thinking is to provide additional pre-existing lookups. For example, when we received the `history` feature from ExampleGen or from online inference time, we would like the `Transform` component to add additional features based on a lookup table, e.g. {item_id: descriptions} or {user_id: location}. One approach we thought of is creating a simple custom component to construct these lookups through our FeatureStore API calls, and use Transform component to apply the lookups. Saving the lookups as part of the model artifacts during serving can significantly reduce online inference latency in our case.

**Comment by pritamdodeja** [comment]
Have you considered using functools partial to accomplish this?

**Comment by EdwardCuiPeacock** [comment]
> Have you considered using functools partial to accomplish this?

Can you provide a specific example on how to achieve this?

**Comment by pritamdodeja** [comment]
This isn't exactly the same as your use-case, but might be close enough to provide a solution:

```
dnn_inputs = {}                                                                                                                                                                           
    dnn_inputs = {                                                                                                                                                                            
        input_name: inputs[input_name]                                                                                                                                                        
        for input_name in dnn_input_names}                                                                                                                                                    
    keras_preprocessing_inputs = {}                                                                                                                                                           
    keras_preprocessing_inputs = {                                                                                                                                                            
        input_name: inputs[input_name]                                                                                                                                                        
        for input_name in keras_preprocessing_input_names}                                                                                                                                    
    _inject_create_model = partial(_make_keras_model, fn_args, inputs, dnn_inputs, keras_preprocessing_inputs, )                                                                              
    tuner = keras_tuner.RandomSearch(                                                                                                                                                         
        _inject_create_model,                                                                                                                                                                 
        max_trials=MAX_TRIALS,                                                                                                                                                                
        hyperparameters = _get_hyperparameters(),                                                                                                                                             
        allow_new_entries=False,                                                                                                                                                              
        objective=keras_tuner.Objective('val_mse', 'min'),                                                                                                                                    
        directory=fn_args.working_dir,                                                                                                                                                        
        project_name='synthetic')
```

**Comment by singhniraj08** [comment]
Hi @EdwardCuiPeacock,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFX team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFX [version](https://pypi.org/project/tfx/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfx/releases) to stay up to date with the latest developments which are happening in the TFX  space. Thank you!
