### ISSUE TITLE
SchemaGen does not infer features' shape

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/tfx#472]
[It looks like SchemaGen's executor hard-codes the `infer_feature_shape` parameter to `False` in `tfdv.infer_schema`](https://github.com/tensorflow/tfx/blob/master/tfx/components/schema_gen/executor.py#L63)
This is the opposite from the default parameters.
This leads to all features to have no shape and consequently, the TFT function `schema_as_feature_spec` generates only `VarLenFeature` because it says:

```
For a Feature with a FixedShape we generate a FixedLenFeature with no default.  
For a Feature without a FixedShape we generate a VarLenFeature.  
For a SparseFeature we generate a SparseFeature.
``` 
[link](https://github.com/tensorflow/transform/blob/187fac0426/tensorflow_transform/tf_metadata/schema_utils.py#L166-L171)

It should be possible to set this parameter to True (Why is it not the default?).
For backward compatibility, I understand this parameter should stay False by default for now.

**Comment by gowthamkpr** [comment]
@martin-laurent You can always change set  `schema_as_feature_spec ` to `True` based on your use case.  As for Why is it set to `False` by default @ruoyu90 Can you PTAL. Thanks!

**Comment by ruoyu90** [comment]
This is something that we're tracking. Will provide the option soon.
