### ISSUE TITLE
can it possible improve the tf serving performance 

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tfx#4759]
Now I train a recommend nn model offline ,and then predict it by tf serving on cpu online machine. There are 8 cores i just applied, and found it cost slow when predict it. More than 0.4% it costs 100ms when predict. The batch size request is 50. There are 167 one hot features and 3 full-connected layers.And the usage of cpu is also slow, it is only 20% usage.
How can i analyze the bottleneck of serving ,and can it possible to reduce the time cost ratio by adjust some parameters?

i have tried many ways followed this links https://www.tensorflow.org/tfx/serving/performance ,but it hardly worked.
Tf serving can't support many sparse features so well?

**Comment by pindinagesh** [comment]
Hi @liumilan 

I have already responded to the same issue in serving repo. Kindly respond to the same

**Comment by liumilan** [comment]
who can help to support this  issus

**Comment by 1025KB** [comment]
Hi, could you reply to [this](https://github.com/tensorflow/serving/issues/1989) thread? thanks

**Comment by pindinagesh** [comment]
Hi @liumilan 

Closing this issue here, you can track this issue in [TF serving](https://github.com/tensorflow/serving/issues) repo. Thanks!
