### ISSUE TITLE
TFX interest in integrating with SimpleML

### ISSUE THREAD

**Issue by eyadgaran** [tensorflow/tfx#4770]
Hi dev team, Elisha, author of SimpleML here. I wanted to reach out to see if there is any interest in integrating parts of SimpleML into the broader TFX ecosystem. The use cases don't necessarily overlap (TFX is enterprise scale first whereas SimpleML is local developer/small team centric), but I see a lot of shared vision in the implementation and would be happy to adapt components already developed and design future work for better compatibility. 

To be clear, I'm not asking for developer time to implement anything. I'm happy to bear that burden if it is of interest to the team. But also don't want to go down that path if there is no interest :) 

https://github.com/eyadgaran/SimpleML

**Comment by 1025KB** [comment]
It would be a good candidate for TFX-[addons](https://github.com/tensorflow/tfx-addons)

**Comment by rcrowe-google** [comment]
@1025KB - I agree, this sounds like a great project for [TFX-Addons](https://github.com/tensorflow/tfx-addons)!

**Comment by singhniraj08** [comment]
@eyadgaran 

Did you got a chance to create PR for adding SimpleML to [TFX-Addons](https://github.com/tensorflow/tfx-addons). Thank you.

**Comment by eyadgaran** [comment]
> @eyadgaran
> 
> Did you got a chance to create PR for adding SimpleML to [TFX-Addons](https://github.com/tensorflow/tfx-addons). Thank you.

Thanks for following up! I've decided to hold off for the moment while I determine the direction of the project. Cheers!

**Comment by singhniraj08** [comment]
@eyadgaran,

Requesting you to close this issue and create a PR in [TFX-Addons](https://github.com/tensorflow/tfx-addons) when you want go ahead with this integration. Thank you!
