### ISSUE TITLE
What is example_gen_pb2 and where is it documented?

### ISSUE THREAD

**Issue by oonisim** [tensorflow/tfx#4830]
## URL(s) with the issue:
https://www.tensorflow.org/tfx/guide/examplegen

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/guide/examplegen

## Description of issue (what needs changing):

[The ExampleGen TFX Pipeline Component][1] has the example code which uses **example_gen_pb2** but cannot find out the documentation which explains it and how to use it. Please provide the URL of the API documentation of example_gen_pb2.

```
# Input has a single split 'input_dir/*'.
# Output 2 splits: train:eval=3:1.
output = proto.Output(
             split_config=example_gen_pb2.SplitConfig(splits=[
                 proto.SplitConfig.Split(name='train', hash_buckets=3),
                 proto.SplitConfig.Split(name='eval', hash_buckets=1)
             ]))
example_gen = CsvExampleGen(input_base=input_dir, output_config=output)
```

  [1]: https://www.tensorflow.org/tfx/guide/examplegen

**Comment by 1025KB** [comment]
The API doc is [here](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/proto) 

but since it's proto file, the easiest way is checking the [definition](https://github.com/tensorflow/tfx/blob/master/tfx/proto/example_gen.proto) itself, which has comment for the data structure

**Comment by gowthamkpr** [comment]
As mentioned [above](https://github.com/tensorflow/tfx/issues/4830#issuecomment-1119149761), since its a protofile, you can look at the definition to understand it and so its not added in docs. Closing this issue as its expected. Thanks!!
