### ISSUE TITLE
Extremely slow performance using remote MLMD CloudSQL instance

### ISSUE THREAD

**Issue by htahir1** [tensorflow/tfx#4911]
Hello. I initially created an issue in the ML Metadata repository (https://github.com/google/ml-metadata/issues/157) but have subsequently realized that this is more of an issue with the `launcher.Launch` logic in TFX. I believe the querying happening in the driver code and preparing each component before each run is very unoptimized for certain use-cases. 

Our team has been trying to use ml-metadata to run pipelines using a Cloud SQL backend. However, we have run into performance issues. Let's say my metadata connection config looks like this:

```
connection_config {
  mysql {
    host: '34.79.128.231'
    port: 3306
    database: 'my_database'
    user: 'root'
    password: '***'
    ssl_options {
      key: 'client-key.pem'
      cert: 'client-cert.pem'
      ca: 'server-ca.pem'
      capath: '/'
      verify_server_cert: false
    }
    skip_db_creation: false
  }
}
```

And run a TFX pipeline with the above, there is a near 60 second waiting time between running components. This is likely caused by the number of queries happening in the portable [launcher code](https://github.com/tensorflow/tfx/blob/51680e4e5e32a9dec4669b7851e5713ecf67f90c/tfx/orchestration/portable/launcher.py#L531).  I have ghetto profiled the performance of the code and it takes way too long to run through the 7 steps to get previous executions and resolve the caching logic.

We have also tried to run through the gRPC server rather than connecting to the DB directly but still the same result. On the other hand, when using the internal Kubeflow MLMD or using Kubeflow (Vertex) with Cloud SQL directly in the same VPC then the performance is fast as expected. The only time you run into this problem is when you try to locally run the pipeline and connect to a public IP like `34.79.128.231`.

Is there a way to solve this problem? We would like to use TFX independant of Kubeflow or Vertex.
_____________________________________________________________________________________________________

If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- Have I specified the code to reproduce the issue (Yes, No):
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc):
- TensorFlow version: ...
- TFX Version: 1.8.0
- Python version: 3.8.10
- Python dependencies (from `pip freeze` output): ...

**Describe the current behavior**
Slow performance for TFX pipelines (up to 60 seconds wait time between simple components)

**Describe the expected behavior**
Fast execution.

**Standalone code to reproduce the issue**
See above

Providing a bare minimum test case or step(s) to reproduce the problem will
greatly help us to debug the issue. If possible, please share a link to
Colab/Jupyter/any notebook.

**Name of your Organization (Optional)**

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by jiyongjung0** [comment]
This seems like an interesting report. @1025KB could you take a look?

**Comment by 1025KB** [comment]
for the 60s, can we confirm if that is taken by MLMD?
There are some costs for e.g., container setup if running on Cloud.

Which DagRunner are you using?

**Comment by singhniraj08** [comment]
Hi @htahir1,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFX team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFX [version](https://pypi.org/project/tfx/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfx/releases) to stay up to date with the latest developments which are happening in the TFX  space. 
Thank you!
