### ISSUE TITLE
Transform component, running beam with Flink Runner. Flink job fails with ModuleNotFoundError.

### ISSUE THREAD

**Issue by jccarles** [tensorflow/tfx#4948]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Linux
- TensorFlow version: 2.5.3
- TFX Version: 1.2.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output):

Docker image for sdk workers built from

FROM apache/beam_python3.7_sdk:2.39.0
tfx==1.2.0
tensorflow==2.5.3

**Describe the current behavior**

Running a tfx pipeline with FlinkRunner for beam. The Transform component manages to start the flink job but it instantly fails with `ModuleNotFoundError: No module named 'pipeline_functions'`.

I wonder where can I find the code responsible for adding user code as `--extra_package` or actually installing the wheel which contains my user code ? I was not able to locate it in the repository...

Also I wonder if this [comment](https://github.com/tensorflow/tfx/issues/3761#issuecomment-854729990) is still "actual" (given my versions of tfx and beam) ?

Should I disable the wheel packaging and set `force_tf_compat_v1=True` in the Transform component ? If yes I wonder what are the implications of this ?

More globally I was hoping to start a discussion with potential other users of TFX who might have a similar setup, we are moving from running TFX pipelines with GCS for storage and Dataflow runners for Beam towards running TFX pipelines with HDFS for storage and Flink runners for Beam. The journey is tortuous and I was hoping to find potential other users who might wanna share their experience.

Thank you !

**Comment by ConverJens** [comment]
@jccarles Are you using beam as a sidecar to your flink deployment? Is pipeline_functions your own custom code?

**Comment by jccarles** [comment]
Yes exactly I am using `beam-worker-pool` as sidecar for all my flink task managers. Yes sorry indeed it is not clear, `pipeline_functions` is my custom module which holds `preprocessing_fn`.

**Comment by ConverJens** [comment]
@jccarles cc @jiyongjung0 
How are you passing your preprocessing code to beam then?
Are you pointing to a module file or function? Can you paste the config of your transform component as well as your beam args?

**Comment by jccarles** [comment]
I am pointing to a module file. When I was using GCS I used package user modules and `force_tf_compat_v1=False` and it was working fine.

Now with beam on Flink I use the following config for transform (with `UNSUPPORTED_DO_NOT_PACKAGE_USER_MODULES`)

```
transform = Transform(
        examples=example_gen.outputs[standard_component_specs.EXAMPLES_KEY],
        schema=infer_schema.outputs[standard_component_specs.SCHEMA_KEY],
        module_file=module_file,
        materialize=materialize,
        custom_config=custom_config,
        force_tf_compat_v1=True
    )
```

And `module_file` is the path within my docker image where I saved my module file. 

I use the following beam args:

```
[
    "--runner=FlinkRunner",
    "--flink_version=flink_version",
    "--flink_master=flink_master_url",
    "--flink_submit_uber_jar",
    "--environment_type=EXTERNAL",
    "--environment_config=localhost:50000",
    "--parallelism=flink_parallelism",
    "--sdk_worker_parallelism=1",
    "--execution_mode_for_batch=BATCH_FORCED",
    .
    .
    . (hdfs_options...)
]
```

So "how I pass my preprocessing code to beam" for now is by including it in the docker image used by the beam_worker_pool, and specifying in transform at which path tfx should find the module_file.

But it seems to me that this is not the desired behavior since tfx 0.30. Also since my flink cluster is not spawned at the start of my pipeline it means I have to restart Flink Task Managers with an updated sidecar image if I update my user code which is not ideal...

**Comment by ConverJens** [comment]
@jccarles 
There are two ways to do this, both of them has issues.

1. Package your code into a whl or similar and pass that as an extra package to beam using the `--extra_package` flag or by uploading your code to an internal artifact registry (e.g. an internal pypi) and pass a requirements.txt to beam.
Note: I've had multiple issue with this and if you google tfx and flink you'll find several github issues with my name on it. One of them being that the beam worker hangs on the second job submitted. I ended up abandoning this approach.

2. As you mentioned, build a custom beam sidecar image containing your code. This is the  best way which conforms with standard MLOps practice. The difficult part here is that you will need to spinn up and to tear down your Flink cluster per pipeline invocation. This is known as a flink application cluster I believe.

I ended up building a few custom kubeflow components that used the k8s api to deploy said flink resources, wait for pipeline termination and then gracefully shut down the resources.

Newer versions of flink and beam might support the flink management on its own though.

**Comment by jccarles** [comment]
O nice I see, were you able to include those custom kubeflow components in a tfx generated pipeline ?

I tried the approach of spawning a Flink cluster for each component which needs it as in previous version of tfx we could write a custom `Launcher` class for each component. This custom launcher was responsible for spawning the Flink cluster, running the component and finally shutting the cluster down. But when migrating to the new tfx ir, this approach does not work anymore as you are not suppose to write a `Launcher` but a `custom_executor_operator`. But the `kubeflow_container_entrypoint` does not emerge the necessaries arguments to make this possible 😞 . I opened a discussion about this point [here](https://github.com/tensorflow/tfx/issues/5054).

But I did not look at having a Flink cluster dedicated for a pipeline run, this could be promising as you said with custom kubeflow components running before and after tfx pipeline. We might have several pipelines running concurrently each with dedicated user code but it looks possible while we keep the Flink clusters separated.

Was it not too painful for debugging purposes though since the cluster gets killed at the end of the pipeline ?

I will look more into flink application cluster too, I did not have the precise vocabulary. Thanks a lot for your time it is very much appreciated !

**Comment by ConverJens** [comment]
@jccarles 
Actually, I created tfx python custom components. They are very similar to kubeflow components: https://www.tensorflow.org/tfx/guide/custom_function_component

To make this work I actually created a second pipeline which spawned the flink resources, started the TFX pipeline and waited for it to finish/crash and then tore down flink. In the event of a failure the resources were kept for a longer time period, say 24h.

Today I believe this could be implemented by using a custom TFX component that spins up flink and then you use the .add_downstream_component (similar to kubeflows .after) and then you add an exit handler which can take care of the graceful flink shutdown.

No worries! I had so much pain with this, so if I can spare someone a portion of this, then that is awsome!

Hope this helps and feel free to let me know if you have any other questions!

**Comment by jccarles** [comment]
Thank you I will try this solution it looks quite elegant ! 

I might have one last question ! Have you ever experienced Flink job hanging forever I think over a grcp issue ? It happens to us quite randomly, retrying the component make it work in most cases... So I added retry and timeout operator functions to pipeline components to detect when it happens and automatically retry the component but it is not ideal 😅 

I was wondering if it comes from our Flink Cluster setup or if another tfx/Flink user might have faced it ?

**Comment by ConverJens** [comment]
@jccarles 
Solution 1 has the upside (if it works) that you only need to deploy one Flink cluster and that can be used for all jobs. This is better if it works, but as I mentioned I had troubles with it.

Not that I recall actually. The issues I have had have usually been about one worker crashing due to some issue, usually data I believe, and then the other workers (processes) eventually fails with a grpc error.

Other issues that I've had has improved by updating beam and flink to the highest available versions.

I'm no expert but I can have a look if you post your flink charts.
