### ISSUE TITLE
Advice on migrating pre-existing Airflow operator ecosystem?

### ISSUE THREAD

**Issue by jinnovation** [tensorflow/tfx#495]
My team at Twitter is looking to adopt TFX for our internal ML workflow product. To that effect, we have a small ecosystem of home-grown Airflow Operators that we'd like to be able to continue to use with ideally as little migration cost as possible.

Does the TFX team have any guidance/advice on ways to, say, "adapter-ize" Airflow Operators for the Component interface so that they can be used within a Pipeline?

**Comment by zhitaoli** [comment]
Thanks for the interest, Jonathan. Really excited to hear that approach.

Before I answer the question in detail, can you please let us know what operators we need to migrate in the process? Specifically:
- Are these open-sourced operators or closed sourced;
- Do they affect control flow of Airflow (i,e, BranchPythonOperator)?
- Are their non-python code involved in these operators? If so what are they.
- Do they have well defined input/output data artifacts, or they simply uses task-dependency between other operators?

**Comment by jinnovation** [comment]
Thanks @zhitaoli. Will try to answer as best I can; let me know where I can elaborate further.

> Are these open-sourced operators or closed-source?

We have a fleet of home-grown, closed-source Operators. These, I believe, are most commonly used, for a variety of reasons. We do not explicitly block users from using open-source "vanilla" Airflow Operators, but these, from what I understand, are used less frequently.

> Do they affect control flow of Airflow?

We have some that inherit from BranchPythonOperator, but they are very few. 

On that subject, I noticed that TFX seems to design Components with the assumption that they don't outright redirect control flow; is this a deliberate design decision?

> Are their non-python code involved in these operators? If so what are they.

Not to my knowledge, no.

> Do they have well-defined input/output data artifacts, or they simply uses task-dependency between other operators?

Our home-grown Operators are instrumented with input-output contracts that map keywords to expected type(s). It is similar in some regard to `ComponentSpec`, except in our case the specification is tightly coupled to each Operator and not explicitly applicable to multiple Operators, as is the case (from my understanding) with ComponentSpec, which can be used across multiple Components.

**Comment by zhitaoli** [comment]
Thanks for the answer, @jinnovation . cc @ruoyu90 who is also familiar with adapting TFX DSL and Airflow.

> Thanks @zhitaoli. Will try to answer as best I can; let me know where I can elaborate further.

> > Do they affect control flow of Airflow?
> 
> We have some that inherit from BranchPythonOperator, but they are very few.
> 
> On that subject, I noticed that TFX seems to design Components with the assumption that they don't outright redirect control flow; is this a deliberate design decision?
This is the current status, but @ruoyu90 etc are also considering a design to provide some kind of conditional branch support. One possible challenge is how to implement such a "component" on multiple orchestrators we support.
One possibility is to only support this on a subset of orchestrators, but it could limit the portability of the underlying pipeline.
I suggest we move corresponding discussions into a separate Github issue. @ruoyu90 
> 
> > Are their non-python code involved in these operators? If so what are they.
> 
> Not to my knowledge, no.
> 
> > Do they have well-defined input/output data artifacts, or they simply uses task-dependency between other operators?
> 
> Our home-grown Operators are instrumented with input-output contracts that map keywords to expected type(s). That instrumentation is similar in purpose (if not interface) in some regard to `ComponentSpec` in that it's used for load-time type-validation of task dependencies. Furthermore, in our case, the specification is tightly coupled to each Operator and not explicitly applicable to multiple Operators, as is the case (from my understanding) with ComponentSpec, which can be used across multiple Components.

@ruoyu90 can probably assist on how ease up the job of data type definitions.

**Comment by ruoyu90** [comment]
Thanks @jinnovation and @zhitaoli ! I have some questions, please see inline:

> We have a fleet of home-grown, closed-source Operators. These, I believe, are most commonly used, for a variety of reasons. We do not explicitly block users from using open-source "vanilla" Airflow Operators, but these, from what I understand, are used less frequently.

If a component `C1` need to use the output `out_1` of another component `C2`, how is it realized in your system? Is it through something like xcom?

> We have some that inherit from BranchPythonOperator, but they are very few.

For BranchPythonOperator, my current thinking is that we might need to break it into two: one PythonOperator that handle the processing logic and one BranchPythonOperator that only hold the comparing and branch. The former will be rewritten from your existing `BranchPythonOperator`, the latter will be auto-generated by TFX from a 'conditional component'. Do you think the cost is reasonable?

**Comment by jinnovation** [comment]
> If a component `C1` need to use the output `out_1` of another component `C2`, how is it realized in your system? Is it through something like xcom?

Yes, value transfer between tasks takes place via XCom. However, rather than each Operator Performing the pull within its own implementation, we implement a layer of flexibility that decouples the pull from the Operator itself, allowing for an interface very similar to that employed by TFX:

``` python
op1 = SomeOperator(task_id='op1') # xcom_push's some value to key 'pushed_key'

op2 = SomeOtherOperator(
    task_id='op2', 
    arg=XComOutput(op1, 'pushed_key'),
)
```

Passing such an XCom argument to our home-grown Operators in this way allows us to decouple Operator implementations from any assumptions about what values are pushed to what key. Given how similar this seems to TFX's pattern, e.g. `component.outputs.output_key`, I imagine that this will facilitate migration.

> For BranchPythonOperator, my current thinking is that we might need to break it into two: one PythonOperator that handle the processing logic and one BranchPythonOperator that only hold the comparing and branch. The former will be rewritten from your existing `BranchPythonOperator`, the latter will be auto-generated by TFX from a 'conditional component'. Do you think the cost is reasonable?

Makes sense. From #498 it sounds like my previous suspicion—that TFX does not intend to support branching components—was incorrect. This is good news 😆 

Only a very small handful of our internal Operators inherit from BranchPythonOperator, so I'm not opposed to hand-writing replacements for those if it's not possible to "adapter-ize" them for Component use like other Operators.

**Comment by ruoyu90** [comment]
Thanks for the info @jinnovation ! I'd like to learn a little more details about what's been passed across components. Are those primarily URIs to resources (`artifacts` in the context of TFX) or other parameters that do not need to be materialized (`train_steps` for example)? If it's the former, do you think leveraging MLMD (which is used by TFX) is an option?

**Comment by jinnovation** [comment]
> Are those primarily URIs to resources or other parameters that do not need to be materialized?

Yes, these are primarily resources to URIs. It is technically possible for somebody to pass values akin to `train_steps` from one task to the next, but this is rare and users tend to set such values via either runtime parametrization or as constants.

> Do you think leveraging MLMD is an option?

Absolutely.

**Comment by ruoyu90** [comment]
> > Are those primarily URIs to resources or other parameters that do not need to be materialized?
> 
> These are primarily URIs to resources—compute job IDs, data reference paths, etc. It is technically possible for somebody to pass values akin to `train_steps` from one task to the next, but this is rare and users tend to set such values via either runtime parametrization or as constants.
> 
> Given that our system does not enforce any strict categorical distinction between such parameters, like TFX seems to with use of ChannelParameter and ExecutionParameter in ComponentSpec, I imagine that this too might be worth taking into consideration for any sort of adapter-based approach. Am I on the right track there?
> 
Yep! Basically the `ChannelParameter` corresponds to *artifact* while `ExecutionParameter` corresponds to *execution properties*. You can think the former as URIs to resources that you might want to share across components. The latter is for normal parameter you would like to use within a component. In terms of outputs, we currently only support *artifact* but we're open to extend that.
> > Do you think leveraging MLMD is an option?
> 
> Absolutely.

Great! In TFX we handle sharing those URIs (we call them *artifacts*) through MLMD. That should cover most of your cross-component sharing. We're also thinking about allowing supporting primitive outputs which I feel will fit into the problems left.

**Comment by Ark-kun** [comment]
> we have a small ecosystem of home-grown Airflow Operators that we'd like to be able to continue to use with ideally as little migration cost as possible.

Related: Kubeflow Pipelines has support for converting arbitrary Airflow operators to pipeline components https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.components.html#kfp.components.create_component_from_airflow_op . Here is the sample demonstrating that function: https://nbviewer.jupyter.org/github/kubeflow/pipelines/blob/f1df367ee42809641187d630d53ae3d7f17e1c62/samples/core/Component%20from%20Airflow%20operator/Component%20from%20Airflow%20operator.ipynb

**Comment by gowthamkpr** [comment]
@jinnovation Can you please try using Kubeflow as we are no longer actively supporting airflow. Thanks!!
