### ISSUE TITLE
Link to the example is broken

### ISSUE THREAD

**Issue by lynnlangit** [tensorflow/tfx#5]
From the Readme.md page - the link to the 'Chicago Taxi...' example returns a 404

**Comment by VikramTiwari** [comment]
@lynnlangit Coming soon! :)

**Comment by wjarek2** [comment]
Thank you for the report. We've updated the file. The example is still sparsely documented but in the meantime please check out the [TFX User Guide](https://github.com/tensorflow/tfx/blob/master/docs/guide/index.md)

**Comment by wjarek2** [comment]
added Readme to the example so closing this issue - thank you for the repot!
