### ISSUE TITLE
Dev docker builds

### ISSUE THREAD

**Issue by valeriano-manassero** [tensorflow/tfx#516]
I noticed we got daily builds from master here: https://hub.docker.com/r/tensorflow/tfx/tags

Can I suggest to have _one_ tag for this automated build like `nightly` or `0.14.0.dev` or `dev` ?
This will result in not having a lot of tags that can be confusing for people not actively developing, moreover, production releases will not hide between many dev builds.

wdyt?

**Comment by zhitaoli** [comment]
This is definitely possible. @ucdmkt, do we foresee any major problem here, or do we even want to move the daily builds into a different docker image repository so it does not pollute main tags?
