### ISSUE TITLE
Expose `num_shards` argument for components using Beam to write TFRecords

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [tensorflow/tfx#5160]
**System information**

- TFX Version (you are using): 1.9.1
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): Google Cloud
- Are you willing to contribute it (Yes/No): Yes (but perhaps not skilled enough)

**Describe the feature and the current behavior/state.**

Currently, `(BigQuery)ExampleGen` and `Transform` components output tfrecords with variable number of shards determined automatically. However, this may impact the performance of subsequent `Evaluator` component when using these tfrecords for evaluation. This is because Apache Beam when reading tfrecords can only parallelize at the file level, i.e. it can only simultaneously read files in parallel workers; this is probably because tfrecords are row-wise serialized and often compressed. We have done experiments that showed that, if we reshard the number of tfrecords from the usual ~30 files to 1000 files, we can decrease the time needed for the evaluation step from ~8 hours to < 1 hour. As a workaround, we currently have a custom component that reshards the tfrecords. However, it would be great if this can be done already within the `(BigQuery)ExampleGen` and/or`Transform` components. We have found that Beam's [`apache_beam.io.tfrecordio.WriteToTFRecord`](https://beam.apache.org/releases/pydoc/2.40.0/apache_beam.io.tfrecordio.html?highlight=num_shards#apache_beam.io.tfrecordio.WriteToTFRecord) (usually aliased as `beam.io.WriteToTFRecord`) method has an argument `num_shards` which can specify how many shards to write. `(BigQuery)ExampleGen` and `Transform` component does seem to leverage the `WriteToTFRecord` method:
* ExampleGen: https://github.com/tensorflow/tfx/blob/3b5290aa77c2df52a4791715cfd761be7696fe81/tfx/components/example_gen/write_split.py#L81-L87
* Transform:
https://github.com/tensorflow/tfx/blob/3b5290aa77c2df52a4791715cfd761be7696fe81/tfx/components/transform/executor.py#L658-L665

Note that this is also applicable to `WriteToParquet`.

**Will this change the current API? How?**
Yes. `num_shards` will be added.

**Who will benefit with this feature?**
Everyone who have performance issues with Beam.

**Do you have a workaround or are completely blocked by this?** :
Workaround described above, but depends on legacy version of Tensorflow, which soon will become deprecated.

**Name of your Organization (Optional)**
NBC Universal Peacock

**Any Other info.**

**Comment by 1025KB** [comment]
Can beam support shards count in beam_args?

I think in general beam doesn't want users to control the shard count

https://stackoverflow.com/questions/49519960/controlling-dataflow-apache-beam-output-sharding

**Comment by EdwardCuiPeacock** [comment]
beam_args are more for the resources that beam will run on. I think this is part of IO for beam.

**Comment by 1025KB** [comment]
Beam is supposed to decide the best shards count, could you also file an issue at beam side too? Thanks
