### ISSUE TITLE
TFX on Windows

### ISSUE THREAD

**Issue by hugoferrero** [tensorflow/tfx#5182]
Hi...Just one question: At the moment, does Windows support TFX?. 

Thanks in advanced.

**Comment by singhniraj08** [comment]
@hugoferrero,

As per the [similar issue](https://github.com/tensorflow/tfx/issues/950#issuecomment-970793241), there is no plan to support windows. Please stay tuned for future updates on windows support. Hope this answers your question. Thank you!

**Comment by hugoferrero** [comment]
Thank you!.
