### ISSUE TITLE
Handling images in TFRecord and TFX

### ISSUE THREAD

**Issue by Longwelwind** [tensorflow/tfx#5184]
Hello!

I'm trying to use TFX to create a pipeline to train a classification model with images. I'm encountering an issue using TFRecord because I don't know exactly how to put my images inside the TFRecord so that it can be properly used by TFX components. Here is the script I used to create a `.tfrecord` file to be fed into the TFX pipeline:

```python
with tf.io.TFRecordWriter("data/processed/dataset.tfrecord") as writer:
    folders_to_scan = [
        ("data/images/OK", 0),
        ("data/images/NOK", 1),
    ]

    for (folder, label) in folders_to_scan:
        for file in glob.glob(folder + "/*.jpg"):
            with open(file, 'rb') as f:
                image_raw = f.read()
            
            feature = {
                # First solution, put the path of the images in the TFRecord
                'image_path': _bytes_feature(file.encode("utf-8")),
                # Second solution, put the JPEG-encoded images in the TFRecord
                'image_raw': _bytes_feature(image_raw),
                # Third solution, put the raw images in the TFRecord
                'image_raw': _bytes_feature(tf.io.decode_jpeg(image_raw)),
                # Label
                'label': _int64_feature(label),
            }

            example = tf.train.Example(features=tf.train.Features(feature=feature))
            writer.write(example.SerializeToString())
``` 

The first or the second solution seem to be the most intuitive ones, but I encounter an issue when using the `Evaluator` or the `BulkInferrer` component. Because my TFRecord doesn't contain _exactly_ what the TF model expects as input (raw images), it fails. It's normal since my model expects raw images and my TFRecord contains file path (in the first solution) or JPEG-encoded images (in the second solution).

For the Trainer component, it works well because it allows custom Python-code, so I can use `open` and `tf.io.decode_jpeg` to properly load the images before feeding them to my model. But for `Evaluator` and `BulkInferrer`, I can't since they just receive a model and some data.

I could put the raw images inside my TFRecord (the third solution in my code), but then my TFRecord becomes huge. I feel like there's probably a way to handle that case well.

Am I missing something ?

I'm putting my `trainer.py` file (which is the file used by the `Trainer` component), in case it's where I should configure my model to take JPEG-encoded images as input:

```python
from tfx.components.trainer.fn_args_utils import FnArgs

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
import tensorflow_data_validation as tfdv
from tfx_bsl.tfxio import dataset_options

def run_fn(fn_args: FnArgs) -> None:
    img_height = 255
    img_width = 255

    output_path = fn_args.serving_model_dir

    schema = tfdv.load_schema_text(fn_args.schema_path)

    train_dataset = fn_args.data_accessor.tf_dataset_factory(
        fn_args.train_files,
        dataset_options.TensorFlowDatasetOptions(batch_size=2, label_key="label"),
        schema
    ).repeat()

    eval_dataset = fn_args.data_accessor.tf_dataset_factory(
        fn_args.eval_files,
        dataset_options.TensorFlowDatasetOptions(batch_size=2, label_key="label"),
        schema
    ).repeat()

    print(fn_args)

    model = Sequential([
        layers.InputLayer(input_shape=(2560, 1920, 3), name="image_raw"),
        layers.Rescaling(1./255, input_shape=(2560, 1920, 3)),
        layers.Conv2D(16, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(32, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(64, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(2)
    ])

    model.compile(
        optimizer='adam',
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy']
    )

    model.summary()

    model.fit(
        train_dataset,
        steps_per_epoch=fn_args.train_steps,
        validation_data=eval_dataset,
        validation_steps=fn_args.eval_steps,
    )

    model.save(output_path)
```

Thanks in advance! 🙂

**Comment by singhniraj08** [comment]
@Longwelwind,

As mentioned for [Evaluator](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/Evaluator) and [BulkInferrer](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/BulkInferrer), they accept examples produced by ExampleGen component. 
You can try importing external TFRecord with `tf.Example` directly as mentioned [here](https://www.tensorflow.org/tfx/guide/examplegen#ingesting_data_formats_which_are_supported_by_apache_beam) and pass it to evaluator and bulkinferrer component. Hope this helps. Thank you!

**Comment by Longwelwind** [comment]
I'm already using ExampleGen, the issue is what should I put in my TFRecord or how I should structure my model.

In the meantime, I found this issue, that describes how to make a TF model accepts JPEG-encoded: https://github.com/tensorflow/serving/issues/1869

I'll close since it seems to fix my issue. Thanks!
