### ISSUE TITLE
RuntimeParameters fail when using interactive context

### ISSUE THREAD

**Issue by ConverJens** [tensorflow/tfx#5200]
- Have I specified the code to reproduce the issue (Yes, No): 
Yes, minimal example in attached notebook
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): 
Fails in interactive notebook in Jupyter wherever it is run (e.g. local, vertex workbench etc)
- TensorFlow version:  Which ever bundles with TFX 1.9
- TFX Version: 1.9
- Python version: 3.8

RuntimeParameter fails when used in Interactive context with:
`ValueError: Unexpected type <class 'tfx.orchestration.data_types.RuntimeParameter'>`

[minimal_example_runtimeparameter_in_interactive_context.ipynb.zip](https://github.com/tensorflow/tfx/files/9527666/minimal_example_runtimeparameter_in_interactive_context.ipynb.zip)

It works well using other executors (tested with LocalDagRunner and Kubeflow_v2 on Vertex pipelines). Minimal example attached in notebook.

**Comment by singhniraj08** [comment]
@ConverJens,

As mentioned in  official documentation of [tfx.v1.dsl.experimental.RuntimeParameter](https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/dsl/experimental/RuntimeParameter), currently runtime parameter is only supported on KubeflowDagRunner. 

Hope this helps. Thank you!

**Comment by ConverJens** [comment]
@singhniraj08 

Thanks for the pointer. We have aslo spotted another issue which is that default values are not shown in vertex. This is a real pain point when one tries to pass more data, using the custom_config in trainer and tuner.

Are you aware if this is also a known limitation?
