### ISSUE TITLE
Macro/Default Variable support

### ISSUE THREAD

**Issue by newtonle** [tensorflow/tfx#531]
Is there any feature in TFX that provides similar functionality to Airflow Macros/Default Variables (see https://airflow.apache.org/macros.html)? We are looking at adopting TFX but our users rely on this Airflow feature. The main use case is to use it in template strings to associate a dagrun to different systems in our infra (for example, HDFS paths or experiment tracking identifiers).

If there isn't something existing like this, can we build support for this feature?

**Comment by jiyongjung0** [comment]
I'm sorry for the late comment but we added runtime parameter support a while ago. For example, you can use runtime parameters including TFX CLI after 1.3.0. https://github.com/tensorflow/tfx/blob/master/RELEASE.md#version-130

Let me close this for now. Please reopen if you need.
