### ISSUE TITLE
Custom component with file output fails on Vertex

### ISSUE THREAD

**Issue by axeltidemann** [tensorflow/tfx#5404]
**System information**

- Have I specified the code to reproduce the issue: Yes.
- Environment in which the code is executed: Vertex AI
- TensorFlow version: 2.6.5, 2.8.2, 2.9.2
- TFX Version: 1.4.0, 1.8.0, 1.10.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output): N/A

**Describe the current behavior**

I have a custom TFX component that writes an HTML file. The custom component works fine using the LocalRunner, the DirectRunner on a Kubeflow cluster, but fails on the Vertex AI platform.

**Describe the expected behavior**

Write output file. If I remove the output Artifact (and have other input Artifacts) the component runs fine on Vertex, so it is definitely linked to the output Artifact.

**Standalone code to reproduce the issue**

```
import os
from tfx.dsl.component.experimental.annotations import OutputArtifact
from tfx.dsl.component.experimental.decorators import component
from tfx.types.standard_artifacts import ExternalArtifact
import tensorflow as tf

@component
def HTMLWriter(
    file_out: OutputArtifact[ExternalArtifact],
) -> None:

    with tf.io.gfile.GFile(os.path.join(file_out.uri, "output.html"), "w") as html:
        html.write("Hello!")

```

The error message on Vertex is: ```com.google.cloud.ai.platform.common.errors.AiPlatformException: code=INVALID_ARGUMENT, message=MetadataSchema must include a schema title that satisfies the following regex: ^[a-z][a-z0-9-_]{2,20}[.][A-Z][a-zA-Z0-9-_]{2,49}$, cause=null```

**Other logs**
When running it locally, I notice that `review-moderation:2022-10-20T11:46:23.727830:HTMLWriter:508:file_out:0` fails the regular expression written above, but even when adding `file_out.set_string_custom_property('name', 'my-html-file')` to my custom component, that does not change the long output name. I think this is what is causing the failure.

```
INFO:absl:Publishing output artifacts defaultdict(<class 'list'>, {'file_out': [Artifact(artifact: uri: "/home/sa_105350268277010201544/tfx-artefacts/tfx_pipeline_output/review-moderation/HTMLWriter/file_out/508"
custom_properties {
  key: "name"
  value {
    string_value: "review-moderation:2022-10-20T11:46:23.727830:HTMLWriter:508:file_out:0"
  }
}
custom_properties {
  key: "tfx_version"
  value {
    string_value: "1.10.0"
  }
}
```

**Comment by axeltidemann** [comment]
@singhniraj08 are you able to reproduce the issue?

**Comment by axeltidemann** [comment]
@1025KB any thoughts from your side? I don't understand how the AI Platform insists on the move to Vertex AI, when it cannot run even such a simple custom component?

![Screenshot 2022-11-15 at 10 29 21](https://user-images.githubusercontent.com/6352118/201869222-494b93f4-3087-43a8-ae96-b5abb690c357.png)

**Comment by axeltidemann** [comment]
@1025KB please let me know if I can assist in any way.

**Comment by AnuarTB** [comment]
From what I can see from my side it seems like `ExternalArtifact` is getting deprecated and causes the error. I am still investigating the cause of issue, but I can advise trying replacing `ExternalArtifact` with for example `Schema` artifact. 

Artifacts in TFX are usually just directories and are distinguished, so that other components could understand what they are fed into. So that's why you can try replacing the artifact with another one, if it is not fed into other components.

**Comment by axeltidemann** [comment]
Thanks for the suggestion. I will try it out, as I have both text and image outputs. I will report back.

**Comment by AnuarTB** [comment]
Surely, I will ask about the deprecation and replacement of `ExternalArtifact`. Will update once I get the answer.

**Comment by AnuarTB** [comment]
After discussion with the team, we came to conclusion that `ExternalArtifact` is too general, and users should declare their own artifact types.

Declaring new type shouldn't be hard, but if you have troubles, I am available for help.
