### ISSUE TITLE
Status of tf-nightly

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tfx#542]
I am running tfx from git, so I installed tf-nightly.
When I imported it, I received the following message:
```
import tfx
WARNING:tensorflow:

  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.
```

Is this anything to worry about?  Are their changes needed soon?

**Comment by robertlugg** [comment]
ok, it sounds like you are aware of the change coming in tf-nightly.  Feel free to close this issue if you are tracking the tf-nightly change elsewhere.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved.
