### ISSUE TITLE
KeyError: 'model_run' when running on premise

### ISSUE THREAD

**Issue by Daard** [tensorflow/tfx#5445]
**System information**

- Have I specified the code to reproduce the issue : Yes
- Environment in which the code is executed : Local Linux
- TensorFlow version: 2.9.2
- TFX Version:1.10.0
- Python version:3.8.10

**Current behavior**

I have deployed Kubeflow via [Charmed Kubeflow guide](https://charmhub.io/topics/kubeflow/quickstart)

Also enable gpu for mincrok8s and deployed mlmd via juju. 

```
microk8s enable gpu
juju deploy mlmd
```

I used Tensorflow with CUDA image - kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.6.0 - for Notebooks and Local Runs
And this one for KubeflowDagRunner - https://hub.docker.com/repository/docker/daard/ihw-tfx-pipeline

**Kubeflow Dag Runner creation**

```
def run():
    """Define a kubeflow pipeline."""

    metadata_config = tfx.orchestration.experimental.get_default_kubeflow_metadata_config()
    
    ## I have read this issue https://github.com/tensorflow/tfx/issues/1287, tried with and without mysql configs
    # metadata_config.mysql_db_service_host.value = 'mysql.kubeflow'
    # metadata_config.mysql_db_service_port.value = "3306"
    # metadata_config.mysql_db_name.value = "metadb"
    # metadata_config.mysql_db_user.value = "root"
    # metadata_config.mysql_db_password.value = ""
    
    metadata_config.grpc_config.grpc_service_host.value = 'metadata-grpc-service.kubeflow'
    metadata_config.grpc_config.grpc_service_port.value = '8080'

    output_filename = "{}.yaml".format(PIPELINE_NAME)
    runner_config = tfx.orchestration.experimental.KubeflowDagRunnerConfig(
        kubeflow_metadata_config=metadata_config,
        tfx_image=PIPELINE_IMAGE,
        pipeline_operator_funcs=(
            [
                onprem.mount_pvc(
                    DATA_PVC.pvc_name,
                    DATA_PVC.volume_name,
                    DATA_PVC.mount_path,
                ),
                onprem.mount_pvc(
                    TFX_PVC.pvc_name,
                    TFX_PVC.volume_name,
                    TFX_PVC.mount_path,
                )
            ]
        )
    )
  
    tfx.orchestration.experimental.KubeflowDagRunner(
        config=runner_config, 
        output_dir='./',
        output_filename=output_filename
    ).run(create_pipeline(PIPELINE_NAME, PIPELINE_ROOT, 
                          CORTEX_DATA_ROOT, TF_DATA_ROOT,
                          TRANSFORM_FILE, TRAINER_FILE,
                          SERVING_MODEL_DIR))
```

But after during the run I have faced this exception in Trainer component: 

```
INFO:absl:MetadataStore with gRPC connection initialized
WARNING:absl:ContextQuery.property_predicate is not supported.
WARNING:absl:ContextQuery.property_predicate is not supported.
WARNING:absl:ContextQuery.property_predicate is not supported.
INFO:root:Adding KFP pod name image-has-watermark-t2jjq-3690395791 to execution
INFO:absl:MetadataStore with gRPC connection initialized
INFO:root:Component Trainer is finished.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 508, in <module>
    main(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 504, in main
    _dump_ui_metadata(pipeline_node, execution_info, args.metadata_ui_path)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 347, in _dump_ui_metadata
    output_model = execution_info.output_dict[name][0]
KeyError: 'model_run'
```

I have read this [issue](https://github.com/tensorflow/tfx/issues/4501), but it is not resolved, thus I do not know what should I do.

**Comment by gaikwadrahul8** [comment]
@Daard 

Hi @Daard Can you take a look at this [article](https://neptune.ai/blog/deep-dive-into-ml-models-in-production-using-tfx-and-kubeflow) and please follow all instructions mentioned in that article. As per your project do necessary changes and see if it helps in resolving your issue? 

I would also suggest you to check compatibility matrix for Kubeflow and TFX [here](https://www.kubeflow.org/docs/components/pipelines/v1/installation/compatibility-matrix/) if possible please try to go with compatibility matrix versions and see if it works for you

If issue still persists please let us know

Thanks!

**Comment by Daard** [comment]
Hi @gaikwadrahul8. 

The [article](https://neptune.ai/blog/deep-dive-into-ml-models-in-production-using-tfx-and-kubeflow) is not relevant, cause I am working on my own infrastructure and deployed kubeflow locally via juju and microk8s ( [charmed kubeflow](https://charmed-kubeflow.io/) from official installation [page](https://www.kubeflow.org/docs/started/installing-kubeflow/). I tried this TFX [guide](https://www.tensorflow.org/tfx/guide/kubeflow) on GCP and it worked fine. 

I used this docker image kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.6.0 for Notebooks and building pipeline yaml configuration file. 

Here are my dependencies: 

```
tensorflow                      2.9.2
tensorflow-data-validation      1.10.0
tensorflow-estimator            2.9.0
tensorflow-gpu                  2.5.0
tensorflow-hub                  0.12.0
tensorflow-io-gcs-filesystem    0.27.0
tensorflow-metadata             1.10.0
tensorflow-model-analysis       0.41.1
tensorflow-serving-api          2.9.2
tensorflow-transform            1.10.1

kfp                             1.6.3
kfp-pipeline-spec               0.1.16
kfp-server-api                  1.6.0

tfx                             1.10.0
tfx-bsl                         1.10.1
```
 
 I also used the latest Kubeflow 1.6 from [Charmed] (https://charmed-kubeflow.io/docs/install). 
 
 I checked compatibility matrix  for Kubeflow and TFX, but it says that 
 'Pipelines written in any version of [TensorFlow Extended (TFX)](https://www.tensorflow.org/tfx) will execute on any version of Kubeflow Pipelines (KFP) backend. However, some UI features may not be functioning properly if the TFX and Kubeflow Pipelines Backend versions are not compatible.' 
 
 My main problem is the exception which I described in the issue above. 
 
I also noticed that component containers do not attach persistent volumes which I created via Kubeflow Web UI, and creates their owns. Thus at first I assumed that the problem with persistent volumes, I tried to create new ones inside kubeflow namespace(if you create via Kubeflow Web UI you will create inside user namespace), but during the run I got error and go back to the PVs with user namespace.

 Could it  be the issue with mlmd?

**Comment by Daard** [comment]
So I checked my custom LoaderGen container: 

This is folder content:

```
root@image-has-watermark-6m964-1211294342:/pipeline/tfx-vol/pipelines# tree
.
└── image_has_watermark
    ├── LoaderGen
    │   └── range_config
    │       └── 103
    │           └── value
    └── _wheels
        ├── tfx_user_code_Trainer-0.0+5ddb94ec81da1339424b8522e0bc56c065f635c222c37b76114632feca124afb-py3-none-any.whl
        ├── tfx_user_code_Trainer-0.0+805c902ef58e1d3b41c0aec346e801216c6b83b6a35a76a5ab4947c800a4bbda-py3-none-any.whl
        ├── tfx_user_code_Transform-0.0+5ddb94ec81da1339424b8522e0bc56c065f635c222c37b76114632feca124afb-py3-none-any.whl
        └── tfx_user_code_Transform-0.0+805c902ef58e1d3b41c0aec346e801216c6b83b6a35a76a5ab4947c800a4bbda-py3-none-any.whl
```

tfx-vol is mounted persistent volume. I tested adding to this volume during attaching it to the Notebook and it works fine: 

```
var/snap/microk8s/common/default-storage/tfx-volume$ tree 
.
└── say_hello_to_my_little_tfx.txt
```

I assume that tfx-vol directory should contains this test file inside container. I was searching for trouble with mlmd, but you can see index of range_config value is 103, so metadata base has information about artifacts, but runner could not find them inside tfx-vol. 

How I can solve this issue? Should I change the host path of folder and move it out of default-storage?

P.S. I do not know if it matters, but I set ./tfx-vol/pipelines/image_has_watermark as pipeline root inside Parameter section during run creation.

**Comment by Daard** [comment]
I found the problem. I configured volumes claims, but the mounted roots were wrong, thus artifacts and data were not shared between containers. 

```
onprem.mount_pvc(
                    DATA_PVC.pvc_name,
                    DATA_PVC.volume_name,
                    DATA_PVC.mount_path, # <- mount path was not in pipeline directory, thus it was empty
                ),
                onprem.mount_pvc(
                    TFX_PVC.pvc_name,
                    TFX_PVC.volume_name,
                    TFX_PVC.mount_path, # <- mount path was not in pipeline directory, thus it was empty
                )
```
