### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by jlopezpena** [tensorflow/tfx#5472]
Apache Beam now supports python 3.10, are there any plans to enable it for TFX soonish?
Particularly interested on the support for `ml-metadata` and `ml-pipelines-sdk`, as upgrading dependencies on those would enable to build other 3rd party tools like zenml on python 3.10

**Comment by gaikwadrahul8** [comment]
@jlopezpena 

I would like to inform you that, TFX 1.10.0 supports Python 3.7,3.8 and 3.9 currently. 3.10 will be supported in the next release ,at the moment we don't have ETA but coming soon.

Thank you!

**Comment by gaikwadrahul8** [comment]
@jlopezpena 

Closing this issue due to lack of recent activity. Please feel free to reopen the issue, if you need any further assistance or update 

Thank you!

**Comment by EdwardCuiPeacock** [comment]
It appears the most recent release TFX 1.11.0 still does not support Python 3.10. @gaikwadrahul8 By "next release", is this going to be TFX 1.12.0?

**Comment by EdwardCuiPeacock** [comment]
It appears the most recent release TFX 1.11.0 still does not support Python 3.10. @gaikwadrahul8 By "next release", is this going to be TFX 1.12.0?

**Comment by gaikwadrahul8** [comment]
Hi, @EdwardCuiPeacock 

We have released TFX 1.12.0 recently, you can refer release notes [here](https://github.com/tensorflow/tfx/releases/tag/v1.12.0) but we are facing some challenges w.r.t python 3.10 support for TFX and our team is working on it and very soon we'll get update on it and once I got the update from our release team, I'll the same here 

Thank you!

**Comment by mereldawu** [comment]
> Hi, @EdwardCuiPeacock
> 
> We have released TFX 1.12.0 recently, you can refer release notes [here](https://github.com/tensorflow/tfx/releases/tag/v1.12.0) but we are facing some challenges w.r.t python 3.10 support for TFX and our team is working on it and very soon we'll get update on it and once I got the update from our release team, I'll update the same here
> 
> Thank you!

Hi @gaikwadrahul8, do you have the update on 3.10 support? We're currently upgrading to 3.10 and an ETA would be appreciated to for our planning.

Thanks!

**Comment by singhniraj08** [comment]
@mereldawu, Python 3.10 support is on the way and getting delayed because of some packages dependency issues. Rest assured, we are working on bring the Python 3.10 support as soon as possible and will update this channel once we have an timeline. 

Thank you!

**Comment by mereldawu** [comment]
> 

Has there been any update on supporting Python 3.10?

**Comment by tanguycdls** [comment]
Hello Colab has updated its python version to Python 3.10 making it impossible to use TFX on it. Any updates on the topic ?

**Comment by rincon-santi** [comment]
Hello, experiencing same issue as @tanguycdls. Any updates?

**Comment by tanguycdls** [comment]
@singhniraj08 @gaikwadrahul8  any updates ? thanks

**Comment by singhniraj08** [comment]
@jlopezpena,

Python 3.10 support is introduced in [TFX 1.14.0 Release](https://github.com/tensorflow/tfx/releases/tag/v1.14.0). 
Please let us know if you face any issues in TFX installation. Thank you!
