### ISSUE TITLE
A more verbose response from InfraValidator

### ISSUE THREAD

**Issue by BikiniBottomsVeryOwn** [tensorflow/tfx#5485]
Original issue that led me to submit this feature request:

https://stackoverflow.com/questions/74426589/infravalidator-component-not-blessing-my-model?noredirect=1#comment131387450_74426589

Ubuntu 22.04 LTS

More verbosity from the infraValidator would be extremely helpful. I get my model is not passing, but I'm having a really hard time figuring our why. I am able to run https://www.tensorflow.org/tfx/serving/docker with no problem, so I know that my docker environment is set up correctly. My  infravalidator is configured exactly how it is in the API docs example. 

I don't know how to find out what it is exactly that's causing my model to not pass infraValidation. 

My pipeline: https://github.com/BikiniBottomsVeryOwn/tfx_pipeline

Thank you

**Comment by gaikwadrahul8** [comment]
@BikiniBottomsVeryOwn 

I have tried to reproduce the same error on google colab and I found there was some connection error with TF serving library  so I have added few lines of code and I'm able to get over that error so for your reference, I have added gist file [here](https://colab.research.google.com/gist/gaikwadrahul8/58f16f18eb8eed6cddf94d4ca85cecfd/infra-validator-component.ipynb) and unfortunately Google Colab does not support Docker and as you know to run InfraValidator TFX Pipeline Component with Local Docker (Docker should be installed in advance) should be installed so I would request you to please try to modify your code as per attached gist file and let us know, is InfraValidator TFX Pipeline Component working as expected ?

For more information about InfraValidator TFX Pipeline Component, please refer official documentation [here](https://www.tensorflow.org/tfx/guide/infra_validator)

Thank you!

**Comment by BikiniBottomsVeryOwn** [comment]
![Screenshot from 2022-11-16 01-36-07](https://user-images.githubusercontent.com/38847726/202116488-18088d56-c1c5-4037-8c77-7106d348a1fc.png)

I entered the commands into my terminal and added that if else statement to my pipeline file. Still isn't passing. 

Thank you for your help, I hope we can figure out what is going on! I would love to explore TFX in more depth!

**Comment by BikiniBottomsVeryOwn** [comment]
@gaikwadrahul8 I also tried running your collab notebood and got this error on the last cell: 


KeyError                                  Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in requires(self, extras)
   2738             try:
-> 2739                 deps.extend(dm[safe_extra(ext)])
   2740             except KeyError as e:

KeyError: 'grpc'


The above exception was the direct cause of the following exception:

UnknownExtra                              Traceback (most recent call last)

25 frames

[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in requires(self, extras)
   2741                 raise UnknownExtra(
   2742                     "%s has no such extra feature %r" % (self, ext)
-> 2743                 ) from e
   2744         return deps
   2745 

UnknownExtra: google-api-core 2.8.2 has no such extra feature 'grpc'

**Comment by BikiniBottomsVeryOwn** [comment]
I'm just kind of frustrated why it's not telling me why the model isn't getting validated.

**Comment by gaikwadrahul8** [comment]
@BikiniBottomsVeryOwn 

Apologies for the delay and I completely understand your situation, InfraValidator focuses on the compatibility between the model server binary (e.g. [TensorFlow Serving](https://www.tensorflow.org/tfx/guide/serving)) and the model to deploy. Despite the name "infra" validator, it is the user's responsibility to configure the environment correctly, and infra validator only interacts with the model server in the user-configured environment to see if it works fine. Configuring this environment correctly will ensure that infra validation passing or failing will be indicative of whether the model would be servable in the production serving environment.

`ServingSpec` is the most crucial configuration for the InfraValidator. It defines:

1. what type of model server to run
2. where to run it

If possible could you please try to use different dataset which you can download from [Kaggle](https://www.kaggle.com/datasets?fileType=csv) website and try to follow same the approach, please check still same issue persists if yes please share error log so it will be easy to do investigation why InfraValidator component is failing ?

Thank you!
