### ISSUE TITLE
AttributeError: as_feature_spec: The tutorial code doesn't work

### ISSUE THREAD

**Issue by wsuchy** [tensorflow/tfx#560]
When executing the code, here: https://github.com/tensorflow/tfx/blob/f665ff8756093afe225f948e87c7a439bf78c562/docs/tutorials/transform/census.ipynb#L646
I am getting an error:
`RAW_DATA_METADATA.schema` has no attribute / method  called `as_feature_spec()`. 
You can replace that line with `RAW_DATA_FEATURE_SPEC` but it is not the point. 

Why that method isn't avail anymore and what to use as a replacement?

Used libs:
```
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-metadata==0.14.0
tensorflow-probability==0.7.0
tensorflow-transform==0.14.0
```

**Comment by rmothukuru** [comment]
Could reproduce this error in Google Colab. 

Couldn't assign it to @mzinkevi or @charlesccychen, hence assigning to @1025KB.

**Comment by KesterTong** [comment]
See the release notes: https://github.com/tensorflow/transform/blob/master/RELEASE.md#breaking-changes-1

In most cases you can follow the examples, note that if the metadata came from TFTransformOutput.raw_metadata or transformed_metadata then you can use the corresponding methods raw_feauture_spec, raw_domains, transformed_feature_spec and transformed_domains.

You can also use schema_utils to convert schema to/from feature spec

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by zoyahav** [comment]
Note: this was fixed by @rcrowe-google in https://github.com/tensorflow/tfx/commit/7be98e99384f03b18e0be04006bac4352af06b8f
