### ISSUE TITLE
TFDV producing wrong value of Freq Top for Categorical Values

### ISSUE THREAD

**Issue by aishgrt** [tensorflow/tfx#5613]
I was trying to run TFDV generate statistics using Ai4i2020. The categorical results seem to be wrong for Product ID. There are 10,000 uniques product IDs, and no repetition. But TFDV shows me Freq Top as 10, which is not correct. 

<img width="1399" alt="Screen Shot 2022-12-28 at 2 14 48 PM" src="https://user-images.githubusercontent.com/15277794/209878649-de4cc302-912e-4afa-9793-b5c878f942a5.png">

**Comment by singhniraj08** [comment]
@aishgrt,

Please let us know which version of TFDV you are using? I tried with latest TFDV release and TFDV gives me the exact count of top categorical feature in freq top column. I also confirmed the same with pandas value_counts() method. Please find attached screenshot and [gist](https://colab.research.google.com/gist/singhniraj08/439f4a4b09569480c521cff9eb991702/tfdv_basic.ipynb) for reference. Thank you!

Setup Used:

> TF version: 2.11.0
> TFDV version: 1.12.0


<img width="943" alt="Screenshot 2022-12-29 at 1 02 25 PM" src="https://user-images.githubusercontent.com/110809167/209919187-837e3bb3-88f0-4112-81c1-45662d179c22.png">

**Comment by aishgrt** [comment]
Hi Niraj

I am using the same version. Can you please try running it using this
dataset.(attached)

**Comment by singhniraj08** [comment]
@aishgrt,

I downloaded and ran visualize_statistics() on ai4i2020 dataset(attached below) with same setup mentioned above and it works as expected. 
Please refer below screenshot. I am getting freq top as 1 for product ID feature. Kindly make sure there are no duplicates in the data and let us know if you face any issue. Thank you!


[ai4i2020.csv](https://github.com/tensorflow/tfx/files/10370443/ai4i2020.csv)

<img width="946" alt="Screenshot 2023-01-09 at 10 24 07 AM" src="https://user-images.githubusercontent.com/110809167/211243459-f39bb076-d9de-460c-8213-c4c6eef898fe.png">
