### ISSUE TITLE
TFX Template with sklearn

### ISSUE THREAD

**Issue by jaymon0703** [tensorflow/tfx#5646]
Is there a TFX template for `sklearn` similar to the penguin and taxi templates? Can anyone point me in the direction of any useful sklearn TFX tutorials?

**Comment by singhniraj08** [comment]
@jaymon0703,

[Penguin Classification Scikit-learn Example](https://github.com/tensorflow/tfx/tree/master/tfx/examples/penguin/experimental) tutorial should help your use case. Thank you!
