### ISSUE TITLE
GSoC'23

### ISSUE THREAD

**Issue by shivance** [tensorflow/tfx#5663]
What are potential projects for tfx re it's participation in GSoC'23 ?

I'm interested ! I would love to do some prior contributions as well regarding the same.

**Comment by singhniraj08** [comment]
@shivance, There are no plans from TFX side in GSoC'23 as for now. Being an open source, contributors are always welcome to suggest features, report bugs to improve our products. You can also create a PR with your contribution and help us improve the product. Kindly let us know if you have anything you would like to contribute. Thank you!
