### ISSUE TITLE
Support click >= 8

### ISSUE THREAD

**Issue by racinmat** [tensorflow/tfx#5667]
Hi, even the newest (1.12.0) version requires click<8 https://github.com/tensorflow/tfx/blob/v1.12.0/tfx/dependencies.py#L82. The click=8.0.0 is over 1 and half year old https://github.com/pallets/click/releases/tag/8.0.0 is there a reason why there is such restriction? Is something in the newer click breaking the tfx? If not, when can we expect supporting it? It makes it hard to use tfx with some newer versions of packages which require click>=8.

**Comment by singhniraj08** [comment]
@briron, 
Kindly have a look into this issue sand suggest if we can upgrade click > 8.0.0 with upcoming TFX releases. Thank you!

**Comment by lego0901** [comment]
Thanks @racinmat for your valuable request. I updated the change from #5682, and it will be included from the next release.
