### ISSUE TITLE
Coerce TFRecord Files into Multiple Parts to Avoid OOM

### ISSUE THREAD

**Issue by AlexanderLavelle** [tensorflow/tfx#5676]
If the feature is related to a specific library below, please raise an issue in
the respective repo directly:

**System information**

- TFX Version (you are using): 1.12.0
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): GCP
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.**

Thank you for submitting a TFX documentation issue. Per our GitHub policy, we
only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub and we welcome external contributions!

The TFX docs are open source! To get involved, please read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/tfx/guide/examplegen
https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/write_split.py
https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/component.py
https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/base_example_gen_executor.py

## Issue
When dealing with loading OOM multilabel datasets, you can write a custom executor to `beam.join` the read labels.

Assuming that you run a relatively vanilla Executor, you can join the labels before `dict_to_example`; however, if your join goes OOM, one would want the TFRecords created in part files. This would be expected behavior: pop the examples and write them to maintain memory usage without exceeding the total memory. 

If all of the data was already in one place to be ingested, things might be fine as you could specify span; unfortunately, if you wanted to join on spans this is not straightforward either in the codebase nor documentation as joining ExampleGen results is not covered either.

**Will this change the current API? How?**
Maybe? It should be made explicit somewhere in the documentation as well as Split or SplitConfig or wherever the code snippet belongs to specify how many TFRecords

**Who will benefit with this feature?**
Everyone with data in TFRecord format where the file is larger than 100MB would be benefitted by more actively controlled partitioned TFRecord scheme [documentation related to filesize](https://www.tensorflow.org/tutorials/load_data/tfrecord)

**Do you have a workaround or are completely blocked by this?** :
Still investigating

**Name of your Organization (Optional)**

**Any Other info.**

**Comment by singhniraj08** [comment]
@AlexanderLavelle,

You can create custom function to split large tfrecord file in multiple tfrecord files.
Ref: [Split .tfrecords file into many .tfrecords files](https://stackoverflow.com/questions/54519309/split-tfrecords-file-into-many-tfrecords-files)

You can create a `tf.data.TFRecordDataset` from your large tfrecord file and use `.batch()` and `.shard()` to break them into small tfrecord files. You can also try [this approach](https://stackoverflow.com/a/64540388/11530462), where first the dataset is batched and generator is used to split the dataset to avoid OOM errors.

Kindly let us know if this helps. Thank you!

**Comment by AlexanderLavelle** [comment]
@singhniraj08 
Unfortunately, that approach will not solve the problem of going OOM during an `ExampleGen` component. While this is a dev/test level issue (as prod autoscaling in Pipelines should remove the problem), it it makes the development more difficult if the process crashes.

**Comment by singhniraj08** [comment]
@roseayeon,

Could you please suggest something for breaking large TFRecords files into small files and avoid OOM errors while running examplegen component. Thank you!

**Comment by roseayeon** [comment]
Hi, @AlexanderLavelle 

DirectRunner (single machine) for beam might not be enough for large dataset. Please consider to use dataflow as runner for beam. Thank you!

**Comment by AlexanderLavelle** [comment]
Hello! I still believe this is important. TFX should segment `tfrecord` files, as is suggested by `data_tfrecord-00000-of-00001.gz`. This will prevent OOM when the datasets are sufficiently large and examples should be popped from the dataset in addition to trimming the tfrecord files (or at least having the option)

**Comment by pritamdodeja** [comment]
@AlexanderLavelle  I 100% agree with you in terms of how this should work in terms of memory considerations.  The one data point I'd add is from https://beam.apache.org/documentation/runners/direct/ - which mentions the following text


> The Direct Runner is not designed for production pipelines, because it’s optimized for correctness rather than performance. The Direct Runner must fit all user data in memory, whereas the Flink and Spark runners can spill data to disk if it doesn’t fit in memory. Consequently, Flink and Spark runners are able to run larger pipelines and are better suited to production workloads.

Setting up other runners locally is problematic, so this is a blocker for me too in processing large datasets which otherwise would be doable with the computing power that I have.  I am considering a few workarounds that would require me to get deeper into beam internals in order to be able to do this.

**Comment by AlexanderLavelle** [comment]
@pritamdodeja I suppose it makes "sense" with a semi-infinitely scalable VertexAI pipe. But for testing, some datasets will easily exceed what is realistic. 

You can do some working around this by doing a brief ExampleGen to get the schema out. This makes manual writing to examples much easier. Else you can find the manual form in the links following. I will try to find an example where I have a simple way to use TFX to manually write TF Records.

[TF Record Tut](https://www.tensorflow.org/tutorials/load_data/tfrecord)
[Kaggle TF Record Basics](https://www.kaggle.com/code/ryanholbrook/tfrecords-basics/notebook)

Granted for your use case -- you can contrive a way to make reasonably sized TF Records for loading, or you can just keep writing to the same file since `tf.data.Datasets` API is lazy in loading. Then, you could do `ImportExampleGen` with an `output_config`. You might need an `input_config` as well. Not incredibly well documented but you can find the resources with a deep Google.

**Comment by roseayeon** [comment]
@AlexanderLavelle 

Hi there,

We can better define and solve the issue you're facing if you can provide us with more information about the specific situation. Could you please provide us details like a minimal reproducible pipeline, the executor, and the dataset (if it's available or at least the size), or any other useful information?

Thanks
