### ISSUE TITLE
Workshop tutorial bug: unexpected keyword argument 'components'

### ISSUE THREAD

**Issue by j3soon** [tensorflow/tfx#57]
The commit 7541df5 seems to break the [TFX Developer Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/workshop) in step 2, when executing:

```shell
# Open a new terminal window, and in that window ...
source ~/tfx-env/bin/activate
airflow webserver -p 8080
```

It outputs the error message:

```
[2019-04-25 18:57:19,644] {__init__.py:416} ERROR - Failed to import: /home/j3soon/airflow/dags/taxi_pipeline_solution.py
Traceback (most recent call last):
  File "/home/j3soon/tfx-env/local/lib/python2.7/site-packages/airflow/models/__init__.py", line 413, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/home/j3soon/airflow/dags/taxi_pipeline_solution.py", line 147, in <module>
    taxi_pipeline = AirflowDAGRunner(_airflow_config).run(_create_pipeline())
  File "/home/j3soon/tfx-env/local/lib/python2.7/site-packages/tfx/orchestration/airflow/airflow_runner.py", line 45, in run
    airflow_dag = airflow_pipeline.AirflowPipeline(**self._config)
TypeError: __init__() got an unexpected keyword argument 'components'
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
```

My partner following the tutorial last week and it works perfectly. However, when I'm trying to follow the tutorial again on the same machine yesterday, the error occurs.

After replacing the file `/home/j3soon/airflow/dags/taxi_pipeline_solution.py` with the old file, the error is resolved.

**Comment by gowtham-kp** [comment]
Thanks for reporting this. I tried at my end and found the same error with the latest tutorial version. We will look into it.

**Comment by ruoyu90** [comment]
This error is caused by [this](https://github.com/tensorflow/tfx/commit/7541df5f3e4dd9b2237b3105b0784f640249efc4) commit which added an extra argument in the `__init__()` function in `Pipeline`. However, the tutorial still pins to our first release version which is not compatible. We will have a PR to fix this soon.
