### ISSUE TITLE
Impossible to get post transform statistics by split train/eva

### ISSUE THREAD

**Issue by ykacer** [tensorflow/tfx#5713]
Hi, the bug is related to tfx and more precisely the `tfx.components.Transform` component.

**System information**

- Have I specified the code to reproduce the issue (Yes, No):

Yes, just run the public colab : https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb

- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows)

Interactive Notebook (see link above)

- TensorFlow version:
 
2.11.0

- TFX Version: 
 
1.12.0

- Python version:
 
3.8.0

**Describe the current behavior**

After running the public colab notebook pipeline in interactive mode, I go inside the `tfx.components.Transform` subfolder artifacts dedicated to post transform statistics  `/tmp/.../Transform/post_transform_stats/5` and i have just one `FeaturesStats.pb` inside, but not subfolders `Split-train` and `Split-eval` with a `FeaturesStats.pb` inside each.

However, I have the subfolders inside artifacts dedicated to transformed examples (`/tmp/.../Transform/transformed_examples/5/`).

**Describe the expected behavior**

Expected `Split-train` and `Split-eval` subfolders for post transform stats artifacts subfolder

**Standalone code to reproduce the issue**

See the public colab notebook link above

sorry for posting it here, but I have already posted an issue inside dedicated stackoverflow page, but without feedbacks.. (https://stackoverflow.com/questions/75373346/impossible-to-get-post-transform-statistics-by-split)

Thanks

**Comment by singhniraj08** [comment]
@ykacer,

Thank you for brining this up. I was able to replicate this issue by running the example notebook. Team will work on this issue and update this thread. Thank you!

<img width="1512" alt="transform_error" src="https://user-images.githubusercontent.com/110809167/218446070-a5c89147-15d1-4ed6-bb4e-931b447753da.png">

**Comment by zoyahav** [comment]
Yes this is expected. StatisticsGen in Transform is currently working on the entire "transform" dataset regardless of split/span.
Technically there's a way to specify differently:
https://github.com/tensorflow/tfx/blob/2735046d6e1d0898ff6174e50f00ee3338068150/tfx/components/transform/executor.py#L1503
Controlled by the `PER_SET_STATS_OUTPUT_PATHS_LABEL` input, though I'm not sure if it's currently possible for TFX users to specify.
