### ISSUE TITLE
Trainer component fails with DATA_LOSS error

### ISSUE THREAD

**Issue by IzakMaraisTAL** [tensorflow/tfx#5739]
**System information**

- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed : Kubeflow pipeline and Google Cloud AI Platform 
- TensorFlow version: 2.11.0
- TFX Version: 1.12.0
- Python version: 3.7
- Python dependencies (Dockerfile):
```Dockerfile
FROM tensorflow/tfx:1.12.0
WORKDIR /pipeline

RUN pip3 install --upgrade --no-cache-dir pip \
    tensorflow-text==2.11.0 \
    tensorflow-recommenders==0.7.2 \
    scann==1.2.9
```
**Describe the current behavior**

On a large dataset, the trainer component fails with an error:
```
E tensorflow/tsl/lib/io/record_reader.cc:50] Unsupported compression_type:INVALID_MIXED_COMPRESSION_TYPES. No compression will be used.
data = next(iterator)
Node: 'IteratorGetNext'
 File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 1803, in step_function
  (0) DATA_LOSS:  corrupted record at 0 (Is this even a TFRecord file?)
```

**Describe the expected behavior**

It should work, or give a more descriptive error indicating which file it is processing. 

The trainer works on smaller dataset but fails on a large one. The dataset is the output of the Transform component (run on Dataflow). 

The dataset consists of about 240 gzipped TFRecord files on GCS. The average file size is 2.3GB and contains 17k examples.  

I have written a script that opens, parses and counts the examples in each record file. There were no failures.

I have run the ImportExampleGen on each of the files, re-splitting it. There were no failures. 

**Other info / logs**

Could you please advise how to debug it further? It would be great if I get more log info about which file is causing the problem. 

Here is the full stack trace. 
[downloaded-logs-20230217-152058.json.zip](https://github.com/tensorflow/tfx/files/10767119/downloaded-logs-20230217-152058.json.zip)

**Comment by singhniraj08** [comment]
@IzakMaraisTAL,

Instead of gzipped TFRecord files, Can you please extract them and provide TFRecord files to the pipeline and see if that works. You can try removing the compression gzip during the writing TFRecord process.

If possible, please create a basic pipeline to replicate the error, and share with us the pipeline code for debugging. 
Thank you!

**Comment by IzakMaraisTAL** [comment]
Thanks for the feedback. After struggling with this for days, it is finally working. 

I suspect the `beam-temp-transformed-examples...` folders might have been causing the problem. The only difference I can see between when it was failing and now (when it is working) is that I have manually deleted these folders from GCS. These folders also failed my manual parsing script. 

![image](https://user-images.githubusercontent.com/103260585/220373353-eda4471e-cf05-4a16-9bb0-ce8b8f1e7d44.png)
