### ISSUE TITLE
Windows Support 

### ISSUE THREAD

**Issue by vaishnavi-sonawane-itp** [tensorflow/tfx#5740]
If the feature is related to a specific library below, please raise an issue in
the respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- TFX Version (you are using):
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): Windows
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.** When running a tfx pipeline in Windows OS, errors related to path resolution and file generation are raised. The Linux backbone is the cause.

**Will this change the current API? How?**

**Who will benefit with this feature?** Ease of setup for students & developers using Windows OS

**Do you have a workaround or are completely blocked by this?** : For now, I am working on a Windows Subsytem for Linux setup with VSCode

**Name of your Organization (Optional)**

**Any Other info.**

**Comment by singhniraj08** [comment]
@vaishnavi-sonawane-itp,

As per [similar issue](https://github.com/tensorflow/tfx/issues/950#issuecomment-970793241), there is currently no plans to support windows.
Suggested way to run TFX on windows is by creating virtual Python environment inside your WSL instance and install TFX. Please refer [solution from similar issue](https://github.com/tensorflow/tfx/issues/5665#issuecomment-1401637945) to setup TF on windows WSL.

Thank you!
