### ISSUE TITLE
How about loosening artifact type_name rule for KubeflowV2 or allowing to register type_name to classpath.

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tfx#5744]
If the feature is related to a specific library below, please raise an issue in
the respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- TFX Version (you are using): 1.12.0
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): Vertex AI
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I can pass custom artifacts for the Vertex AI pipeline following this naming rule.
https://github.com/tensorflow/tfx/blob/933441ed6e4b754317391cef52062cd5766b943f/tfx/orchestration/kubeflow/v2/compiler_utils.py#L46-L49
And at the beginning of the component, the artifact class is imported as follows:
https://github.com/tensorflow/tfx/blob/933441ed6e4b754317391cef52062cd5766b943f/tfx/orchestration/kubeflow/v2/container/kubeflow_v2_entrypoint_utils.py#L248-L250

However, due to the naming convention, it may be necessary to place the artifact class in the root of the package or create an alias for the class. Since in-house Python library shares common [namespaces](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) in my team, it can be tricky to place the class in the root of the package.

**Will this change the current API? How?**

I think this can be achived in two ways.
1. Loosen the artifact schema title. It allows for the artifact class to put in a subpackage.
2. Support registering schema titles to classpath maps.
    https://github.com/tensorflow/tfx/blob/933441ed6e4b754317391cef52062cd5766b943f/tfx/orchestration/kubeflow/v2/compiler_utils.py#L65-L68

**Who will benefit with this feature?**

The people who want to use custom artifacts in Vertex AI. I'm sure that this feature makes custom artifacts more flexible.

**Do you have a workaround or are completely blocked by this?** :

Not blocked by this.

**Name of your Organization (Optional)**

**Any Other info.**

**Comment by singhniraj08** [comment]
@jeongukjae, Since you are willing to contribute this feature, requesting you to create a PR and share us on this thread and we can take it forward. Thank you for contributing!

**Comment by jeongukjae** [comment]
I'm gonna work on this issue soon :)

**Comment by jeongukjae** [comment]
resolved at https://github.com/tensorflow/tfx/commit/30b2155f4b13f548b1aa9ff8802c41b372f09c67
