### ISSUE TITLE
Doc example url broken

### ISSUE THREAD

**Issue by LuigiCerone** [tensorflow/tfx#5752]
Hello everyone,

the link inside this [README](https://github.com/tensorflow/tfx/blob/master/tfx/benchmarks/datasets/chicago_taxi/README.md) pointing to [taxi_pipeline_kubeflow_gcp.py](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_gcp.py) is broken and so is the one in [this kubeflow](https://github.com/kubeflow/pipelines/blob/master/samples/core/tfx-oss/TFX%20Example.ipynb) example notebook.

**Comment by singhniraj08** [comment]
@LuigiCerone,

Please refer to [taxi_pipeline_kubeflow_gcp_bqml.py](https://github.com/tensorflow/tfx/blob/master/tfx/examples/bigquery_ml/taxi_pipeline_kubeflow_gcp_bqml.py) for the TFX pipeline example with Chicago taxi bigquery dataset. Also PR #5753 is created to fix the README file to point to right example.

I couldn't find anything broken in the second TFX example posted, Please recheck and let us know if the broken link issue persists in second example. Thank you!

**Comment by singhniraj08** [comment]
@LuigiCerone,
Since the PR #5753 is merged, requesting you to close this issue. Thank you!
