### ISSUE TITLE
Optional output artifact support

### ISSUE THREAD

**Issue by jccarles** [tensorflow/tfx#5813]
TFX does not handle optional output artifact.

I am unsure of the mechanics at stake nor why it is needed exactly but I believe that in the [launcher](https://github.com/tensorflow/tfx/blob/41fb383262c87fe01e758c1423b8262bab7adc3a/tfx/orchestration/portable/launcher.py#L352)) `output_artifacts = self._output_resolver.generate_output_artifacts(execution.id)`, when we generate output artifact, if we could only generate those which are not optional, it would allow support for optional output. Because currently even if output is optional, we instantiate output artifacts in this function.

So if we can have the information in this [function](https://github.com/tensorflow/tfx/blob/41fb383262c87fe01e758c1423b8262bab7adc3a/tfx/orchestration/portable/outputs_utils.py#L253) whether an artefact is optional or not, it would prevent us from adding it to the output_dict all the time.

Curious to know why we need to generate the output artifacts dict, then update it with the driver output ? And if this would be acceptable / the way to get optional outputs ?

My use case is a component which based on its input decide if it outputs one or two artifact. We manage to do that by writing a custom driver. But even when we want to output only one artifact, `generate_output_resolver` function adds the other one.

I can provide a skeleton of code if needed to make my example clearer.

**Comment by singhniraj08** [comment]
@jccarles,

Output artifacts are generated for tracking the inputs and outputs of all components/steps in an ML workflow and their lineage allows ML platforms to enable [several important features](https://www.tensorflow.org/tfx/guide/mlmd#mlmd_functionality).
When a pipeline is executed, events record every artifact that was used by the execution, and every artifact that was produced. These records allow for lineage tracking throughout a workflow. By looking at all events, MLMD knows what executions happened and what artifacts were created as a result. MLMD can then recurse back from any artifact to all of its upstream inputs.

Can you try using convenient functions available in [artifact_utils](https://github.com/tensorflow/tfx/blob/41823f91dbdcb93195225a538968a80ba4bb1f55/tfx/types/artifact_utils.py) class in your custom executor code, to fetch and output particular artifact instance as shown [here](https://www.tensorflow.org/tfx/guide/custom_component#executor)
Thank you!
