### ISSUE TITLE
Pipeline fails with tf.keras.Model subclass

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/tfx#584]
Running a pipeline throws a `KeyError: user_module while running 'Run[Transform]'` when using a custom tf.Estimator whose `model_fn` references a `tf.keras.Model` subclass. This bug was first tracked by https://github.com/tensorflow/tfx/issues/500 before I figured out what the root cause was. Replacing the subclass with a direct call to tf.keras.Sequential with the same layers works just fine, however, this is only a stopgap solution since more complicated models might require subclassing or the keras functional API (which I will test).

**Comment by ruoyu90** [comment]
@JakeTheWise IIUC you have a custom `tf.keras.Model` subclass and want to use that in your trainer module? If so, where is the definition of the subclass?

**Comment by JakeTheWise** [comment]
I define my custom class in my pipeline utils file, where preprocessing_fn, trainer_fn etc lives too. The class is instantiated in `model_fn`, which in turn is called in `trainer_fn`

**Comment by ruoyu90** [comment]
@JakeTheWise can you share the code (or skeleton of the code)? It'll be easier to debug.

**Comment by neuromage** [comment]
@ruoyu90 The skeleton is in #500, I asked for it as well :-)

**Comment by ruoyu90** [comment]
Thanks @neuromage ! 
>```
>     estimator = tf.estimator.Estimator(
>         model_fn, params=hparams, config=config)
> ```
@JakeTheWise can you try to use `tf.keras.estimator.model_to_estimator` to convert a keras model to estimator?

**Comment by JakeTheWise** [comment]
Yep I'll try that, thanks.
