### ISSUE TITLE
Foundation to allow BigQueryExampleGen to correctly take temporary location

### ISSUE THREAD

**Issue by AlexanderLavelle** [tensorflow/tfx#5859]
**System information**

- TFX Version (you are using): master
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): gcp / Linux
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In the current state, `BigQueryExampleGen` has a few issues for non-standard use. [This pull request](https://github.com/tensorflow/tfx/pull/5858) is the first, and lower touch, of two to allow options to propagate into the `Executor`.

The greatest of these issues is when you are a tenant and therefore do not have access to BQ Dataset at the "project" administrative level. **You need to specify the table to write to. This cannot be done in `beam_pipeline_args` anymore, as far as I can tell**.

See [this issue (3754)](https://github.com/tensorflow/tfx/issues/3754) for rationale on why this was not previously changed. 

None of the following work as independent solutions within the `beam_pipeline_args`:
`f'--project={PROJECT}.{TABLE}'` 
`f'--project={PROJECT}:{TABLE}'` 
`f'--project={PROJECT}:{TABLE}.{TEMP_NAME}'` 
`f'--temp-location={os.path.join(BUCKET, 'tmp')}'`

The TRUE issue to this is the `utils.ReadFromBigQuery` which could _potentially_ take other commands, but the BEST way to initiate this is to allow the ability to pass custom pieces into the pipeline. From the `custom_config` perspective, you could later pass along things that might want to be retrieved, as in the `Parquet Executor` which is part of the `FileBasedExampleGen`. 

This commit aligns the other pieces with the notation in FileBasedExampleGen.

**Will this change the current API? How?**

Most users will not notice the difference, unless those users are familiar enough with the TFX ecosystem to want to do things that are in line with existing pieces but just slightly different. However, this opens the opportunity for people to **better utilize custom Executors when needed / desired**.

**Who will benefit with this feature?**

Users in industrial settings who navigate tenancy permissions

**Do you have a workaround or are completely blocked by this?** :

This is the workaround

**Name of your Organization (Optional)**

**Any Other info.**

**Comment by singhniraj08** [comment]
@AlexanderLavelle,

I can see a PR is already submitted by you to fix the identified issue. Once PR is approved and merged, we will update this thread. Thank you for your contribution!

**Comment by lego0901** [comment]
This is COOL! It has a great potential on the custom executors! Thanks a lot for your contribution.

But I found some internal code references of `utils.ReadFromBigQuery`, so we cannot easily delete the function definition.

How is about to introduce new `custom_configs` parameter on the `utils.ReadFromBigQuery` so that other code references can take the benefit you suggested?

**Comment by AlexanderLavelle** [comment]
@lego0901 It seems like the other place this comes up is `BigQueryToElwcExampleGen` -- that component will have the same fundamental problem if the end-user is attempting to `ReadFromBigQuery` inside of a tenancy, as per the same rationale explained above. 

However, the `BigQueryToElwcExampleGen` already has some functionality for inserting what ends up being its `custom_config`, and I am not really that familiar with that piece of code or who uses it. The code also differs in execution pattern -- [lines 72, 73, and 78](https://github.com/tensorflow/tfx/blob/82b8284a3a639192454a3df6b0f8de12feb5bd91/tfx/extensions/google_cloud_big_query/experimental/elwc_example_gen/component/component.py#L72-L73). I think in this case, the end user would potentially code a custom executor as well.

Granted, the point of the first two commits on this branch are meant to enable any sort of custom configuration going into BQEG, a functionality it did not previously have, so I have modified the call in BQTEEG executor to not call the `utils.ReadFromBigQuery` which is sort of just a re-alias. As mentioned just above, the user of the BQTEEG would be probably want to provide a custom executor as well, which an advanced user could provide using subclassing.

Anyway, I suppose a more important question regarding whether or not to maintain the `utils.ReadFromBigQuery` comes down to the TFX team's anticipation of the need for additional components for dealing with BigQuery? If there will be additional work in this area, then perhaps it does make sense to add the new argument to the utils function.

I'll push what I have and then await your input

**Comment by singhniraj08** [comment]
@AlexanderLavelle,

I see #5858 and #5860 merged which address this issue. Please let us know if this issue can be closed. Thank you!

**Comment by AlexanderLavelle** [comment]
@singhniraj08 thank you again!
