### ISSUE TITLE
Pass custom_config with keys that are args to beam's ReadFromBigQuery

### ISSUE THREAD

**Issue by AlexanderLavelle** [tensorflow/tfx#5861]
**System information**

- TFX Version (you are using): master
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): gcp / Linux
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, `BigQueryExampleGen's` aspect where it finally runs `ReadFromBigQuery` affects tenants by not allowing temporary locations, [as described here](https://github.com/tensorflow/tfx/issues/5859). Once that issue is solved, the next step, which is much more hands-on, is to manipulate the codebase away from allowing a function in `utils` that is redundant and/or does not allow the propagation of configurations. 

This code attempts to solve this issue in a permanent and clear way by allowing a passthrough using the `custom_config`, as is seen in other TFX components. [Here is the PR](https://github.com/tensorflow/tfx/pull/5860)

**Will this change the current API? How?**

Tenancy users will be able to redirect their `BigQueryExampleGen` temporary tables, enabling the use of this piece. It also enables even more flexible `Executor`s in the future.

**Who will benefit with this feature?**

Users who need to do custom logic as part of their attempts to build examples from `BigQuery`

**Do you have a workaround or are completely blocked by this?** :

This is the workaround

**Name of your Organization (Optional)**

**Any Other info.**

**Comment by AlexanderLavelle** [comment]
One comment / concern / issue that I do have is how to handle if no custom_config is passed. In that case, I have temporarily coded in [this option flow](https://github.com/AlexanderLavelle/tfx/blob/0e4080ffe0523f5ea47ec8cf16c6134b7c3c0d98/tfx/extensions/google_cloud_big_query/example_gen/executor.py#L71-L74), but I think due to `json` storage, this should return an empty dictionary, which should hopefully still be okay to unpack in this manner.

**Comment by lego0901** [comment]
Oh, I lately see your comment. You are right. It has a hole on that case. This is actually handled by

```python
  big_query_custom_config = (
      json.loads(exec_properties['custom_config'])
      if 'custom_config' in exec_properties
      else None
  )
```

I am having internal code review and it is about to be merged.

**Comment by singhniraj08** [comment]
@AlexanderLavelle,

I see #5858 and #5860 merged which address this issue. Please let us know if this issue can be closed. Thank you!

**Comment by AlexanderLavelle** [comment]
@singhniraj08 yes thank you!
