### ISSUE TITLE
Support on multiple input datasets for trainer component

### ISSUE THREAD

**Issue by xzhang95** [tensorflow/tfx#5863]
We are trying to build a model that takes in two different input dataset from multiple sources. Hence we want a way to pass in output samples from two separate transform components. 
A brief pseudo sample of what we want to implement in trainer looks like [this](https://gist.github.com/xzhang95/4a7b22aea2bf47eeaf8c6a4faf876dba).
I noticed the [fn_args generated for trainer components](https://github.com/tensorflow/tfx/blob/98002d6aa7e831f7dc4b8d5fbdcb03fd37af6953/tfx/components/trainer/fn_args_utils.py#L141) seems can only parsed from one specific splits on one component. 
Is there any possibilities of supporting multiple input sources for trainer? Or is there any other recommended ways to achieve this?

**Comment by rcrowe-google** [comment]
I can think of at least two ways to approach this.

1. You could feed both datasets into one Transform component and create one Transform graph to be prepended to your model.  You will probably need to subclass and extend the current Transform component to accept an additional input channel.
2. You could use two Transform components, and produce two Transform graphs, which would be prepended to two different input layers in your model, which both feed into your first hidden layer.  You will probably need to subclass and extend the current Trainer component to accept an additional input channel.
