### ISSUE TITLE
How to run custom data validation using tfx.components.ExampleValidator

### ISSUE THREAD

**Issue by danilyef** [tensorflow/tfx#5934]
## Description of issue :
I want to run custom validation for the specific features using tfx.components.ExampleValidator. Specificaly, I want to check if length of a string feature "subject" is > 0. 

```
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext

example_validator = tfx.components.ExampleValidator(
    statistics=statistics_gen.outputs['statistics'],  # Use the output statistics from StatisticsGen
    schema=schema_gen.outputs['schema'],  # Use the output schema from SchemaGen
    custom_validation_config=custom_validation_config_pb2(
            #perform check
        )
)

context.run(example_validator, enable_cache=True)
```
    

On both pages I didn't find any detailed example on how to perform it:

- https://www.tensorflow.org/tfx/guide/exampleval
- https://www.tensorflow.org/tfx/api_docs/python/tfx/v1/components/ExampleValidator

there is also github page of  CustomValidationConfig:

-  https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/anomalies/proto/custom_validation_config.proto

but it's not very clear for me, becuase I am relative new to tensorflow.

- tensorflow version: 2.10
- tensorflow extended version: 1.11

**Comment by singhniraj08** [comment]
@danilyef,

You can provide [this example](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/anomalies/proto/custom_validation_config.proto#L38-L50) custom validation proto to apply custom validation for specific feature in `tfx.components.ExampleValidator` component by passing it using `custom_validation_config` args.
For anomaly types detected by TFDV, schema and statistics fields used, you can refer [TensorFlow Data Validation Anomalies Reference](https://www.tensorflow.org/tfx/data_validation/anomalies).

To check length of string feature, can you try using `sql_expression: 'feature.string_stats.unique > 0'` in custom validation config and let us know if that works for you. Thank you!
