### ISSUE TITLE
Upgrade cuda and cudnn versions in Docker image?

### ISSUE THREAD

**Issue by deep-diver** [tensorflow/tfx#5966]
From TensorFlow 2.12, the recommended versions of cuda and cudnn are `11.8` and `8.6`. However, it seems that the `latest` tfx docker image only supports `11.3` and `8.2`. I think this legacy versions led some significant problems when I used KerasNLP as follows(in `Trainer` component):
```
Node: 'StatefulPartitionedCall'
RET_CHECK failure (tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:618) dnn != nullptr 
	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_train_function_241897]
```

Any plan to update them? or any guides for people to update them?

**Comment by singhniraj08** [comment]
@deep-diver, Thank you for brining this up. We will discuss this internally and update this thread.

**Comment by singhniraj08** [comment]
@deep-diver,

We internally discussed this issue and this is pending because of Python 3.10 support which is in progress. The image will be upgraded with updated dependencies once python 3.10 support is introduced. 

We will update this thread once python 3.10 support is introduced and CUDA, CUDNN dependencies are updated. Thank you.

**Comment by deep-diver** [comment]
@singhniraj08 thanks for the updates 

Can you share the ETA roughly?

**Comment by briron** [comment]
TFX 1.14.0 has been released, and it is now supporting Python 3.10.

**Comment by deep-diver** [comment]
@briron thanks!
How about cuda depencies?

**Comment by singhniraj08** [comment]
@deep-diver,

[Latest TFX docker image](https://hub.docker.com/layers/tensorflow/tfx/latest/images/sha256-4336f1c78d1f21732e9cb386d98493a1be2e1549e592d0936661421adfe1f105?context=explore) supports CUDA 11.8 and CUDNN 8.9. Please try the latest docker image and let us know if you face any issues. Thank you!
