### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by wsuchy** [tensorflow/tfx#597]
I think you might be aware of that, but it seems worth mentioning that Python 2 is going EOL in less than 4 months from now (Jan 1, 2020; https://pythonclock.org/). 
Do you plan to switch by then to Python 3, or keep using the old one even though it won't be maintained anymore?

**Comment by ruoyu90** [comment]
Hi @wsuchy , TFX already supports Python 3 now (with the upcoming 0.14 release, we will have better support for Python 3.6+).

**Comment by wsuchy** [comment]
Hi, I am glad to hear that. Actually I saw in many code examples strict checking for Python 2, e.g. here: https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi_pipeline, but the readme might have not been updated yet.

**Comment by ruoyu90** [comment]
@wsuchy Ah that is an outdated documentation. Will fix them soon.
