### ISSUE TITLE
include supported Python version >= 3.10

### ISSUE THREAD

**Issue by deep-diver** [tensorflow/tfx#5970]
In the past few months, I have heavily used Google Colab to verify TFX pipeline w/ Interactive Context. However, since Google Colab upgraded its default Python version to 3.10, it is impossible to experiment with TFX. Is there any plan to support higher versions of Python in near future?

**Comment by singhniraj08** [comment]
@deep-diver,

We are working on upgrading Python 3.10 for all TFX packages. And meanwhile you can follow instructions given in [TFX tutorials](https://www.tensorflow.org/tfx/tutorials) to install TFX in current colab setup. Please let us know if yo face any issues while TFX installation in Colab. Thank you!
