### ISSUE TITLE
loading a keras model inside preprocessing_fn during Transform

### ISSUE THREAD

**Issue by ykacer** [tensorflow/tfx#5974]
**System information**

- Have I specified the code to reproduce the issue (Yes, No):
Yes
- Environment in which the code is executed
Kubeflow (Google Cloud/GKE)

- TensorFlow version:
2.11.0
- TFX Version:
1.12.0
- Python version:
3.8

Hi,

I would like to load a homemade compiled Keras SavedModel during the `tfx.components.Transform` execution in order to compute and output some embeddings applied to text inputs.
(NB: Actually, the model i try to load is a model saved by the `Trainer` component of a previous successful tfx pipeline.)
The main constraint is that the path to the model is provided only inside  `preprocessing_fn` through `custom_config`, so i know the model path only inside `preprocessing_fn`.

First of all, is it a good practise to do so? Does `tfx.components.Transform` fit with such pattern?

Here is a simplified version of the code I made, note that I lift the model loading inside the context `tf.init_scope()` :

```
def preprocessing_fn(inputs, custom_config):

    with tf.init_scope():
        loaded_model = tf.keras.models.load_model(custom_config['path_to_model'])
   outputs['embeddings'] = loaded_model(inputs['text'])

   return outputs
```

Executing the code above, i got the common error during model loading, saying:
```
`ValueError: tf.function only supports singleton tf.Variables created on the first call. Make sure the tf.Variable is only created once or created outside tf.function. See https://www.tensorflow.org/guide/function#creating_tfvariables for more information
```

The tensorflow guide page show how to avoid creating variables at each call of a `tf.function`, but i did not figure out how to apply it in the context of `preprocessing_fn()` called during `tfx.components.Transform` execution.

Thanks a lot for any comment or suggestion that could help me.

Regards

**Comment by singhniraj08** [comment]
@ykacer,

`tfx.components.Transform` cannot take in TensorFlow custom model directly into the preprocessing_fn for the preprocessing. The `preprocessing_fn()` function currently accepts TensorFlow ops and TensorFlow Transform analyzers to transform the data and builds transformations into the TensorFlow graph. 

Can you try loading your preprocessing model in Trainer component to include it in model graph as shown in [TFX Raking example](https://www.tensorflow.org/recommenders/examples/ranking_tfx#write_model_training_code). Please let us know if this helps your use-case.

Thank you!

**Comment by ykacer** [comment]
@singhniraj08

Thanks for your answer, that's what i feared : i'm not doing things properly. The link you sent me is very clear on how to perform embedding preprocessing in a proper way.
I close the ticket.

Thanks
