### ISSUE TITLE
Docker image 0.14.0 missing

### ISSUE THREAD

**Issue by valeriano-manassero** [tensorflow/tfx#603]
After release of `0.14.0` version, pipelines not specifying the image version will fail due to missing image with this tag in dockerhub repo (atm there's only `0.14.0rc1` available).

**Comment by ruoyu90** [comment]
Hi @valeriano-manassero thanks for the patience! it's [available](https://hub.docker.com/layers/tensorflow/tfx/0.14.0/images/sha256-b608a71f505376bd0091c759cc171b874a4bc42cb2f0a5102a22d80411603095) now
