### ISSUE TITLE
Getting error with building Docker image from 'tfx/tools/docker/build_docker_image.sh'

### ISSUE THREAD

**Issue by AbdirayimovS** [tensorflow/tfx#6152]
Dear friends,
I want to build a docker image with tfx.
I copied the **build_docker_image.sh** file and **Dockerfile** into my local machine. 
Environment in which the code is executed: MacOS

**Describe the current behavior**
I have changes direction of Dockerfile in the build_docker_image.sh file: 
`docker build --target wheel-builder\
  -t ${wheel_builder_tag} \
  -f _tfx/tools/docker/${DOCKER_FILE}_ \ -> **${DOCKER_FILE}**
  --build-arg TFX_DEPENDENCY_SELECTOR=${TFX_DEPENDENCY_SELECTOR} \
  . "$@"`

# Output
`Dockerfile:63
--------------------
  61 |     
  62 |     # Build stage to extend DLVM image.
  63 | >>> FROM ${BASE_IMAGE} as install
  64 |     
  65 |     # Additional Python packages which will be installed.
--------------------
ERROR: failed to solve: base name (${BASE_IMAGE}) should not be blank`

Looking forward to hearing from you!

Sincerely,
Sardor

**Comment by singhniraj08** [comment]
@AbdirayimovS,

It looks like the `build_docker_image.sh` script is broken. I tried to patch the Dockerfile by explicitly providing the `BASE_IMAGE` and `BEAM_VERSION` as shown below.
```
# Base image for the final image. Required.
ARG BASE_IMAGE="gcr.io/deeplearning-platform-release/tf2-gpu.2-12.py310:latest"
# Apache beam version to get Beam binaries.
ARG BEAM_VERSION="2.40.0"
```
This patch resolves this error but the build fails with conflicting dependencies of pyarrow package. Let us work on this issue and we will update this thread once we resolve it. Thank you for bringing this up to our attention.

**Comment by singhniraj08** [comment]
@AbdirayimovS,

We need to pass certain flags while running the script to build TFX image. I am able to build the image successfully with this command.  Please try the below steps and let us know if you face any issues. Thank you!

Clone the TFX repository and change the directory to tfx and run the script with flags as shown below.

```
git clone https://github.com/tensorflow/tfx.git
cd tfx
./tfx/tools/docker/build_docker_image.sh --build-arg TFX_DEPENDENCY_SELECTOR=NIGHTLY --build-arg BASE_IMAGE=gcr.io/deeplearning-platform-release/tf2-gpu.2-13.py310 --build-arg BEAM_VERSION=2.49.0 --build-arg ADDITIONAL_PACKAGES=tensorflow==2.13.0
```

Ref: screenshot
![image](https://github.com/tensorflow/tfx/assets/110809167/04e6b965-26bc-4926-9711-8151c6532702)
![image](https://github.com/tensorflow/tfx/assets/110809167/4187e8c9-8f6b-461a-b052-bdc5b83fde89)
