### ISSUE TITLE
Unable to install tfx: metadata-generation-failed

### ISSUE THREAD

**Issue by cuebelhoer** [tensorflow/tfx#6158]
- Python3 --version:
Python 3.8.17
- pip list: 

Package    Version
---------- -------
pip        23.2.1
setuptools 56.0.0

Hi all, 
I want to contribute to OSS TFX and am following the steps in here: https://github.com/tensorflow/tfx/blob/master/CONTRIBUTING.md#testing-conventions to install TFX on my local machine within a virtual env. 

Running the following cmds: 

export TFX_DEPENDENCY_SELECTOR=NIGHTLY
pip install -e . --extra-index-url https://pypi-nightly.tensorflow.org/simple

results in the following error message: 

Looking in indexes: https://pypi.org/simple, https://pypi-nightly.tensorflow.org/simple
Obtaining file:///Users/cuebelhoer/VSCode%20Projects%20%28Workspace%29/tfx
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]

<full error message>

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
 

[full_error_message.txt](https://github.com/tensorflow/tfx/files/12321490/full_error_message.txt)

**Comment by singhniraj08** [comment]
@cuebelhoer,

This issue looks like you are trying to install TFX on Mac OS. As discussed internally, we are already working on supporting Mac M1 and meanwhile please use VM based options for installing TFX. 

#5804 feature is already there for Mac M1 support tracking, requesting you to close this issue and follow and +1 similar issue for updates. Thank you!

**Comment by singhniraj08** [comment]
@cuebelhoer,

Below are the steps to successfully setup TFX environment for contributing to TFX following [CONTRIBUTUNG.MD](https://github.com/tensorflow/tfx/blob/master/CONTRIBUTING.md).
1. Install Python 3.9 (Python 3.10 support is work-in progress)
2. Install Bazel following this [guide](https://bazel.build/install/ubuntu)
3. Clone TFX repository from github and change directory to tfx by running 
```
git clone https://github.com/tensorflow/tfx.git
cd tfx
```
4. install TFX source code in a virtual environment in editable (-e) mode, which will pick up your local changes immediately
```
export TFX_DEPENDENCY_SELECTOR=NIGHTLY
pip install -e . --extra-index-url https://pypi-nightly.tensorflow.org/simple
```
5. install additional packages to run all end-to-end tests
```
pip install -e .[kfp] --extra-index-url https://pypi-nightly.tensorflow.org/simple
```

Please let us know if you face any issues. Thank you!
