### ISSUE TITLE
Simplify package names

### ISSUE THREAD

**Issue by ageron** [tensorflow/tfx#618]
I love TFX, but the package names are unnecessarily long. For example:

```python
from tfx.components.evaluator.component import Evaluator
```

Could just be:

```python
from tfx.components import Evaluator
```

Why repeat "evaluator" and "component" twice?

The same goes for all other components of course:

```python
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
from tfx.components.example_validator.component import ExampleValidator
from tfx.components.model_validator.component import ModelValidator
from tfx.components.pusher.component import Pusher
from tfx.components.schema_gen.component import SchemaGen
from tfx.components.statistics_gen.component import StatisticsGen
from tfx.components.trainer.component import Trainer
from tfx.components.transform.component import Transform
```

could just be:

```python
from tfx.components import CsvExampleGen
from tfx.components import ExampleValidator
from tfx.components import ModelValidator
from tfx.components import Pusher
from tfx.components import SchemaGen
from tfx.components import StatisticsGen
from tfx.components import Trainer
from tfx.components import Transform
```

At that point users might even use `tfx.components.CsvExampleGen` directly in their code, no need for imports.

There are similar repetitions in other package names, for example:

```python
from tfx.orchestration.interactive.interactive_context import InteractiveContext
```

This could just be:

```python
from tfx.orchestration import InteractiveContext
```

In other cases, the package depth could probably be reduced as well, for example:

```python
from tfx.utils.dsl_utils import csv_input
```

could just be:

```python
from tfx.utils import csv_input
```

Why simplify package names?
* Code is easier to read, write and maintain
* The API is easier to learn, and can be memorized (much like Keras' API)
* Forcing the API to remain simple and clean imposes good design

This issue can be fixed easily using aliases (just like TensorFlow does), no need to move files and directories around. Existing code will not break.

Just my 2 cents!
ps: I'll probably open a similar issue for TF Agents.

**Comment by zhitaoli** [comment]
Thanks for your comment.

The part of components makes sense to me, given that we can still easily distinguish TFX component (first party) with custom or third party components (in the sense that they should have different prefix).

For utils, I'm not fully convinced that merging all functions into one `utils` modules is better than `xyz_utils`, since latter helps us to keep different functionalities into separate packages. Can you elaborate more with examples from tensorflow on this one?

**Comment by ageron** [comment]
Thanks for your answer @zhitaoli . Many libraries have a `utils` package (example `keras.utils`), and it's usually composed of stuff that doesn't really belong anywhere else. Sort of a `tfx.miscellaneous` package. Because of that, it's probably best to try to keep it as flat as possible. Indeed, if it starts to contain many functions of the same type (such as I/O functions), then it probably means that these functions would be better off placed in their own root-level package, such as `tfx.io`, rather than building a hierarchy under `tfx.utils`, such as `tfx.utils.io`.

Side-note: what exactly does DSL stand for in this case? Is it Domain Specific Language? If so, then why is `csv_input()` a part of that? It seems like it should be in something like `tfx.io` or something like that. If there are going to be many DSL functions, then there should probably be a `tfx.dsl` package.

I had a chat with François Chollet about organizing packages: he reminded me that Keras used to contain `keras.layers.recurrent`, but now all layers are located in `keras.layers`. Having just 2 levels of packages makes the API much easier to learn and remember. Plus, you can definitely keep a deeper hierarchy for the purpose of organizing the code, and just add aliases.

One last thing: I noticed that there's a `tfx.configs.configs` package. Why the duplication?
Cheers!

**Comment by charlesccychen** [comment]
We are keeping 1 version of API backwards compatibility, so we will add support for the component aliases but not use them in examples until the next version 0.15 is released.

As for the utils, we will look to pare them down to what we are comfortable exposing as a public API.  For example, we may be able to get rid of the csv_input helper function.

**Comment by 1025KB** [comment]
added components to top level as suggested
