### ISSUE TITLE
Long running custom component cancelled on Vertex AI after exactly 7 days

### ISSUE THREAD

**Issue by IzakMaraisTAL** [tensorflow/tfx#6223]
I have a long running custom TFX component. The TFX pipeline is run on Vertex AI. After 7 days it gets cancelled.

![image](https://github.com/tensorflow/tfx/assets/103260585/89447622-5fa2-4e08-9826-30f60fc0605d)

I have tried this twice and found the same result. From the component logs, there is no error happening inside the component. 

If you have the patience, you can reproduce this with a minimal custom component that just sleeps, waking every couple of minutes to log a message (this is what the component was doing when it was cancelled). 

```python
from tfx.dsl.component.experimental.decorators import component
import tensorflow as tf
import datetime
import time

@component
def Sleeper():
    while True:
        tf.print( f"{datetime.datetime.now()}. Sleeping for 5 minutes." )
        time.sleep(5 * 60)
```

TFX version: 1.12
Python version: 3.7

Is there a way to configure this apparent 7 day job timeout?

**Comment by singhniraj08** [comment]
@IzakMaraisTAL,

By default, the maximum job running time is 7 days in Vertex AI and can be changed by passing `"timeout"` in [scheduling](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/CustomJobSpec#scheduling) section of `CustomJobSpec` and passing the configuration to TFX pipeline as shown [here](https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_vertex_training#write_a_pipeline_definition).

Thank you!

**Comment by IzakMaraisTAL** [comment]
That looks very promising, thanks for the feedback. 

I am not sure how to apply the `CustomJobSpec` to my custom component. In [your example](https://www.tensorflow.org/tfx/tutorials/tfx/gcp/vertex_pipelines_vertex_training#write_a_pipeline_definition) TFX pipeline, `vertex_job_spec` value (the `CustomJobSpec`) is passed into the `tfx.extensions.google_cloud_ai_platform.Trainer` component by assigning it to the key `cusom_config[tfx.extensions.google_cloud_ai_platform.TRAINING_ARGS_KEY]`. 

What is the equivalent  when working with a [custom Python function based component](https://www.tensorflow.org/tfx/guide/custom_function_component)?

**Comment by AnuarTB** [comment]
@singhniraj08 from what I have found in code, unfortunately it seems like you can pass `CustomJobSpec` only to `Trainer` and `Tuner` components. Making the timeout last for longer seems like a feature request which will require some time. I will try to raise this issue during our Wednesday meeting and report back. Meanwhile, I can try running component as a custom job, but I am not sure about it.

**Comment by AnuarTB** [comment]
@IzakMaraisTAL could you please give context on what you are trying to do with the long-running component? TFX components were not designed to be long running, and we also fear that long-running components might cause billing problems. 

What do you think of an idea to setup a custom job outside of TFX pipeline which will do the same work?

**Comment by IzakMaraisTAL** [comment]
Thanks for the feedback. 

For each example, the custom component downloads an image from an image service given the URL in the example. 

To avoid a heavy load on the image service, the downloading is limited to early morning hours. Outside of morning hours, the component sleeps. Due to the large number of images it takes multiple days to download them all. 

We realise this is not a great long-term architecture; the goal was do the simplest implementation for the first iteration of this machine learning project.  If the project proves successful we refine the image downloading architecture and move it outside of TFX.

**Comment by AnuarTB** [comment]
From what I can see from the description, is it possible to have outside job downloading images and when it finishes downloading, make it so it can trigger the pipeline with all the gathered data?

Regarding the feature, unfortunately it is unlikely to be implemented in near future.

**Comment by IzakMaraisTAL** [comment]
> From what I can see from the description, is it possible to have outside job downloading images and when it finishes downloading, make it so it can trigger the pipeline with all the gathered data?

Yes, that would be possible. We had hoped that we could simplify it by doing everything in TFX for the first iteration.
