### ISSUE TITLE
 TFX Trainer component error

### ISSUE THREAD

**Issue by Aditya-171** [tensorflow/tfx#6238]
While running the following pipeline, ->(https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_pipeline_local.py)

Module file being used -> [tfx/tfx/examples/penguin/penguin_utils_keras.py at master · tensorflow/tfx (github.com)](https://github.com/tensorflow/tfx/blob/master/tfx/examples/penguin/penguin_utils_keras.py)

I am facing error in Trainer Component as

Failed to Convert elements of SparceTensor(indices=Tensor(“DeserilizeSparse_121:0”, shape=(None,2) dtype=int64), values=Tensor(" DeserilizeSparse_121:1", shape=(None, ), dtype=int64), dense_type=Tensor("Stack_121:0 ",shape=(2, ), dtype=int64) ) to Tensor

Getting the error as model.fit( )

**Comment by Aditya-171** [comment]
Slight changes in the make_keras_model() give me error as 

ValueError: Missing Data for input "dense_4_input". You passed a data dictionary with keys[, , , ,] . Expected the following keys:[dense_4_input ].

I am unable to figure this issue

**Comment by singhniraj08** [comment]
@Aditya-171,

I am able to run the penguin example on local runner successfully without any changes by following the [instructions](https://github.com/tensorflow/tfx/tree/master/tfx/examples/penguin#instruction) in example. Please find below the exact steps below and make sure bazel in installed in you environment. Ref: Screenshot below

```
# create python 3.10 environment
# activate environment
# install bazel
# clone tfx repository
git clone https://github.com/tensorflow/tfx ~/tfx-source
# cd to tfx folder
cd tfx
# install tfx nightly latest
export TFX_DEPENDENCY_SELECTOR=NIGHTLY
pip install -e . --extra-index-url https://pypi-nightly.tensorflow.org/simple
pip install -e .[kfp] --extra-index-url https://pypi-nightly.tensorflow.org/simple
# copy penguin folder from tfx folder to local
cp -r ~/tfx-source/tfx/examples/penguin ~/
# run penguin example
python ~/penguin/penguin_pipeline_local.py
```

![image](https://github.com/tensorflow/tfx/assets/110809167/9c9662b2-9f17-46ae-818e-05e2872aba7e)
