### ISSUE TITLE
Support ExampleValidator on all splits

### ISSUE THREAD

**Issue by ucdmkt** [tensorflow/tfx#628]
As raised in #571 by @alionkun, ExampleValidator should perform validation on all splits against a provided schema, regardless of inferred from training split, or user-provided.

**Comment by 1025KB** [comment]
currently the schema is auto generated from train split so we only validate eval split, we are planing to support user schema, after that, we can make it available for all splits, let's keep this as a feature request, thanks!

**Comment by andrewsmartin** [comment]
Hi, has there been any movement on this? Having ExampleValidator validate the eval set where the schema is inferred from the train set makes sense, but now that user-provided Schema is supported, it would be very valuable to have the option of validating against all splits.

I'm happy to submit a PR for this if there hasn't been any development work done yet.

**Comment by sngahane** [comment]
It was added as part of #2265, can be closed.
