### ISSUE TITLE
Schema and statistics in Transform TFX Pipeline Component

### ISSUE THREAD

**Issue by wsuchy** [tensorflow/tfx#629]
The main entry point in Transform component (`preprocessing_fn`) should also provide computed Stats and Schema next to the inputs. In some scenarios users might want to benefit from the statistics e.g. to eliminate unnecessary features.

**Comment by gowthamkpr** [comment]
@wsuchy Can you please also try posting this issue in the [tensorflow/transform](https://github.com/tensorflow/transform/issues) as this feature also is primarily targeted towards transform component. Thanks!

**Comment by wsuchy** [comment]
I've created related issue: https://github.com/tensorflow/transform/issues/136

**Comment by zoyahav** [comment]
Could you please expand on what this feature request is asking for?
Stats and transformed schema are computed by the Transform component, are you asking for easier access?

**Comment by wsuchy** [comment]
@zoyahav Indeed. Currently in the TFX Transform Pipeline Component the `processing_fn` has a signature of 
```
processing_fn(inputs:Dict[tf.Tensor]) -> Dict[tf.Tensor]
```
and I am proposing to change it as follows:
```
processing_fn(inputs:Dict[tf.Tensor], metadata:DatasetMetadata, stats:DatasetFeatureStatisticsList ) -> Dict[tf.Tensor]
```
or even better, as a higher order function / factory:
```
processing_fn_factory(metadata:DatasetMetadata, stats:DatasetFeatureStatisticsList ) 
-> Callable[Dict[tf.Tensor], Dict[tf.Tensor]]
```
So now my processing function could depend on the stats and schema. 
I know I could reach for it Stats and Schema manually, yet it requires me to talk to the SQLite database and keeping track of paths, etc.

**Comment by JoshLipschultz** [comment]
I'd like to re-up this request—having easier access to the metadata and schema from within the Transform callback would be tremendously useful. Some feature transformations could depend on the inferred schema. Is there some other workaround?

**Comment by singhniraj08** [comment]
@wsuchy,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TFX 1.13 release so that we can work on fixing it. Thank you for your contributions.
