### ISSUE TITLE
Allow List of Lists and SequenceExample in dict_to_example

### ISSUE THREAD

**Issue by AlexanderLavelle** [tensorflow/tfx#6374]
**System information**

- TFX Version (you are using): `1.14.0`
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): Linux (anywhere)
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The current behavior will not allow a list of lists because list is not an acceptable type (int, str, float). The feature allows a list of lists to be encoder (per sequence modeling etc)

**Will this change the current API? How?**
The current API will not be affected, although user experience on the read varies -- this function as a standalone with the writer is fine, but a user who does not implement [5689](https://github.com/tensorflow/tfx/pull/5689) will not see the Sequences encoded as a result of this modification

**Who will benefit with this feature?**
Users who want to do sequence modeling whose native data is list of lists or `tf.RaggedTensor`s

**Do you have a workaround or are completely blocked by this?** :
This is the workaround

**Name of your Organization (Optional)**

**Any Other info.**

PR # [6373](https://github.com/tensorflow/tfx/pull/6373)

**Comment by singhniraj08** [comment]
@AlexanderLavelle,

I see a PR already attached by you for the feature implementation. We will keep you updated on the PR. Thank you for your contributions.
