### ISSUE TITLE
Trainer component crashed in an execution on Kubeflow on GCP 

### ISSUE THREAD

**Issue by mesaverde0207** [tensorflow/tfx#657]
/kind bug

I was running [the TFX ml pipeline of the Chicago taxi example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py) on Kubeflow 0.6.2 which was deployed to GCP by the UI deployment tool. I used TFX 0.14.0 for compiling DAG dsl. When it came to the trainer component execution,  the component crashed.

The logs in Kubeflow says:
```
INFO:googleapiclient.discovery:URL being requested: POST 
https://ml.googleapis.com/v1/projects/sandbox-192306/jobs?alt=json
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 200, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 196, in main
    launcher.launch()
  File "/opt/venv/lib/python3.6/site-packages/tfx/orchestration/component_launcher.py", line 158, in launch
    execution_decision.exec_properties)
  File "/opt/venv/lib/python3.6/site-packages/tfx/orchestration/component_launcher.py", line 129, in _run_executor
    executor.Do(input_dict, output_dict, exec_properties)
  File "/opt/venv/lib/python3.6/site-packages/tfx/extensions/google_cloud_ai_platform/trainer/executor.py", line 67, in Do
    executor_class_path, training_inputs)
  File "/opt/venv/lib/python3.6/site-packages/tfx/extensions/google_cloud_ai_platform/runner.py", line 128, in start_cmle_training
    request.execute()
  File "/opt/venv/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting 
https://ml.googleapis.com/v1/projects/sandbox-192306/jobs?alt=json
 returned "Field: master_config.image_uri Error: Failed to read the container uri [gcr.io/tfx-oss-public/tfx:0.14.0], Please make sure that the image exists and CloudML Engine service account has access to it.". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'master_config.image_uri', 'description': 'Failed to read the container uri [gcr.io/tfx-oss-public/tfx:0.14.0], Please make sure that the image exists and CloudML Engine service account has access to it.'}]}]">
```

As the error message said, there is not a container ```gcr.io/tfx-oss-public/tfx:0.14.0``` but ```tfx:0.14.0rc1```, ```tfx:0.14.0dev```,  and so on. (https://console.cloud.google.com/gcr/images/tfx-oss-public/GLOBAL/tfx?tag=0.14.0&gcrImageListsize=30)

And I found the following line in https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_ai_platform/runner.py#L36
```python
_TFX_IMAGE = 'gcr.io/tfx-oss-public/tfx:%s' % (version.__version__)
```
It seems that this is the part to be fixed?

**Comment by charlesccychen** [comment]
CC: @zhitaoli @neuromage

**Comment by neuromage** [comment]
Thanks @mesaverde0207 for filing this issue!

Something went wrong with our internal image release process. We're fixing it. In the meantime, we've pushed the image `gcr.io/tfx-oss-public/tfx:0.14.0`, so custom containers on AI Platform training should work. Would you be willing to try this again and let us know if this works for you? Thanks!

**Comment by mesaverde0207** [comment]
Thank you for pushing a new container image!
The master_config.image_uri Error does no longer happen.
