### ISSUE TITLE
TFX 0.14.0 on PyPI did not strip type hints for Py2

### ISSUE THREAD

**Issue by jinnovation** [tensorflow/tfx#662]
It seems that latest release of TFX on PyPI ([0.14.0](https://pypi.org/project/tfx/0.14.0/#files)) did not create a Py2-compatible version with stripped type hints. Presumably related to it being a universal wheel.

```
┌─[jonathanj@]──[11:30:55]──[/tmp]
└─> $ unzip tfx-0.14.0-py2.py3-none-any.whl 
┌─[jonathanj@]──[11:31:02]──[/tmp]
└─> $ cd tfx/
┌─[jonathanj@]──[11:31:04]──[/tmp/tfx]
└─> $ cat types/artifact.py 
<TRIMMED>
  def __init__(self,
               type_name: Optional[Text] = None,
               split: Optional[Text] = ''):
<TRIMMED>
```

**Comment by zhitaoli** [comment]
@ruoyu90 Something went wrong in our release process: https://pypi.org/project/tfx/0.14.0/#files and https://pypi.org/project/tfx/0.14.0rc1/#files have inconsistent files.

I'm going to see how much we can fix this in place. If not we might need to release a new tag for 0.14.1.

Sorry for the problem.

**Comment by jinnovation** [comment]
@zhitaoli: No worries; it happens. Thanks in advance for addressing.

**Comment by ruoyu90** [comment]
Hey @jinnovation we just updated the [wheels](https://pypi.org/project/tfx/#files). Hopefully it will work now :)

**Comment by jinnovation** [comment]
Perfect, LGTM. Thanks for taking care of this.
