### ISSUE TITLE
The ModelValidator implementation is effectively useless

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/tfx#663]
Hi,
Given today's implementation of the [ModelValidator's Executor](https://github.com/tensorflow/tfx/blob/master/tfx/components/model_validator/executor.py), it does not make a lot of sense to use it. There are two major problems with it.

1. The implementation for `_pass_threshold` is `return True`. In https://github.com/tensorflow/tfx/pull/652 I propose that the user could pass a `threshold_config` that would map some of the model's metrics to a threshold than need to be exceeded.
2. The implementation of `_compare_eval_result` only checks if current_model's `accuracy`'s `doubleValue` is strictly greater than blessing_model's. This is way too constraint as many models don't output this metric and also the user might not want to compare on this metric only.

Generally, metrics comparison should be done using the protobuf type from TFMA that is much easier to deal with and test because it somewhat typed as opposed to arbitrary values in dictionaries. This is what I propose to do in https://github.com/tensorflow/tfx/pull/652/files#diff-c1d62ad820a65cf4a5fa4c95b2e9656c (to be completed with other MetricValue types).

**Comment by mdreves** [comment]
Agreed it is not useful. We are currently working on merging the Evaluator and ModelValidator components into a single component. This merged component will have an enhanced config both for setting more evaluator configuration options but also for configuring the model validation thresholds, etc.

**Comment by martin-laurent** [comment]
@mdreves Interesting! In our company, we also have our own implementation of the Evaluator component to make it configurable. I'd be interested to have more details into what the implementation of this combined component will look like so that we can maybe start to make ours closer to what you came up with?

**Comment by 1025KB** [comment]
Hi, Martin, internally we have a proto config for define threshold but this one doesn't available in oss, the oss version of threshold config are WIP now

**Comment by ruoyu90** [comment]
Leaving this open as a FR for more full-featured ModelValidator.

**Comment by jiyongjung0** [comment]
ModelValidator was deprecated and we have Evaluator which accepts variety of configurations. Let me close this issue. Please reopen if you need.
