### ISSUE TITLE
Upgrade Tensorflow version

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tfx#6685]
If the feature is related to a specific library below, please raise an issue in
the respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- TFX Version (you are using): latest
- Environment in which you plan to use the feature (e.g., Local
  (Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc..): linux
- Are you willing to contribute it (Yes/No):
na
**Describe the feature and the current behavior/state.**
Could we upgrade the version of tensorflow locked in TFX ? to 1.14 or 1.15. 1.16 is going to be released soon. 

**Will this change the current API? How?**
no

**Who will benefit with this feature?**
Users wanting to use latest Tensorflow feature

**Do you have a workaround or are completely blocked by this?** :
blocked

**Name of your Organization (Optional)**
Tinyclues / Splio

**Any Other info.**

**Comment by singhniraj08** [comment]
@tanguycdls,

We are working on new TFX release which is being blocked because of few dependency issues and we are working on it. The new TFX release would support upgraded Tensorflow version. I will update this thread once new version is released. 
Thank you!
