### ISSUE TITLE
Model Validator cannot find Trainer output

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/tfx#673]
The error in ModelValidator is: `Could not find directory gs://.../Trainer/output/12/eval_model_dir`. Looks like the Trainer wrote to `gs://.../Trainer/output/150/eval_model_dir`...

Running on GKE with kubeflow version 0.6.2. Not using any custom components.

**Comment by 1025KB** [comment]
ModelValidator is trying to find previous blessed model to compare with current model, it looks like previous model are deleted

**Comment by JakeTheWise** [comment]
Right, I cleared my tfx output directories because I didn't think it would affect subsequent pipeline runs. Is there a way to fix this model referencing issue without nuking my kubeflow deployment?

**Comment by 1025KB** [comment]
one hack way to fix this is copy the current trainer ouput eval model to the blessed model path recorded in metadata, or drop the entire metadata (you will lose all tracking information)
