### ISSUE TITLE
TFX Team provide more information on project plans and roadmaps

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tfx#675]
This request is for the Google TFX team to provide more planning information to the community.  This will help us 3rd parties manage our usage of TFX .

I realize that TFX will change a lot and I'm happy to see that.  However, I would also like to develop using TFX.  Knowing more about your plans for TFX will make my usage easier.

**Comment by 1025KB** [comment]
Hi, thanks for the advice! 

for roadmap, please check [here](https://github.com/tensorflow/tfx/blob/master/ROADMAP.md), this will be updated quarterly  

for detailed changes, please check [here](https://github.com/tensorflow/tfx/blob/master/RELEASE.md)

for designs, we started to publish [rfc](https://github.com/tensorflow/community/tree/master/rfcs) under tensorflow community

for user DSL API, we will ensure at least one version backward compatibility, after we release 1.0 (plan first half of next year), all user API will be maintained until 2.0

if you find our change break you, feel free to create an issue here, we can see if we could add a small fix to unblock you

**Comment by zhitaoli** [comment]
To augment what Jiayi said above, another way to ensure upcoming changes of TFX does not break your system is to helping out in RC testing phase. We will announce each RC to our user group (tfx@tensorflow.org) and wait for at least one week before finalizing a release, and any issues discovered in the process will be fixed before we finalize the release. So please consider joining the user group and help us test out our RCs.
