### ISSUE TITLE
tfx apache beam with spark - setup_beam_on_spark - not running

### ISSUE THREAD

**Issue by darisettysuneel** [tensorflow/tfx#691]
I tried running chicago taxi simple DAG in airflow - Successfull

But

When I tried to test apache beam with spark implementation I am unable to run it. Please find the below attachments for reference

Error:

[2019-10-01 15:45:20,572] {logging_mixin.py:95} INFO - [[34m2019-10-01 15:45:20,572[0m] {[34mstager.py:[0m486} INFO[0m - Executing command: [1m['/home/administrator/SuneelDriveA/tfx/env_taxi/bin/python3.6', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', '/tmp/tmpha52ijoe/requirement.txt', '--exists-action', 'i', '--no-binary', ':all:'][0m[0m
[2019-10-01 15:45:21,547] {taskinstance.py:1051} ERROR - Full traceback: Traceback (most recent call last):
  File "/home/administrator/SuneelDriveA/tfx/env_taxi/lib/python3.6/site-packages/apache_beam/utils/processes.py", line 83, in check_output
    out = subprocess.check_output(*args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/administrator/SuneelDriveA/tfx/env_taxi/bin/python3.6', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', '/tmp/tmpha52ijoe/requirement.txt', '--exists-action', 'i', '--no-binary', ':all:']' returned non-zero exit status 1.
 
 Pip install failed for package: -r         
 Output from execution of subprocess: b'Collecting tfx==0.14.0 (from -r /tmp/tmpha52ijoe/requirement.txt (line 1))\n  ERROR: Could not find a version that satisfies the requirement tfx==0.14.0 (from -r /tmp/tmpha52ijoe/requirement.txt (line 1)) (from versions: none)\nERROR: No matching distribution found for tfx==0.14.0 (from -r /tmp/tmpha52ijoe/requirement.txt (line 1))\n'
Traceback (most recent call last):
  File "/home/administrator/SuneelDriveA/tfx/env_taxi/lib/python3.6/site-packages/apache_beam/utils/processes.py", line 83, in check_output
    out = subprocess.check_output(*args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/administrator/SuneelDriveA/tfx/env_taxi/bin/python3.6', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', '/tmp/tmpha52ijoe/requirement.txt', '--exists-action', 'i', '--no-binary', ':all:']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

setup_beam_on_spark.sh output:

> Task :runners:spark:job-server:runShadow
Listening for transport dt_socket at address: 5005
log4j:WARN No appenders could be found for logger (org.apache.beam.vendor.grpc.v1p13p1.io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
<============-> 98% EXECUTING [32m 21s]
> IDLE
> :runners:spark:job-server:runShadow

![airflow_graph](https://user-images.githubusercontent.com/41149713/65955969-ee75b780-e466-11e9-9d2e-909a9bc6b6d8.png)

**Comment by darisettysuneel** [comment]
Note:
I have already installed tfx==0.14.0 but subprocess in apache_beam/utils/processes.py is  throwing error.

**Comment by gowthamkpr** [comment]
Similar to issue mentioned in this [comment](https://github.com/tensorflow/tfx/issues/649#issuecomment-536219717)

**Comment by 1025KB** [comment]
are you able to see the job in spark UI? what's your beam and spark version?

**Comment by darisettysuneel** [comment]
@1025KB 
Thanks much for your response. I've changed my virtualenv  inside the setup beam on spark file through os module. It works.

Python 3.6
spark-2.4.4-bin-hadoop2.7.tgz

@gowthamkpr 
Thanks for your reference.

**Comment by darisettysuneel** [comment]
@1025KB 
Update:
when I ran second time same dag it was not visible in spark UI. is it same with you?

**Comment by 1025KB** [comment]
that is because the second run are cached, so it doesn't go through beam calculate, you can change the input, so it won't cache

if you use the taxi_pipeline_beam.py  example I mentioned above, you can notice the cached run only takes second to finish, airflow needs extra time to bring up component so it's not that obvious for small dataset

**Comment by darisettysuneel** [comment]
Thanks @1025KB 
My airflow master is shutting down when I am running my spark job even when I decrease no of cores and increased memory per executor. Is there any parameters to change from tfx end to avoid this kind of situation?

**Comment by 1025KB** [comment]
you mean airflow scheduler? is there any logs?

**Comment by darisettysuneel** [comment]
@1025KB  thanks for your help! I missed the logs.

**Comment by tejaslodaya** [comment]
For anyone who didn't follow the above steps mentioned by @darisettysuneel (maybe because of lack of verbosity), please do this:

1. Go to site-packages inside your virtual environment and go to apache_beam/runners/portability/stager.py file.
2. Go to `_populate_requirements_cache` function and remove these two lines
        '--no-binary',
        ':all:'
3. Reload the package inside your jupyter notebook/ main call.

In my case, I had created conda environment and changed this file: `~/miniconda3/envs/tfx_test/lib/python3.7/site-packages/apache_beam/runners/portability/stager.py`  where my environment name is `tfx_test`.

This solves the issue.
