### ISSUE TITLE
Documentation Follow-up Work

### ISSUE THREAD

**Issue by peytondmurray** [tensorflow/tfx#6912]
After the [recent change to documentation hosting and format](https://github.com/tensorflow/tfx/pull/6901), there is some follow up work:

- [x] The "Run in Google Colab" etc buttons found in the guides need to be restyled as actual buttons instead of links. See https://tensorflow.github.io/tfx/tutorials/tfx/gcp/vertex_pipelines_simple/
- [x] Main API reference landing page is empty. We need some links for the various child pages here: https://tensorflow.github.io/tfx/api/v1/
- [x] Addons page is broken: https://tensorflow.github.io/tfx/addons/
- [x] The "TFX for Mobile" page is broken: https://tensorflow.github.io/tfx/tutorials/tfx_for_mobile. However https://tensorflow.github.io/tfx/tutorials/tfx/tfx_for_mobile/ is not; not sure which one is the correct one, or if there should be two?
- [x] Remove the TF logo; visibility is not high enough

cc @rcrowe-google for visibility.

**Comment by smokestacklightnin** [comment]
There is a PR for the Addons page: #6913

**Comment by smokestacklightnin** [comment]
> The "TFX for Mobile" page is broken: https://tensorflow.github.io/tfx/tutorials/tfx_for_mobile. However https://tensorflow.github.io/tfx/tutorials/tfx/tfx_for_mobile/ is not; not sure which one is the correct one, or if there should be two?

Fixed in [this commit](https://github.com/tensorflow/tfx/pull/6914/commits/cbb5675f0ba4a117eed6a30ce84433314466b466)

**Comment by smokestacklightnin** [comment]
> * Main API reference landing page is empty. We need some links for the various child pages here: https://tensorflow.github.io/tfx/api/v1/

Fixed in [this commit](https://github.com/tensorflow/tfx/pull/6914/commits/69f7d541b2bb9a9421f98325f19215b10d9b24c2)
