### ISSUE TITLE
[__JUSTIN@TV__]Jake Paul-Tyson-Maçı-Canlı-izle-16-Kasıms-2024 #449

### ISSUE THREAD

**Issue by groovapapazo** [tensorflow/tfx#7019]
Jake Paul vs. Mike Tyson: How to watch the weigh-in and fight live, full card and more

### [𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🟢==►► Jake Paul vs. Mike Tyson Live=►► ](https://masum-optv.blogspot.com/2024/11/jake-paul.html)

Mike Tyson-Jake Paul boks maçı canlı yayın detaylar, sporseverlerin yanı sıra özellikle boks dünyası tarafından heyecanla araştırılıyor. Eski ağır sıklet boks şampiyonu Mike Tyson ile YouTuber Jake Paul karşı karşıya geliyor. Merakla beklenen karşılaşma Teksas eyaletine bağlı Arlington şehrindeki 80 bin kişilik AT&T Stadı'nda gerçekleştirilecek. Tyson-Paul boks maçının geçtiğimiz aylarda yapılacağı planlanmıştı. Ancak daha sonra erteleme kararı alınmıştı. Diğer taraftan 80 milyon dolarlık randevuda boks tarihinin en pahalı bileti 2 milyon dolara piyasaya sürüldü. Karşı karşıya gelecek iki isim 80 milyon dolar kazanacak. Bu paranın eşit bölüştürüleceği belirtilirken Mike Tyson’ın 20 milyon dolar alabileceği de iddia edildi. Müsabaka, iki dakikalık 8 raunt üzerinden yapılacak. Peki Mike Tyson Jake Paul boks maçı bu gece mi, ne zaman? Mike Tyson Jake Paul maçı hangi kanalda, saat kaçta? İşte milyonların heyecanla beklediği karşılaşmanın detayları...

Mike Tyson Jake Paul maçı canlı izle ekranı yoğun olarak araştırılıyor. Milyonların beklediği bu heyecanlı karşılaşma için geri sayım sürerken maç öncesi gerilim tırmandı ve büyük olaylar yaşandı. Müsabaka öncesi karşı karşıya gelen iki arasında sinirler gerildi. Mike Tyson'ın Jake Paul'u tokatlamasıyla da ortalık karıştı. Jake Paul-Mike Tyson bu gece gerçekleştirilecek. müsabaka öncesi süper orta sıklette Neeraj Goyat-Whindersson Nunes, yarı orta sıklette Mario Barrios-Abel Ramos ve süper hafif sıklette Katie Taylor-Amanda Serrano maçları yapılacak. Aktif kariyeri boyunca ringdeki hırçın tarzıyla rakiplerinin korkulu rüyası haline gelen Mike Tyson, tarihin en iyi boksörleri arasında gösteriliyor. YouTube'da 20,8 milyon takipçi ve yaklaşık 7,7 milyar izlenmeye sahip Jake Paul ise 2018'de boks kariyerine başladı. Peki Mike Tyson-Jake Paul maçı ne zaman, saat kaçta, hangi kanalda? İşte Tyson-Paul maçı TSİ saati ve müsabaka programı...

TYSON-PAUL BOKS MAÇI TÜRKİYE SAATİ || MIKE TYSON-JAKE PAUL MAÇI NE ZAMAN, SAAT KAÇTA, HANGİ KANALDA?

Mike Tyson Jake Paul'ün karşı karşıya geleceği profesyonel ağır sıklet boks müsabakası, TSİ 04.00'te başlayacak. Tyson-Paul boks maçı dijital yayın platformu Netflix'ten canlı yayınlanacak.

Uzun süredir heyecanla beklenen maç, Amerikan Futbolu Ligi (NFL) takımlarından Dallas Cowboys'a da ev sahipliği yapan, Teksas eyaletine bağlı Arlington şehrindeki 80 bin kişilik AT&T Stadı'nda gerçekleştirilecek.

KARŞILAŞMA ÖNCESİNDE ÜÇ MÜSABAHA DAHA OLACAK

Gecenin ana etkinliği Jake Paul-Mike Tyson maçından önce üç karşılaşma daha gerçekleştirilecek.

AT&T Stadı'nda merakla beklenen müsabaka öncesi süper orta sıklette Neeraj Goyat-Whindersson Nunes, yarı orta sıklette Mario Barrios-Abel Ramos ve süper hafif sıklette Katie Taylor-Amanda Serrano maçları yapılacak.

İKİ DAKİKALIK 8 RAUNT

Bu üç müsabakanın ardından gecenin ana etkinliğinde ise Jake Paul ile Mike Tyson ringe çıkacak. Müsabaka, iki dakikalık 8 raunt üzerinden gerçekleştirilecek.

TYSON-PAUL MAÇI BÜYÜK ÖDÜL NE KADAR?

Boks tarihinin en pahalı biletine sahip olan maçta her iki boksör de maçtan 40 milyon dolar kazanacak.

Paul, boks kariyerinden büyük bir servet kazandı ve 27 yaşındaki boksörün tahmini net kazancı 80 milyon dolar civarında. Bu dövüş, ona büyük bir kazanç sağlayacak ve bazı raporlara göre Paul'ün bu karşılaşmadan alacağı ödeme 40 milyon dolar olacak. Paul, Ağustos ayında yaptığı bir açıklamada, "Ben buradayım, 40 milyon dolar kazanacağım ve bir efsaneyi nakavt edeceğim. Başka hiçbir şey umurumda değil" dedi.

Tyson ise bu dövüşü maddi kazanç için yapmadığını belirtti. 58 yaşındaki boks efsanesi, "Bu dövüşten kazanacağım para yaşam tarzımı değiştirmez. Bu dövüş finansal bir amaçla yapılmıyor. Sadece kendimi test etmek istiyorum" dedi. Ancak dövüşün toplam değeri yaklaşık 80 milyon dolar civarında ve bu maç, Netflix'in boks dünyasına adım atması açısından önemli bir kilometre taşı olacak. Netflix, dövüşü canlı olarak yayınlamak için Most Valuable Promotions ile bir ortaklık yaptı.

KARŞILAŞMA ÖNCESİ TANSİYON YÜKSELDİ

Dünyanın beklediği Mike Tyson ile Jake Paul arasında yapılacak olan boks maçı öncesinde gerilim tırmandı ve büyük olaylar yaşandı. Dev karşılaşma öncesi yüz yüze gelen ikili arasında sinirler gerildi ve Mike Tyson kendisini daha fazla tutamadı.

Jake Paul, yerde ilginç hareketler yaparak sahneye çıktı ve Mike Tyson'ın ayak ucuna basarak yüz yüze geldi. Bu durumu kendisine tehdit ve saygısızlık olarak algılayan Tyson, Paul'ün yüzüne sert bir tokat attı.

Görevlilerin araya girmesiyle olay daha fazla büyümezken, Mike Tyson'ın oldukça sinirli olduğu ve onlarca kişi tarafından zor zaptedildiği görüldü.

Jake Paul'ün ise yediği tokadı alaycı bir şekilde karşılaması ve seyircilere gülerek bir şeyler anlatması dikkat çekti.

50 GALİBİYETLİK MUHTEŞEM KARİYER

Aktif kariyeri boyunca ringdeki hırçın tarzıyla rakiplerinin korkulu rüyası haline gelen Mike Tyson, tarihin en iyi boksörleri arasında gösteriliyor.

Kariyerinde 44'ü nakavt olmak üzere 50 galibiyet ve 6 yenilgisi bulunan 58 yaşındaki Tyson, 1986'da 20 yaşındayken karşılaştığı Trevor Berbick'i nakavt ederek "en genç ağır sıklet şampiyonu" ünvanını aldı.

Tyson, aynı anda Dünya Boks Birliği (WBA), Dünya Boks Konseyi (WBC) ve Uluslararası Boks Federasyonu (IBF) ünvanlarına sahip ilk ağır sıklet boksör oldu.

Kariyerine 2005'te son veren ABD'li boksör, 15 yıl aradan sonra 2020'de gösteri maçı için ringlere dönerek sporseverleri ekran başına kilitledi.

Ringlerin asi boksörü Tyson, sporseverlerin aklında Evander Holyfield ile 1997'de yaptığı maçla yer etti. Ünvan maçında Holyfield'ın kulağını ısırarak koparan ve diskalifiye edilen Tyson, spor dünyasının yıllar geçse de unutamayacağı bir ana tanıklık etmesine sebebiyet verdi.

Yumrukları kadar özel hayatındaki çalkantılar ve yasa dışı olaylarla da anılan Tyson, İngiliz spor kanalı Sky Sports tarafından "Belki de profesyonel ringe adım atan en vahşi dövüşçü" olarak tanımlandı.

BOKSA 2018'DE BAŞLADI

YouTube'da 20,8 milyon takipçi ve yaklaşık 7,7 milyar izlenmeye sahip Jake Paul, 2018'de boks kariyerine başladı.

Kendisi gibi YouTuber olan ve daha sonra boksa başlayan Deji Olatunji karşısında ringlere ilk kez amatör maçta adım atan Paul, sonrasında profesyonel kariyere geçiş yaptı.

Profesyonel olarak 11 dövüşe çıkan 27 yaşındaki ABD'li boksör Paul, 7'si nakavtla olmak üzere 10 galibiyet ve bir mağlubiyet yaşadı. Paul'ün dövüştüğü isimler arasında Amerikan Basketbol Ligi'nin (NBA) eski oyuncularından Nate Robinson da yer aldı.

Paul, tek yenilgisini ise Şubat 2023'te Suudi Arabistan'da yapılan müsabakada Büyük Britanyalı boksör Tommy Fury karşısında yaşadı.

Jake Paul vs. Mike Tyson fight card

*Full card will be available to w.atch on Netflix.

Heavyweight: Mike Tyson vs. Jake Paul

Super Lightweight: Katie Taylor vs. Amanda Serrano for Taylor's IBF, WBA, WBC and WBO women's super-lightweight titles

Welterweight: Mario Barrios vs. Abel Ramos for Barrios' WBC welterweight title

Super Middleweight: Neeraj Goyat vs. Whindersson Nunes

Super Middleweight: Shadasia Green vs Melinda Watpool for vacant women’s WBO super middleweight title

Super Lightweight: Lucas Bahdi vs. Armando Casamonica

Featherweight: Bruce Carrington vs Dana Coolwell

**Comment by sadiapervin7** [comment]
fdd

**Comment by dharkanpok** [comment]
hgjy

**Comment by tilakrayal** [comment]
**Closing this issue as SPAM**
