### ISSUE TITLE
ORIGINAL-VIDEOs-Indonesian-Celeb-Lydia-Onic's-Alleged-Private-Video-Leaked

### ISSUE THREAD

**Issue by groovapapazo** [tensorflow/tfx#7072]
Ini Link Viral Lydia Onic dengan beredarnya video 12 menit, Ini fakta-fakta Terbarunya

### [➤ ►🌍📺📱👉 𝖫𝖾𝖺𝚔𝖾𝖽 𝗏𝗂𝗋𝖺𝗅 𝗅𝗂𝗇𝗄 2024 𝖫𝖾𝖺𝚔𝖾𝖽 𝖵𝗂𝖽𝖾𝗈 𝖵𝗂𝗋𝖺𝗅 𝖮𝗇 𝖲𝗈𝖼𝗂𝖺𝗅 𝖬𝖾𝖽𝗂𝖺](https://server-unknown-issue.blogspot.com/2024/11/ol.html)

Radar Jember – Selebgram Lydia ONIC tampaknya tidak terlalu terganggu dengan isu yang tengah beredar di media sosial terkait video syur berdurasi 12 menit yang diklaim mirip dirinya.

Alih-alih memberikan klarifikasi, Lydia memilih untuk melanjutkan aktivitasnya seperti biasa.

Nama Lydia ONIC mendadak menjadi perbincangan publik setelah tersebarnya video panas yang dikatakan mirip dengannya di Twitter atau X.

Hingga saat ini belum ada konfirmasi pasti mengenai apakah video itu benar-benar milik Lydia atau hanya rumor belaka.

Di akun Instagram pribadinya, @lydiaaas__, yang memiliki lebih dari 1,1 juta pengikut, Lydia belum memberikan pernyataan resmi mengenai isu ini.

Ia belum memberikan klarifikasi apapun terkait video viral tersebut.

Lydia lebih memilih untuk fokus pada aktivitas endorsenya, salah satunya mempromosikan produk skincare di Instagram.

Postingan terbarunya pada 12 November 2024 pun langsung dibanjiri komentar, namun ia tidak memberikan penjelasan atau klarifikasi mengenai video yang tengah viral.

Beberapa netizen berspekulasi bahwa video tersebut mungkin merupakan hasil rekayasa dengan teknologi Deepfake atau AI, meskipun ada juga yang tetap yakin bahwa itu adalah dirinya.

Di Instagram Story-nya, Lydia tampak santai mengenakan daster, seolah tidak peduli dengan gosip yang beredar.

Link Video 12 Menitnya Banyak Diburu, Siapa Lydia Onic?

Suara.com - Rekaman video syur yang diduga gamers esports Lydia ONIC berdurasi 12 menit 13 detik viral di media sosial. 

Artikel ini telah tayang di Suara.com dengan judul "Link Video 12 Menitnya Banyak Diburu, Siapa Lydia Onic

.
.

.
.
.
.
Ini Link Viral Lydia Onic dengan beredarnya video 12 menit, Ini fakta-fakta Terbarunya

### [➤ ►🌍📺📱👉 𝖫𝖾𝖺𝚔𝖾𝖽 𝗏𝗂𝗋𝖺𝗅 𝗅𝗂𝗇𝗄 2024 𝖫𝖾𝖺𝚔𝖾𝖽 𝖵𝗂𝖽𝖾𝗈 𝖵𝗂𝗋𝖺𝗅 𝖮𝗇 𝖲𝗈𝖼𝗂𝖺𝗅 𝖬𝖾𝖽𝗂𝖺](https://server-unknown-issue.blogspot.com/2024/11/ol.html)

Radar Jember – Selebgram Lydia ONIC tampaknya tidak terlalu terganggu dengan isu yang tengah beredar di media sosial terkait video syur berdurasi 12 menit yang diklaim mirip dirinya.

Alih-alih memberikan klarifikasi, Lydia memilih untuk melanjutkan aktivitasnya seperti biasa.

Nama Lydia ONIC mendadak menjadi perbincangan publik setelah tersebarnya video panas yang dikatakan mirip dengannya di Twitter atau X.

Hingga saat ini belum ada konfirmasi pasti mengenai apakah video itu benar-benar milik Lydia atau hanya rumor belaka.

Di akun Instagram pribadinya, @lydiaaas__, yang memiliki lebih dari 1,1 juta pengikut, Lydia belum memberikan pernyataan resmi mengenai isu ini.

Ia belum memberikan klarifikasi apapun terkait video viral tersebut.

Lydia lebih memilih untuk fokus pada aktivitas endorsenya, salah satunya mempromosikan produk skincare di Instagram.

Postingan terbarunya pada 12 November 2024 pun langsung dibanjiri komentar, namun ia tidak memberikan penjelasan atau klarifikasi mengenai video yang tengah viral.

Beberapa netizen berspekulasi bahwa video tersebut mungkin merupakan hasil rekayasa dengan teknologi Deepfake atau AI, meskipun ada juga yang tetap yakin bahwa itu adalah dirinya.

Di Instagram Story-nya, Lydia tampak santai mengenakan daster, seolah tidak peduli dengan gosip yang beredar.

Link Video 12 Menitnya Banyak Diburu, Siapa Lydia Onic?

Suara.com - Rekaman video syur yang diduga gamers esports Lydia ONIC berdurasi 12 menit 13 detik viral di media sosial. 

Artikel ini telah tayang di Suara.com dengan judul "Link Video 12 Menitnya Banyak Diburu, Siapa Lydia Onic

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

.
.
.
.
.
.
.

**Comment by namulhossen** [comment]
cvbcv

**Comment by aasaakija** [comment]
cvbcvb

**Comment by sumiahsan06** [comment]
nnnn

<a href="https://costafo.blogspot.com" rel="nofollow">

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>
<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/25529aba-1488-4341-bf00-8109893bb45c" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/697fcbff-6915-432f-9b8a-625957d21ad6" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/fff760c8-8614-4429-aeec-706d5e7d4701" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/697fcbff-6915-432f-9b8a-625957d21ad6" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/4eb6a3bb-b84f-477a-8200-1a17b55dc431" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/9ac055d8-fb4e-42a7-8a3a-8c9f1034e0b0" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/41aaf8be-3301-4345-8037-b2b362644d11" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/41aaf8be-3301-4345-8037-b2b362644d11" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/d9e4eb6c-0892-4c85-a9ee-339ac45aee0b" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/25529aba-1488-4341-bf00-8109893bb45c" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/507f562c-45a6-45bb-9741-929429e8a082" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

. 
.
<img src="https://github.com/user-attachments/assets/697fcbff-6915-432f-9b8a-625957d21ad6" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>

xxx

**Comment by tilakrayal** [comment]
**Closing this issue as SPAM**
