### ISSUE TITLE
Adding support for parquet files for exampleGen

### ISSUE THREAD

**Issue by R4dlk** [tensorflow/tfx#74]
Hi,
Currently the pipeline supports only inputs from CSV and BigQuery.
Is there a chance to add support for parquet files as well?
Perhaps even adding a tutorial on how to generate a custom exampleGen (component, driver, executor).
Thanks!

**Comment by KamalAman** [comment]
There is a PR opened with Paraquet support, https://github.com/tensorflow/tfx/pull/49
However, it will probably have to wait for `some internal refactoring about example gen`

**Comment by 1025KB** [comment]
PR merged
