### ISSUE TITLE
Could pipeline_root in tfx.pipeline set to other file system 

### ISSUE THREAD

**Issue by pingsutw** [tensorflow/tfx#756]
The **pipeline_root** was set in pipeline.Pipeline, but it was set to local file system and gs in tfx example. 
Can it set to other file system, like Hadoop or S3, etc.

**Comment by 1025KB** [comment]
the file system supported by [tf.io](https://www.tensorflow.org/api_docs/python/tf/io) should be fine, 
here is a similar [thread](https://github.com/tensorflow/tfx/issues/740) for hdfs if you are interested

**Comment by gowthamkpr** [comment]
Closing this issue as it has been answered. Please add additional information and we can open this issue again. Thanks!

**Comment by pingsutw** [comment]
Thanks @1025KB @gowthamkpr for the comment.
It's very helpful
