### ISSUE TITLE
Tutorial missing step: airflow initdb

### ISSUE THREAD

**Issue by geugon** [tensorflow/tfx#77]
Never used airflow before, but it appears you need to run:

airflow initdb

before you make the webserver for it to operate correctly.  This command was not listed in the tutorial instructions, please update.

Failure to do so gives an error about None not having at method to create dags, because a get_dag() somewhere in the airflow code returns None.

**Comment by 1025KB** [comment]
Hi, Geugon, which tutorial you are checking? I checked [this](https://github.com/tensorflow/tfx/tree/master/tfx/examples/chicago_taxi_pipeline) which contains the airflow initdb

if you are talking about [workshop](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/workshop.md) , the airflow initdb is within [setup_demo.sh](https://github.com/tensorflow/tfx/blob/master/tfx/examples/workshop/setup/setup_demo.sh)

**Comment by geugon** [comment]
I was referring to the workshop, and I see you are correct about the airflow initdb being in the setup_demo.sh.

I was getting the error I mentioned above, and I thought adding airflow initdb was what fixed it.  Now I am unsure what the underlying issue was or how it resolved itself....  Regardless, I will close this issue.  Thanks!
