### ISSUE TITLE
ExecutionParameter type-checking does not assert against generics

### ISSUE THREAD

**Issue by jinnovation** [tensorflow/tfx#784]
I've noticed that while `ExecutionParameter` *accepts* subscripted generics, e.g. `ExecutionParameter(type=Dict[Text, Any], optional=True)` (as in `TrainerSpec`), there's no actual assertion being performed on this value, as evidenced by the definition for `ExecutionParameter.type_check`:
``` python
  def type_check(self, arg_name: Text, value: Any):
    # Can't type check generics. Note that we need to do this strange check form
    # since typing.GenericMeta (which became typing._GenericAlias in Python 3.7)
    # is not exposed.
    if self.type.__class__.__name__ in ('GenericMeta', '_GenericAlias'):
      return
    if not isinstance(value, self.type):
      raise TypeError('Expected type %s for parameter %r but got %s.' %
                      (self.type, arg_name, value))
```
This relegates the type information in `ExecutionParameter` in such cases to documentation. This is valuable in its own right, and I understand that a part of the problem stems from Python's `typing` package itself. Nevertheless, it would be nice to converge enable recursive type checking in the future, such that a user specifying an ExecutionParameter with a subscripted generic type (or at least some subset thereof) can have analogous assertions performed.

**Comment by charlesccychen** [comment]
Thanks for this issue.  I've filed this as a feature request for a future improvement.

**Comment by martin-laurent** [comment]
Hi, Any update on this? It makes tfx effectively incompatible with python 3.7 for us.

**Comment by numerology** [comment]
Hi, #979 fixed this. Marked as fixed for now.
