### ISSUE TITLE
Include python version information in the User Guide

### ISSUE THREAD

**Issue by wjarek2** [tensorflow/tfx#8]

**Comment by wjarek2** [comment]
context: https://twitter.com/wjarek/status/1103719781830545408

**Comment by DanlanChen** [comment]
why you do not support tfx in python 3 version, for pip install , it only accept python 2.7

**Comment by DanlanChen** [comment]
@googlebot

**Comment by DanlanChen** [comment]
you should upgrade your example to 3.6 , 2.7 is no longer used in 2020,January

**Comment by wjarek2** [comment]
Hi @DanlanChen   - the code in the repo and dependent libraries do support Python 3 already, but we're doing more testing before releasing the Py3 package on PyPI. Thank you for your patience!
PS> Is this a Marie Skłodowska photo? :)

**Comment by wjarek2** [comment]
https://github.com/tensorflow/tfx/commit/b5e238338a775ff0b3f7ad457dda94fd7a4c8576 addressed it, supported environment is now shown in the TFX User Guide: https://www.tensorflow.org/tfx/guide
