### ISSUE TITLE
float data type for dropoff_census_tract due to missing values

### ISSUE THREAD

**Issue by yangju2011** [tensorflow/tfx#819]
in step 4 notebook, for this line in example data" 
`"dropoff_census_tract": [12345.0],  # No idea why this is a float`

The reason why this feature is float, rather than int or string, is because pandas dataframe cast `int` to `float` when there are missing values in the column.

**Comment by gowthamkpr** [comment]
@yangju2011 Can you please explain what the issue here is? Thanks!

**Comment by yangju2011** [comment]
@gowthamkpr in this step 4 notebook, there is this inline comment`# No idea why this is a float`
and i think the reason for this is a float is because there are missing values in the column, thus pandas interprets this column as float, rather than int.

**Comment by gowthamkpr** [comment]
@yangju2011 Thanks for giving your insight. Will look into it.

**Comment by ruoyu90** [comment]
Thanks @yangju2011 for the feedback!

**Comment by gowthamkpr** [comment]
I don't this this issue is valid anymore as the documentation has changed. Can you please close the issue. Thanks!
