### ISSUE TITLE
Is it possible for TFX to generate unique node id when instance_name is not provided?

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/tfx#864]
Hi! For many users in my organization, it is common to have multiple instances of a component in the same pipeline in order to easily experiment with features. For us this has been a tricky source of errors, because while it is possible to set a unique `instance_name` when initializing the component, the default if left out is to [just use the class name](https://github.com/tensorflow/tfx/blob/0.15.0rc0/tfx/components/base/base_node.py#L84). While a sensible default for pipelines that don't have this pattern, it is a really tricky silent error for our users that forget to pass in `instance_name`, because of the way input artifact resolution works.

Would it be possible for TFX to generate some unique name if `instance_name` is not provided? Maybe a uuid or even an incrementing integer?

**Comment by andrewsmartin** [comment]
Ideally this would be done in a deterministic, repeatable way so that caching between runs is still possible.

**Comment by ruoyu90** [comment]
Hi @andrewsmartin , thanks for bringing up this! Actually with [this change](https://github.com/tensorflow/tfx/commit/f03f425af730c13ed3770bf138bb470e165dfb9a), `instance_name` is mandatory if there are multiple component instances for the same component type in a pipeline. It is available in 0.14.

**Comment by andrewsmartin** [comment]
Oh, I see, thanks @ruoyu90!
