### ISSUE TITLE
Colab InteractiveContext Unable to Determine ProjectID for BQ

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tfx#882]
When trying to use TFX in Colab, specifically the BigQueryExampleGen, there is an issue where we get the following error regarding the GCP project_id:
"Project was not passed and could not be determined from the environment."

`gcloud config list` shows the project is recognized, so the issue is within the last, or second-to-last line.

Perhaps there is a parameter within  `InteractiveContext()` or `BigQueryExampleGen()`, but I couldn't find any documentation on this. Is there a way to specify the project_id in any of these functions? Or is this a bug? 

Below is the exact replica of the issue:

```
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from tfx.components.example_gen.big_query_example_gen.component import BigQueryExampleGen
from google.cloud import bigquery
from google.colab import auth

auth.authenticate_user( )
project_id = 'Project-ID'
!gcloud config set project {project_id}
!gcloud config list


context = InteractiveContext()

QUERY = '''
SELECT * 
FROM `bigquery-public-data.chicago_taxi_trips.taxi_trips` 
LIMIT 1000
'''
example_gen = BigQueryExampleGen(query=QUERY )
context.run(example_gen)

```

**Comment by 1025KB** [comment]
Could you try following the instruction [here](https://cloud.google.com/docs/authentication/getting-started) and set up the GOOGLE_APPLICATION_CREDENTIALS in your env?

**Comment by luischinchillagarcia** [comment]
Yes I did, and it still doesn't seem to work. It seems it's an issue with `InteractiveContext` that the actual credentials. This issue can be replicated in a Colab notebook as well, after you fully authenticate you env.

**Comment by 1025KB** [comment]
are you able to run the [gcp example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_gcp.py) without InteractiveContext or Colab?

**Comment by charlesccychen** [comment]
Can you try setting the following?

```python
import os
os.environ['GCLOUD_PROJECT'] = '<your project name>'
```

**Comment by charlesccychen** [comment]
(edited) Can you try setting your project ID with the following code?

```python
import os
os.environ['GCLOUD_PROJECT'] = '<your project name>'
```

**Comment by luischinchillagarcia** [comment]
So far, yes. The issue appears only when running this in a notebook with the BigQueryExampleGen. The CsvExampleGen works. Here is the issue that appears, even using the suggestion above.

![image](https://user-images.githubusercontent.com/50338632/68159413-9539f180-ff06-11e9-8d6f-c2d75b0781fe.png)

**Comment by charlesccychen** [comment]
(edited) Can you try setting your project ID with the following code?

```python
import os
os.environ['GCLOUD_PROJECT'] = '<your project name>'
```

And then verifying that it shows up with

```python
os.getenv('GCLOUD_PROJECT')
```

**Comment by charlesccychen** [comment]
Thanks, it looks like the long-term solution will be to pipe in `beam_pipeline_args` through `context.run()`.  A workaround right now is to do the following:

```
from apache_beam.internal.gcp import auth
auth.executing_project = '<your project name>'
```

Note that there is no compatibility guarantee for this workaround.

**Comment by luischinchillagarcia** [comment]
It seems it does not work. So currently there is no way to add to `beam_pipeline_args` through context.run()? I presume InteractiveContext is using `PipelineOptions()` with a DirectRunner right?

**Comment by charlesccychen** [comment]
I have proposed https://github.com/tensorflow/tfx/pull/888 to make this work.  With that change, you would be able to do `context.run(..., beam_pipeline_args=['--project', 'my-project'])`.

To be clear on your last comment, are you saying that setting `auth.executing_project` does not work?

**Comment by luischinchillagarcia** [comment]
"To be clear on your last comment, are you saying that setting auth.executing_project does not work?"
> Yes, exactly.

**Comment by luischinchillagarcia** [comment]
Thank you so much for the prompt responses with this issue.

**Comment by 1025KB** [comment]
#888 is merged into master, could you try again?

**Comment by charlesccychen** [comment]
@luischinchillagarcia can you try installing `pip install -i https://test.pypi.org/simple/ tfx==0.16.0.dev20191105` and then adding `context.run(..., beam_pipeline_args=['--project', 'my-project'])`?

**Comment by luischinchillagarcia** [comment]
It works perfectly! Thank you so much.

**Comment by charlesccychen** [comment]
Great, thanks for reporting this issue.
