### ISSUE TITLE
[Metadata] pipeline_name should be a property of Context, not Artifact or Execution

### ISSUE THREAD

**Issue by Ark-kun** [tensorflow/tfx#905]
From Metadata and DB schema perspective, the "pipeline_name" is a property of Context, not Artifact or Execution.

https://github.com/tensorflow/tfx/blob/9f6412be9e8c6d3b065eb15ea85859ab4604af5e/tfx/types/artifact.py#L117

https://github.com/tensorflow/tfx/blob/92832988691c82c6b142a6251385c46e86c38991/tfx/orchestration/metadata.py#L46

Same with `run_id` and `pipeline_root`.

**Comment by 1025KB** [comment]
agree, we recently add the context concept, and it contains pipeline_name already [[1]](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/metadata.py#L645), before the context exists, we need the pipeline information in artifacts or execution for caching reason, it should be deprecated in the future

**Comment by gowthamkpr** [comment]
@Ark-kun Did the above comment answer your question? Can I close this issue?

**Comment by Ark-kun** [comment]
@1025KB Will TFX stop adding `pipeline_name` property to the artifacts and executions in near future? What are the backward and forward compatibility implications for this global schema change?

**Comment by jiyongjung0** [comment]
I believe that we don't add `pipeline_name` to artifacts or executions any more. We changed the behavior before we publish 1.0 and it would be backward compatible after that.

Please re-open if you need. Thanks!
