### ISSUE TITLE
How to use tf.keras.estimator.model_to_estimator in Trainer?

### ISSUE THREAD

**Issue by iLikeToCodeZ** [tensorflow/tfx#912]
I'm failing at using an estimator build from keras in the Trainer component. Any examples on how to do this?

TF Version: 2.0.0
TFX Version: 0.15.0rc0

**Comment by 1025KB** [comment]
we have this [example](https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/iris_utils.py#L190) using model_to_estimator
