### ISSUE TITLE
Why not call tf_transform_output.transform_raw_features in a tf.keras.Layer subclass?

### ISSUE THREAD

**Issue by schmidt-jake** [tensorflow/tfx#922]
The preprocessing function is something that will be applied in training, evaluation, and serving. The current method involves transforming raw features in multiple places (the train, eval and serve `input_fn`s) in the pipeline, violating the DRY principle. I find it easier to subclass `tf.keras.Layer` to hold my single call to `transform_raw_features`, especially since TF2 is moving to keras being the standard high-level API. Is this a good idea or should I not be doing this?

**Comment by 1025KB** [comment]
preprocessing_fn is used by transform, train and eval doesn't need to write the preprocessing code again, they can directly use the transform's output to make sure it is applied to the same transform logic.

tf transform is currently not supported in keras yet, tensorflow team is working on that, if I remember correctly, implementing tft in keras input Layer is one of the option, could you ask the tft keras support  in tensorflow repo too?

**Comment by pindinagesh** [comment]
@schmidt-jake 

As @1025KB mentioned above, have you posted this issue in tft keras support in tensorflow repo? if yes kindly respond to this comment so that this issue can be closed.

**Comment by pindinagesh** [comment]
@schmidt-jake 

Closing this issue. Please feel free to reopen if this still persists, can you please refer [documentation](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/TFTransformOutput#transform_features_layer) and [Transform](https://github.com/tensorflow/transform/blob/master/examples/census_example_v2.py#L344-L356). Thanks
