### ISSUE TITLE
try to recovery example_gen['examples'] Channel from json got TypeError when run StatisticsGen

### ISSUE THREAD

**Issue by PingThePeng** [tensorflow/tfx#923]
to json code:

def example_channel_to_json(channel:Channel):
    artifact_dicts = [i.to_json_dict() for i in channel.get()]
    return json.dumps({"type_name":"ExamplesPath","_artifacts":artifact_dicts})

-------------------------------------------------------------------------------------------------
to channel code:

def load_example_channel(file_name:str)->Channel:
    with open(file_name,encoding='utf-8') as f:
        content = f.read()
        example_json_dict = json.loads(content)
        example_json_dict['_artifacts']=[Examples.from_json_dict(dic) for dic in example_json_dict['_artifacts']]
        return Channel.from_json_dict(example_json_dict)

-------------------------------------------------------------------------------------------------
run code:

examples_channel = load_example_channel("./o_s1.json")
statistics_gen = StatisticsGen(
    examples=examples_channel)

-------------------------------------------------------------------------------------------------
error:

InvalidArgumentError                      Traceback (most recent call last)
~/project/tfx-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3325                 else:
-> 3326                     exec(code_obj, self.user_global_ns, self.user_ns)
   3327             finally:

<ipython-input-60-52e4af76b6cf> in <module>
----> 1 context.run(statistics_gen)

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     64       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 65       return fn(*args, **kwargs)
     66     else:

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache)
    162         beam_pipeline_args, additional_pipeline_args)
--> 163     execution_id = launcher.launch()
    164 

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    190                         execution_decision.input_dict,
--> 191                         execution_decision.output_dict)
    192 

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py in _run_publisher(self, use_cached_results, execution_id, input_dict, output_dict)
    164           output_dict=output_dict,
--> 165           use_cached_results=use_cached_results)
    166 

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/publisher.py in publish_execution(self, execution_id, input_dict, output_dict, use_cached_results)
     69         output_dict=output_dict,
---> 70         state=final_execution_state)

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/metadata.py in publish_execution(self, execution_id, input_dict, output_dict, state)
    400                   single_output)
--> 401             [published_artifact] = self.publish_artifacts([single_output])  # pylint: disable=unbalanced-tuple-unpacking
    402             single_output.set_artifact(published_artifact)

~/project/tfx-env/lib/python3.7/site-packages/tfx/orchestration/metadata.py in publish_artifacts(self, raw_artifact_list)
    173         raw_artifact.state = ArtifactState.PUBLISHED
--> 174         [artifact_id] = self._store.put_artifacts([raw_artifact.artifact])
    175         raw_artifact.id = artifact_id

~/project/tfx-env/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py in put_artifacts(self, artifacts)
    168 
--> 169     self._call('PutArtifacts', request, response)
    170     result = []

~/project/tfx-env/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py in _call(self, method_name, request, response)
    119       swig_method = getattr(metadata_store_serialized, method_name)
--> 120       self._swig_call(swig_method, request, response)
    121     else:

~/project/tfx-env/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py in _swig_call(self, method, request, response)
    145     if status_code != 0:
--> 146       raise _make_exception(error_message, status_code)
    147     response.ParseFromString(response_str)

<class 'str'>: (<class 'TypeError'>, TypeError('__str__ returned non-string (type bytes)'))

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/project/tfx-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3341             if result is not None:
   3342                 result.error_in_exec = sys.exc_info()[1]
-> 3343             self.showtraceback(running_compiled_code=True)
   3344         else:
   3345             outflag = False

~/project/tfx-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2043                                             value, tb, tb_offset=tb_offset)
   2044 
-> 2045                     self._showtraceback(etype, value, stb)
   2046                     if self.call_pdb:
   2047                         # drop into debugger

~/project/tfx-env/lib/python3.7/site-packages/ipykernel/zmqshell.py in _showtraceback(self, etype, evalue, stb)
    544             u'traceback' : stb,
    545             u'ename' : unicode_type(etype.__name__),
--> 546             u'evalue' : py3compat.safe_unicode(evalue),
    547         }
    548 

~/project/tfx-env/lib/python3.7/site-packages/ipython_genutils/py3compat.py in safe_unicode(e)
     63     """
     64     try:
---> 65         return unicode_type(e)
     66     except UnicodeError:
     67         pass

TypeError: __str__ returned non-string (type bytes)

-------------------------------------------------------------------------------------------------
json :

{"type_name": "ExamplesPath", "_artifacts": [{"artifact": {"id": "2", "typeId": "4", "uri": "/tmp/tfx-interactive-2019-11-10T04_04_03.116020-iv1_yl62/ImportExampleGen/examples/1/train/", "properties": {"name": {"stringValue": "examples"}, "type_name": {"stringValue": "ExamplesPath"}, "state": {"stringValue": "published"}, "span": {}, "pipeline_name": {"stringValue": "interactive-2019-11-10T04_04_03.116020"}, "producer_component": {"stringValue": "ImportExampleGen"}, "split": {"stringValue": "train"}}}, "artifact_type": {"id": "4", "name": "ExamplesPath", "properties": {"split": "STRING", "name": "STRING", "type_name": "STRING", "state": "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING"}}}, {"artifact": {"id": "3", "typeId": "4", "uri": "/tmp/tfx-interactive-2019-11-10T04_04_03.116020-iv1_yl62/ImportExampleGen/examples/1/eval/", "properties": {"name": {"stringValue": "examples"}, "type_name": {"stringValue": "ExamplesPath"}, "state": {"stringValue": "published"}, "span": {}, "pipeline_name": {"stringValue": "interactive-2019-11-10T04_04_03.116020"}, "producer_component": {"stringValue": "ImportExampleGen"}, "split": {"stringValue": "eval"}}}, "artifact_type": {"id": "4", "name": "ExamplesPath", "properties": {"name": "STRING", "type_name": "STRING", "state": "STRING", "producer_component": "STRING", "span": "INT", "pipeline_name": "STRING", "split": "STRING"}}}]}

**Comment by 1025KB** [comment]
Channel doesn't have from_json_dict function in the latest version, that function is for [artifact](https://github.com/tensorflow/tfx/blob/master/tfx/types/artifact.py#L146) not channel, channel contains a list of artifacts.

BTW, could you help us understand what's the need here for serialize channel?

**Comment by PingThePeng** [comment]
> Channel doesn't have from_json_dict function in the latest version, that function is for [artifact](https://github.com/tensorflow/tfx/blob/master/tfx/types/artifact.py#L146) not channel, channel contains a list of artifacts.
> 
> BTW, could you help us understand what's the need here for serialize channel?

I'm trying to do preprocessing on beam and training on single gpu-machine.So as a newbee thinks maybe i can just cut the pipeline into two part and serialize channel as message then connect them.

Realized it's a wrong way...

**Comment by 1025KB** [comment]
it might be doable as channel is [jsonable](https://github.com/tensorflow/tfx/blob/master/tfx/types/channel.py#L26), you need to make sure the two part are using same mlmd, so that the second part can find the information in mlmd and continue, 

Normally examplegen and importer is our entry point as those components can register external file into mlmd, but serialized channel should work

**Comment by rmothukuru** [comment]
@PingThePeng,
Can you please confirm if @1025KB's comment resolved your issue. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
