### ISSUE TITLE
Pusher GAIP Extension unable to push to any region other than us-central1 on Google Cloud Platform

### ISSUE THREAD

**Issue by htahir1** [tensorflow/tfx#926]
The runner that creates and deploys models on Google Cloud AI Platform can for now only push to the region 'us-central1'. This is because the 'body' that is used to actually make the model only includes the name of the model and the region is defaulted to us-central1: Reference: https://github.com/tensorflow/tfx/blob/359dcc95e6104e183b685a683d502744305e5eba/tfx/extensions/google_cloud_ai_platform/runner.py#L187

I was hoping that by using a Google Cloud Project that is by default in Europe would help, but it seems you need to specify it in the API call to create the model.

Is there any plan to be able to change this, so that one can specify the region via the Pusher configuration?

**Comment by neuromage** [comment]
Yes, definitely. This should be an easy fix. We'll send one out shortly.

**Comment by pindinagesh** [comment]
Hi @htahir1 

Could please tell us what is the status of this issue so that the issue can be discussed further or suggest whether this can be closed. Thank you!

**Comment by jiyongjung0** [comment]
I believe that this was already fixed and users can specify regions. See https://github.com/tensorflow/tfx/blob/bca8168dfc50d1a28218391c4114081275129da7/tfx/extensions/google_cloud_ai_platform/pusher/executor.py#L61

Feel free to reopen if there is anything missing.
