### ISSUE TITLE
Taxi_pipeline_beam SchemaGen split train error when using MySQL for metadata.

### ISSUE THREAD

**Issue by tkakantousis** [tensorflow/tfx#929]
Hi everyone,

Running the [taxi_pipeline_beam](https://github.com/tensorflow/tfx/blob/r0.14/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_beam.py) example, throws the following error 

```
srv/hops/anaconda/anaconda/envs/python27/lib/python2.7/site-packages/tfx/types/artifact_utils.pyc in get_split_uri(artifact_list, split)
    107     ValueError: If number with matching split in artifact_list is not one.
    108   """
--> 109   return _get_split_instance(artifact_list, split).uri

/srv/hops/anaconda/anaconda/envs/python27/lib/python2.7/site-packages/tfx/types/artifact_utils.pyc in _get_split_instance(artifact_list, split)
     90   matched = [x for x in artifact_list if x.split == split]
     91   if len(matched) != 1:
---> 92     raise ValueError('{} elements matches split {}'.format(len(matched), split))
     93   return matched[0]
     94 

ValueError: 0 elements matches split train [while running 'Run[SchemaGen]']
```
when using a MySQL database for metadata. With the default Sqlite it works ok. Artifact and ArtifactType tables are populated in MySQL. Any hints on what could be the issue or where to look at? Thank you!

**Comment by charlesccychen** [comment]
Hey there, the example you pointed to comes from the 0.14 release.  Version 0.15 was recently released--can you try again with the newer version?  (You may need to remove the existing tables in the database if they are not in a good state).

**Comment by charlesccychen** [comment]
@tkakantousis Hey there, the example you pointed to comes from the 0.14 release.  Version 0.15 was recently released--can you try again with the newer version?  (You may need to remove the existing tables in the database if they are not in a good state).

**Comment by rmothukuru** [comment]
@tkakantousis,
Can you please confirm if @charlesccychen's comment resolved your issue so that we can close this issue. Thanks!

**Comment by tkakantousis** [comment]
Hi @charlesccychen and @rmothukuru 
Thank you very much for looking into this. I haven't had the chance to try it with 0.15 yet. Maybe you can close the issue and then if I encounter the same issue on 0.15 I can open a new one?

**Comment by rmothukuru** [comment]
Closing the issue as per @tkakantousis's comment. Thanks!
