### ISSUE TITLE
SchemaGen default_environment Error

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tfx#935]
When attempting to create different schema environments for training and serving (serving doesn't have the label feature) while using a schema derived from SchemaGen, the error `AttributeError: 'SchemaGen' object has no attribute 'default_environment'` appears. Is there a way to have this TFDV-like functionality? 

A secondary question is more general: what is the relationship between TFDV and TFX Components (StatisticsGen, SchemaGen, ExampleValidator). Is there a reason to choose one over the other?

```
# ExampleGen from CSV data
input_data_serve = external_input(os.path.join('example_gen','serve'))
example_gen_serve = CsvExampleGen(input=input_data_serve)
context.run(example_gen_serve)

# StatisticsGen to infer stats
statistics_gen_serve = StatisticsGen(examples=example_gen_serve.outputs['examples'],
                               instance_name='compute-train-stats'
                               )
context.run(statistics_gen_serve)

# Create schema environments
schema_train.default_environment.append('TRAINING') # Error here
schema_train.default_environment.append('SERVING')

# Specify that 'label' feature is not in SERVING environment.
tfdv.get_feature(schema_train, 'label').not_in_environment.append('SERVING')

serving_anomalies_with_env = tfdv.validate_statistics(stats_serve, 
                                                      schema_train, 
                                                      environment='SERVING')

tfdv.display_anomalies(serving_anomalies_with_env)
```

**Comment by charlesccychen** [comment]
Hey @luischinchillagarcia, this feature of Tensorflow Data Validation isn't yet supported by the SchemaGen component.  I've filed a feature request to support TFDV environments (CC: @1025KB @ruoyu90 @zhitaoli)

At a high level, TFX components like you mentioned are meant to be orchestrated together in a pipeline.  These use the TFDV library (which you can also use yourself directly).  While the TFX components together would give you an end-to-end solution, sometimes you only want to use the library version without the pipeline aspect; here, you would use the TFDV library directly.
