### ISSUE TITLE
Output_config Argument and _PropertyDictWrapper Path Error

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tfx#938]
In order to save TF-Example files from the TFX ExampleGen component to a specific location, you would have to use ComponentOutputs (from tfx.components.base.base_component) as shown below. However, ComponentOutputs seems to be completely gone, and have not found any documentation that points to how to save these ExampleGen TF-Example to a custom location. What is the most optimal manner of doing this task now?

```python
examples = csv_input(_data_root)

# Brings data into the pipeline or otherwise joins/converts training data.
train_config = example_gen_pb2.SplitConfig.Split(name='train', hash_buckets=2)
eval_config = example_gen_pb2.SplitConfig.Split(name='eval', hash_buckets=1)
output_config = example_gen_pb2.Output(
    split_config=example_gen_pb2.SplitConfig(splits=[
        train_config,
        eval_config
    ]))

# Create outputs
train_examples = types.TfxType(type_name='ExamplesPath', split='train')
train_examples.uri = os.path.join(_data_root, 'csv_example_gen/train/')

eval_examples = types.TfxType(type_name='ExamplesPath', split='eval')
eval_examples.uri = os.path.join(_data_root, 'csv_example_gen/eval/')

# Error, ComponentOutputs does not exist 
example_outputs = ComponentOutputs({
    'examples': Channel(
        type_name='ExamplesPath',
        static_artifact_collection=[train_examples, eval_examples]
    ),
    'training_examples': Channel(
        type_name='ExamplesPath',
        static_artifact_collection=[train_examples]
    ),
    'eval_examples': Channel(
        type_name='ExamplesPath',
        static_artifact_collection=[eval_examples]
    ),    
})

example_gen = CsvExampleGen(
    input_base=examples, # A Channel of 'ExternalPath' type, it contains path of data source.
    output_config=output_config,  # An example_gen_pb2.Output instance, it contains train-eval split ratio.
    outputs=example_outputs # dict from name to output channel, it will be stored example_gen.outputs
)
```

**Comment by luischinchillagarcia** [comment]
## **Follow up** 
Looking deeper, I fixed the modules by doing the following : 
1. "base_component.ComponentOutputs class has been renamed to base_component._PropertyDictWrapper"
2. tfx.utils.types.channel was changed to tfx.types.channel

## **However:**
Before, it was expected that a wrapped dict with values of `Channel`(shown below as 'Trial 1') would change the uri of the `ExamplePath` for each output. This fails because the `example_artifacts` argument expects a `Channel` object. 

If we include a Channel object as in 'Trial 2', the uri path still does not change despite not throwing any errors.

**Goal:**
For clarity, the ultimate goal is to be able to change the `ExamplePath` uri path. This is so we could use a GCS bucket to store large file split by ExampleGen(I presume keeping large files in the default temp file might cause major issues).

_How can we achieve this goal under the recent changes?_

```python
examples = csv_input(_data_root)

# Brings data into the pipeline or otherwise joins/converts training data.
train_config = example_gen_pb2.SplitConfig.Split(name='train', hash_buckets=2)
eval_config = example_gen_pb2.SplitConfig.Split(name='eval', hash_buckets=1)
output_config = example_gen_pb2.Output(
    split_config=example_gen_pb2.SplitConfig(splits=[
        train_config,
        eval_config
    ]))

# Create outputs
train_examples = types.TfxType(type_name='ExamplesPath', split='train')
train_examples.uri = 'csv_example_gen/train/' # Assuming this path exists

eval_examples = types.TfxType(type_name='ExamplesPath', split='eval')
eval_examples.uri = 'csv_example_gen/eval/' # Assuming this path exists

# Trial 1. (Fails) Before, it was expected that this wrapped dict would change 
# the uri of the `ExamplePath`
example_outputs = _PropertyDictWrapper({
    'examples': Channel(
        type_name='ExamplesPath',
        artifacts=[train_examples, eval_examples]
    ),
    'training_examples': Channel(
        type_name='ExamplesPath',
        artifacts=[train_examples]
    ),
    'eval_examples': Channel(
        type_name='ExamplesPath',
        artifacts=[eval_examples]
    ),    
})

# Trial 2. (Successful but incorrect)`artifacts` expects a `Channel` obj, but doesn't change `ExamplePath` uri
example_outputs = Channel(  
        type_name='ExamplesPath',
        artifacts=[train_examples, eval_examples]
        )

example_gen = CsvExampleGen(     
    input_base=examples, # A Channel of 'ExternalPath' type, it contains path of data source.
    output_config=output_config,  # An example_gen_pb2.Output instance, it contains train-eval split ratio.
    example_artifacts=example_outputs
)
context.run(example_gen)

example_gen.outputs['examples']._artifacts
>> [Artifact(type_name: ExamplesPath, uri: /tmp/tfx-interactive-2019-11-15T22_01_01.450230-vnetewst/CsvExampleGen/examples/1/train/, split: train, id: 2),
 Artifact(type_name: ExamplesPath, uri: /tmp/tfx-interactive-2019-11-15T22_01_01.450230-vnetewst/CsvExampleGen/examples/1/eval/, split: eval, id: 3)]
```

**Comment by charlesccychen** [comment]
@luischinchillagarcia Hey there, would providing the `pipeline_root` argument to the InteractiveContext solve your problem?  You can provide this as the root path to contain all your artifacts for your execution.

**Comment by luischinchillagarcia** [comment]
Yes, I think this would be a perfect solution!

**Comment by luischinchillagarcia** [comment]
I would like to add  - Do we expect _propertydictwrapper to act in the same way as ComponentOutputs?

ComponentOutputs was used to create a dict of `Channel` objects. Is that still the case?

**Comment by charlesccychen** [comment]
@luischinchillagarcia No, the `_PropertyDictWrapper` is meant to be internal-only and is meant to create a dict-like object of Channels.  We have the wrapper right now for some backwards compatibility reasons, but recommend that you just use a dict instead in your own code.  When you want to specify specific channels as outputs for a component, the component should be passed its appropriate optional argument (there is no longer a unified outputs dictionary passed in, as you have noted).

**Comment by luischinchillagarcia** [comment]
Thank you for the quick responses. 

To clarify, you mention to use a normal dict but that "there is no longer a unified outputs dictionary passed in". So in the `example_artifacts` argument found in the components (shown below), how can we pass in multiple Channels that require associations to different names. Before you had to specify the training/eval `Artifact` names are keys, and the `Channel` objects as values.


```python
example_gen = CsvExampleGen(     
    input_base=examples, # A Channel of 'ExternalPath' type, it contains path of data source.
    output_config=output_config,  # An example_gen_pb2.Output instance, it contains train-eval split ratio.
    example_artifacts=example_outputs
)
```
