### ISSUE TITLE
Serving with TF Lite: "expected names to be a vector, got shape: []" while executing ParseExample

### ISSUE THREAD

**Issue by loiccordone** [tensorflow/tfx#94]
Hello,

I successfully converted my model trained and served with TFX to TF Lite with the following code:
```
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
I am trying to run the [TF Lite benchmark](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark), and after having built the TF Lite libraries with the additional TensorFlow ops library ('benchmark_model_plus_flex'), I got the following error when I run the benchmark:

```
STARTING!
Min num runs: [50]
Min runs duration (seconds): [1]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Min warmup runs: [1]
Min warmup runs duration (seconds): [0.5]
Graph: [converted_model.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
Use legacy nnapi : [0]
Use gpu : [0]
Allow fp16 : [0]
Loaded model converted_model.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for select TF ops.
2019-05-07 15:25:15.623225: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Initialized session in 16.254ms
Running benchmark for at least 1 iterations and at least 0.5 seconds
ERROR: Expected names to be a vector, got shape: []
	 (while executing 'ParseExample' via Eager)
ERROR: Node number 176 (TfLiteFlexDelegate) failed to invoke.

Failed to invoke!
Aborted (core dumped)
```

I'm not sure this error comes from the served model by TFX, but I didn't find info on a similar error elsewhere. The benchmark works with public .tflite models (Mobilenet 1.0) though.
I'm using TFX 0.12 and TF 1.13.1

Thank you!

**Comment by gowtham-kp** [comment]
@loiccordone Can you please post this issue in [Tensorflow/Tensorflow](https://github.com/tensorflow/tensorflow/issues). Thanks!

**Comment by gowtham-kp** [comment]
Closing this issue due to the lack of recent activity. Please feel free to add additional comments and we will reopen the issue again!

**Comment by wjarek2** [comment]
Heads up @loiccordone  - the support for TF Lite in TFX is improving, more info coming soon but if you'd like to take a look here's the 0.21 release notes: https://github.com/tensorflow/tfx/releases/tag/0.21.0 and more information will be coming soon.
