### ISSUE TITLE
Can't install TFX using python 3.7-venv/pip on windows 8.1/10

### ISSUE THREAD

**Issue by hasansaikat** [tensorflow/tfx#950]
Hi,
I recently tried to install TFX on windows 8.1/10 using pip(latest version) & python3.7 inside virtual environment.But it throws dependency error for all the different standalone packages are given below: 
tensorflow-data-validation,
tensorflow-transform,
tensorflow-model-analysis,
ml-metadata, etc.

pip install tfx-bsl on windows 8.1/10 using python3.7 also throws the same error.

#885
![Screenshot (6549)](https://user-images.githubusercontent.com/11005653/69176040-21672e00-0b2f-11ea-9ec0-bd8f6de95a3d.png)
![Screenshot (6550)](https://user-images.githubusercontent.com/11005653/69176041-21672e00-0b2f-11ea-8b11-a6577a076fd6.png)
![Screenshot (6551)](https://user-images.githubusercontent.com/11005653/69176042-21ffc480-0b2f-11ea-9869-86841f13c6f0.png)
![Screenshot (6552)](https://user-images.githubusercontent.com/11005653/69176043-21ffc480-0b2f-11ea-8065-bde51c4581d4.png)
![Screenshot (6553)](https://user-images.githubusercontent.com/11005653/69176045-22985b00-0b2f-11ea-9ae6-3ce110f85539.png)

@wjarek-zz 
@wjarek2 
@rcrowe-google 
@zhitaoli

**Comment by ruoyu90** [comment]
Hi @hasansaikat thanks for the feedback! Our windows support is not ready yet but we're working on that and hope to have that ready soon :)

**Comment by DmitriyBaykov** [comment]
Same for me. @ruoyu90 do you have some estimates on adding win 10 support?

**Comment by sakhawath19** [comment]
@ruoyu90 does TFX works for windows 10 now?

**Comment by yonil7** [comment]
Hi, is there any plan to support windows?

**Comment by rcrowe-google** [comment]
Unfortunately there is currently no plan to support Windows.  It's not a request that we get very often, as you might guess from this thread.

**Comment by yonil7** [comment]
Maybe we should at least make sure the `ml-pipelines-sdk` package (specifically the `TFX DSL`) can run on windows.

Reason/motivation:
* On python there are currently multiple pipeline DSLs:
  * `TFX pipelines DSL`
  * `KFP DSL`
  * [`Prefect DSL`](https://orion-docs.prefect.io/)
  * [`Dagster DSL`](https://docs.dagster.io/getting-started)
  * [`Ray workflow DSL`](https://docs.ray.io/en/master/workflows/concepts.html)
  * ...
* GCP Vertex AI pipelines can be written using `TFX pipelines DSL` or `KFP DSL` (`KFP DSL` is the "older" one)
* I prefer to develop my pipelines using `TFX DSL` for the following reasons:
  * It gives better, higher level abstraction
  * It can run on different orchestrator (including local runner for testing)
  * It does not depend on Kubernetes
  * It has metadata integration
  * Its easy to scale using GCP Vertex AI pipelines (as its a managed/serverless service)
  * ...
* I think that if `TFX pipelines DSL` wants to be a dominant player among the different python pipeline DSL packages it should be cross platform and have a low barrier of entry (such as `Prefect Orion DSL` for example - just add a few decorators to your existing code and your code becomes a pipeline)

**Comment by UsharaniPagadala** [comment]
@hasansaikat 
Closing this issue.Please feel free to reopen if you still need any assistance.Thanks
