### ISSUE TITLE
TFX function validate_dataset_keys under tensorflow_transform\beam\analyzer_cache doesn't handle windows style path

### ISSUE THREAD

**Issue by sarochida** [tensorflow/tfx#954]
file: analyzer_cache.py
function: validate_dataset_keys()
issue: windows style path seperator '\\' is NOT handled
suspect: line 231   regex = re.compile(r'^[a-zA-Z0-9\.\-_]+$')
------------------ Context ---------------------------------------
Leveraging TFX tutorial @ https://www.tensorflow.org/tfx/tutorials/tfx/components
Using MNIST data in csv form and created following flow (aligning to tutorial with my csv file instead of chicago_taxi_pipeline):
- CsvExampleGen
- StatisticsGen
- SchemaGen
- ExampleValidator
- Transform
^^^^ fails at this point unable to  ^^^^^^^
using basic dummy preprocessing_fn and constants .py files
backtrace (attached)
-------------------- Version info -----------------------------------
Python 3.6.9
TensorFlow version: 2.0.0
TFX version: 0.15.0
Windows 10
-------------------- Library usage model --------------------------
import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()
import tfx
pipeline_root was not provided with the InteractiveContext
-------------------- Initial Triage -----------------------------------
c:\users\saroc\repo\workspace\envs\tfx\lib\site-packages\tensorflow_transform\beam\analyzer_cache.py(236) validate_dataset_keys()
    231   regex = re.compile(r'^[a-zA-Z0-9\.\-_]+$')
    232   for key in keys:
    233     if not regex.match(key):
    234       raise ValueError(
    235           'Dataset key {!r} does not match allowed pattern: {!r}'.format(
--> 236               key, regex.pattern))
    237 
    238 

ipdb> key
'tfx-interactive-2019-11-20T18_28_10.989204-xzgs28b8\\CsvExampleGen\\examples\\1\\train\\STAR'

ipdb> print(regex.match(key))
None
[bt.txt](https://github.com/tensorflow/tfx/files/3869909/bt.txt)

**Comment by ruoyu90** [comment]
Thanks for the feedback @sarochida ! Our windows support is not ready yet but we're working on that and hope to have that ready soon :)

**Comment by gowthamkpr** [comment]
@sarochida This issue has been fixed now. You should not face any problem with Windows style paths now. Please try it using the latest version of tfx. Thanks!
