### ISSUE TITLE
ImportExampleGen raises ValueError when input is in `gs://...`

### ISSUE THREAD

**Issue by ucdmkt** [tensorflow/tfx#956]
TFX 0.15.0 and its Beam dependency as installed by pip.

```
data_root = 'gs://my_bucket/path/to/tfrecord'  # This folder has `data1.tfrecord`, `data2.tfrecord`, ....
example_gen = ImportExampleGen(
      input=dsl_utils.external_input(data_root),
)
```

This will cause `ValueError` as follows.
```
...
  File "/usr/local/google/home/muchida/miniconda3/envs/tfx-kfp-2/lib/python3.5/site-packages/apache_beam/io/tfrecordio.py", line 186, in read_records
    record = _TFRecordUtil.read_record(file_handle)
  File "/usr/local/google/home/muchida/miniconda3/envs/tfx-kfp-2/lib/python3.5/site-packages/apache_beam/io/tfrecordio.py", line 133, in read_record
    (buf_length_expected, codecs.encode(buf, 'hex')))
ValueError: Not a valid TFRecord. Fewer than 12 bytes: b'706c616365686f6c646572' [while running 'Run[ImportExampleGen]']
```

This is because ImportExampleGen [appends `*` at the end](https://github.com/tensorflow/tfx/blob/60dedacca908ef1fd9f832e479129a9003f49088/tfx/components/example_gen/utils.py#L118), but since GCS is not POSIX file system, it matches with the folder itself.

```
$ gsutil ls -l gs://my_bucket/path/to/tfrecord/*
        11  2019-11-16T03:30:18Z  gs://my_bucket/path/to/tfrecord/
      2160  2019-11-16T04:12:57Z  gs://my_bucket/path/to/tfrecord/data1.tfrecord
      2160  2019-11-16T04:13:05Z  gs://my_bucket/path/to/tfrecord/data2.tfrecord
      :
      :
```

Although, Beam [TFRecordIO](https://github.com/apache/beam/blob/v2.16.0/sdks/python/apache_beam/io/tfrecordio.py#L132) expects all matched files are valid TFRecord. Hence the error.

In order to work around, configuration must be like this.

```
data_root = 'gs://my_bucket/path/to/tfrecord' 
example_gen = ImportExampleGen(
    input=dsl_utils.external_input(data_root),
    input_config=example_gen_pb2.Input(
        splits=[
            example_gen_pb2.Input.Split(name='all', pattern='*.tfrecord'),
        ]
    )
)
```

**Comment by 1025KB** [comment]
One potential solution for us is we don't use the 'dir/*' pattern but just get all files ourselves and feed 'file1,file2,file3,...' as pattern to beam

keep this as a feature request

**Comment by ucdmkt** [comment]
I think the issue comes from the fact that in GCS, there is not distinction between folders and files. 

One possible 'fix' is to ignore all matching paths that ends with '/'. This may be a feature request and/or bug fix to Beam.

**Comment by numerology** [comment]
Is it doable to temporarily branch the logic based on the protocol?
For example:
```python
if data_root.startswith('gs://'):
    # Ignore slash, grab the real files
else:
    # Follow the current logic.
```

**Comment by singhniraj08** [comment]
@ucdmkt,

Apologies for delayed response, I was able to run ImportExampleGen with file path set to gcs bucket. Please refer to [gist](https://colab.research.google.com/gist/singhniraj08/104a5a12949c9af66b8ce0dc9b26b7c4/components_keras.ipynb).

Kindly let us know if you still face this issue. Thank you!

<img width="1124" alt="Screenshot 2023-03-29 at 3 00 55 PM" src="https://user-images.githubusercontent.com/110809167/228492809-fb71eb58-231f-4f2a-84fa-0ce6628d2c14.png">
