### ISSUE TITLE
overriding project in BigQueryExampleGen executor?

### ISSUE THREAD

**Issue by jasonbrancazio** [tensorflow/tfx#994]
The executor does not permit explicitly supplying a project when the BigQuery client is instantiated: https://github.com/tensorflow/tfx/blob/1b7db9d5c0081ada72d46bb337f2f34161d63ea0/tfx/components/example_gen/big_query_example_gen/executor.py#L35

We have been having trouble getting a TFX pipeline to see our BQ project, getting a "Missing executing project information" error. While this might not be the root cause of our error, it does seem odd that the executor can't pass a project id to the BQ client.

**Comment by 1025KB** [comment]
Could you try following the instruction [here](https://cloud.google.com/docs/authentication/getting-started) and set up the GOOGLE_APPLICATION_CREDENTIALS in your env?

**Comment by jasonbrancazio** [comment]
We resolved our problem yesterday by correctly distinguishing between beam_orchestrator_args and beam_pipeline_args. But the comment above misses the point: Wouldn't there be some utility in specifying the project directly in the BQ client? What if the project specified by GOOGLE_APPLICATION_CREDENTIALS is different than the project where the data resides or where, for whatever reason, the BigQuery resources are wished to be used?

**Comment by 1025KB** [comment]
I see, in beam_pipeline_args, you need to set up '--project=xxx',
for bigquery, yep we don't support params for bigquery client init yet

currently we only support GOOGLE_APPLICATION_CREDENTIALS for bigquery and dataflow

will keep this as a feature request

**Comment by codesue** [comment]
PR #2640 recently merged and may close this issue.

**Comment by rmothukuru** [comment]
@jasonbrancazio,
Can you please confirm if your issue is resolved so that we can close this issue. Thanks!

**Comment by jasonbrancazio** [comment]
We're not using TFX at the moment, so I won't be able to confirm resolution. Feel free to close the issue.

**Comment by rmothukuru** [comment]
Closing the issue as per the above comment. Thanks!

**Comment by UsharaniPagadala** [comment]
@jasonbrancazio 
Closing this issue as it is resolved and the [PR](https://github.com/tensorflow/tfx/pull/2640) also merged.Feel free to reopen if this still exists.Thanks
